### ISSUE TITLE
Applications' icons in manager can be drag and dropped

### ISSUE THREAD

**Issue by amougel** [LedgerHQ/ledger-live-desktop#1005]
#### Ledger Live Version and Operating System

- Ledger Live **1.0.1**
- Platform: **mac**

#### Expected behavior

You should not be able to select nor drag and drop images in the app
#### Actual behavior

You can drag and drop app icons out of the manager page
#### Steps to reproduce the behavior
![jul-10-2018 11-25-14](https://user-images.githubusercontent.com/14826906/42501425-04aa2fca-8434-11e8-95cf-bae42ee82ddb.gif)

**Comment by gre** [comment]
EZ fix (incoming)
