### ISSUE TITLE
Add a dark mode to Ledger Live

### ISSUE THREAD

**Issue by Zerophase** [LedgerHQ/ledger-live-desktop#1025]
It would be nice if Ledger Live had a dark mode available. Being able to change text color, fonts, and background would be ideal in the future. But, just a default dark mode would be nice as well.

**Comment by Evgeniy6180** [comment]
I wish there was a dark interface mode in Ledger live!

**Comment by fishcharlie** [comment]
There is now dark mode support as well in Electron: https://electronjs.org/docs/tutorial/mojave-dark-mode-guide. Might also be able to use the `prefers-color-scheme` media query as well: https://caniuse.com/#feat=prefers-color-scheme.

**Comment by fishcharlie** [comment]
Although the new dark mode in Ledger Live is awesome, really a major let down that it doesn't respect the OS level dark mode setting by default...

**Comment by gre** [comment]
@fishcharlie  The support of "use system default" was always planned, sadly we're using a too old version of electron at the moment but we have plans to upgrade it.

**Comment by gre** [comment]
Closing this issue as the feature is shipped :)

**Comment by fishcharlie** [comment]
@gre Awesome! Glad there are plans to add that feature soon!! Great job to the entire team who made this happen!! Mobile app next? 🤔😛

**Comment by Evgeniy6180** [comment]
Hello!  Thank you so much for adding a black theme ... Now Ledger Leve
began to look very cool !!!  MANY THANKS TO YOU DEVELOPERS !!!

вс, 17 нояб. 2019 г., 23:53 Charlie Fish <notifications@github.com>:
