### ISSUE TITLE
Support for Ubiq (UBQ)

### ISSUE THREAD

**Issue by jskjorv** [LedgerHQ/ledger-live-desktop#1031]
Ubiq is not in the list for "add account" (Is in the manager)

**Comment by erikrijn** [comment]
I've noticed too. Could someone explain the reason for this?
And can Ubiq somehow help to make this possible?

**Comment by tobyjaguar** [comment]
I would advocate for its inclusion

**Comment by jyap808** [comment]
Hi, Ubiq devs are happy to discuss this further with the Ledger team. Thanks!

**Comment by digitalsleeper** [comment]
Yes, please add support for Ubiq.

**Comment by pioniere** [comment]
Please add support for Ubiq! Not having this in the new app is quite inconvenient.

**Comment by gre** [comment]
Thanks for the issue.
We're unifying integration requests into [#1560](https://github.com/LedgerHQ/ledger-live-desktop/issues/1560).

Please follow [#1560](https://github.com/LedgerHQ/ledger-live-desktop/issues/1560) for updates on what will be the process.
