### ISSUE TITLE
API HTTP 403 (Sorry, try again) | ERROR

### ISSUE THREAD

**Issue by Patrizius** [LedgerHQ/ledger-live-desktop#1035]
- Ledger Live 1.0.1
- Platform: Windows 10 Pro (Version: 10.0.17134 Build 17134)
- Ledger Nano S 

Whenever I want to open the Manager in the Main Screen under the Portfolio tab or add an account and select a crypto asset for example Bitcoin (same happens with altcoins) it tells me to "_Connect and unlock your Ledger device_", "_Navigate to the dashboard or an app on your device_". Those two steps successfully get the checkmark ✓ and after I instantly recieve an Error stating: "_! Sorry, try again (API HTTP 403)"_.
Clicking on the _Retry_ option will give me the same Error after two seconds.

I haven't encountered many posts online that describe this issue and I couldn't find a working solution to it, I tried reinstalling the program, setting up my Ledger Nano S again and even did a fresh Win10 installation. 
I also tried using my home LAN and WLAN connection plus resetting the router, in case it had something to do with my connection. 
Even disabling Windows Defender & Firewall didn't lead to any success.

My Ledger Nano S is running the latest firmware, checking my funds/sending/recieving btc and altcoins never caused any problems with the Chrome Browser apps.

![error1](https://user-images.githubusercontent.com/41090937/42543305-8a6b494c-84ab-11e8-809f-39ade48326c8.png)

**Comment by maciejbozemoj** [comment]
Hi @Patrizius , I have error on similar step, but my is kinda different "oops it seems internet is down". Im using Linux behind proxy. I'd like to know if you are using proxy on Windows. Then we could more specify title and description.

**Comment by Patrizius** [comment]
Hey @maciejbozemoj, no I wasn’t using a Proxy.

**Comment by Patrizius** [comment]
Hello @gre , thank you for your reply. I just tested it again, the error is still occuring for me, as of now.

**Comment by bergjs** [comment]
Happens for me two

**Comment by fdv** [comment]
Hello,

After investigating, there's nothing on the API itself. 

It looks like you have reached the HSM throttling limits for some reasons. Can someone here wait 36 hours between 2 tries and tell me if it works? (BTW the more you try, the longer the ban).

**Comment by bergjs** [comment]
Well that's unfortunate because I clicked "retry" a ton of times this morning. Will try again on Monday. Is the throttling based on IP or something else?

**Comment by Patrizius** [comment]
@bergjs @fdv Yes me too, I clicked "retry" a bunch of times as well, I am also gonna wait the weekend and retry on Monday after that I will report back with my results.

**Comment by Patrizius** [comment]
@gre @fdv @bergjs , Hello guys, I just wanted to inform you that I found out there is a 1.0.2 version, I updated my Ledger Live and retried. 
The Error is not showing up anymore, so I can't tell for 100% if only the waiting for 36h+ helped or also the new version (1.0.2) helped.

Thank you all for your investigation, all problems are solved for me for now. 
And I am glad that I can use your product again.

**Comment by gre** [comment]
i don't think there is anything that was fixed in 1.0.2 regarding that so I would guess it's the API.

in future, maybe we should write a better message

**Comment by bergjs** [comment]
I didn't update and it worked for me today as well. So I'd also assume that waiting for a couple of days did the trick. 👍

**Comment by douglasdeodato** [comment]
getting this error : Sorry, try again (API HTTP 403)
Interacting with Ledger's API server went wrong. Please retry.

having this on my mac, everything was fine just today I started get this error.

**Comment by douglasdeodato** [comment]
i am getting this error since yesterday, in my mac and windows machine, now I cant do any transaction, cant believe a multi millionaire company does not test the hardware well before release a version for the users, please get a better QA team.

**Comment by andrehortab2u** [comment]
When we going to have the solution?

**Comment by LeeMichael343** [comment]
I am having trouble with LedgerLive downloads freezing and not being able to open wallet, BCH and LTC. Uninstalled and then the new install won't work. Existing apps are fine.

**Comment by maciejbozemoj** [comment]
My issue still remain the same "Oops, internet seems down" on the step "Allow Ledger Manager on your device" I want to use ledger behind proxy. Stack trace:
`dev 3f0 / 304a : usage_page:2e34, usage:2f33
dev 3f0 / 304a : usage_page:2e34, usage:2f33
dev b0e / 306 : usage_page:2e34, usage:2f34
Checking for update
Sentry=> { extra: 
   { unhandledPromiseRejection: true,
     Error: 
      { code: 'ECONNRESET',
        path: null,
        host: '10.144.1.10',
        port: '8080',
        localAddress: undefined,
        config: [Object],
        request: [Object],
        response: undefined },
     node: 'v8.2.1' },
  message: 'Error: socket hang up',
  exception: [ { type: 'Error', value: 'socket hang up', stacktrace: [Object] } ],
  user: { ip_address: null, id: '5e0cd8ea-41c9-498a-b3f0-d838e1636834' },
  tags: {},
  breadcrumbs: { values: [] },
  request: {},
  modules: 
   { 'source-map-support': '0.5.6',
     'buffer-from': '1.1.0',
     invariant: '2.2.4',
     winston: '3.0.0',
     logform: '1.9.1',
     colors: '1.3.0',
     'triple-beam': '1.3.0',
     'readable-stream': '2.3.6',
     'process-nextick-args': '2.0.0',
     isarray: '1.0.0',
     'safe-buffer': '5.1.2',
     'core-util-is': '1.0.2',
     inherits: '2.0.3',
     'util-deprecate': '1.0.2',
     async: '2.6.1',
     lodash: '4.17.10',
     'is-stream': '1.1.0',
     diagnostics: '1.1.0',
     colorspace: '1.0.1',
     'color-string': '0.3.0',
     'color-name': '1.1.3',
     'text-hex': '0.0.0',
     enabled: '1.0.2',
     'env-variable': '0.0.4',
     kuler: '0.0.0',
     colornames: '0.0.2',
     'one-time': '0.0.4',
     'stack-trace': '0.0.10',
     'winston-transport': '4.2.0',
     'fast-safe-stringify': '2.0.4',
     moment: '2.22.2',
     'winston-daily-rotate-file': '3.2.3',
     semver: '5.5.0',
     'winston-compat': '0.1.4',
     cycle: '1.0.3',
     fecha: '2.3.3',
     'file-stream-rotator': '0.2.1',
     rxjs: '6.2.1',
     '@ledgerhq/hw-transport-node-hid': '4.18.0',
     'babel-runtime': '6.26.0',
     'core-js': '2.5.7',
     'regenerator-runtime': '0.11.1',
     'node-hid': '0.7.3',
     '@ledgerhq/hw-transport': '4.15.0',
     '@ledgerhq/hw-app-btc': '4.17.0',
     'create-hash': '1.2.0',
     '@ledgerhq/hw-app-eth': '4.15.0',
     eip55: '1.0.3',
     keccak: '1.4.0',
     bindings: '1.3.0',
     '@ledgerhq/hw-app-xrp': '4.15.0',
     'bip32-path': '0.4.2',
     axios: '0.18.0',
     'is-buffer': '1.1.6',
     'follow-redirects': '1.5.0',
     debug: '3.1.0',
     ms: '2.0.0',
     'supports-color': '3.2.3',
     'has-flag': '1.0.0',
     qs: '6.5.2',
     ws: '5.2.1',
     'async-limiter': '1.0.0',
     'ethereumjs-tx': '1.3.6',
     'ethereumjs-util': '5.2.0',
     rlp: '2.1.0',
     'bn.js': '4.11.8',
     'ethjs-util': '0.1.6',
     'is-hex-prefixed': '1.0.0',
     'strip-hex-prefix': '1.0.0',
     'ethereum-common': '0.0.18',
     'ripple-binary-codec': '0.1.13',
     'ripple-address-codec': '2.0.1',
     'hash.js': '1.1.4',
     'minimalistic-assert': '1.0.1',
     'x-address-codec': '0.7.2',
     'decimal.js': '5.0.8',
     raven: '2.6.3',
     cookie: '0.3.1',
     'timed-out': '4.0.1',
     md5: '2.2.1',
     crypt: '0.0.2',
     charenc: '0.0.2',
     '@ledgerhq/ledger-core': '2.0.0-rc.4' },
  environment: 'production',
  event_id: 'b50c37d0ce7149b2a5a329a280f4dcc5',
  timestamp: '2018-09-20T10:38:27',
  project: '274561',
  platform: 'node',
  release: '1.0.1' }
Found version 1.1.11 (url: ledger-live-desktop-1.1.11-linux-x86_64.AppImage)
Downloading update from ledger-live-desktop-1.1.11-linux-x86_64.AppImage
No cached update info available
raven@2.6.3 alert: failed to send exception to sentry: Connection timed out on request to sentry.io
raven@2.6.3 alert: failed to send exception to sentry: socket hang up
File has 3391 changed blocks
Full: 77,724.05 KB, To download: 69,229.25 KB (89%)
Differential download: https://github.com/LedgerHQ/ledger-live-desktop/releases/download/v1.1.11/ledger-live-desktop-1.1.11-linux-x86_64.AppImage
Redirect to https://github-production-release-asset-2e65be.s3.amazonaws.com/82679495/6e8f8900-b74f-11e8-9874-a8f7633fb135
`

**Comment by meriadec** [comment]
@maciejbozemoj as said proxy is clearly the issue here, so the workaround is.. not use proxy. If you have a fix/hints to provide we would be happy to merge PR. Socket job is done here: [src/helpers/socket.js](https://github.com/LedgerHQ/ledger-live-desktop/blob/develop/src/helpers/socket.js).

**Comment by maciejbozemoj** [comment]
@meriadec I'm behind corporate proxy, I can't access anything without this. I'm afraid I can't disable proxy for all my company. Ok I will take a look.

**Comment by piucham** [comment]
Oops, internet seems down 
1 year has happened and still I cannot use the updated ledger live and it continues without working, I have the application ledger live in the telephone and still it does not work. The one who can help me please?

**Comment by gre** [comment]
sorry I misunderstood your error. Do you have HTTP 403 ? please contact our tech support.

**Comment by piucham** [comment]
I have windows 10 pro v1803

**Comment by vaibhavmuchandi** [comment]
Facing the same issue on Linux, anyone got it resolved ?

**Comment by UNIcodeX** [comment]
Getting this for TRX sync on Ledger Live Mobile.

**Comment by serkanutku** [comment]
> Getting this for TRX sync on Ledger Live Mobile.

same here. eth is fine but i cannot sync with TRX.

**Comment by harrypnyce** [comment]
`Ledger Live v2.26.1
firmware v1.6.1
Windows 10 Pro v20H2`

Same issue as @UNIcodeX & @serkanutku just recently started getting sync errors ONLY with `TRX` account, which was added somewhat recently and may or may not remain empty (i can't tell, because I'm getting **APT HTTP 403 Synchronization error** and no amount of refreshes seems to help).

**Comment by 77xrp** [comment]
> `Ledger Live v2.26.1 firmware v1.6.1 Windows 10 Pro v20H2`
> 
> Та же проблема, что и у @UNIcodeX и @serkanutku, только недавно начали получать ошибки синхронизации ТОЛЬКО с `TRX`учетной записью, которая была добавлена ​​недавно и может или не может оставаться пустой (я не могу сказать, потому что я получаю **ошибку синхронизации APT HTTP 403** и нет суммы обновлений вроде помогает).
> 
> ![изображение](https://user-images.githubusercontent.com/32494212/116931260-c8aa2900-ac2e-11eb-87c1-e9af8df707cb.png)
> [РЕДАКТИРОВАТЬ: добавлен современный график ошибок, для акцента и на всякий случай, если кому-то посчастливится НЕ быть знакомым]

Такая же проблема сегодня произошла после обновления новои версии 2.26.1. После закинул на леджер лайв TRX много. Час назад обнаружыл ошибку синхронизации только трон. API HTTP 403.
