### ISSUE TITLE
Request to remove "Exchanges" Tab

### ISSUE THREAD

**Issue by ktechmidas** [LedgerHQ/ledger-live-desktop#1045]
It is blatantly silly to favour any exchanges for a hardware wallet, you're going to have all kinda of small & shitty exchanges contacting Ledger wanting to get listed there and willing to pay for it. You're going to have people like me wondering why on Earth binance isn't there...

People will blame ledger if they use anything from the exchanges tab and it goes wrong/bankrupt/whatever opening Ledger up to potential issues. Listing Changelly for example, while they blatantly accept transactions to XMR then ask for KYC later a person could argue they used it because Ledger recommended it.

Anyone who owns a hardware wallet already knows some big name exchanges or can search if they need otherwise.

#### Ledger Live Version

- Ledger Live 1.0.1

#### Part of the application to improve

Exchanges

**Comment by meriadec** [comment]
Hello, the Exchange page code is located [here](https://github.com/LedgerHQ/ledger-live-desktop/tree/develop/src/components/ExchangePage), so if having that page bother you, I would recommend you to build your own version of the app :wink: 

Have a good day :rose:
