### ISSUE TITLE
Add the possibility to launch the onboarding once again

### ISSUE THREAD

**Issue by EricLarch** [LedgerHQ/ledger-live-desktop#1055]
A user can have more than one device. Relaunching the onboarding is necessary to either check the integrity of further devices, or get help to restore/initialize another device.

This option could be available from a button located in the settings.

**Comment by EricLarch** [comment]
In the section **Help** of the app settings, add at the bottom a new section.

**Onboarding**
Launch again the onboarding to add a new device to the Ledger Live application

Button: **Launch**

**Comment by gre** [comment]
@NastiaS can you assess the implication of such a feature?
I suspect strange thing will happen on Password screen..

IMO such a feature should not have the two last steps (password, analytics), do you concur @EricLarch ? 🤔

**Comment by NastiaS** [comment]
Yes, it does seem a bit awkward to ask the same user about Password and Analytics again in the context of the same app. Some steps of the onboarding are not relevant to the device. I am looking into filtering some steps for this case.
