### ISSUE TITLE
Detect & document Linux USB connection issues

### ISSUE THREAD

**Issue by meriadec** [LedgerHQ/ledger-live-desktop#1057]
Some Linux distributions (all?) require adding custom udev rules to correctly communicate with the device.

If the rules are not present, the device can be detected but interacting with it (e.g: checking if an app is opened) will fail. We may be able to detect the problem, and at minimum display an understandable error, and better: provide a link to [the help page with full instructions](https://support.ledgerwallet.com/hc/en-us/articles/115005165269-Connection-issues-with-Windows-or-Linux).

**Comment by ryanpaulfyfe** [comment]
Thanks, yes this resolved the issue, if doing this on behalf of the user is not an option, then recommend adding this directly into the UI as an instruction for linux users, like: "Having trouble connecting on linux?"

Either way, thanks for the quick response! New Live App is great, Can't wait to see ERC20 support in it ;)
