### ISSUE TITLE
Show last 5 release notes in the update modal

### ISSUE THREAD

**Issue by EricLarch** [LedgerHQ/ledger-live-desktop#1061]
Just after an update, or when click on the "Details" button
![image](https://user-images.githubusercontent.com/1017848/42585841-fa0bfd4c-8536-11e8-8054-3c4911472217.png)
a modal with release notes is shown. It should show the last 5 release notes instead of just the last one.

**Comment by gre** [comment]
totally agree. what do you think about actually filtering to only show the patches?
for instance for 1.0.2 we will display the release notes of 1.0.2, 1.0.1 and 1.0.0
it will always just be 1.0.x . and for next minor 1.1.x etc.. 
this would prevent displaying the release notes of unrelevant parts like rc, beta, 🤔
