### ISSUE TITLE
Remove region from the settings

### ISSUE THREAD

**Issue by EricLarch** [LedgerHQ/ledger-live-desktop#1063]
The region popup is quite confusing, since it depends of the language selected. We need to remove it, and use the timezone of the host computer.

**Comment by gre** [comment]
we already use the timezone of the host computer actually. it's a wording issue.
region is used in a very minor way today, and have a minor role in determining the formatting of numbers etc.. but we also rely on what Electron support so i don't think removing it will have a big impact.. 

On the bigger picture, i actually think it would be better to have control on what's happening with your app, including:

- a number format settings (so you can chose among: `USD 1,000.00` / `1 000.00` / `1000,00` `EUR 1 000,00`  , these are just random example basically meaning using predefered "locale reference" by default init to the system locale )
- a date format settings (so you can chose among: `YYYY/MM/DD` / `YYYY/DD/MM` or whatever choices there is  )

**Comment by gre** [comment]
probably more for 1.1.0, need to discuss with the team on monday. and we should have the 1.0.2 asap (ideally friday)
