### ISSUE TITLE
Set the standard fee at 1 sat per byte for Bitcoin Cash

### ISSUE THREAD

**Issue by EricLarch** [LedgerHQ/ledger-live-desktop#1064]
Right now, it is at 10 sat per byte

**Comment by gre** [comment]
(not sure if we should track the API related tasks here)

**Comment by EricLarch** [comment]
I did it as it's a request from the BCH community and it's important to show we are taking it into account.

**Comment by gre** [comment]
make sense :)

**Comment by pollastri-pierre** [comment]
This issue is fixed, but we have another bug regarding fees https://github.com/LedgerHQ/ledger-live-desktop/issues/1099

Therefore if users click on "Send" in the left menu, and select a BCH account (or any currencies) it will keep the already loaded fees.
