### ISSUE TITLE
Max password length is 20, while google allow 60 chars, and facebook 1000 chars+

### ISSUE THREAD

**Issue by Incog5** [LedgerHQ/ledger-live-desktop#1066]
https://github.com/LedgerHQ/ledger-live-desktop/blob/142d9d9c34034fdb6d76679405c09fb6a0160fe8/src/components/base/InputPassword/index.js#L61

**Comment by Luuk2016** [comment]
I think that most of the times a maximum of 20 is enough.
You don't use the password to confirm/send transactions, you only use it for viewing your balances.
Maybe increase it to 30 or so. But 60 or 1000+ is overkill.

**Comment by gre** [comment]
good point.
hopefully this will be fixed in 1.0.2. was fixed in our develop branch
