### ISSUE TITLE
Bitcoin Cash account can be added without opening the specific app

### ISSUE THREAD

**Issue by Luuk2016** [LedgerHQ/ledger-live-desktop#1076]
#### Ledger Live Version and Operating System

- Ledger Live 1.0.1
- Platform: Windows 10

#### Expected behavior

Retrieve an error that the wrong app has been opened.

#### Actual behavior

The app will get added if the Bitcoin app has been opened.
Is this a bug or is this normal?
I would say that you can only add an account with the specific app.

#### Steps to reproduce the behavior

Click on add new account.
Click on "Bitcoin Cash".
Open the normal "Bitcoin" app on the Ledger.
Wait for the sync.
Click on add account.

**Comment by gre** [comment]
This is a technical limitation. We currently have no way to diffenciate between the Bitcoin app and Bitcoin Cash app on the device. We will address in the future. Hopefully it's the only case this happen across all other applications.

**Comment by gre** [comment]
We expect this to be fixed in context of a big rework that just got merged. we'll reopen in this does not fix in the next release https://github.com/LedgerHQ/ledger-live-desktop/pull/2596
