### ISSUE TITLE
PivX chain doesn't sync

### ISSUE THREAD

**Issue by JanDs2nd** [LedgerHQ/ledger-live-desktop#1089]
#### Ledger Live Version and Operating System

- Ledger Live 1.0.1
- Platform: MAC

#### Expected behavior

Add a new account for PivX

#### Actual behavior

Not possible to add the account, error Message:
"Something went wrong during synchronization, pls try again.
With the legacy Chrome App it works and PivX Balance is shown.

#### Steps to reproduce the behavior

![bildschirmfoto 2018-07-12 um 15 39 46](https://user-images.githubusercontent.com/32761292/42637014-6814ec96-85ea-11e8-8c84-ed7252cde7f9.png)

**Comment by gre** [comment]
Can you tell which Mac version you are on? thanks

**Comment by JanDs2nd** [comment]
![bildschirmfoto 2018-07-12 um 18 05 31](https://user-images.githubusercontent.com/32761292/42645422-3ac628a4-85fe-11e8-8083-e8bae341c771.png)
i did already clear the cache, uninstall, reinstall doesn't work so far...
Thanks 
Jan

**Comment by KhalilBellakrid** [comment]
@JanDs2nd could you please provide your log files located in `Library/Application Support/Ledger Live` ? 
Be sure to not provide any personal info in it !
Thanks

**Comment by JanDs2nd** [comment]
Hi, 
hope that helps:
`
{"type":"libcore","level":"info","message":"🛠  Info: 2018-07-13T11:46:35Z+02:00 I: Building wallet instance ‚XXXXX__pivx' for pivx with parameters: \n","pname":"internal","timestamp":"2018-07-13T09:46:35.304Z"}
{"type":"libcore","level":"info","message":"🛠  Info: 2018-07-13T11:46:35Z+02:00 I: Starting synchronization for account#0 (ToXXXXXap) of wallet XXXXXx__pivx at 2018-07-13T09:46:35Z\n","pname":"internal","timestamp":"2018-07-13T09:46:35.392Z"}
{"type":"network","level":"info","message":"➡📡  GET https://explorers.api.live.ledger.com/blockchain/v2/pivx/blocks/current","pname":"internal","timestamp":"2018-07-13T09:46:35.401Z"}
{"type":"libcore","level":"info","message":"🛠  Info: 2018-07-13T11:46:35Z+02:00 I: GET https://explorers.api.live.ledger.com/blockchain/v2/pivx/blocks/current\n","pname":"internal","timestamp":"2018-07-13T09:46:35.401Z"}
{"type":"network","level":"info","message":"➡📡  GET https://explorers.api.live.ledger.com/blockchain/v2/pivx/syncToken","pname":"internal","timestamp":"2018-07-13T09:46:35.404Z"}
{"type":"libcore","level":"info","message":"🛠  Info: 2018-07-13T11:46:35Z+02:00 I: GET https://explorers.api.live.ledger.com/blockchain/v2/pivx/syncToken\n","pname":"internal","timestamp":"2018-07-13T09:46:35.405Z"}
{"type":"network","level":"info","message":"➡📡  GET https://explorers.api.live.ledger.com/blockchain/v2/pivx/blocks/current","pname":"internal","timestamp":"2018-07-13T09:46:35.410Z"}
{"type":"libcore","level":"info","message":"🛠  Info: 2018-07-13T11:46:35Z+02:00 I: GET https://explorers.api.live.ledger.com/blockchain/v2/pivx/blocks/current\n","pname":"internal","timestamp":"2018-07-13T09:46:35.410Z"}
{"type":"network-response","level":"info","message":"✔📡  HTTP 200 GET https://explorers.api.live.ledger.com/blockchain/v2/pivx/blocks/current – finished in 320ms","pname":"internal","timestamp":"2018-07-13T09:46:35.720Z"}
{"type":"libcore","level":"info","message":"🛠  Info: 2018-07-13T11:46:35Z+02:00 I: GET https://explorers.api.live.ledger.com/blockchain/v2/pivx/blocks/current - 200 OK\n","pname":"internal","timestamp":"2018-07-13T09:46:35.721Z"}
{"type":"network-response","level":"info","message":"✔📡  HTTP 200 GET https://explorers.api.live.ledger.com/blockchain/v2/pivx/syncToken – finished in 356ms","pname":"internal","timestamp":"2018-07-13T09:46:35.761Z"}
{"type":"libcore","level":"info","message":"🛠  Info: 2018-07-13T11:46:35Z+02:00 I: GET https://explorers.api.live.ledger.com/blockchain/v2/pivx/syncToken - 200 OK\n","pname":"internal","timestamp":"2018-07-13T09:46:35.761Z"}
{"type":"libcore","level":"info","message":"🛠  Info: 2018-07-13T11:46:35Z+02:00 I: Synchronization token obtained\n","pname":"internal","timestamp":"2018-07-13T09:46:35.764Z"}
{"type":"libcore","level":"info","message":"🛠  Info: 2018-07-13T11:46:35Z+02:00 I: SYNC BATCHES\n","pname":"internal","timestamp":"2018-07-13T09:46:35.764Z"}
{"type":"libcore","level":"info","message":"🛠  Info: 2018-07-13T11:46:35Z+02:00 I: Synchronize batch 0 started.\n","pname":"internal","timestamp":"2018-07-13T09:46:35.765Z"}
{"type":"libcore","level":"info","message":"🛠  Info: 2018-07-13T11:46:35Z+02:00 I: SYNC BATCH 0\n","pname":"internal","timestamp":"2018-07-13T09:46:35.766Z"}
{"type":"libcore","level":"info","message":"🛠  Info: 2018-07-13T11:46:35Z+02:00 I: Batch derivation started.\n","pname":"internal","timestamp":"2018-07-13T09:46:35.766Z"}
{"type":"libcore","level":"info","message":"🛠  Info: 2018-07-13T11:46:35Z+02:00 I: Batch derivation took 0:0:0.4.\n","pname":"internal","timestamp":"2018-07-13T09:46:35.771Z"}
{"type":"libcore","level":"info","message":"🛠  Info: 2018-07-13T11:46:35Z+02:00 I: Get batch started.\n","pname":"internal","timestamp":"2018-07-13T09:46:35.771Z"}
{"type":"network","level":"info","message":"➡📡  GET https://explorers.api.live.ledger.com/blockchain/v2/pivx/addresses/<HIDDEN>/transactions","pname":"internal","timestamp":"2018-07-13T09:46:35.772Z"}
{"type":"libcore","level":"info","message":"🛠  Info: 2018-07-13T11:46:35Z+02:00 I: GET https://explorers.api.live.ledger.com/blockchain/v2/pivx/addresses/XXXXXj/transactions\n","pname":"internal","timestamp":"2018-07-13T09:46:35.772Z"}
{"type":"network-response","level":"info","message":"✔📡  HTTP 200 GET https://explorers.api.live.ledger.com/blockchain/v2/pivx/blocks/current – finished in 368ms","pname":"internal","timestamp":"2018-07-13T09:46:35.778Z"}
{"type":"libcore","level":"info","message":"🛠  Info: 2018-07-13T11:46:35Z+02:00 I: GET https://explorers.api.live.ledger.com/blockchain/v2/pivx/blocks/current - 200 OK\n","pname":"internal","timestamp":"2018-07-13T09:46:35.778Z"}
{"type":"network-response","level":"info","message":"✔📡  HTTP 200 GET https://explorers.api.live.ledger.com/blockchain/v2/pivx/addresses/<HIDDEN>/transactions – finished in 350ms","pname":"internal","timestamp":"2018-07-13T09:46:36.121Z"}
{"type":"libcore","level":"info","message":"🛠  Info: 2018-07-13T11:46:36Z+02:00 I: GET https://explorers.api.live.ledger.com/blockchain/v2/pivx/addresses/XXXXXXj/transactions - 200 OK\n","pname":"internal","timestamp":"2018-07-13T09:46:36.121Z"}
{"type":"libcore","level":"info","message":"🛠  Info: 2018-07-13T11:46:36Z+02:00 I: Get batch took 0:0:0.354.\n","pname":"internal","timestamp":"2018-07-13T09:46:36.125Z"}
{"type":"libcore","level":"info","message":"🛠  Info: 2018-07-13T11:46:36Z+02:00 I: Transaction computation started.\n","pname":"internal","timestamp":"2018-07-13T09:46:36.125Z"}
{"type":"libcore","level":"info","message":"🛠  Error: 2018-07-13T11:46:36Z+02:00 E: Error during during synchronization for account#0 of wallet XXXXX__pivx in 1000 ms\n","pname":"internal","timestamp":"2018-07-13T09:46:36.148Z"}
{"type":"libcore","level":"info","message":"🛠  Error: 2018-07-13T11:46:36Z+02:00 E: Due to RUNTIME_ERROR, Dynamic exception type: soci::sqlite3_soci_error\nstd::exception::what: sqlite3_statement_backend::loadOne: UNIQUE constraint failed: bitcoin_inputs.uid\n (RUNTIME_ERROR)\n","pname":"internal","timestamp":"2018-07-13T09:46:36.148Z"}
{"level":"warn","message":"Command error:","pname":"internal","timestamp":"2018-07-13T09:46:36.150Z"}
{"type":"cmd.ERROR","data":"Dynamic exception type: soci::sqlite3_soci_error\nstd::exception::what: sqlite3_statement_backend::loadOne: UNIQUE constraint failed: bitcoin_inputs.uid\n (RUNTIME_ERROR)","level":"warn","message":"✖ CMD libcoreScanAccounts error","pname":"internal","timestamp":"2018-07-13T09:46:36.150Z"}
{"type":"cmd.ERROR","data":"Dynamic exception type: soci::sqlite3_soci_error\nstd::exception::what: sqlite3_statement_backend::loadOne: UNIQUE constraint failed: bitcoin_inputs.uid\n (RUNTIME_ERROR)","level":"warn","message":"✖ CMD libcoreScanAccounts error","pname":"renderer","timestamp":"2018-07-13T09:46:36.151Z"}
{"type":"action","action":{"type":"MODAL_CLOSE","payload":{"name":"MODAL_ADD_ACCOUNTS"}},"level":"info","message":"⚛️  MODAL_CLOSE","pname":"renderer","timestamp":"2018-07-13T09:46:41.390Z"}
{"type":"anaytics-track","properties":{},"level":"info","message":"△ track CloseModalAddAccounts","pname":"renderer","timestamp":"2018-07-13T09:46:41.884Z"}
{"level":"info","message":"killing internal process...","pname":"main","timestamp":"2018-07-13T09:46:45.207Z"}
{"type":"cmd.ERROR","data":{"message":"Internal process error (null)","name":"InternalError"},"level":"warn","message":"✖ CMD listenDevices error","pname":"renderer","timestamp":"2018-07-13T09:46:45.302Z"}
`

**Comment by KhalilBellakrid** [comment]
I have additional questions:

- Did you use older versions of app before the official release (1.0.0)? 

- Did you import other accounts on other cryptos before getting this error (like Dash)? 

If the answer is yes for the first question then please remove your `Library/Application Support/Ledger Live` directory and relaunch the app, it should fix the problem !

**Comment by JanDs2nd** [comment]
Question 1: no
Question 2: yes: BTC, ETH... works fine.
i've deleted /Ledger Live, restarted app, but no change same error.

**Comment by KhalilBellakrid** [comment]
To sum up:

1. Removing `Library/Application Support/Ledger Live`,

2. Launching the app,

3. Importing PIVX accounts

reproduces the bug ? Or are you importing other accounts before importing PIVX ? 

Thanks !

**Comment by KhalilBellakrid** [comment]
Alright thank you for testing.
I think we'll need a private channel (slack, mail ...), get your PIVX xpub, scan accounts and then reproduce the bug.
Because we can't reproduce from ou side !

**Comment by JanDs2nd** [comment]
Thank u for your patience. i can join your slack channel, which one is it?
Jan

**Comment by KhalilBellakrid** [comment]
Actually the best way is to send a message to our support team : https://support.ledgerwallet.com/hc/en-us/requests/new
You can attach this issue and your xpub to your request.
Thanks !

**Comment by JanDs2nd** [comment]
Hi, 
question: how can i extract my pivx xpub?
Meanwhile i updated to Livewallet 1.4.2, which result in a new error Message:
![bildschirmfoto 2018-07-17 um 20 40 01](https://user-images.githubusercontent.com/32761292/42838767-f7d59dc4-8a01-11e8-8000-36fa17aaf1fa.png)

**Comment by KhalilBellakrid** [comment]
Since error occurs at import the only way is to export your logs (from settings) you'll find your xpub there ! 
Thank you

**Comment by JanDs2nd** [comment]
I've sent it. 
Thanks!

**Comment by KhalilBellakrid** [comment]
@JanDs2nd thank you, I received it!
I reproduced your issue and actually this is due to the Zero-Knowledge protocol (basically no transaction history available) implemented by Pivx and since we rely on previous transaction hash (which is not available here) to compute bitcoin_inputs' uids this fails ! So we have to support this new kind of transactions
We'll work on a fix and let you know when a fix is available !

**Comment by JanDs2nd** [comment]
Thanks!
Really excellent support Guys!

**Comment by meriadec** [comment]
Hey @lubinalubina thanks for the feedback and sorry for the experience you got :(
There is definitely things to improve in the process, the project has been launched very recently so it can leads to misunderstandings and communication problems. Expect this to be better in the next months :)

**Comment by ElvisPresly** [comment]
I have the same problem. In the beginning Pivx has ceased to be synchronized, now Ledger Live isn't synchronized at all.
![screen shot 2018-08-01 at 19 50 10 pm](https://user-images.githubusercontent.com/18265958/43536098-696a22d4-95c4-11e8-85f2-7d26921d2c3d.png)

**Comment by meriadec** [comment]
We pushed a pre-release including a fix for that specific case.
You can test it right now from here: https://github.com/LedgerHQ/ledger-live-desktop/releases/tag/v1.1.6

It should be released on monday.

**Comment by KhalilBellakrid** [comment]
Hello @JanDs2nd @lubinalubina @ElvisPresly ,
Could you please test latest release (1.1.6) and see if the issue is fixed? 
Thank you !

**Comment by lubinalubina** [comment]
It now works for me. Thanks for the fix!

13. Aug 2018 11:31 by notifications@github.com <mailto:notifications@github.com>:

**Comment by meriadec** [comment]
Great job @KhalilBellakrid ! :tada: 

bye unique constraint :wave:

**Comment by JanDs2nd** [comment]
Works for me Too!
Thx Guys!
