### ISSUE TITLE
See what apps are already installed in the manager

### ISSUE THREAD

**Issue by Luuk2016** [LedgerHQ/ledger-live-desktop#1092]
- [x] I have checked this feature was not yet requested.

It would be great to see what apps are already installed on the Ledger.

#### Part of the application

The manager

**Comment by drizzt** [comment]
and also which application are outdated and can be updated

**Comment by EricLarch** [comment]
It will be possible with the upcoming 1.5 Nano S firmware update scheduled for end of Q3

**Comment by gre** [comment]
We expect this to be fixed in context of a big rework that just got merged. we'll reopen in this does not fix in the next release https://github.com/LedgerHQ/ledger-live-desktop/pull/2596
