### ISSUE TITLE
Selecting accounts in send modal doesn't refresh fees

### ISSUE THREAD

**Issue by pollastri-pierre** [LedgerHQ/ledger-live-desktop#1099]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.0.1
- Platform and version: Mac 10.12.6

#### Expected behavior

When clicking on send (on the left panel), the application automatically select the first account and fetch the fees. If I select another account, the app should refresh its fees for the selected currency.

#### Actual behavior

Selecting other accounts doesn't refresh the fees and keeps the former one.

#### Steps to reproduce the behavior

1 - Click on "Send" on the left menu
2 - Change account by using the select

**Comment by gre** [comment]
good catch
