### ISSUE TITLE
Add "copy error" on multiple places

### ISSUE THREAD

**Issue by meriadec** [LedgerHQ/ledger-live-desktop#1111]
To be discussed with design, but we may want to give users ability to copy error stack to clipboard directly when it shows up, for example in an import step, etc.

e.g:

<img width="495" alt="screen shot 2018-07-13 at 15 30 19" src="https://user-images.githubusercontent.com/315259/42694608-4fcbfc96-86b3-11e8-9de0-ebedc8c35b69.png">

**Comment by gre** [comment]
or maybe Export button 🤔

**Comment by gre** [comment]
I mean, it's not really useful to copy text. I prefer either users to send us Screenshot or to send us Logs.

**Comment by gre** [comment]
Explore logs kinda cover that. We'll assume it's good enough for now
