### ISSUE TITLE
Bitcoin Cash adding New or Split Account Error

### ISSUE THREAD

**Issue by tharp94895** [LedgerHQ/ledger-live-desktop#1121]
Ledger Live Version and Operating System
Ledger Live 1.0.2
Platform: Windows 10 1803
Expected behavior
Add a New or Split accounts to Ledger Live

Actual behavior
The app will get stuck on "Synchronizing" from the "Add account" menu 
Is this a bug or is this normal?
Bug

Steps to reproduce the behavior
Click on add new account.
Click on "Bitcoin Cash".
Open the "Bitcoin Cash" app on the Ledger.
Wait for the sync.
Already added accounts in portfolio will show the accounts already added.
It will hang here and won't go any further.

**Comment by gre** [comment]
can you screenshot the state you are in? I'm not sure to understand, you basically don't see a section "Add a new Account" but it's still spinning?

<img width="501" alt="capture d ecran 2018-07-16 a 09 05 17" src="https://user-images.githubusercontent.com/211411/42746291-681ea02a-88d7-11e8-992d-f5aaef3c5a06.png">

**Comment by tharp94895** [comment]
This is what I am seeing without it progressing any further. It's been sitting in this state for about 30min now without progressing.

![image](https://user-images.githubusercontent.com/14061331/42762156-21b5bce2-88d5-11e8-9ab0-f855b5a66369.png)

**Comment by gre** [comment]
cc @KhalilBellakrid

**Comment by tharp94895** [comment]
Any progress being made on this? Need more info on my side of things? Still seeing the same on 1.0.3

**Comment by KhalilBellakrid** [comment]
Unfortunately we can't reproduce the issue from our side, could you please export your logs and send them to us ?

**Comment by tharp94895** [comment]
This is an older one. The log from today just crashed. I'll send log from 1.0.3 in a bit.

[ledgerlive-export-2018.07.09-15.12.30-c7c5c51e1dd0136251485114e6020ab354789a23.log](https://github.com/LedgerHQ/ledger-live-desktop/files/2203214/ledgerlive-export-2018.07.09-15.12.30-c7c5c51e1dd0136251485114e6020ab354789a23.log)

**Comment by tharp94895** [comment]
JSON format was restricting the upload... see attached.

[ledgerlive-export-2018.07.17-15.01.13-e22b31b14f1a604a954bf1ef66405cf07b354a88.txt](https://github.com/LedgerHQ/ledger-live-desktop/files/2203234/ledgerlive-export-2018.07.17-15.01.13-e22b31b14f1a604a954bf1ef66405cf07b354a88.txt)

**Comment by gre** [comment]
[ GRE: i've removed it for privacy, we'll soon have a way to send logs privately, meanwhile please don't send on Github ]

**Comment by KhalilBellakrid** [comment]
Hello @tharp94895, 
Could you please test if you still have the issue with BTC on Live with this pre-release : https://github.com/LedgerHQ/ledger-live-desktop/releases/tag/v1.1.7 ? 
Thank you !

**Comment by meriadec** [comment]
feel free to re-open if the issue persists
