### ISSUE TITLE
Advanced settings to enable creation of legacy accounts

### ISSUE THREAD

**Issue by gre** [LedgerHQ/ledger-live-desktop#1129]

**Comment by EricLarch** [comment]
A toggle "Expert mode" in the settings to unlock a few advanced features and/or and "Advanced settings" is a good idea.

Some features:

- enable creation of legacy accounts
- enter a path in the import modal to scan arbitrary accounts
- raise the 20 BIP44 limit to scan accounts

**Comment by gre** [comment]
I think an Advanced section of settings would be great yeah. we could already move "Developer mode" there ^^

**Comment by gre** [comment]
let's make sure to create one issue per subject
