### ISSUE TITLE
No Icon and Error after start MAC-OS

### ISSUE THREAD

**Issue by martin8573** [LedgerHQ/ledger-live-desktop#1142]
#### Ledger Live Version and Operating System

- tested on Ledger Live ****ledger-live-desktop-1.0.1-mac
- Platform and version: **Mac OSX Yosemite 10.10.5 **

#### Expected behavior

---

#### Actual behavior

<Installer shows no icon, error after program start...-->
![bildschirmfoto 2018-07-15 um 19 26 29](https://user-images.githubusercontent.com/7840093/42736329-6b464360-8865-11e8-993a-4c14450f986b.png)
![bildschirmfoto 2018-07-15 um 19 27 53](https://user-images.githubusercontent.com/7840093/42736331-6e149a10-8865-11e8-87c1-35181afef911.png)
[ledgerlive-export-2018.07.15-19.27.36-c7c5c51e1dd0136251485114e6020ab354789a23.log](https://github.com/LedgerHQ/ledger-live-desktop/files/2195948/ledgerlive-export-2018.07.15-19.27.36-c7c5c51e1dd0136251485114e6020ab354789a23.log)

`{"type":"db","level":"info","message":"📁  read user","pname":"main","timestamp":"2018-07-15T17:27:26.439Z"}
{"type":"db","level":"info","message":"📁  write user","pname":"main","timestamp":"2018-07-15T17:27:26.457Z"}
{"level":"info","message":"booting internal process...","pname":"main","timestamp":"2018-07-15T17:27:28.499Z"}
{"type":"db","level":"info","message":"📁  read migrations","pname":"renderer","timestamp":"2018-07-15T17:27:28.390Z"}
{"type":"db","level":"info","message":"📁  write migrations","pname":"renderer","timestamp":"2018-07-15T17:27:28.399Z"}
{"type":"db","level":"info","message":"📁  read settings","pname":"renderer","timestamp":"2018-07-15T17:27:28.425Z"}
{"type":"action","action":{"type":"FETCH_SETTINGS","payload":{}},"level":"info","message":"⚛️  FETCH_SETTINGS","pname":"renderer","timestamp":"2018-07-15T17:27:28.426Z"}
{"type":"db","level":"info","message":"📁  write settings","pname":"renderer","timestamp":"2018-07-15T17:27:28.433Z"}
{"type":"db","level":"info","message":"📁  read countervalues","pname":"renderer","timestamp":"2018-07-15T17:27:28.444Z"}
{"type":"db","level":"info","message":"📁  read user","pname":"renderer","timestamp":"2018-07-15T17:27:28.451Z"}
{"type":"db","level":"info","message":"📁  read accounts","pname":"renderer","timestamp":"2018-07-15T17:27:28.476Z"}
{"type":"action","action":{"type":"SET_ACCOUNTS","payload":[]},"level":"info","message":"⚛️  SET_ACCOUNTS","pname":"renderer","timestamp":"2018-07-15T17:27:28.476Z"}
{"type":"action","action":{"type":"@@router/LOCATION_CHANGE","payload":{"pathname":"/","search":"","hash":""}},"level":"info","message":"⚛️  @@router/LOCATION_CHANGE","pname":"renderer","timestamp":"2018-07-15T17:27:28.489Z"}
{"level":"info","message":"info","pname":"renderer","timestamp":"2018-07-15T17:27:28.499Z"}
{"level":"info","message":"info","pname":"renderer","timestamp":"2018-07-15T17:27:28.500Z"}
{"type":"anaytics-track","properties":{},"level":"info","message":"△ track App Starts","pname":"renderer","timestamp":"2018-07-15T17:27:28.542Z"}
{"type":"anaytics-page","properties":{},"level":"info","message":"△ page Onboarding Start","pname":"renderer","timestamp":"2018-07-15T17:27:28.560Z"}
{"level":"info","message":"Internal process is up!","pname":"internal","timestamp":"2018-07-15T17:27:29.086Z"}
{"level":"info","message":"info","pname":"internal","timestamp":"2018-07-15T17:27:29.104Z"}
{"level":"info","message":"info","pname":"internal","timestamp":"2018-07-15T17:27:29.119Z"}
{"level":"warn","message":"Command error:","pname":"internal","timestamp":"2018-07-15T17:27:29.134Z"}
{"type":"cmd.ERROR","data":{},"level":"warn","message":"✖ CMD libcoreGetVersion error","pname":"internal","timestamp":"2018-07-15T17:27:29.134Z"}
{"type":"cmd.ERROR","data":{"message":"dlopen(/Applications/Ledger Live.app/Contents/Resources/app.asar.unpacked/node_modules/@ledgerhq/ledger-core/build/Release/ledger-core-node.node, 1): Library not loaded: @rpath/libledger-core.dylib\n  Referenced from: /Applications/Ledger Live.app/Contents/Resources/app.asar.unpacked/node_modules/@ledgerhq/ledger-core/build/Release/ledger-core-node.node\n  Reason: no suitable image found.  Did find:\n\t/Applications/Ledger Live.app/Contents/Resources/app.asar.unpacked/node_modules/@ledgerhq/ledger-core/build/Release/libledger-core.dylib: code signature invalid for '/Applications/Ledger Live.app/Contents/Resources/app.asar.unpacked/node_modules/@ledgerhq/ledger-core/build/Release/libledger-core.dylib'\n","name":"Error","stack":"Error: dlopen(/Applications/Ledger Live.app/Contents/Resources/app.asar.unpacked/node_modules/@ledgerhq/ledger-core/build/Release/ledger-core-node.node, 1): Library not loaded: @rpath/libledger-core.dylib\n  Referenced from: /Applications/Ledger Live.app/Contents/Resources/app.asar.unpacked/node_modules/@ledgerhq/ledger-core/build/Release/ledger-core-node.node\n  Reason: no suitable image found.  Did find:\n\t/Applications/Ledger Live.app/Contents/Resources/app.asar.unpacked/node_modules/@ledgerhq/ledger-core/build/Release/libledger-core.dylib: code signature invalid for '/Applications/Ledger Live.app/Contents/Resources/app.asar.unpacked/node_modules/@ledgerhq/ledger-core/build/Release/libledger-core.dylib'\n\n    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)\n    at Object.Module._extensions..node (module.js:598:18)\n    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)\n    at Module.load (module.js:503:32)\n    at tryModuleLoad (module.js:466:12)\n    at Function.Module._load (module.js:458:3)\n    at Module.require (module.js:513:17)\n    at require (internal/module.js:11:18)\n    at bindings (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:81:44)\n    at Object.<anonymous> (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/@ledgerhq/ledger-core/js/index.js:1:148)\n    at Object.<anonymous> (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/@ledgerhq/ledger-core/js/index.js:117:3)\n    at Module._compile (module.js:569:30)\n    at Object.Module._extensions..js (module.js:580:10)\n    at Module.load (module.js:503:32)\n    at tryModuleLoad (module.js:466:12)\n    at Function.Module._load (module.js:458:3)\n    at Module.require (module.js:513:17)\n    at require (internal/module.js:11:18)\n    at Object.<anonymous> (/Applications/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/external \"@ledgerhq/ledger-core\":1:1)\n    at r (/Applications/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/webpack/bootstrap:37:1)\n    at Module.module.exports.Object.defineProperty.value (/Applications/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/src/helpers/init-libcore.js:22:7)\n    at r (/Applications/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/webpack/bootstrap:37:1)\n    at Ve (/Applications/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/src/helpers/withLibcore.js:14:9)\n    at p.f [as impl] (/Applications/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/src/commands/libcoreGetVersion.js:18:31)\n    at process.on.e (/Applications/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/src/internals/index.js:69:17)\n    at emitTwo (events.js:125:13)\n    at process.emit (events.js:213:7)\n    at process.emit (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/source-map-support/source-map-support.js:454:21)\n    at emit (internal/child_process.js:768:12)\n    at _combinedTickCallback (internal/process/next_tick.js:141:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)"},"level":"warn","message":"✖ CMD libcoreGetVersion error","pname":"renderer","timestamp":"2018-07-15T17:27:29.183Z"}
{"message":"dlopen(/Applications/Ledger Live.app/Contents/Resources/app.asar.unpacked/node_modules/@ledgerhq/ledger-core/build/Release/ledger-core-node.node, 1): Library not loaded: @rpath/libledger-core.dylib\n  Referenced from: /Applications/Ledger Live.app/Contents/Resources/app.asar.unpacked/node_modules/@ledgerhq/ledger-core/build/Release/ledger-core-node.node\n  Reason: no suitable image found.  Did find:\n\t/Applications/Ledger Live.app/Contents/Resources/app.asar.unpacked/node_modules/@ledgerhq/ledger-core/build/Release/libledger-core.dylib: code signature invalid for '/Applications/Ledger Live.app/Contents/Resources/app.asar.unpacked/node_modules/@ledgerhq/ledger-core/build/Release/libledger-core.dylib'\n","name":"Error","stack":"Error: dlopen(/Applications/Ledger Live.app/Contents/Resources/app.asar.unpacked/node_modules/@ledgerhq/ledger-core/build/Release/ledger-core-node.node, 1): Library not loaded: @rpath/libledger-core.dylib\n  Referenced from: /Applications/Ledger Live.app/Contents/Resources/app.asar.unpacked/node_modules/@ledgerhq/ledger-core/build/Release/ledger-core-node.node\n  Reason: no suitable image found.  Did find:\n\t/Applications/Ledger Live.app/Contents/Resources/app.asar.unpacked/node_modules/@ledgerhq/ledger-core/build/Release/libledger-core.dylib: code signature invalid for '/Applications/Ledger Live.app/Contents/Resources/app.asar.unpacked/node_modules/@ledgerhq/ledger-core/build/Release/libledger-core.dylib'\n\n    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)\n    at Object.Module._extensions..node (module.js:598:18)\n    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)\n    at Module.load (module.js:503:32)\n    at tryModuleLoad (module.js:466:12)\n    at Function.Module._load (module.js:458:3)\n    at Module.require (module.js:513:17)\n    at require (internal/module.js:11:18)\n    at bindings (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:81:44)\n    at Object.<anonymous> (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/@ledgerhq/ledger-core/js/index.js:1:148)\n    at Object.<anonymous> (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/@ledgerhq/ledger-core/js/index.js:117:3)\n    at Module._compile (module.js:569:30)\n    at Object.Module._extensions..js (module.js:580:10)\n    at Module.load (module.js:503:32)\n    at tryModuleLoad (module.js:466:12)\n    at Function.Module._load (module.js:458:3)\n    at Module.require (module.js:513:17)\n    at require (internal/module.js:11:18)\n    at Object.<anonymous> (/Applications/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/external \"@ledgerhq/ledger-core\":1:1)\n    at r (/Applications/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/webpack/bootstrap:37:1)\n    at Module.module.exports.Object.defineProperty.value (/Applications/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/src/helpers/init-libcore.js:22:7)\n    at r (/Applications/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/webpack/bootstrap:37:1)\n    at Ve (/Applications/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/src/helpers/withLibcore.js:14:9)\n    at p.f [as impl] (/Applications/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/src/commands/libcoreGetVersion.js:18:31)\n    at process.on.e (/Applications/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/src/internals/index.js:69:17)\n    at emitTwo (events.js:125:13)\n    at process.emit (events.js:213:7)\n    at process.emit (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/source-map-support/source-map-support.js:454:21)\n    at emit (internal/child_process.js:768:12)\n    at _combinedTickCallback (internal/process/next_tick.js:141:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","level":"error","pname":"renderer","timestamp":"2018-07-15T17:27:29.184Z"}
{"type":"action","action":{"type":"UPDATE_SET_STATUS","payload":{"status":"checking"}},"level":"info","message":"⚛️  UPDATE_SET_STATUS","pname":"renderer","timestamp":"2018-07-15T17:27:33.646Z"}
{"type":"action","action":{"type":"UPDATE_SET_STATUS","payload":{"status":"unavailable"}},"level":"info","message":"⚛️  UPDATE_SET_STATUS","pname":"renderer","timestamp":"2018-07-15T17:27:35.752Z"}
{"type":"anaytics-track","level":"info","message":"△ track ExportLogs","pname":"renderer","timestamp":"2018-07-15T17:27:36.666Z"}
{"resourceUsage":{"images":{"count":3,"size":56360,"liveSize":15376},"scripts":{"count":1,"size":2882382,"liveSize":1918712},"cssStyleSheets":{"count":0,"size":0,"liveSize":0},"xslStyleSheets":{"count":0,"size":0,"liveSize":0},"fonts":{"count":11,"size":89912,"liveSize":0},"other":{"count":0,"size":0,"liveSize":0}},"release":"1.0.1","git_commit":"c7c5c51e1dd0136251485114e6020ab354789a23","environment":"production","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) LedgerLive/1.0.1 Chrome/59.0.3071.115 Electron/1.8.7 Safari/537.36","level":"info","message":"exportLogsMeta","pname":"renderer","timestamp":"2018-07-15T17:27:36.668Z"}

**Comment by gre** [comment]
Thanks, you are right, the app was not supporting Mac OS X 10.10

we have a fixed in 1.0.2 (you might want to try the prerelease or wait we release it tomorrow)

**Comment by martin8573** [comment]
Thanks for your help, im waiting for tomorrow ;-)
