### ISSUE TITLE
Add a warning before restarting the onboarding

### ISSUE THREAD

**Issue by Luuk2016** [LedgerHQ/ledger-live-desktop#1146]
- [x] I have checked this feature was not yet requested.

It would be nice add a warning that appears before you restart the onboarding

#### Part of the application

Settings

**Comment by gre** [comment]
the real problem you are meeting is you accidentally clicked on it and you have to do onboarding again to pass the screens?

**one acceptable solution is that, if you close the app, and open it again, you should not be on onboarding again if it was from a "relaunch**. We already have a flag in onboarding reducers to know if it's a relaunch.

Pull Requests are open to fix this, i can't give an ETA on when this is fixed but community can help 🙏

**Comment by Luuk2016** [comment]
Because whats the reason you've added the 'Onboarding' button?
If you press 'Reset Ledger Live' you will get the same result.

**Comment by Luuk2016** [comment]
Then wouldn't it be better to display a popup where the user can do the recovery sheet workflow & genuine check again. How can a user go back to his other account if he verified it using the "Onboarding" button?

**Comment by gre** [comment]
it would be much work to implement. maybe if a user can at any time leave the "relaunched" onboarding with a "X" on top right, that would work.

reimpl the all workflow into a modal is asking more work to devs for not much benefit. (e.g. the genuine check itself is a modal, etc..)

**Comment by gre** [comment]
we can take this via PR. our team for now are focused on more important bugs and features

**Comment by EricLarch** [comment]
The main problem is that once you clicked on the onboarding button, you cannot abort it unless you complete the process (which requires to have a device on hand). Restarting the app doesn't abort the onboarding, so you are stuck.

My recomendation is to add a top right "cancel" cross on the main onboarding screen (see below)

![image](https://user-images.githubusercontent.com/1017848/42759454-5147b99c-8907-11e8-957d-fc5bd4d8623c.png)

**Comment by Luuk2016** [comment]
When i accidentally pressed the "reboard" button i got back by changing the "hasCompletedOnboarding" in the settings.json file.
