### ISSUE TITLE
Add support for more fiat countervalues

### ISSUE THREAD

**Issue by cryptohappy** [LedgerHQ/ledger-live-desktop#1148]
- [x] I have checked this feature was not yet requested.

With the current method of using exchanges as price drivers, there will be users in many countries that will have no countervalues in their currency. I suggest using CoinMarketCap as a price driver. CMC has values in 32 fiat currencies.

**Comment by gre** [comment]
no ETA for this. for now we only support crypto->BTC->fiat pair. this would probably require to do things like  crypto->BTC->USD->fiat which is the next level

**Comment by hukumsingh87** [comment]
Please Add INR support.

**Comment by cthepot-ledger** [comment]
Duplicate #2326
