### ISSUE TITLE
Restarting the app during a second onboarding will wipe all user data

### ISSUE THREAD

**Issue by EricLarch** [LedgerHQ/ledger-live-desktop#1152]
#### Ledger Live Version and Operating System

- tested on Ledger Live **1.0.2**
- Platform and version: **Mac 10.13.5**

#### Expected behavior

Relaunching the application during a second onboarding shouldn't wipe user data

#### Actual behavior

If you quit the app during a second onboarding (at any moment), it will wipe all user data

#### Steps to reproduce the behavior

- do the onboarding and import accounts normally
- go to settings > help > onboarding to add another device
- restart the Ledger Live
- complete onboarding (I tried only "I already have a configured device")
- all previously imported accounts have been wiped

I have tested this with a password enabled

**Comment by Luuk2016** [comment]
If you are on Windows you can go to the Ledger Live's userdata.
In the file settings.json you can change the value from "hasCompletedOnboarding" to true.
If you restart the app you are back in your account

**Comment by gre** [comment]
working on a fix
