### ISSUE TITLE
View Stellar and Nano

### ISSUE THREAD

**Issue by jada855** [LedgerHQ/ledger-live-desktop#1158]
Hello,

Will there be support to view Stellar or Nano inside the Ledger Live app and not the external browser application? I can install the application but do not see their names when using the add account button. Is there a work around thanks!

**Comment by gre** [comment]
no ETA from our side but PR from community are welcome.
we'll clarify in the future how external contribution can happen.
( this comment apply also for #936 #937 #939 )

**Comment by gre** [comment]
Thanks for the issue.
We're unifying integration requests into [#1560](https://github.com/LedgerHQ/ledger-live-desktop/issues/1560).

Please follow [#1560](https://github.com/LedgerHQ/ledger-live-desktop/issues/1560) for updates on what will be the process.
