### ISSUE TITLE
app icon missing

### ISSUE THREAD

**Issue by thijstriemstra** [LedgerHQ/ledger-live-desktop#1159]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.0.2
- Platform and version: Mac 10.11.6

#### Expected behavior

Icon is missing for Ledger Live.app when inspecting it in Finder:

<img width="323" alt="screen shot 2018-07-17 at 01 17 09" src="https://user-images.githubusercontent.com/305679/42788328-3b713f78-895f-11e8-89cb-dc82742111a8.png">

it's visible in the dock though:

<img width="113" alt="screen shot 2018-07-17 at 01 18 12" src="https://user-images.githubusercontent.com/305679/42788352-53986374-895f-11e8-8e6c-afc8421442d0.png">

**Comment by gre** [comment]
for this bug, maybe we have not fulfilled all icon sizes, etc.. we'll need to to a double check on this 🤔

**Comment by gre** [comment]
we'll close in favor of https://github.com/LedgerHQ/ledger-live-desktop/issues/961 that have a longer history
