### ISSUE TITLE
Be able to export the transactions.

### ISSUE THREAD

**Issue by jdevora** [LedgerHQ/ledger-live-desktop#1167]
- [x] I have checked this feature was not yet requested.

For various reasons, we usually need to keep the list of transactions on an external program.
Right now that is impossible.

Could be it possible to add an "export" button at the beginning of the transaction list?
Or even hidden in some "Advanced" menu will be fine, if you don't want to clutter the UI

**Comment by gre** [comment]
any idea what would be the format of the export? CSV?
any standard you are aware of?

**Comment by jdevora** [comment]
Yes, I say that CSV is the best format, is the most used one and there are plenty of tools to convert it to any other.
Usually the exchanges and portfolio trackers use a format similar to the Bitcoin's wallet CSV export  format, but if the header names are clear enough any format will do.

**Comment by Luuk2016** [comment]
JSON would also be very handy

**Comment by meriadec** [comment]
If JSON is handy you can find all txs in the `accounts.json` located in user data folder.
You can open the folder via `Help > Open user data directory`

![2018-07-17_650x102](https://user-images.githubusercontent.com/315259/42828724-22db1ada-89e9-11e8-8a07-2f7f694d4cf1.png)

**Comment by gre** [comment]
(if you have not set an encryption)

**Comment by pvmining** [comment]
I would still love to see a transaction export as .CSV format.
It would be independent of the password encryption and usable for all skills.

**Comment by gre** [comment]
do you know standard for these format? I've seen this https://github.com/picksco/harmony

**Comment by pvmining** [comment]
AFAIK, there is no real standard for a .csv export by now. Every exchange and HW wallet makes it in a different way. your harmony link looks interesting.

for me personally it would be fine if we had an export with this data.
Date, Time, Asset type, TX id, Address, TX type, TX Value, Fee, TX total, account Balance, account name

**Comment by chrisgilpin** [comment]
> AFAIK, there is no real standard for a .csv export by now. Every exchange and HW wallet makes it in a different way. your harmony link looks interesting.
> 
> for me personally it would be fine if we had an export with this data.
> Date, Time, Asset type, TX id, Address, TX type, TX Value, Fee, TX total, account Balance, account name

Agreed - a simple export (to csv, or json) with the above data would bee great. I am unable to find accounts.json file

**Comment by 1point21gigabytes** [comment]
A CSV export should be a high priority feature; I am astonished that Ledger Live doesn't have one yet.  It is pretty tedious to copy and paste the transactions one by one.

**Comment by pvmining** [comment]
> ...I am unable to find accounts.json file

settings => help => view user data.
this opens the ledger live dir and there you have to look at a file called **app.json** (not accounts.json). its only usable if you have not encrypted your ledger live.

**Comment by Kimland** [comment]
I am surprised Ledger still doesn't have this feature.  I thought I could go around Ledger by getting the xpub from the wallet which I would use to create a watch only blockchain wallet from which I would export a csv history.  Strangely, the wallet that i create with the copied xpub does not list the address I was trying to track.  This must be something I do not understand about blockchain.  The right xpub should support an export the relevant history by the procedure I describe here.  I would appreciate if somebody would help me by pointing out where I am going wrong in not getting the history of the intended address.  In the meantime, I think Ledger can solve this problem instantaneously, because history by address is a blockchain feature ... Ledger has simply chosen not to bring that forward into the gadget.

**Comment by Kimland** [comment]
> (if you have not set an encryption)

But why would you not have set encryption?  Isn't encryption the primary purpose of using Ledger?

**Comment by gre** [comment]
@Kimland Ledger Live desktop app password feature provide data encryption to protect your privacy, it's not a security feature at all, security is solved by the Ledger device that is the only trustable way to verify addresses and sign transactions.


This feature was not in the initial MVP but is planned to be implemented soon.

**Comment by sp33dy** [comment]
Just trying to do my taxes and this REALLY sucks! Please do provide a way to export all transactions as CSV and/or JSON. Can't believe this isn't incorporated. I might have to scroll through thousands manually and going to take me days to do. Unbelievably POOR.

**Comment by gre** [comment]
@sp33dy well, it is shipped in Prerelease 1.7.0
