### ISSUE TITLE
Ability to scan accounts by xpub

### ISSUE THREAD

**Issue by meriadec** [LedgerHQ/ledger-live-desktop#1174]
- [x] I have checked this feature was not yet requested.

Would be neat as dev/support tool to have the ability to import an account by providing currency + xpub. I think we can use our already defined `Dev mode`, that would add a cta in AddAccountsModal to be able to bypass the device step and directly give xpub to libcore/xrp/eth bridges.

WDYT

**Comment by gre** [comment]
what are the minimal required info to create an account tho?

it seems that, first you need a walletname

to create a walletname. we actually use all of these:

publicKey + currencyId + isSegwit + isUnsplit

and to create the account

xpub + index  (also type and version, but these can be hardcoded)

**Comment by meriadec** [comment]
What I imagine, taking BTC like example (so: with libcore), it would "only" need to stub the publicKey here:
https://github.com/LedgerHQ/ledger-live-desktop/blob/771b905dcbfe0a51e1f755fc0aee0a58f111e27d/src/helpers/libcore.js#L138-L140

Everything else will remain the same. (note that it's also the case for `createAccount`, in the same file)

**Comment by gre** [comment]
mmh but you can't do this if it does not correspond to xpub, does not make sense , maybe we could just hardcode the walletname to like `dev_${currencyId}` :D

**Comment by EricLarch** [comment]
If you do that, it should then be clear that these accounts would be **read only**, and use a different UX to avoid any confusion. This feature should be visible/enabled only in advanced/expert mode.

**Comment by gre** [comment]
we can only enable it in DEV mode

**Comment by gre** [comment]
the account are going to be read only anyway, because you couldn't pass neither Send nor Receive! it would stop at step 2. because "device don't match account"
