### ISSUE TITLE
Ripple bug: 'not exactly one'..

### ISSUE THREAD

**Issue by gre** [LedgerHQ/ledger-live-desktop#1186]
i've been reported this bug from one user that tried to send a big amount of XRP (e.g. 1k)

"works with 100 but not 1k" 

![img_4304](https://user-images.githubusercontent.com/211411/42878759-86c4f93a-8a8e-11e8-88aa-249c93fee256.jpg)

might just be related to ripple-lib.

**Comment by gre** [comment]
not sure if related https://github.com/LedgerHQ/ripple-recovery-tool/issues/4

**Comment by gre** [comment]
https://github.com/ripple/ripple-lib/issues/829

**Comment by ferozkhanhamid** [comment]
My friend says it worked with 999 XRP, but not 1000. I'll also try to duplicate this.

**Comment by ferozkhanhamid** [comment]
I tried sending 10 XRP, 999 XRP, and i get this different error (on both) : 

![screen shot 2018-07-18 at 5 23 35 pm](https://user-images.githubusercontent.com/41228015/42879777-7f712c50-8aaf-11e8-8191-1b7e0947f6b6.png)

**Comment by gre** [comment]
I think, for "ledger sequence too high" it means you have try to send twice too fast, without synchronizing again.
it often happen, but disappear if you wait synchronization to finish (you can click on sync button to force it)

**Comment by ferozkhanhamid** [comment]
No, I just opened the app, waited for the sync to finish and then tried. But as per your request I've force synced it and tried and every time the same error (<1000 XRP, same error).

**Comment by michaeljfazio** [comment]
Hit this one today myself. Gave up on it and reverted back to legacy ripple wallet.

**Comment by gre** [comment]
status update: I can reproduce the problem and am investigating a solution.

**Comment by gre** [comment]
The issue is simply because numbers get formatted as `1,000.00` instead of `1000.00` , therefore the bug above 999

the fix should arrive in next patch we'll do.

Thanks for your patience

**Comment by ferozkhanhamid** [comment]
@gre I'm still getting the 'Ledger Sequence too high' error. Can't send any XRP out.

On another note, when i reconnected my Nano S to try again, the device randomly gave me this message instead of the PIN screen : ‘MCU firmware is not genuine’. Upon reconnecting again, it showed the PIN input screen as usual. Any idea why this happened ? One of my buttons seems to have problems responding to click, if that has anything to do with this (since MCU controls the buttons, screen USB conn etc).

**Comment by gre** [comment]
Please contact tech support because their might be able to offer an exchange for defected hardware (to be checked with them). I think the mcu not genuine can technically happen if there are USB issues like bad contact of the cable.


I'm going to investigate about this Ledger sequence too high related to ripple API, have you tried to **Clear Cache** ? This sometimes help retriggering a full resync

**Comment by gre** [comment]
@ferozkhanhamid you might want to validate the TX on your device a bit faster. this is due to using the default timeout of Ripple-lib which is way too fast.

had to define a maxLedgerVersionOffset that is a bit higher than the default one

**Comment by ferozkhanhamid** [comment]
@gre Oh this makes sense. I've waited to see the XRP amount, dest address and fee to press the button to approve, just to be secure. But this is how Ledger suggests as well to users right. So a higher timeout can be expected on Ledger Live 1.0.4 for this ?

**Comment by gre** [comment]
@ferozkhanhamid validating everything is definitely how you're supposed to use the Ledger device, always trust and validate all on device. so yeah definitely need a bigger timeout, we might even consider bigger timeout if we see people raising again the error.

**Comment by ferozkhanhamid** [comment]
@gre So would there be a bigger timeout in v1.0.4 ?

**Comment by gre** [comment]
yes. we've set it to 12 ledgers (ledger = block).
