### ISSUE TITLE
Current crypto price on each account page & market price

### ISSUE THREAD

**Issue by leyei** [LedgerHQ/ledger-live-desktop#1189]
- [ x ] I have checked this feature was not yet requested.

Can you add current crypto price on each account page when a crypto is viewed? Example when Litecoin is selected, maybe somewhere in the space between the Litecoin Ł logo and the send button.

Would also be nice to have market prices just as it is on coinmarketcap.com. [Check how it is nicely implemented in the Delta Cryptop portfolio tracker app]

#### Part of the application

Under each account and for the market prices, under 'Menu'

**Comment by davidzet2** [comment]
Agreed!

Now you can see your portfolio value (PRICE*QUANTITY) for each asset, but it would be nice to see the PRICE of each coin. Can you add this feature?

**Comment by tmlee** [comment]
As a consideration, may i suggest looking at the CoinGecko API at https://www.coingecko.com/api
No keys and straightforward to consume.
Happy to answer any questions you guys might have, cheers!

**Comment by gre** [comment]
i consider this addressed by the new portfolio distribution
