### ISSUE TITLE
Ledger Live wallet password not recognised after upgrading to v.1.0.3,

### ISSUE THREAD

**Issue by tcheeric** [LedgerHQ/ledger-live-desktop#1200]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.0.3
- Platform and version: Linux Ubuntu 16.04

#### Expected behavior

I should be able to use my password again without having to reset Ledger Live

#### Actual behavior

After upgrading to the current version, my password is not recognised anymore.

#### Steps to reproduce the behavior

1. $ ./ledger-live-desktop-1.0.3-linux-x86_64.AppImage
2. Password prompt and press 'Enter'
3. I enter the password and get the error message: 'The password you enter is incorrect.' but the password IS correct.

**Comment by gre** [comment]
thanks for the report. we'll look into it over the next days.

dup https://github.com/LedgerHQ/ledger-live-desktop/issues/1184
