### ISSUE TITLE
Device not detected on Ubuntu

### ISSUE THREAD

**Issue by ryanpaulfyfe** [LedgerHQ/ledger-live-desktop#1220]
#### Ledger Live Version and Operating System

- tested on Ledger Live **1.0.3**
- Platform and version: **Ubuntu 18.04**

#### Expected behavior

After recognizing the device it asks to browse to the dashboard of device.
It should recognize the device is on the dashboard.

#### Actual behavior

It never recognizes the device is on the dashboard.

#### Steps to reproduce the behavior

-open Ledger Liver
-Verify Device
-Connect Device
-Navigate to dashboard (on Device)

**Comment by meriadec** [comment]
Can you add udev rules as described in that help section: [Connection issues with Windows or Linux](https://support.ledgerwallet.com/hc/en-us/articles/115005165269-Connection-issues-with-Windows-or-Linux)?

See also: https://github.com/LedgerHQ/ledger-live-desktop/issues/1057, we will display a link to the article inside the app to help in those cases.

**Comment by LorenzoAlluminio** [comment]
I had the exact same issue, adding the udev rules solved it, thanks :smile:

**Comment by christianbundy** [comment]
Having the same problem but adding the udev rules haven't resolved it for me. I've added both the rules for the subsystem and the kernel, even after `sudo udevadm trigger && sudo udevadm control --reload-rules`.

```console
$ stat ./ledger*
  File: ./ledger-live-desktop-1.0.3-linux-x86_64.AppImage
  Size: 81840061  	Blocks: 159856     IO Block: 4096   regular file
Device: 802h/2050d	Inode: 820047      Links: 1
Access: (0755/-rwxr-xr-x)  Uid: ( 1000/christianbundy)   Gid: ( 1000/christianbundy)
Access: 2018-07-23 11:51:57.503338804 -0700
Modify: 2018-07-23 11:50:26.823338042 -0700
Change: 2018-07-23 11:51:56.173338793 -0700
 Birth: -
$ uname -a
Linux samus 4.17.8-1-ARCH #1 SMP PREEMPT Wed Jul 18 09:56:24 UTC 2018 x86_64 GNU/Linux
```

**Comment by leyei** [comment]
I am still having this problem in Fedora28. Cant get pass "Navigate to the dashboard on your device" stage. I have added udev rules, added owner="usrname" and even the last suggestion [here:](https://support.ledgerwallet.com/hc/en-us/articles/115005165269-Fix-connection-issues)

```
$ uname -a
Linux Fedora 4.17.7-200.fc28.x86_64 #1 SMP Tue Jul 17 16:28:31 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Any other way to  make this work on my Linux machine? This is an already initialized [on Windows] Nano S

**Comment by christianbundy** [comment]
@leyei Can you copy and paste your full udev rules here? Also, can you verify that you've run the below commands after making the changes?

```
udevadm trigger
udevadm control --reload-rules
```

**Comment by leyei** [comment]
Thanks @christianbundy. Here is what I have under 20-hw1 for now

```
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0660", GROUP="plugdev", ATTRS{idVendor}=="2c97"
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0660", GROUP="plugdev", ATTRS{idVendor}=="2581"

OWNER="xi", SUBSYSTEMS=="usb", ATTRS{idVendor}=="2581", ATTRS{idProduct}=="1b7c", MODE="0660", GROUP="plugdev"
OWNER="xi", SUBSYSTEMS=="usb", ATTRS{idVendor}=="2581", ATTRS{idProduct}=="2b7c", MODE="0660", GROUP="plugdev"
OWNER="xi", SUBSYSTEMS=="usb", ATTRS{idVendor}=="2581", ATTRS{idProduct}=="3b7c", MODE="0660", GROUP="plugdev"
OWNER="xi", SUBSYSTEMS=="usb", ATTRS{idVendor}=="2581", ATTRS{idProduct}=="4b7c", MODE="0660", GROUP="plugdev"
OWNER="xi", SUBSYSTEMS=="usb", ATTRS{idVendor}=="2581", ATTRS{idProduct}=="1807", MODE="0660", GROUP="plugdev"
OWNER="xi", SUBSYSTEMS=="usb", ATTRS{idVendor}=="2581", ATTRS{idProduct}=="1808", MODE="0660", GROUP="plugdev"
OWNER="xi", SUBSYSTEMS=="usb", ATTRS{idVendor}=="2c97", ATTRS{idProduct}=="0000", MODE="0660", GROUP="plugdev"
OWNER="xi", SUBSYSTEMS=="usb", ATTRS{idVendor}=="2c97", ATTRS{idProduct}=="0001", MODE="0660", GROUP="plugdev"

```

**Comment by cnu80** [comment]
fedora 28 removed the group "plugdev".  I changed the rules from GROUP="plugdev" to OWNER="MYUSERACCOUNT". But I still cannot verify my devices.

**Comment by leyei** [comment]
Thanks @cnu80 for that clarification. So I think this solution wont work for Fedora28. Will there be a fix from Ledger that will make it possible to use Ledger Live on Linux smoothly?

**Comment by meriadec** [comment]
Ye, that's the goal, but you know there is multiple differences across distributions ;)

At first, builds were done on Arch, then Ubuntu 18, then (latest build) has been done on Ubuntu 16.04 to be as compatible as possible (dylibs problems..). The optimal will be to push build scripts directly on distribution repositories (already done for Arch Linux).

So keep updated, and sorry for the inconvenience!

**Comment by leyei** [comment]
Finally @meriadec! Thanks for this clarification. Apparently we will have to wait for a Ledger Live application that works on major Linux distros or package management systems they're based on. Example, you could just work on debian-based, RPM-based, Pacman-based and Gentoo-based. This should cover majority of Linux users out there.

**Comment by christianbundy** [comment]
@leyei You can drop the `GROUP=plugdev`, but I'm wondering whether adding `OWNER="xi"` to the first two [kernel] rules might help. For your reference, here's what works for me:

```
OWNER="christianbundy", SUBSYSTEMS=="usb", ATTRS{idVendor}=="2581", ATTRS{idProduct}=="1b7c", MODE="0660"
OWNER="christianbundy", SUBSYSTEMS=="usb", ATTRS{idVendor}=="2581", ATTRS{idProduct}=="2b7c", MODE="0660"
OWNER="christianbundy", SUBSYSTEMS=="usb", ATTRS{idVendor}=="2581", ATTRS{idProduct}=="3b7c", MODE="0660"
OWNER="christianbundy", SUBSYSTEMS=="usb", ATTRS{idVendor}=="2581", ATTRS{idProduct}=="4b7c", MODE="0660"
OWNER="christianbundy", SUBSYSTEMS=="usb", ATTRS{idVendor}=="2581", ATTRS{idProduct}=="1807", MODE="0660"
OWNER="christianbundy", SUBSYSTEMS=="usb", ATTRS{idVendor}=="2581", ATTRS{idProduct}=="1808", MODE="0660"
OWNER="christianbundy", SUBSYSTEMS=="usb", ATTRS{idVendor}=="2c97", ATTRS{idProduct}=="0000", MODE="0660"
OWNER="christianbundy", SUBSYSTEMS=="usb", ATTRS{idVendor}=="2c97", ATTRS{idProduct}=="0001", MODE="0660"

OWNER="christianbundy", KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0660", ATTRS{idVendor}=="2c97"
OWNER="christianbundy", KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0660", ATTRS{idVendor}=="2581"
```

And then:

```shell
sudo udevadm trigger && sudo udevadm control --reload-rules
```

If that doesn't work I might increase the logging with:

```shell
udevadm control --log-priority=info
```

Or you can read the logs directly with:

```shell
udevadm monitor --environment
```

Hopefully the logs give you enough info that we can get this working on your system!

**Comment by leyei** [comment]
Thanks @christianbundy ! Now I can get pass this stage by adding `OWNER="xi"` to the first two [KERNEL] rules without dropping `GROUP=plugdev`

Unfortunately, I am getting new error already reported [950](https://github.com/LedgerHQ/ledger-live-desktop/issues/950) and [1010](https://github.com/LedgerHQ/ledger-live-desktop/issues/1010)

**Comment by meriadec** [comment]
To bring clarifications on Linux builds, I'm currently working on the fix for https://github.com/LedgerHQ/ledger-live-desktop/issues/1184 (feature issue: https://github.com/LedgerHQ/ledger-live-desktop/issues/1235) and we choose to priorize it over other issues. So, we don't forget the problem :) but it will come after.

**Comment by cnu80** [comment]
Now my Ledger S is working on Fedora 28. I changed my udev rule from group to owner and replaced my USB cable. With the old usb cable it was not possible to verify my ledger device. Now I am waiting for the Bitcoin/Dash fix. Thanks for your great work !!! Is a flatpak version also planned?

**Comment by meriadec** [comment]
electron-builder is not yet providing automatic flatpak build (see [list of targets](https://www.electron.build/configuration/linux/)) but it has `rpm`. Does providing `rpm` builds would do the trick?

**Comment by meriadec** [comment]
Just tested on fresh Fedora 28 install, adding udev rules as described in the help documentation resolve the problem (see https://github.com/LedgerHQ/ledger-live-desktop/issues/1220#issuecomment-407783703 and https://support.ledgerwallet.com/hc/en-us/articles/115005165269-Fix-connection-issues)

**Comment by naddeoa** [comment]
In my case, it turns out that I was using a USB cable with no data pin...

See no events at all with `udevadm monitor --environment` was the tip. Also, that command is awesome.

**Comment by SergeyIstomin96** [comment]
I had same problem on Ubuntu 16.04.
There is such message in logs: 
```
"data": {
    "message": "/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.MvNkfs)",
    "name": "Error",
    ...
},
```
I had not this lib supported on my system. Check:
`strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX`

Then I've install this llib:
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-4.9
sudo apt-get upgrade libstdc++6
```
This work for me.
