### ISSUE TITLE
Improve crash screen UX by removing buttons

### ISSUE THREAD

**Issue by dasilvarosa** [LedgerHQ/ledger-live-desktop#1221]
As of #1001 there are 5 buttons on the crash screen. This is bound to increase confusion. 

- Restart: In most cases, users will want to try this before getting help.
- Export: This becomes relevant only when contacting support. I suggest to remove this button and to integrate this function in the contact support button.
- Contact Support: If restarting does not work and users get the crash screen again, they will want to get help. Clicking this button could automatically export the logs to the desktop. Then on the Zendesk support form, we can inform the user that logs have been exported to the desktop and request to upload them (a more advanced log hosting server can be integrated later, that could ask explicit permission to upload logs and include the URL in the ticket).
- GitHub: Also, it's not very (non-dev) user-friendly to send users to GitHub without explaining what it is. Perhaps we could remove this button and instead include the GitHub logo (with tooltip) that's also on the final screen of the on-boarding. GitHub users will be familiar with the logo and find the repo issues if they want to.
- Reset: Last resort if support can not find a solution to the problem. Remove this button in favor of instructions given by tech support (1. open explorer, 2. Open user data directory, 3. delete all files).  

![42498649-0349b7a6-842d-11e8-818d-956ddc149c04](https://user-images.githubusercontent.com/712580/42991064-c6d2dde0-8c04-11e8-94fa-bb8dd3e01f63.png)

#### Part of the application

Crash screen

**Comment by meriadec** [comment]
- +1 for keeping restart
- +1 for remove export and integrate the functionality in "Contact support"
- +1 for moving github link to discret icon

For the reset I think it's *very* important to keep it here because there will be cases where user can't even navigate to the `Settings > Help > Open user data` and we definitely don't want to ask non-tech to navigate to hidden folders, %APPDATA% etc.

**Comment by gre** [comment]
I don't really see how we can easily implement the "Contact Support" also export the logs feature tho today.
I have some thoughts in how this could work in future tho (with a more integrated way of "sending logs to our server, giving back an URL that we can include directly in the link `ledgerwallet.com/support?reportLogs=id_of_the_log_uploaded`" if it's technically possible to prefill forms like so), but not something we can easily do now..

I honestly would really prefer us to focus on fixing the remaining bugs that make this screen appearing than polishing the actual screen.. 

agree for the "social links" to appear in this screen. same footer we have in onboarding could be on the bottom-right corner.

**Comment by dasilvarosa** [comment]
I think that if users are stimulated to contact us with valuable feedback and logs, you can better focus your efforts on fixing important bugs and that will help prevent the screen in the first place. Polishing the crash screen is indeed in our common interest.

That aside. thanks for your feedback 👍 . Proposed improvements:
- Social footer
- Keep restart, contact and reset buttons but change styling to accentuate logical order.
- Use the same style as _I forgot my password_ for Reset application.

![1221](https://user-images.githubusercontent.com/712580/42996509-0ff84c26-8c14-11e8-8317-8adc7e9e3d3e.png)


I'm looking into Zendesk functionality for pre-filling fields from the URL. It seems it's not directly featured, there maybe some solutions.

**Comment by gre** [comment]
ok, but again, we can't today automate the Export , it still need to be an user action for now.

**Comment by dasilvarosa** [comment]
No problem, we'll change the wording to ask them to close and restart the application. It's easy to do manually, we do not really need the restart button for that. Then we keep the Export button for now instead of restart. Reset could stay as well.

![1221-v2](https://user-images.githubusercontent.com/712580/42996874-2cf38132-8c15-11e8-887c-a5baa2666028.png)

**Comment by gre** [comment]
yeah, the restart is actually not helpful because most of the time, error will happen again anyway. for the crash at boot cases

**Comment by dasilvarosa** [comment]
I've asked @khalilbenihoud to have a look and work out a solution.
