### ISSUE TITLE
I can not build AUR package

### ISSUE THREAD

**Issue by Incont** [LedgerHQ/ledger-live-desktop#1237]
Hello.
I tried install package from https://aur.archlinux.org/packages/ledger-live/.
Is it official aur package?
And I had error:

==> Downloading ledger-live PKGBUILD from AUR...
x .SRCINFO
x PKGBUILD
x ledger-live.desktop
ledger-live 1.0.3-1  (2018-07-19 09:01)
( Unsupported package: Potentially dangerous ! )
==> Edit PKGBUILD ? [Y/n] ("A" to abort)
==> ------------------------------------
==> n

==> ledger-live dependencies:
 - python2 (already installed) [makedepend]
 - yarn (package found) [makedepend]

==> Continue building ledger-live ? [Y/n]
==> -------------------------------------
==> y

==> Building and installing package
==> Install or build missing dependencies for ledger-live:
resolving dependencies...
looking for conflicting packages...

Packages (4) c-ares-1.14.0-1  http-parser-2.8.1-1  nodejs-10.6.0-1
             yarn-1.7.0-1

Total Download Size:    5,78 MiB
Total Installed Size:  24,40 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 c-ares-1.14.0-1-x86_64   103,6 KiB   250K/s 00:00 [######################] 100%
 http-parser-2.8.1-1...    19,1 KiB   579K/s 00:00 [######################] 100%
 nodejs-10.6.0-1-x86_64     5,0 MiB  1954K/s 00:03 [######################] 100%
 yarn-1.7.0-1-any         682,4 KiB  4,17M/s 00:00 [######################] 100%
(4/4) checking keys in keyring                     [######################] 100%
(4/4) checking package integrity                   [######################] 100%
(4/4) loading package files                        [######################] 100%
(4/4) checking for file conflicts                  [######################] 100%
(4/4) checking available disk space                [######################] 100%
:: Processing package changes...
(1/4) installing http-parser                       [######################] 100%
(2/4) installing c-ares                            [######################] 100%
(3/4) installing nodejs                            [######################] 100%
Optional dependencies for nodejs
    npm: nodejs package manager
(4/4) installing yarn                              [######################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
==> Making package: ledger-live 1.0.3-1 (Сб 21 июл 2018 09:32:54)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading v1.0.3.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   136    0   136    0     0    153      0 --:--:-- --:--:-- --:--:--   153
100 1804k    0 1804k    0     0   435k      0 --:--:--  0:00:04 --:--:--  847k
  -> Found ledger-live.desktop
==> Validating source files with md5sums...
    v1.0.3.tar.gz ... Passed
    ledger-live.desktop ... Passed
==> Extracting sources...
  -> Extracting v1.0.3.tar.gz with bsdtar
==> Starting prepare()...
yarn install v1.7.0
[1/4] Resolving packages...
warning Resolution field "webpack-sources@1.0.1" is incompatible with requested version "webpack-sources@^1.1.0"
warning Resolution field "webpack-sources@1.0.1" is incompatible with requested version "webpack-sources@^1.1.0"
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > downshift@1.31.16" has unmet peer dependency "prop-types@>=15".
warning " > react-spring@5.3.18" has unmet peer dependency "prop-types@15.x.x".
warning "@storybook/react > babel-loader@7.1.4" has incorrect peer dependency "babel-core@6".
[4/4] Building fresh packages...
warning Ignored scripts due to flag.
Done in 96.06s.
==> Starting build()...
yarn run v1.7.0
$ bash ./scripts/dist.sh
$ bash ./scripts/compile.sh
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
error Command failed with exit code 128.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Done in 0.77s.
==> Entering fakeroot environment...
==> Starting package()...
cp: cannot stat 'dist/linux-unpacked': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
==> ERROR: Makepkg was unable to build ledger-live.
==> Restart building ledger-live ? [y/N]
==> ------------------------------------

**Comment by drizzt** [comment]
Hi,
reading the PKGBUILD source code and the ledger-live-desktop source it seems that 1.0.3 miss a commit (ec4d4da5) that is needed by the PKGBUILD in order to build correctly.

I suggest to add the commit as a patch in the aur package and to remove it on 1.0.4

CC: @meriadec

**Comment by meriadec** [comment]
That's right (I noticed the problem but on my side it didnt prevented the project to build).
We release 1.0.4 this week, so this will be fixed on it. Sry!

**Comment by Incont** [comment]
==> New package :
aur/ledger-live 1.0.5-1 (required by -)

==> Continue upgrade ? [Y/n]
==> [V]iew package detail   [M]anually select packages
==> --------------------------------------------------
==> y

==> Downloading ledger-live PKGBUILD from AUR...
x .SRCINFO
x PKGBUILD
x ledger-live.desktop
ledger-live 1.0.5-1  (2018-07-27 07:43)
( Unsupported package: Potentially dangerous ! )
==> Edit PKGBUILD ? [Y/n] ("A" to abort)
==> ------------------------------------
==> n

==> ledger-live dependencies:
 - yarn (already installed) [makedepend]
 - python2 (already installed) [makedepend]


==> Continue building ledger-live ? [Y/n]
==> -------------------------------------
==> y

==> Building and installing package
==> Making package: ledger-live 1.0.5-1 (Сб 28 июл 2018 09:39:07)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading v1.0.5.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   136    0   136    0     0    147      0 --:--:-- --:--:-- --:--:--   147
100 1842k  100 1842k    0     0   190k      0  0:00:09  0:00:09 --:--:--  276k
  -> Found ledger-live.desktop
==> Validating source files with md5sums...
    v1.0.5.tar.gz ... Passed
    ledger-live.desktop ... Passed
==> Extracting sources...
  -> Extracting v1.0.5.tar.gz with bsdtar
==> Starting prepare()...
yarn install v1.7.0
[1/4] Resolving packages...
warning Resolution field "webpack-sources@1.0.1" is incompatible with requested version "webpack-sources@^1.1.0"
warning Resolution field "webpack-sources@1.0.1" is incompatible with requested version "webpack-sources@^1.1.0"
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > downshift@1.31.16" has unmet peer dependency "prop-types@>=15".
warning " > react-spring@5.3.18" has unmet peer dependency "prop-types@15.x.x".
warning "@storybook/react > babel-loader@7.1.4" has incorrect peer dependency "babel-core@6".
[4/4] Building fresh packages...
warning Ignored scripts due to flag.
Done in 22.28s.
==> Starting build()...
yarn run v1.7.0
$ bash ./scripts/dist.sh
$ bash ./scripts/compile.sh
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
error Command failed with exit code 128.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Done in 0.53s.
==> Entering fakeroot environment...
==> Starting package()...
cp: cannot stat 'dist/linux-unpacked': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
==> ERROR: Makepkg was unable to build ledger-live.
==> Restart building ledger-live ? [y/N]

**Comment by Incont** [comment]
I still have problem
