### ISSUE TITLE
Sending error: Something went wrong. Please replug your device. 0x6f00

### ISSUE THREAD

**Issue by OhHaiAndy** [LedgerHQ/ledger-live-desktop#1239]
Ledger Live v1.0.3 on Windows 10

I am attempting to send ZenCash, but when it moves to the "verification" section, I do not get the prompt on my ledger device. Instead it moves to "confirmation" and shows an error:

"Something went wrong. Please replug your device.

Ledger device: Internal error, please report (0x6f00)

I have tried multiple different amounts and I have tried sending to anther address. Same results.

Ideas?

![image](https://user-images.githubusercontent.com/41521498/43038845-c5ba6fbc-8ce6-11e8-8c02-ef710b5b59f1.png)

**Comment by GoedeMG** [comment]
Am having the same issue but with Zcash. Also Ledger Live v1.0.3 on Windows 10. Initially received (exchanged) Zcash via a t- address. Also trying to send to a t- address

**Comment by LedgerUser1** [comment]
Same issue with Bitcoin Cash. Ledger Live v1.0.3 on MacOS (10.13.6).
Other error code:
Ledger device: Invalid data received (0x6a80)
The Chrome App does not work either.

**Comment by Kmahecha** [comment]
I have the same problem trying to send my Zen Cash to any wallet... How long does it usually take ledger to update?

**Comment by PhAlAnXcOiN** [comment]
I am experiencing same issue as ohhaiandy. 

I managed to send my zencash transaction with the old chrome ledger wallet app though. 

Screenshot of error:

![ledgerzen](https://user-images.githubusercontent.com/41816684/43353854-0c5a9ef6-91f6-11e8-8ea8-edb20a5504e8.JPG)

Have never used a z address. 

Most of transactions were sent before overwinter update and address was generated prior to update as well. 

Don't know if that has anything to do with it. Sending on chrome app took about 60 seconds to verify so maybe has to do with numerous utxos on address?

**Comment by gre** [comment]
@amougel do you know if the fix we did for zcash also need to be for zencash ? (extraData )

**Comment by gre** [comment]
ZenCash isn't a fork a ZCash?

**Comment by PhAlAnXcOiN** [comment]
@gre when I had this problem sending zcash, switching to the chrome app didn't help. I got the same problem. However, with zencash switching to the chrome app allowed me to send transaction.

I am assuming it is a similar problem although maybe not identical. Probably related to overwinter.

**Comment by Kmahecha** [comment]
@PhAlAnXcOiN 
Which chrome app you using? I’m having same problem with zencash not sending out.

**Comment by Kaplan007** [comment]
I already solve this issue with Ledger Support. Communication is good with them but they dont know how to solve this issue. They asking about my version of apps etc. but my apps are up to date.

**Comment by pydlv** [comment]
I'm having this issue as well. Same error code.

**Comment by rocknet** [comment]
I wanted to add that many in the ZenCash (now Horizen) are experiencing this issue.  The current advice is not to use Ledger Live because of this.  I'm keen to try to help get to the bottom of this if I can offer additional troubleshooting.  I had been working with support for about a month and had sent my logs in a while back.  I'm also in the dev slack channel.

**Comment by KaganRoman** [comment]
sick, I have same problem. Is there any way to get the funds from the ledger? It is very frustrating to have funds locked

**Comment by meriadec** [comment]
as a workaround you can use the legacy chrome apps ([see here](https://support.ledgerwallet.com/hc/en-us/articles/360007534774-Download-Ledger-Chrome-apps))

**Comment by KaganRoman** [comment]
Thank you, it really helped @meriadec !

**Comment by Kmahecha** [comment]
I was able to transfer my Zen to a new address using the old ledger chrome btc app.

**Comment by ncodedbpm** [comment]
Yep same here. LTC funds locked can't send unless i use the Chrome app. I really hope they aren't planning to discontinue the old Chrome app anytime soon.

**Comment by dutchakdev** [comment]
Same problem with bitcoin legacy

**Comment by kf6kjg** [comment]
On v1.1.10 with Win10 using ZCash, it just took a couple of minutes to show the transaction info and allow confirmation.  Then it bombed with the below "Dynamic exception type: class std::out_of_range"..."Offset [...] is too high"
![image](https://user-images.githubusercontent.com/1157224/45246505-90ec5700-b2b6-11e8-8a51-fe503e2e88d9.png)

**Comment by MarcusWI** [comment]
I experience the same bug for btc and eth on Windows 10 and x64.

"Something went wrong. Please reconnect your device. Ledger device: Internal error, please report (0x6f01)"

I have just reinstalled Ledger Live 1.2.0 and updated to the newest firmware for Nano S. Is there any solution besides the workaround with Chrome App?

**Comment by dmsmith1991** [comment]
Still experiencing this issue after a complete factory reset & restore of my Ledger Nano S, and a clean install of the latest Ledger Live application (v1.3.2).

The legacy bitcoin chrome app used to work as a backup, but now this is failing after a very slow "transaction in progress" loading bar.

This now renders my ledger nano inoperable for sending horizen.

**Comment by xjmzx** [comment]
Had the same problem described by OP. However, now after factory reset and firmware update I get this: 

Wrong device or passphrase for ‘HZEN’
Please use the device or passphrase for the selected account

Which is pretty weird, sure I've got the right seed/device

I tried the chrome apps, but says there is 0 in Zen cash account

**Comment by gre** [comment]
I consider the initial exact fixed. the series of comment diverged to other topics, please create individual issues if needed.
the "wrong device" is discussed in https://github.com/LedgerHQ/ledger-live-desktop/issues/1781

**Comment by Kronkmeister** [comment]
I had this problem with trying to send BCH.

I realized it was because I've put the receiver address as the new "cashaddr"-format. You can convert your cashaddr into legacy here and then try sending it.
 
https://cashaddr.bitcoincash.org/

the cashaddr format looks like this: "bitcoincash:akjdshakjsdlha1212"
legacy looks like the common Bitcoin format.
