### ISSUE TITLE
Support connecting to the user's own full node

### ISSUE THREAD

**Issue by durbanpoison** [LedgerHQ/ledger-live-desktop#1240]
- [x] I have checked this feature was not yet requested.

The way Ledger Live works today is that the wallet is getting its balances from a central server run by a third party. This is convenient because it means the user doesn't have to run their own full node for each coin they have in their wallet. But this convenience comes at the cost of some security and privacy guarantees that full nodes provide.

I would like to be able to connect my Ledger Live app to my own full nodes, either nodes running locally on my computer or on a remote server. These full nodes might only be running traffic through Tor, so the wallet application should also support connecting to these nodes through Tor.

#### Part of the application

Settings

**Comment by attakorns** [comment]
Agreed! This would be a very useful feature!

**Comment by kravens** [comment]
We need this, my node my rules, not my node not my rules!

**Comment by 2pac1** [comment]
This is a must.
Electrum is lightning years ahead of ledger live.
There should be an option to force the use of TOR + option to pin it to your NODE
Why would Ledger HQ keep logs of your IP address and what UTXOs are you checking!? Come on

**Comment by Thasugeas** [comment]
Please allow this, even without TOR, it would be fine!

**Comment by System-Glitch** [comment]
Any news on this?

**Comment by althea16** [comment]
Isn't this already by possible by just using your Ledger with Wasabi or Electrum, for example, which are connected to your own node??

**Comment by kravens** [comment]
Many users have indeed switched to Electrum or Wasabi to connect their own node to the hardware-wallet, including me.

**Comment by MikeD10375** [comment]
This feature request has been open for years now with no movement on the issue. What is the problem? Is Ledger making money from this data? I would rather not leave Ledger products/services, however since we are being ignored I may have no choice.

**Comment by Jacksper13** [comment]
Following up on this

**Comment by MikeD10375** [comment]
I've had no success using Ledger Live Desktop on my Ubuntu 20.04.1 laptop. I've been using Ledger Live on my Android phone in the meanwhile.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by System-Glitch** [comment]
#3291 adds support for [satstack](https://github.com/ledgerhq/satstack). I think this addition will allow this issue to be closed.
