### ISSUE TITLE
Better control on the Update mecanism

### ISSUE THREAD

**Issue by gre** [LedgerHQ/ledger-live-desktop#1243]
this is a big picture issue proposal on how the app currently manage updates and how it can be improved. Please give your feedback and discuss.

## behavior of the current 1.0.x

- at boot of the application, we check if there is an update,
  - if there is it is downloaded in background without any feedback on the interface.
  - Once it is fully downloaded, we show a notification on the Portfolio to inform the update was downloaded with an Update button.
  - Update button just do a reboot of the app, weither you click it or not, the next reboot of the app will actually patch and update the app. 

## problem with current approach

- the notification appears after some time, like after 30s or 1 minute, which is confusing for users that are already in the middle of a process (like Sending funds from portfolio and you see the notif in background)
- we never recheck again of the app is up to date once it is opened which can be a problem if users keep the app forever opened ( ctx #1175 )
- The feature that the app automatically download and update itself is seen by some of our users too intrusive.

## proposal behavior for the future

the idea is to give more control to the user.

- At boot of the app, we would check if it is up to date. If there is a new update, we would directly show a banner, straight-away, but the app would not automatically download for you: the "Update" action would actually do this work, once you click it, we could show `Downloading... 33%` and at the end "Update" would reboot like currently. ( technically quite easy https://www.electron.build/auto-update/ ).
- we would call `checkForUpdate` also recurrently, something like each 1 Hour (to address #1175 )
- I'm not yet sure if it worth it, but we could have our own infra on top of GitHub: there are possible tools like the ones shown in https://github.com/electron/electron/blob/master/docs/tutorial/updates.md#deploying-an-update-server ( for instance, Nuts: https://github.com/GitbookIO/nuts )

**Comment by gre** [comment]
complementary notes:

if we do this, we need to make sure the banner would also appear:

- on Error screen
- on Onboarding, allow to have banner appear too

**Comment by punkay** [comment]
i am sorry. i typed the wrong password. i'm stupid. again, excuse me for causing trouble.

**Comment by fdv** [comment]
This is something we need to implement quickly. 

- Hourly check of an available release
- A mechanism to force the update + restart in case we have an urgent release

**Comment by MortalKastor** [comment]
> A mechanism to force the update + restart in case we have an urgent release

I'm not confortable with remotely closing user apps.
What about a sticky red banner explaining the issue and urging the user to restart?

**Comment by meriadec** [comment]
It can also be a modal "on top of everything", that can't be closed until you press "restart". Windows update like :trollface: .

**Comment by gre** [comment]
Imo a banner is enough explicit that user have to update. I would recommend against doing the update automatically..users want to proof check the update is legit etc.. this is what this issue wanted to address too, the fact it autopatch the app is seen as too intrusive and potential security vector.
Man in the middle attacks on the update would be too easy otherwise..

**Comment by meriadec** [comment]
Maybe I was not explicit enough but I didn't talked about doing the update automatically without user consent ;) (that's the current behaviour that we want to change!)

BUT we clearly need to make it appear more explicitly and ask user action to proceed. Additionally, it would be nice to have possibility to "block everything" until he accept, for critical bugfixes.

**Comment by gre** [comment]
Fixed by now
