### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by vidaru** [LedgerHQ/ledger-live-desktop#1244]
#### Ledger Live Version and Operating System

- tested on Ledger Live v1.0.3
- Platform and version: Arch Linux
#### Expected behavior
Normal memory usage

#### Actual behavior

On a 32GB system, 70% of the total memory was being consumed by ledger live.

#### Steps to reproduce the behavior
Leave ledger live running for an hour or so, system had been hibernating and reloading, had received one transaction and sent a transaction during that time. Ledger live had been running for just over an hour.

Here is a screenshot of my `top` output

![screenshot from 2018-07-23 15-47-56](https://user-images.githubusercontent.com/38734836/43084307-5420b112-8e90-11e8-8c6a-4fcf8b6454c9.png)

**Comment by gre** [comment]
is it happening when you see "Synchronizing" or does it say "Synchronized" ?
it looks like the Internal process is working so it might be related to sync (libcore)

**Comment by vidaru** [comment]
It often says 'Synchronized failed' on my system, however it does seem to synchronize successfully as prices and transactions update

**Comment by gre** [comment]
if you "hover" the error, what does it says? "timeout error"? I think we have some sort of queue getting accumulate in some cases and i'll try to tackle this in #1108

**Comment by vidaru** [comment]
"Oops, a time out occurred" 
![screenshot from 2018-07-23 16-16-59](https://user-images.githubusercontent.com/38734836/43085810-d9b4ab96-8e93-11e8-8c4b-59a01d521aa5.png)

**Comment by gre** [comment]
BTW as a workaround (/second thing to test) is to kill the "Ledger Live Internal" process when it happens, if my intuition is correct it would fix the issue.

it's totally ok to kill it at any time, the app will always be able to recreate it and is resilient to it being killed. it's purpose is exactly to encapsulate complex work (device access, c++ backend) so we might want to ping it to check if it respond and kill it from the main thread.

**Comment by vidaru** [comment]
The app still responds fine and I killed it using the standard window close button (x). I only discovered the memory usage because I couldn't open up any other app on my system as gnome was complaining about a lack of memory.

**Comment by KhalilBellakrid** [comment]
I didn't know there were cases where libcore is hanging for ever, there was an issue related to BCH about a hanging synchro but I could not reproduce after trying with user's xpub.
It would be nice to have scenario to investigate !

**Comment by gre** [comment]
next time it happens again, it would be useful if you could Export your logs (Ctrl+E) .

if you wish to send the logs to us don't send them publicly (but you can send them to our tech support) / if you wish to view yourself the logs, you can drag & drop them on our offline tool https://ledger-live-tools.netlify.com/logsviewer (very early and ugly tool but at least to read the logs)

**Comment by bumbar1** [comment]
I'm experiencing a memory leak on v1.1.11 (elementary OS 0.4.1, 4.15.0-34-generic kernel). It locks machine completely by filling up ram and then swap (_only_ have 16 GB of each). It was synchronized, but left minimized in background. Task manager became unresponsive before I could kill, and couldn't ssh in time to get a log.

**Comment by gre** [comment]
I consider this fixed. reopen if still not fixed.
