### ISSUE TITLE
Cannot get pass genuine check

### ISSUE THREAD

**Issue by tinova** [LedgerHQ/ledger-live-desktop#1249]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.0.3
- Platform and version: Mac 10.13.5

#### Expected behavior

Be able to access the apps in my ledger

#### Actual behavior

Stays in "connect and unlock your Ledger device" step while the ledger is connected and unlocked

**Comment by gre** [comment]
if you try on the Chrome Manager App , does it work?

**Comment by tinova** [comment]
Well, turns out it didn't. I've tried several USB cables until one worked with Chrome Manager App, and afterwards I can confirm it does pass the genuine check in Ledger Live.

I should have thought of that, thanks a lot and sorry for the noise.
