### ISSUE TITLE
Not persistent account importation

### ISSUE THREAD

**Issue by EricLarch** [LedgerHQ/ledger-live-desktop#1259]
If advanced mode is activated, add a "not persistent" property for each account on the import modal. When the Ledger Live app is closed, the account will be removed.

**Comment by gre** [comment]
( ctx https://github.com/LedgerHQ/ledger-live-desktop/issues/954 )

good idea.

- we can only start this feature as soon as @meriadec have finished on refactoring the persistence model ( it will improve performance + address the bug of the "can't unlock with my same password" that need user to reset data )
- quick thought on how to implement this: we could simply `filter(shouldAccountBePersisted)` in the db middleware.
