### ISSUE TITLE
Eth received from a contract not well managed by Ledger Live

### ISSUE THREAD

**Issue by Kozzi07** [LedgerHQ/ledger-live-desktop#1267]
#### Ledger Live Version and Operating System

Leger Live 1.0.3 / Windows 7 64bit

#### Expected behavior

Eth received via contract (withdrawal from bitstamp for example) should have a transaction appearing in the operations list with a date so the portfolio history can be correctly drawn

#### Actual behavior

Eth received via contract have no received date, no transaction is displayed in operations list.
They are considered as always present in the account and so the portofolio history is completely wrong.

#### Steps to reproduce the behavior

receive some eth from a contract and check the history graph. (account and global)

**Comment by gre** [comment]
thanks.
we are aware of the problem and I can reproduce it on my side as well (because have used Radar Relay and wrapped some ETH to WETH and back to ETH).
this is a current limitation of our API that are being reworked on.

**Comment by gre** [comment]
basically your balance should still be correct, but only the Graph and Operations list are affected.
it does not prevent you to do Send/Receive hopefully, so it's basically a glitch (only subset of operations visible).

Same could happen for Ripple as well, until we support all possible kind of "operation"s.

**Comment by mdesroubins** [comment]
I see this too:
- Created an ETH wallet via Ledger Live
- Send ETH from Bitstamp (via Smart Contract) to the Ledger address
- Waited forever, no change in balance
- Deleted the ETH Account in Ledger Live
- Added a "new" ETH Wallet (new is what Ledger Live displays)
- Balance is correct

I re-tested this multiple times with the same ETH Wallet on Ledger Live. Always the same behavior.
As noted before, there is also no transaction history for the smart contract transfers.

**Comment by gre** [comment]
@mdesroubins good catch, this is happening because our API still don't send the txs for contract yet. I've provided a workaround for now: https://github.com/LedgerHQ/ledger-live-desktop/pull/1326

So I guess the present bug is related to this 🤔  i'm going to provide a fix to scan accounts even tho they have only smart contract transfers
