### ISSUE TITLE
Last day shown twice on the chart

### ISSUE THREAD

**Issue by juliusosokinas** [LedgerHQ/ledger-live-desktop#1269]
#### Ledger Live Version and Operating System

- Ledger Live 1.0.5
- Platform: macOS

#### Expected behavior

When the chart is rendered, each day should have only one point in the chart.

#### Actual behavior

When the chart is rendered, the most recent day is displayed twice.

#### Steps to reproduce the behavior

Click on image to see the video:

[![Reproducing the current issue](https://cdn-b-east.streamable.com/image/w3g5k.jpg)](https://streamable.com/w3g5k)

Please note that this behaviour is currently only when viewing single accounts (hence is not present on the portfolio view).

**Comment by gre** [comment]
yes. this was fixed a few days ago in our develop branch.
#917

**Comment by juliusosokinas** [comment]
I still can see the same issue not being fixed yet on the latest release.

Please note - I've mentioned that this is _not_ on the main portfolio chart but on all the rest of individual crypto charts.

P.S. I'm in a London zone.
