### ISSUE TITLE
Manager v2

### ISSUE THREAD

**Issue by pollastri-pierre** [LedgerHQ/ledger-live-desktop#1270]
Design a smarter version of the current manager with a better integration with the device:
- Know what is installed on the device
- Ability to have a update button on application (if there is any)
- Show uninstall button only when the application is installed on the device
- Draw a distribution indicator of what is installed on the device
- Reinstall previously installed app after firmware update
- Have application categories, publishers, support links...

**Comment by EricLarch** [comment]
- Have a tag "compatible with Ledger Live"
- Link to supported wallet if not directly compatible with Ledger Live

**Comment by gre** [comment]
for the "compatible with Ledger Live", i wonder if it should be a dedicated category (if we introduce concept of category). ctx #1130

**Comment by meriadec** [comment]
@valpinkman does apps can be in multiple categories ? like tags behaviour

**Comment by gre** [comment]
I don't know if part of this plan, but i would personally dream about 2 features:

- a way to "trash all" apps
- make the install / install actions non blocking in term of UI, meaning they would just queue in an operation list. it's super annoying to install one by one and go through this blocking modal.

**Comment by gre** [comment]
We expect this to be fixed in context of a big rework that just got merged. we'll reopen in this does not fix in the next release https://github.com/LedgerHQ/ledger-live-desktop/pull/2596
