### ISSUE TITLE
Easier way to send report logs FROM the app

### ISSUE THREAD

**Issue by gre** [LedgerHQ/ledger-live-desktop#1289]
- [ ] need to specify it more clearly and validate
- [ ] design & wording
- [ ] implementation

**Comment by alexiri** [comment]
Also, the logs shouldn't contain all the addresses and public keys, for privacy reasons. It may be acceptable to truncate them to 4 characters or something like that, but there's no need for the full content.

**Comment by meriadec** [comment]
@alexiri the logs are **never** automatically shared, and are [cleaned up](https://github.com/LedgerHQ/ledger-live-desktop/blob/9c45918cc660e3de0cd6dafb16db073bdaa48724/src/helpers/log.js#L14-L17) when app is closed. But keeping xpub etc. can be useful for us to debug special cases if user shares it with us.

**Comment by alexiri** [comment]
Still, I think it would be nice to give the user the option of censoring them before sending them to support. I recently had to send the logs to support and I had to clean it up manually, which was a major PITA.

**Comment by meriadec** [comment]
Yep :100: , would be the optimal solution.

**Comment by gre** [comment]
We expect this to be fixed in context of a big rework that just got merged. we'll reopen in this does not fix in the next release #2596
