### ISSUE TITLE
Live doesn't find existing Ether wallets on ledger

### ISSUE THREAD

**Issue by PascalPrecht** [LedgerHQ/ledger-live-desktop#1291]
Hi everyone,

first of all I'd like to say that I appreciate your effort in building a nicely designed uniformed application for the ledger hardware wallets! Keep up the great work! 👏

As stated in the subject line, Live app doesn't seem to find my existing wallets on my ledger when trying to add them to live. I've already been through the support documentation, specifically this one: https://support.ledgerwallet.com/hc/en-us/articles/360006410253-Add-existing-accounts

Following the steps is pretty straight forward, unfortunately my existing Ether wallet doesn't show up in Live. So I've already created therefore another Ether wallet through Live on my Ledger. **However** (this may be important), when using the legacy Ledger Wallet Ethereum app, it **does** still find that address older existing address (but not the newly created one). 

I'm not sure how these apps distinguish between multiple Ether wallets on the Ledger, but it'd be nice if you could give some updates on whether this is a known issue and if there's a fix in the making :)

Please let me know if you need any more information!

**Comment by gre** [comment]
- the legacy wallet ethereum app won't find the Ledger Live account
- however, Ledger Live will discover the legacy Ledger Wallet Ethereum account. so if you still want to use legacy, you should create an account from it and is it everywhere.
- https://www.myetherwallet.com/ or http://mycrypto.com/ should help you discover any of your accounts, this is particularly useful to locate where things are.. 

the inherent problem is there is not yet a clear specification on how to derive Ethereum address, so we have to support many derivation paths at same time..
We would be very interested to know where is the Eth account that didn't show up for you, where are they located when you use MEW/MyCrypto ?

please also inform us which version of Ledger Live you are using.

( ctx discussion https://github.com/LedgerHQ/ledger-live-desktop/issues/1185 https://github.com/MyCryptoHQ/MyCrypto/issues/2070 )

**Comment by PascalPrecht** [comment]
Hi @gre thanks for your quick response.

> please also inform us which version of Ledger Live you are using.

Latest at the time of writing this issue - version `1.0.5`

> however, Ledger Live will discover the legacy Ledger Wallet Ethereum account. so if you still want to use legacy, you should create an account from it and is it everywhere.

Uhm.. this throws me off a bit. So I've got a legacy Ledger wallet Ethereum account, which I've created through my Nano S. This is exactly the one that I'd like to be able to see and manage in Ledger Live, but it doesn't seem to find it on my Nano S.

> https://www.myetherwallet.com/ or http://mycrypto.com/ should help you discover any of your accounts, this is particularly useful to locate where things are..

Yeap, I'm aware of that. I just expected my Ether wallet that I've generated via Nano S to simply show up and work with the new Ledger Live app, which kind of deprecated the Ledger Wallet Ethereum app (in which I've created my original Ether wallet in the first place).

> We would be very interested to know where is the Eth account that didn't show up for you

As mentioned above, it's my only Ether address I've created through Nano S

I'll need to setup MEW to give you that other information.

But just to confirm, legacy Ledger Wallet Ethereum accounts are supposed to work, correct? Then I'd assume this is a bug (as it doesn't work for me)

**Comment by PascalPrecht** [comment]
@gre quick update here, this is the path for the address that doesn't show up in Live: `m/44'/60'/0'`

Hope this is what you were looking for

**Comment by NastiaS** [comment]
@PascalPrecht , if this account doesn't have any transaction history, it will not show up as an existing account. You could try maybe to use env var SHOW_LEGACY_NEW_ACCOUNT=1 to see if it comes up. Otherwise, maybe you could fund it before importing.

**Comment by PascalPrecht** [comment]
Hey @NastiaS 

>  if this account doesn't have any transaction history, it will not show up as an existing account. 

so in my case, that particular address **does** have transaction history.

> You could try maybe to use env var SHOW_LEGACY_NEW_ACCOUNT=1 to see if it comes up

Where exactly am I supposed to do that? 

I do get the feeling though that this is a bug then as it sounds like it should just show up :)

**Comment by NastiaS** [comment]
ok, @PascalPrecht , had to ask, often it is the case - a newly created account with no transactions on it :-) thanks for confirming.
Most of our env var can be run locally from the command line. For exp:
```SHOW_LEGACY_NEW_ACCOUNT=1 yarn start```

**Comment by PascalPrecht** [comment]
@NastiaS ah got it. I'm not actually running on latest `master`, I've just installed the latest official release, downloaded from the main website.

Shouldn't this be enabled by default then, assuming that Live supports legacy accounts?

**Comment by gre** [comment]
> (SHOW_LEGACY_NEW_ACCOUNT is not used for ethereum. only a debug constant used for Bitcoin.)

Ok so we're not aware of the bug you described if I understand it. So just to confirm: you can see an ETH account on Ledger Wallet Ethereum (chrome app) that *does not* appear in all the ETH account imported on Ledger Live with the same device?

If i go to the chrome app right now, i can see the same account that is also imported on Ledger Live. which is also the first address that correspond to selecting `m/44'/60'/0' – Ledger (ETH)` on MEW.

can you confirm you can also see if you select this MEW option, your account in the first item of the list of address?

<img width="805" alt="capture d ecran 2018-07-26 a 11 04 48" src="https://user-images.githubusercontent.com/211411/43252854-cd4eded0-90c3-11e8-8bc6-5a0f6797b78c.png">

^ here is mine, i tested many diff address. they all appear in LL. the first one appear in Chrome app (because Ledger Wallet Ethereum only actually support a single account)

**Comment by PascalPrecht** [comment]
> So just to confirm: you can see an ETH account on Ledger Wallet Ethereum (chrome app) that does not appear in all the ETH account imported on Ledger Live with the same devicedg

Correct. I see an ETH account on Ledger Wallet Ethereum (originally also created with that through my nano S) and that same account **does not** get recognized by LL.

> If i go to the chrome app right now, i can see the same account that is also imported on Ledger Live. which is also the first address that correspond to selecting m/44'/60'/0' – Ledger (ETH) on MEW.

I see that address when selecting m/44'/60'/0' – Ledger (ETH) on MEW as well, plus a bunch of other address which are naturally derived. 

It just doesn't get synced with LL.

> can you confirm you can also see if you select this MEW option, your account in the first item of the list of address?

Yes, the first item in the addresses is that address that LL doesn't manage to sync from my nano S.

**Comment by gre** [comment]
if you test this URL:

```
http://api.ledgerwallet.com/blockchain/v2/eth/addresses/REPLACE_YOUR_ETH_ADDRESS/transactions?noToken=1
```


(by replacing with the first account that don't show)

does it show a list transactions? ( or is it `"txs":[]` )

same question with

```
http://api.ledgerwallet.com/blockchain/v2/eth/addresses/REPLACE_YOUR_ETH_ADDRESS/balance
```

do you have a non zero balance `"balance": 0` ?


If not, i'm not really understanding this problem. You could try to Ctrl+E just after doing the scan and see how it looks like on https://ledger-live-tools.netlify.com/logsviewer (tmp tool we use before better workflow)

do you have any logs that shows:

```
scanning ethereum at 44'/60'/0'/0: YOUR_ETH_ADDRESS resulted of Account with 61 txs.
```

?

**Comment by PascalPrecht** [comment]
So for the first URL - yes, I do have transactions.
For the second URL - yep, I do have balance

> If not, i'm not really understanding this problem. You could try to Ctrl+E just after doing the scan and see how it looks like on https://ledger-live-tools.netlify.com/logsviewer (tmp tool we use before better workflow)

You mean after trying to add an existing account?

**Comment by gre** [comment]
yes.

so basically at the time you should see this

<img width="499" alt="capture d ecran 2018-07-26 a 11 34 48" src="https://user-images.githubusercontent.com/211411/43254619-1bb5e7cc-90c8-11e8-9442-206125566ac3.png">

**Comment by PascalPrecht** [comment]
@gre Okay so... I have no idea what has changed now, but for some reason the legacy account now showed up 🤷‍♂️

Not sure if that makes sense, but maybe it has something to do how old the txs are? Because I just made one with this account.

Anyways, closing this one as resolved then.

**Comment by PascalPrecht** [comment]
Oh, and thank you so much for being super responsive here!! 🙏

**Comment by gre** [comment]
definitely weird. I suspect something weird happen in our API and the app was thinking your account had no transaction 🤔  .

**Comment by PascalPrecht** [comment]
Yea, maybe something worth looking into..

**Comment by PehrGit** [comment]
@gre I'm not sure if this is the right place to mention this, but I'm having the same issue. Balance in a wallet that I created in the old chrome app is not showing up in the Ledger Live application. I can try to make a transaction from LL to see if that helps, but then we may never find out what causes this. Maybe you would like me to do some troubleshooting first, to help others who run into the same problem?

**Comment by alamojoe60** [comment]
I have the same  problem going on 2 years now and I can’t find anyone with a clear explanation of how to recover the Eth.  As this post just fell away with no clear cut explanation. Does someone out there have a step by step way to recover The ETHER. I would be glad to be able to know how to get my old legacy account back maybe I could find my Ethereum there because it did not transfer to Ledger Live.Sorry to say  I just go in circles with ledger support. You would think by now there would be a solution since I’m not the only one with the same issue.
Thank you.
David

**Comment by gre** [comment]
@alamojoe60 do you know exactly where your funds are? by *where* I mean, on which derivation path?

If you go on MEW, do you see the funds, what did you chose as an option and on which index do you see it.

for further investigation we might have to go through support.ledger.com contact

**Comment by alamojoe60** [comment]
Hello gre. I wish I would have checked back here, I just ran across this that I had saved in my email. I’m going try and do the same things you did to find my Eth but I get confused at some of the post and end up not getting anywhere. I hope I do not need the old legacy wallet because it’s says no longer supported. I hope you get this post. His there an alert system to be notified when someone comments to your post? I will check back here every day now to see if you r anyone has posted back. Thank you for reaching out. 
David

**Comment by gre** [comment]
Hi @alamojoe60 ,

Ledger Live supports all paths that ledger softwares supported in the past, we never dropped one but just added a few different scanning paths. Happy to help, you might need to go through tech support for helping us to investigate the problem https://support.ledger.com/hc/en-us/requests/new

thanks

**Comment by alamojoe60** [comment]
Ok Renaudeau  will start trying that when I get back home Saturday. 
Thank you for your help.

**Comment by maxgmer** [comment]
Same problem, havent got into my ledger in a while, just entered  to update firmware, then decided to chech my eth and didn't see my existing account i had last time, when i was sending my funds to ledger

**Comment by alamojoe60** [comment]
﻿Is this email from ledger

New Ledgеr Nano X deviсe?

Dear davit12@aol.com,
Dіd yоu trу to lоg into yоur Lеdgеr aсcоunt frоm nеw Lеdgеr Nano devіce reсentlу?
Nеw lоcatiоn
IP address: 32.234.63.69 
Вrоwsеr: Ореra
Devіce іd: lеdger-5471213fea6mcz935x
User agеnt: Mozіllа/5.0 (Mаcintosh; Intel Mас оS X 10_15_3) apрleWеbKit/537.36 Оpеrа/81.0.3987.163 Safarі/537.36
Nоtе: Unusuаl activіty оn уоur aсcount.
If you arе nоt the оnе whо tried tо log іn, plеase cаncel devісе authоrіzаtіon nоw in уour аcсоunt settіngs.


Canсеl


Bеst rеgards,
Ledgеr Suрpоrt Тeam.

Sent from my iPhone
