### ISSUE TITLE
Install/notify udev rules requirement during the onboarding

### ISSUE THREAD

**Issue by pollastri-pierre** [LedgerHQ/ledger-live-desktop#1292]
Currently users need to setup correct udev rules to be able to use the device on their computer.
The only place to find this information is in the knowledge base.

We could either:
- Have a screen which explains what are udev rules and how to install them.
- Require super user rights and add them automatically.

**Comment by gre** [comment]
@pollastri-pierre today, we already have a custom feature that should show a link "Help" that point to documentation for this specific case.
not sure if we should go any farther.


https://github.com/LedgerHQ/ledger-live-desktop/pull/1224

https://user-images.githubusercontent.com/315259/42997043-a84d83b4-8c15-11e8-86cc-3e32dded03f7.gif

**Comment by gre** [comment]
not yet. but i think we'll need this system everywhere 🤔  
and if there is no "help" link to provide, it would be a generic "Contact us" .. we'll need to have contact us each time we dislpay errors to prepare some future in-app report logs features..

**Comment by dasilvarosa** [comment]
I think adding a screen or modal in the onboarding for linux users would be the most user-friendly. Relying on the error message to convey this info seems less intuitive.
