### ISSUE TITLE
Specify Inputs/Coins to spend in a transaction

### ISSUE THREAD

**Issue by rblaine95** [LedgerHQ/ledger-live-desktop#1294]
- [x] I have checked this feature was not yet requested.

#### Description:
In Electrum ([git](https://github.com/spesmilo/electrum)/[home](https://electrum.org)), you can choose which inputs to spend in a transaction. I think this would be a very useful feature for Ledger Live.

#### Part of the application:
Bitcoin (maybe other currencies?) Send function.

**Comment by 2pac1** [comment]
And if they implement option of detecting dust payments, then you can mark them automatically NOT SPENDABLE.

**Comment by rblaine95** [comment]
@2pac1 Yes! That would be great!

**Comment by 2pac1** [comment]
https://github.com/LedgerHQ/ledger-live-desktop/issues/1626

**Comment by tsujp** [comment]
Is there any news on this? Would a PR be accepted?

I'd also like to have the ability to select inputs via some characteristics like amount (inputs of a certain size only); and FIFO vs LIFO. Currently Ledger Live is locked to FIFO.

**Comment by gre** [comment]
No ETA on shipping this feature but we have internal discussions on implementing this. First step that is being worked on is an API that will be exposed by [lib-ledger-core](https://github.com/LedgerHQ/lib-ledger-core) level which will then make it possible from our UI side.

**Comment by cthepot-ledger** [comment]
#3130
