### ISSUE TITLE
ETC transaction asks for ETH confirmation on Nano S

### ISSUE THREAD

**Issue by titusz** [LedgerHQ/ledger-live-desktop#1300]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.0.5
- Platform and version: Windows 10

#### Expected behavior

When sending ETC the Nano S should ask to confirm an ETC transaction

#### Actual behavior

When sending ETC the Nano S asks to confirm an ETH transaction

#### Steps to reproduce the behavior

Send ETC and see Nano S asking to conform transacting ETH.

**Comment by gre** [comment]
If you look in your account settings (little cogs in the account screen) and you look in the advanced logs, what do you have as "path" ?

**Comment by titusz** [comment]
The path is `44'/60'/160720'/0'/0`. I should also mention that the ETC transaction went out fine. It is just that the nano s display showed the amount to be confirmed as ETH. Which is a bit confusing/unsettling :).

**Comment by gre** [comment]
I suspect the device will just use the path to determine what is the currency. because `44'/60'` means ETH 🤔
maybe @btchip will know better.


new ETC address created on LL would probably not have the same problem. Only issue is it makes it harder to use in MEW (cf discussions #1185) until a final ETH derivation spec settle these questions.

**Comment by titusz** [comment]
According to [SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) the ETC derivation path should be `44'/61'` and not `44'/60'` as ledger live shows?

**Comment by gre** [comment]
yes. and this is what we are deriving now.
but MyEtherWallet / the old ledger chrome app, was using this weird path (no idea about the reason).

Ledger Live is following BIP 44 for all coin derivation in the new accounts you will create.

**Comment by titusz** [comment]
Ok so I guess this can be handled as legacy bagage. The nano s ethereum app could special case '44'/60'/160720'/' derived transaction and ask for ETC confirmation to not confuse beginners. But I am not sure if it is worth the effort.

**Comment by gre** [comment]
i was thinking the app was using the `chainId` to determine on which network it goes and what's the currency, apparently it's not done like this 🤔, i'll ask

**Comment by gre** [comment]
should be fixed now
