### ISSUE TITLE
[develop branch] Performance of Portfolio accounts tile list

### ISSUE THREAD

**Issue by gre** [LedgerHQ/ledger-live-desktop#1313]
the fact we display lot of tiles of accounts with the graphs in the portfolio is a **huge** performance deal.

I'm testing the app with 40 accounts and it's barely usable. I get 5 fps when i scroll and if a sync is happening (because it refreshs the graphs)
If i remove the section that contains the graphs, the perf is good even with 40 accounts.

If we make a new screen that have this "list of accounts", we would no longer have to display them in Portfolio, which would also have these nice benefit:
- better perf as mentioned here
- when you have lot of accounts, this is barely useful, you have to scroll through lot of accounts until seeing the "Last Operations" which is the important part.

**Comment by meriadec** [comment]
I remember someone already mentionned the fact it was hard to see latest operations when having many accounts, on Portfolio. And we still have list of accounts on side menu.
So :+1: because I'm not sure there is many we can do to increase our graphs perfs.

**Comment by gre** [comment]
@meriadec that's a bit extreme, but we could freeze the re-rendering of the graph.. meaning they only actually refresh if you leave and come back... that would be the least solution.. also if these graph would display the value in crypto, and not the value in countervalues, that would make not ALWAYS refresh each time value refresh^^

**Comment by gre** [comment]
I assume it done by #1336
