### ISSUE TITLE
Live doesn't find existing Ether wallets on ledger #1291

### ISSUE THREAD

**Issue by Kryptotom** [LedgerHQ/ledger-live-desktop#1314]
Same Problem as in the closed
Case from PascalPrecht. The Account on the Chrome Wallet shows the correct Balance. The ledger live shows zero Balance. The Adress has a trading History, the ETH Adress is created with the ledger ETH Chrome wallet. The latest transaction
was one year ago. Maybe you have a problem with older balances? I think, it is a bug. What can i do?

**Comment by gre** [comment]
@Kryptotom so you are basically falling on step 3 with this ?

![](https://user-images.githubusercontent.com/211411/43254619-1bb5e7cc-90c8-11e8-9442-206125566ac3.png)

**Comment by Kryptotom** [comment]
Yes - i see this window and if i click on Ethereum 1 (cross) and add, i get zero wallet balance. The Nano Web Wallet shows the correct balance and History.

**Comment by gre** [comment]
what you see under "Add a new account" is always a new unused account, so it will always be 0, but what I don't understand is that your account was not discovered, normally there should be another section above for "Existing accounts"..
Our team will double check the code next week to investigate why this could happen. No one was able to reproduce the problem last week.

**Comment by wadshrad** [comment]
I had trouble adding Eth account. 
It Live would find the device but then when I opened the Eth app on the device live would start looking for it again.
I went in to the app settings on the device and changed browser support to no then it seemed to work.

**Comment by Kryptotom** [comment]
Browser support in the ledger App is disabled.I think it is some issue with the transaction date and old ETH Wallet format.

**Comment by Kryptotom** [comment]
If you want, i can give you a secure remote connection on a VM-Ware machine, so that you can check this issue, after you have confirmed your identity.

**Comment by gre** [comment]
@Kryptotom thanks,

I guess for now it would already be useful if you could export logs, (press Ctrl+E) JUST after the scanning (when you see like the screenshot above)..
to provide us the log, don't share it here, best would be to send them on https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165 and link to this GitHub issue as well.

**Comment by mdesroubins** [comment]
I see the exact same behavior. An old Ether Wallet created with the Ledger Chrome App is not discovered by Ledger Live (1.0.5). In the Ledger Chrome App or in MyEtherWallet it is available.

**Comment by Kryptotom** [comment]
Logs are sended.

**Comment by gre** [comment]
@Kryptotom ok so I can confirm that the bug occurs because our API don't support yet the contract data for you case, I can see in the logs that the address is getting scanned but Ledger Live thinks there is no transactions (because our API don't return any as it's only contract transactions).
We have a workaround for this that will be shipped in 1.1.0 and that should address this by also taking the balance into account.

the real fix will come as soon as our backend is improved.
