### ISSUE TITLE
LEDGER LIVE (BTC)  Wallet fees should be discounted from the full amount

### ISSUE THREAD

**Issue by douglasdeodato** [LedgerHQ/ledger-live-desktop#1316]
#### Ledger Live Version and Operating System

ledger live bitcoin wallet, windows 10

- tested on Ledger Live **version_here** 
1.0.6
- Platform and version: **e.g. Mac 10.13.5 / Windows 10 / ..**
windows 10

#### Expected behavior
fees should be discounted from the full amount, after the user choose the fees he wants spend this should be discounted from the main amount .

#### Actual behavior
right now it is very hard to send small amounts as we don't know how much fee we need pay.

for example in that case: I want send my full ammount: 0.0023921 and says it is not enough balance, that it is very frustrate as I don't know how much fees it is charging me.

#### Steps to reproduce the behavior

![img-0102 1](https://user-images.githubusercontent.com/993318/43358233-a7995a1a-9264-11e8-86ce-ab1b6a5c0a59.JPG)

**Comment by gre** [comment]
we should have a MAX button ( #905 ) in the future that would address this usecase.
i'm not sure how we should address the "fees included in amount" tho and i'm not aware of any wallet having such feature (do you?). Usually, when you send funds, you want the recipient to receive exactly an amount (like the price of something) not the price minus the fees.

**Comment by douglasdeodato** [comment]
I can't use the chrome extension anymore, but I kinda think the fees used to be discounted from the amount I was sending to be fair I can't remember anymore.

tis feature exists in loads of exchanges right now.

I will give to you a sample:
u have 10 btc accounts in the wallet right?  so u want transfer everything from the 9 wallets to 1, so in that case I need send the full ammount and I need the fees be calculated so I can clean up the account.

yes I was about to create a issue related to the max button, thanks to link that.

**Comment by gre** [comment]
I see yeah. I think it would be great to offfer the two possibilities. I don't know yet how in term of UI but i'll let our designers know and we'll re-discuss about this in future.

**Comment by 2pac1** [comment]
its crazy that you cant empty the wallet. That there is no MAX meaning send out everything, and then deduct fees from it. User should type and calculate and then is left with some dust btc in the account? 
Look up to electrum!

**Comment by gre** [comment]
It is not planned to have fees exclusive amount, however we'll implement send max in this quarter. #905
