### ISSUE TITLE
ledger live  - be able to reorganize and drag  accounts already created on the left sidebar

### ISSUE THREAD

**Issue by douglasdeodato** [LedgerHQ/ledger-live-desktop#1317]
- [ ] I have checked this feature was not yet requested.

### **Issue related to the left sidebar in the App.**

right now if I add any new account btc, ltc or another one, this account goes to the end of the left sidebar

would be nice this account was add bellow of the coin shes belong not random as now.

**case 1:**
example: on this sample I have 2 btc accounts, after I create the third one, the account goes to the end of the sidebar, very bad to find the account, imagine someone having 100 or 1000 accounts (wallets adresses) , would be good to have it per coin?

**so for example:** 

bitcoin accounts = and show all bitcoins accounts
litecoin accounts = and show all litecoins accounts

don't need change much  the application color, could be using the dark and light colours already using on the app.

so the bitcoins will be a dark bg and litecoin a ligther one.

**case 2:** 
just organize new account created to be insert bellow the last one created according of the coin.

sample: I have 3 btc accounts if I create another one goes bellow the other 2 btc accounts and not to the end.

**case 3:**
 be able to move the accounts in the side bar like draggable , so I could move  the accounts and leave wherever i want top, middle, bottom

like that:
https://jqueryui.com/draggable/

#### Part of the application

![sidebar](https://user-images.githubusercontent.com/993318/43359379-d6a2b1f4-9277-11e8-8590-8ebf5589c7d6.png)

**Comment by Luuk2016** [comment]
Something like this has already been requested:
#1154
