### ISSUE TITLE
Requires running as Root on Ubuntu/Pop!_OS 18.04

### ISSUE THREAD

**Issue by ChiefGyk** [LedgerHQ/ledger-live-desktop#1318]
#### Ledger Live Version and Operating System

- tested on Ledger Live **1.0.5**
- Platform and version: **Ubuntu/Pop!_OS 18.04**

#### Expected behavior

It's supposed to pass the genuine check as it did on the windows side of this laptop and pop up with an option to allow ledger manager on the device. 

#### Actual behavior

Does nothing just spins in circles and the actual device is doing nothing despite being at the dashboard. It worked flawless on the Windows 10 side of this laptop but not on Pop!_OS 18.04 which is a flavor of Ubuntu. All rules are inserted including 
```
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0660", GROUP="plugdev", ATTRS{idVendor}=="2c97"

KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0660", GROUP="plugdev", ATTRS{idVendor}=="2581"
```
Confirmed this on my work desktop which also runs Pop!_OS 18.04 as well as my laptop. I even tried resetting the damn device and upgrading the firmware from 1.4.1 on the Windows side to 1.4.2. But on Linux I can't get past the genuine check

#### Steps to reproduce the behavior
![image](https://user-images.githubusercontent.com/19499446/43359951-ce7a5042-927a-11e8-8413-18b30434230f.png)

**Comment by ChiefGyk** [comment]
Update it allowed me when I ran the program as root

**Comment by ChiefGyk** [comment]
But it still won't allow me to add accounts or do much unless I run the app as root

**Comment by ChiefGyk** [comment]
Yup anything actually involving an interaction with the ledger itself requires running as root, but otherwise once setup I can login and see what information was saved prior.

**Comment by meriadec** [comment]
Can you try prepending all lines of your udev rules by `OWNER="<your-username>" ` (more details [in the help page](https://support.ledgerwallet.com/hc/en-us/articles/115005165269-Fix-connection-issues))?

**Comment by gre** [comment]
related to the [usb setup to do on Linux](https://support.ledgerwallet.com/hc/en-us/articles/115005165269-Fix-connection-issues)
