### ISSUE TITLE
Allow countervalue settings to be a crypto currency

### ISSUE THREAD

**Issue by gre** [LedgerHQ/ledger-live-desktop#1323]
This feature request was requested by multiple people on various places (github, twitter, reddit): "it would be great to see portfolio in bitcoin".

More generally, I think it would be great to have **Countervalue** settings to support not just fiats, but also crypto currencies.

This is roughly easy to add, but there are some subtilities:

- in live-common, we need to allow the "intermediary" calculation to use reverse pair for the intemediary->currency. ( for instance, let's say we select ETH as countervalue, to do ZEC->ETH, we would still use BTC intermediary, as in ZEC->BTC->ETH, but instead of doing `rate(ZECBTC)*rate(BTCETH)` we would have to do `rate(ZECBTC)/rate(ETHBTC)` because BTCETH don't exist.
- once that is done, we enable this reverse mode basically only if it's a cryptocurrency. Then we need to make sure the pairsSelector is correctly following the same paradigm.
- figuring out how we can mix a select of fiats and crypto currencies. do we make 2 groups or do we mix them with a alphabetic sort?
- figuring out what happen if we are supposed to display a countervalue of the same crypto (e.g. if i set countervalue to BTC, and i'm seeing a BTC account, do we repeat the information? (easiest))

**Comment by dasilvarosa** [comment]
A community member submitted this idea: 

Add the option to show a line for the Bitcoin value aside the fiat Value in the graph. (example: https://bitinfocharts.com/bitcoin/address/1PnMfRF2enSZnR6JSexxBHuQnxG8Vo5FVK) 

This way users can tell in a glance: 
- how the portfolio performs in crypto value 
- when they deposited or withdrew

**Comment by gre** [comment]
this is shipped for Bitcoin
