### ISSUE TITLE
I can't dismiss the "Receive" dialog

### ISSUE THREAD

**Issue by jdevora** [LedgerHQ/ledger-live-desktop#1329]
#### Ledger Live Version and Operating System
version 1.0.6 On Windows 10
- tested on Ledger Live 1.0.6  (I had to close the app for see the version and it auto-updated to 1.0.7)
-
#### Expected behavior
There should be Back or close button or the dialog should dismist itself when you click outside it

#### Actual behavior
The pop up with the new address and its QR is shown and there isn't a way to close this dialog and go back to the main screen
#### Steps to reproduce the behavior

![imagen](https://user-images.githubusercontent.com/10220619/43397192-e17aa9d0-93fb-11e8-9327-17a2b8f24962.png)

**Comment by gre** [comment]
You are supposed to verify on your device at this time.
**By design, we actually want the app to block** until you validate OR deny on your device.

so this step is not dismissable until you do an action on your device.

> we basically want to avoid any case where you can go to anther part of the app while the device being in a blocking step (this is also true for signing transactions)

**Comment by jdevora** [comment]
If that is the case, you should say something in the dialog.
I validated it on my device, but it could be it was after I closed Ledger Live
