### ISSUE TITLE
Setting wrong expectations on confidentiality

### ISSUE THREAD

**Issue by Legogris** [LedgerHQ/ledger-live-desktop#1337]
Running 1.0.7 on Arch Linux.

During the onboarding, the user is told that if their password is compromised, an attacker could get hold of their account information. Some users are likely to get the impression that any private information on the file system is encrypted. Account information is, however, by default saved in clear-text in logs and Cache.

As long as this is the case, can we change the text on this in the onboarding to avoid misunderstandings?

**Comment by gre** [comment]
one quick way we could take to fix the problem is to remove the log files when you quit (gently) the app.

> Logs are saved in clear, but technically data are decrypted when the app is opened in the RAM, so if you dump the memory you can see the data as well. it's only when you quit the app that obviously, the data are gone from the RAM. we'll see if we can manage to only keep logs during the app is opened as well.

**Comment by gre** [comment]
best issue number
