### ISSUE TITLE
Password incorrect just after update to 1.0.7

### ISSUE THREAD

**Issue by welcoMattic** [LedgerHQ/ledger-live-desktop#1347]
#### Ledger Live Version and Operating System

- tested on Ledger Live **1.0.7**
- Platform and version: **macOS 10.12.6**

#### Expected behavior

My password is correct, double checked. I want to be able to open my Ledger Live app

#### Actual behavior

My password is correct, double check. But Ledger Live 1.0.7 shows me `This password is incorrect`, and I can not open my account.

#### Steps to reproduce the behavior

Login with your correct password on Ledger Live 1.0.7

**Comment by welcoMattic** [comment]
Really?? I spent hours to import them !!

**Comment by meriadec** [comment]
Can you try with the v1.1.0 prerelease? https://github.com/LedgerHQ/ledger-live-desktop/releases/tag/v1.1.0-rc.3

**Comment by welcoMattic** [comment]
Password decryption doesn't work.

**Comment by gre** [comment]
have you changed your password or it was always the same? either the data is encrypted with a password or it's not. I don't really see what could be a third case, we didn't change the encryption algorithm AFAIK so it can only be a wrong password case to me unless bug.

**Comment by meriadec** [comment]
I confirm encryption algorithm didn't change ([before](https://github.com/sindresorhus/conf/blob/d41ec3a31ac074a7a94d657f80550375542b37d4/index.js#L133) / [after](https://github.com/LedgerHQ/ledger-live-desktop/blob/69ddbdf990bc81ac7766a91f4ef3085220a367dd/src/helpers/db/index.js#L25)), so only thing I can imagine is either password change or data being corrupted after update
