### ISSUE TITLE
having a test page to check health of services

### ISSUE THREAD

**Issue by gre** [LedgerHQ/ledger-live-desktop#1349]
I'm not sure if it's an in-app feature (would be better) or a blank page feature,
but it would be neat to have a quick status page that check some critical endpoints to work.. some users are experiencing Network Down (maybe because proxy or something) so it would be great for support and us to investigate on these if you had a check page.

key things to check:
- that a `wss://` websocket works (do we have a specific status hello world for this?)
- that countervalues work (can just ping https://countervalues.api.live.ledger.com/status )
- that blockchain api works (can just ping https://api.ledgerwallet.com/blockchain/v2/btc/fees )

It could be a minimal text that shows up if you browse Settings > Help..

**Comment by valpinkman** [comment]
Also we need to check for

- manager api, for app install/uninstall and firmware updates

**Comment by 2pac1** [comment]
That is great idea, because when Ledger had their node down, you start panicking immediately

**Comment by gre** [comment]
@2pac1 for the infrastructure side I would recommend checking http://status.ledger.fr
This feature would not cover it because would just check basic connectivity
But there will definitely need to be some improvement in the error message. Related #1383
