### ISSUE TITLE
Windows: Internal process error (3221226505)

### ISSUE THREAD

**Issue by plavirudar** [LedgerHQ/ledger-live-desktop#1351]
#### Ledger Live Version and Operating System

- tested on Ledger Live **1.07 and 1.10rc3 and 1.1.7**
- Platform and version: **Windows 10**

#### Expected behavior

Adding a new coin account should succeed

#### Actual behavior

When adding one of my Bitcoin wallets, I receive the error `Internal process error (3221226505)`. Other coin wallets (including another Bitcoin wallet on a different seed) do not appear to be affected by this bug. 

![ledger live_2018-07-31_21-04-27](https://user-images.githubusercontent.com/36850308/43495304-53539684-9505-11e8-94a6-43c9f94f7da0.png)

#### Steps to reproduce the behavior
Relevant logs are pasted below, removing personally identifying information. The emoji appear to be verbatim and were also present in the original log file. 

`{"stack":"Error\n    at o (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/renderer.js:1:25595)\n    at a (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/renderer.js:1:25782)\n    at EventEmitter.l (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/renderer.js:1:27245)\n    at emitTwo (events.js:130:20)\n    at EventEmitter.emit (events.js:213:7)","message":"Internal process error (3221226505)","name":"InternalError","level":"error","pname":"renderer","timestamp":"2018-08-01T01:09:19.442Z"},{"level":"info","message":"booting internal process...","pname":"main","timestamp":"2018-08-01T01:09:19.441Z"},{"type":"cmd.START","level":"info","message":"CMD listenDevices.send()","pname":"renderer","timestamp":"2018-08-01T01:09:19.440Z"},{"type":"cmd.ERROR","data":{"message":"Internal process error (3221226505)","name":"InternalError"},"level":"warn","message":"✖ CMD libcoreScanAccounts error","pname":"renderer","timestamp":"2018-08-01T01:09:19.440Z"},{"message":"listenDevices error","name":"InternalError","level":"warn","pname":"renderer","timestamp":"2018-08-01T01:09:19.373Z"},{"type":"action","level":"debug","message":"⚛️  RESET_DEVICES","pname":"renderer","timestamp":"2018-08-01T01:09:19.373Z"},{"type":"cmd.ERROR","data":{"message":"Internal process error (3221226505)","name":"InternalError"},"level":"warn","message":"✖ CMD listenDevices error","pname":"renderer","timestamp":"2018-08-01T01:09:19.361Z"},{"type":"db","level":"debug","message":"📁  write app:countervalues","pname":"renderer","timestamp":"2018-08-01T01:09:19.345Z"},{"type":"action","level":"debug","message":"⚛️  LEDGER_CV:POLL","pname":"renderer","timestamp":"2018-08-01T01:09:19.296Z"},{"level":"warn","message":"Internal process ended with code 3221226505","pname":"main","timestamp":"2018-08-01T01:09:18.995Z"},{"type":"network-response","level":"info","message":"✔📡  HTTP 200 GET https://explorers.api.live.ledger.com/blockchain/v2/btc/blocks/current – finished in 1056ms","pname":"internal","timestamp":"2018-08-01T01:09:18.620Z"},{"type":"libcore","level":"info","message":"🛠  2018-07-31T21:09:18Z-04:00 I: GET https://explorers.api.live.ledger.com/blockchain/v2/btc/blocks/current - 200 OK\r\n","pname":"internal","timestamp":"2018-08-01T01:09:18.620Z"}`

Potentially also related: https://www.reddit.com/r/ledgerwallet/comments/92oahz/internal_process_error_3221226505/

**Comment by andrehortab2u** [comment]
Same problem here with BTC wallet, ledger live and Windows.

**Comment by KhalilBellakrid** [comment]
Hello @andrehortab2u  @plavirudar  ,
We didn't manage to reproduce this issue, so could you please test this pre-release Live version : https://github.com/LedgerHQ/ledger-live-desktop/releases/tag/v1.1.7 and see if you still have the problem?
This pre-release fixes some Internal Errors and I want to see if yours is included in it, if you still got the issue please send us your logs (with this version) and xpubs.
Thank you for your help !

**Comment by plavirudar** [comment]
@KhalilBellakrid 

Same bug persists on 1.1.7, I suspect that it's something to do with certain transactions on the wallet (I recall the same wallet working without issues until I sent an RBF transaction due to network congestion), however I was unable to replicate the bug with another wallet using RBF. 

How should I go about sending the full logs in a private and secure manner? Can one of the devs provide a PGP public key to which I can send the relevant logs?

**Comment by plavirudar** [comment]
@KhalilBellakrid  I have opened Ticket #198454 with the full logs attached.

**Comment by plavirudar** [comment]
This has been solved through Ledger support. 

You need to delete your `%appdata%/Ledger Live` directory and perform a full reset, and the wallet will sync fine after that.

**Comment by KhalilBellakrid** [comment]
@plavirudar 
Yes I've asked for that and emphasised on the fact that you should be warned about losing all your data, thank you for your feedbacks and for closing the issue, @andrehortab2u could you confirm that deleting ` %AppData%/Ledger Live` solves also the problem for you ? 
Thank you.

**Comment by andrehortab2u** [comment]
Worked! Thank you!

**Comment by jwbats** [comment]
> This has been solved through Ledger support.
> 
> You need to delete your `%appdata%/Ledger Live` directory and perform a full reset, and the wallet will sync fine after that.

Yeah, we've noticed it syncs fine on the first initialization. But what about thereafter? Have you generated  more txs after that to check?

I don't want to have to reinit my whole wallet to have to force-sync it.

**Comment by meriadec** [comment]
@jwbats you can safely copy your `%APPDATA%\Ledger Live` folder somewhere else, test, and if it fails you put it back. All local data is contained inside.

**Comment by jwbats** [comment]
> @jwbats you can safely copy your `%APPDATA%\Ledger Live` folder somewhere else, test, and if it fails you put it back. All local data is contained inside.

Thanks for the tip. I've just done this. Giving it a completely new re-init has successfully synced the whole wallet.

Now, when I click the sync button, it will not give me an error.

I'm currently using the latest 1.1.0 release. It was the re-init that fixed the problem, though.

**Comment by plavirudar** [comment]
@jwbats Yes, my initial bug appeared after sending a RBF tx. It's pretty likely that it's some unexpected handling of RBF that's causing the error. I've sent a few RBF tx to trigger the sync bug but couldn't reproduce the bug, so it's likely that this only happens when certain conditions are fulfilled.

**Comment by jwbats** [comment]
If I were given the option of turning on logging at the info level, I'd happily run up a few hundred megs of logs until it happened again, so I could submit it to the devs.

**Comment by meriadec** [comment]
@ah2020b for Linux based system, user data folder is located at `~/.config/Ledger Live`.
You can open it directly from the app in the Settings > Help section.

![2018-10-17_1374x255](https://user-images.githubusercontent.com/315259/47109164-dacd4300-d24d-11e8-982f-73a70201b659.png)

**Comment by jwbats** [comment]
I promised you guys I'd keep you up to date. I've received another rbf tx and I am dealing with the sync error once again. The same issue still persists in Bitcoin wallet version 1.3.7.

**Comment by AndoroidX** [comment]
Happened to me with Algorand and Ledger nano S. Algorand wallet version 1.2.15.
