### ISSUE TITLE
ETH 'Internal Transaction' doesn't reflect in log, doesn't update balance.

### ISSUE THREAD

**Issue by ferozkhanhamid** [LedgerHQ/ledger-live-desktop#1352]
#### Ledger Live Version and Operating System

- tested on Ledger Live v1.0.7
- Platform and version: MacOS 10.13.6

#### Expected behavior

Transaction Log should show the transaction and the balance should update to reflect actual account balance.

#### Actual behavior

- The transaction log for ETH address doesn't show an *internal transaction. 
- Balance of internal transaction not updated for the ETH account.
- Unable to send received funds from ETH address, as balance is shown as zero.

*Internal transaction - ETH was sent from an exchange, so from a contract address.

#### Steps to reproduce the behavior

- transfer ETH from Bitstamp exchange (didn't try any other exchange) to Ledger ETH address.

Note : 

- Force synced multiple times, but no change.
- The transaction was not visible in the old Ledger Wallet Ethereum Chrome App either.
- However, the old app's BALANCE was updated to show the actual account balance.
- Was able to send ETH from the old app.
- The ETH sent txn (made from old ETH chrome app) was updated in Ledger Live App.
- Transaction in question : 0x45c63a93c0dc7c91adbc1ff4d49a57f8db19df31952ed830c94b48babb963a4b

#### Screenshots

![screen shot 2018-08-01 at 5 09 20 pm](https://user-images.githubusercontent.com/41228015/43519770-53b57792-95ae-11e8-84c8-7d95fecc8abb.png)

![screen shot 2018-08-01 at 5 11 24 pm](https://user-images.githubusercontent.com/41228015/43519777-58e35ebe-95ae-11e8-9e09-7f515b6f9e68.png)

**Comment by gre** [comment]
this is a missing feature in our API, this is getting reworked. nothing we can do from Ledger Live side.

**Comment by gre** [comment]
@ferozkhanhamid   I'm surprised because both projects use the same API.

And even on your screenshot, I don't see anything wrong 🤔   appart from the different formatting choice (one displaying less digits)

<img width="678" alt="capture d ecran 2018-08-01 a 16 33 17" src="https://user-images.githubusercontent.com/211411/43528230-c6e9199a-95a8-11e8-99e5-23db8ce6161f.png">

**Comment by ferozkhanhamid** [comment]
@gre I didn't think to take a screenshot of the old app when the balance was there, but be assured, it was there. I took the screenshots later after the transaction was done (from the old app). So, my bad on not getting that, but it was visible :)

**Comment by gre** [comment]
AH ok 🤔   what i'm sure is there are also inconsistencies between nodes which is another bug in current API. so hopefully as soon as backend team fix it, everything will be good. 🤞

**Comment by alexiri** [comment]
With the latest 1.1.1 release I can finally add ETH addresses with only internal transactions, but those transactions are still not showing up in the list of Last Operations.

**Comment by Kryptotom** [comment]
I have this problem, too.
@Gre: you said, in the 1.1.1y fix i will see the balance of my with the ETH Ledger Chrome App created Adress. But yet i can‘t add the ETH Account in Ledger Live. It says „Error, the adress shows 0“ and now i could not add it. Do you need another logfile?

**Comment by gre** [comment]
@Kryptotom there were a bug fixed in a second patch, can you try a more recent version? And yes it's still going to miss the contract operations. This is not something we can fix in ledger live side but first need to get fixed by our API team

**Comment by gre** [comment]
ETA 1-2 months
