### ISSUE TITLE
ETH Accounts: Cannot match against 'undefined' or 'null'.

### ISSUE THREAD

**Issue by mdesroubins** [LedgerHQ/ledger-live-desktop#1362]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.1.0
- Platform and version: Mac 10.13.6

#### Expected behavior

When adding an ETH Account, it should find accounts that have only received ETH issued by smart contracts..

#### Actual behavior

Step 3:
- Synchronizing...
- Error: Cannot match against 'undefined' or 'null'.

**Comment by gre** [comment]
Hi, thanks a lot of raising this issue.

could you send your logs to our support team and mention this github issue? 🙏  basically you can press Ctrl+E just after the error occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.netlify.com/logsviewer )

I just tried and I can not reproduce on my end (even tho I have many accounts from various places MEW and LL)

**Comment by mdesroubins** [comment]
Done.
Ticket ID is: #192271
