### ISSUE TITLE
Author email field for Linux packages

### ISSUE THREAD

**Issue by meriadec** [LedgerHQ/ledger-live-desktop#1369]
at least for `.deb` package (and I imagine some other targets requiring a "maintainer" field) we have to specify author `email` field in the `package.json`.

![2018-08-03_1315x171](https://user-images.githubusercontent.com/315259/43632811-83393ec2-9707-11e8-8f3b-1b465d0f3dd9.png)

What should we put here? some catch-all Ledger address?

**Comment by gre** [comment]
@EricLarch do you know about what email we should put as "maintainer" of the LL binaries?

**Comment by EricLarch** [comment]
We should create a role email for that, for instance ll-package-maintainer@ledger.fr which would redirect to a list of engineers emails.

**Comment by meriadec** [comment]
`team-live@ledger` has been created
