### ISSUE TITLE
Bug: ENOENT: no such file or directory, open '.../accounts.json'

### ISSUE THREAD

**Issue by lautarodragan** [LedgerHQ/ledger-live-desktop#1378]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.1.0
- Platform and version: Mac 10.13.6

#### Expected behavior

To function properly.

#### Actual behavior

Displays an error on start up.

#### Steps to reproduce the behavior

Open app a second time. First time worked well. 
Tried restarting and resetting. Neither worked. 

- Closing app, 
- `mv Ledger\ Live/ LedgerLiveBackup`, 
- opening app again 

seems to actually reset the app (unlike the reset button). Went through the initialization process again and now seems to be working.

**Comment by cardeo** [comment]
I'm seeing this too on a MacBook Air 2017, running Sierra 10.12.6

Reset button does nothing

**Comment by dogcowuk** [comment]
Same problem here, using MacBook Pro 2018 running Mac OSX High Sierra 10.13.6.
Initially after update today it was working fine, after I quit the app and restarted it I got this message and unable to login.
"ENOENT: no such file or directory"

**Comment by amsimoes** [comment]
Same here. And also after Resetting, sometimes it displayed no "countervalues.json"

**Comment by meriadec** [comment]
Sry for the inconvenience :/
The bug has been fixed in v1.1.2 (see https://github.com/LedgerHQ/ledger-live-desktop/pull/1375 for more context).
