### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/Users/XXX/Library/Application Support/Ledger Live/accounts.json'

### ISSUE THREAD

**Issue by clin54** [LedgerHQ/ledger-live-desktop#1380]
I keep seeing this error even though I have uninstalled Ledger live thoroughly and reinstalled it several times.

**Comment by meriadec** [comment]
Sry for the inconvenience :/
The bug has been fixed in v1.1.2 (see https://github.com/LedgerHQ/ledger-live-desktop/pull/1375 for more context).
