### ISSUE TITLE
Account sorting and PC synchronization

### ISSUE THREAD

**Issue by ceozero** [LedgerHQ/ledger-live-desktop#1381]
How to customize an account, add too many accounts, and often find no required account.

I want to have several computers use the same accounts, MAC and Windows, but I find that copying past user files is often confusing? Do I just need to copy SQLITE?

**Comment by meriadec** [comment]
Hey, thanks for your feedback. We are aware of similar needs, that have been discussed here https://github.com/LedgerHQ/ledger-live-desktop/issues/986, https://github.com/LedgerHQ/ledger-live-desktop/issues/1154. 

For accounts sorting, there will be a dedicated "manage accounts" page where you will be able to sort/archive/rename them more easily.

To sync accounts across computers, there is no "easy" solution for now (it's a choice to not have data centralization ;) ), but only transferring `app.json` located in user data folder is enough to sync all your accounts/settings.
