### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/Users/josh/Library/Application Support/Ledger Live/accounts.json'

### ISSUE THREAD

**Issue by Risiko111** [LedgerHQ/ledger-live-desktop#1382]
#### Ledger Live Version and Operating System

- tested on Ledger Live v.1.1.1.
- Platform and version: **e.g. Mac 10.13.5 / Windows 10 / ..**
MacOS 10.13.06
#### Expected behavior

I tried to open Ledger Live for the first time, after having set up my Ledger Live account a few days ago.

#### Actual behavior

Ledger Live provides the following screen with the following error:
"Error: ENOENT: no such file or directory, open '/Users/josh/Library/Application Support/Ledger Live/accounts.json'"

Nothing else opens after

**Comment by meriadec** [comment]
Fixed in v1.1.2
https://github.com/LedgerHQ/ledger-live-desktop/releases/tag/v1.1.2
