### ISSUE TITLE
Syncing error management enhancement

### ISSUE THREAD

**Issue by EricLarch** [LedgerHQ/ledger-live-desktop#1383]
When there is a sync issue, the UX is reporting the following:
![image](https://user-images.githubusercontent.com/1017848/43709916-70dd245a-996e-11e8-9f55-6c30abd9666c.png)

This is not useful at all. It should give more context and more information to the user, with a link to status. It should also show which coin doesn't sync (maybe BTC is ok, but ETH is not). If the Live is pooling multiple API, the status should have a better granularity. If the Live is pooling only one central API which is itself pooling more APIs, then the error management of the central API should be revised to give more information and allow some granularity as well.

**Comment by andrehortab2u** [comment]
Same problem here with BTC. What I need to do to fix?

**Comment by gre** [comment]
I consider this fixed in the next release. ETA end of May
