### ISSUE TITLE
User friendly error message for outdated app versions 

### ISSUE THREAD

**Issue by dasilvarosa** [LedgerHQ/ledger-live-desktop#1384]
- [x] I have checked this feature was not yet requested.

Users that try to do an operation that requires the latest version of an app (or it's dependency BTC/ETH), get the error 0x6b00 (checked with @btchip).  

> Something went wrong. Please replug your device.
> Ledger device: Invalid parameter received (0x6b00). 

![screen shot 2018-08-04 at 9 19 28 am](https://user-images.githubusercontent.com/712580/43722745-49ba9baa-9996-11e8-8f87-e2276918b104.png)

This can be made more user friendly by returning a specific error message when the device returns 0x6b00. Something like:

> App updates required. 
> Reinstall the apps on your device and try again.

#### Part of the application

Device operations, error messages.

**Comment by gre** [comment]
I think it can happen before, at time we check the app is opened, we should ask the app version and verify it's not too old.
