### ISSUE TITLE
Ledger device: Internal error, please report (0x6f01)

### ISSUE THREAD

**Issue by dmflahive** [LedgerHQ/ledger-live-desktop#1386]
Ledger device: Internal error, please report (0x6f01)

I get this error every time I try to send currency. On both MacOS and Windows.

**Comment by meriadec** [comment]
Can you specify which app is used?

**Comment by dmflahive** [comment]
Both BTC and LTC give this error. 

How is this invalid? My currency is currently locked in the wallet and I can't get it out.

**Comment by meriadec** [comment]
The error `0x6f01` indicates a technical problem while communicating with the device (see [btchip-doc](https://ledgerhq.github.io/btchip-doc/bitcoin-technical-beta.html#_status_words)). You can start testing with another usb port, another usb cable, another computer and see if it's working.

If still not working, can you try sending your funds with the [legacy Chrome app](https://chrome.google.com/webstore/detail/ledger-wallet-bitcoin/kkdpmhnladdopljabkgpacgpliggeeaf)?

**Comment by dmflahive** [comment]
Thank you for that information. I have already tried a different cable and USB port and it still doesn't work, but I can accept that it may not be the software. I'm using a 2018 MacBook Pro with a usb-c to usb-a adapter I get the feeling there may be something lost in the conversion there. 

I see that the legacy app is working now. When I submitted the ticket the legacy app would force me to download Ledger Live without the option to use the app.

**Comment by dmflahive** [comment]
So the legacy app is working fine, I just sent funds using it. Ledger Live is still giving the following error: Ledger device: Internal error, please report (0x6f01). Seems like it must be a software issue if the legacy app works but Live doesn't using the same wallet, same USB port, etc...

If you are able to reproduce the issue and would like for me to test on my end just let me know.

**Comment by meriadec** [comment]
Thanks for the details. As you said, if legacy app is working but not Live, it's probably a software problem (there is also one other possibility: Chrome app is using U2F for USB connection, while Live is using HID).

I reopen this

**Comment by northbound1** [comment]
Same here sending LTC 
Win 10. 

![ledger live error](https://user-images.githubusercontent.com/15316281/44268641-1cb31c00-a200-11e8-868a-c925b9ff50c9.GIF)

**Comment by meriadec** [comment]
We may want to try to add delay between each APDU call (parametrable with environment variable). Seen with firmware team, it can happen when device is sollicitated too much.

**Comment by samacumen** [comment]
The only workaround (for now) I found for this is to use the standard Chrome App for Bitcoin and open Litecoin on your ledger with it. Use Legacy Litecoin address to send. All should work until LedgerLive is fixed.

**Comment by rocknet** [comment]
What is the difference between 6f00 and 6f01?  This issue is very similar to the one Zen users are experiencing, but the code for us is 6f00: https://github.com/LedgerHQ/ledger-live-desktop/issues/1239

**Comment by cryptofiend** [comment]
I'm having exactly the same issue trying to send LTC from my nano S using Ledger Live.  I'm using a 2018 MacBook Pro with a USB-C to USB-A dongle.  Tried all four USB-C ports, same result.  Was finally able to send LTC using the legacy Chrome app.

**Comment by ncodedbpm** [comment]
Yes I have also have had a ticket into support for a while now on this for LTC. Please do not get rid of the legacy app.

**Comment by federov31** [comment]
Same problem with Ledger Live transfering BTC

**Comment by gre** [comment]
> We may want to try to add delay between each APDU call (parametrable with environment variable). Seen with firmware team, it can happen when device is sollicitated too much.

@meriadec  i forgot to address this in the incoming release, but we'll try to do something in next sprint.
I think it's an interesting idea but i'm not sure it would actually help, we might also review our transport code.
One scenario I know that can create problem for sure is if you open 2 apps that use the ledger at same time, there going to be problems.


Ideally we need to be in the same setup some person have the bug and systematically reproduce it.

**Comment by meriadec** [comment]
Also, interesting hint raised by @amougel is being on the manager page while having add/send/receive modal opened. The background page continuously ping the device (I thought we paused that!) and that sounds bad.

**Comment by gre** [comment]
we should be protected by `withDevice` tho.

The problem you raise is to me a UX problem. should not be able to Send/Receive from manager.

**Comment by gre** [comment]
what about having some "cooldown" between each withDevice so we have some time to let the device catch up if needed?

**Comment by amougel** [comment]
@gre some device calls are blocking, just waiting is not enough if user action is required. I think the manager should be disabled if a modal is present, why would we want to update a screen that is masked by a modal and that you can't interact with.

**Comment by gre** [comment]
I agree with the "manager spinning behind" problem. it's just not easy to implement to change this.
Also, what i'm saying is I think it's a non problem. we have a lock system, called withDevice, that would prevent any concurrent call with the device. if something is blocking on the device, it is still not redeemed from the promise, any other attempt to do something with the device would just wait. the fact concurrent job happen would just slow down the global things. it's like CPU multi-tasking. now if you tell me there is a bug that potentially two concurrent APDU exchanges break the device, we have a wider problem than this manager thing

**Comment by meriadec** [comment]
What can be easily done is to make the Manager a modal (big modal), so one does not simply open two modals at the same time

**Comment by gre** [comment]
what about we disable Send and Receive button if you are on Manager.

**Comment by gre** [comment]
or we force the navigation to go Portfolio if you click it

**Comment by meriadec** [comment]
Yes, even smaller to implement

**Comment by cmbconcretefire** [comment]
Hey guys, I REALLY don't mean to be a ball buster, but I need fast help. I am getting the same exact error trying to send LTC. (Oddly enough, I DID NOT have trouble sending LTC just last week on ledger live??) Anyway.....that is no concern to me. All I care about is ..... I need to get my LTC OUT ....so can someone take me by the hand and step by step show me what I need to install now? (Or Uninstall and then install) and where to get everything I need to do so? (Links please) 

I don't need actual step by step. I understand the process. Just need a link or something to get me fixed up. I'm currently using ledger live. LTC Legacy account. HELP. Thanks.

**Comment by cmbconcretefire** [comment]
update, I figured out how to do via the old chrome app (Ledger Wallet Bitcoin) and the TX sent......HOWEVER......I am now sitting at 22 minutes and only have 4 confirmations.......I understand this is legacy....but that is not acceptable. Meanwhile....price continues to drop. LEDGER LIVE obviously has a problem, it's been known for at least 22 days now.....and no fix......also unacceptable.

**Comment by gre** [comment]
This issue is hard for us to tackle because no one from our internal teams was able to reproduce it. If the issue was easy to fix, it would have been from the start but we are aware there is a bug based on all the feedback we got on this problem.

As it was mentioned here, one potential idea of what the problem can be is too much exchange done with the device, therefore i've sent a PR attempting to fix the bug following this idea.

https://github.com/LedgerHQ/ledger-live-desktop/pull/1549

> As no one from our develop team was able to reproduce the problem, we encourage our community to help us testing this, investigating on the problem and experimenting solutions. 

Thanks!

**Comment by RudyBouwman** [comment]
I am getting this error when  sending DigiBytes.
Have send a ticket to Support and added a log file.

**Comment by sameersbn** [comment]
I faced this issue while sending a transaction in the cashaddr format. I had to convert the address to the legacy format for it to work.

**Comment by alighazi** [comment]
I still have this issue when sending BCH

**Comment by shak3nbak3** [comment]
I got this error on Particl QT when I updated Ledger to 1.6. At first it was the 0x6f01 error, and then progressed to AddStandardInputs failed: [default wallet] PrepareTransaction for device failed: Dongle error: 4af7 Unknown.

After reading the thread it seems like it's a BTC CORE issue
