### ISSUE TITLE
confirm transaction address as an option

### ISSUE THREAD

**Issue by Gahzayah** [LedgerHQ/ledger-live-desktop#1396]
The Step to confirm a sending / receiving transaction address each time to prevents a Man-in-the-middle attack to verify where its sent to.

This should be in the hand of user at own risk to disable this in the settings.

**Comment by meriadec** [comment]
The device confirmation step for "Receive" is already skippable, by clicking on "I don't have my device" CTA:

![2018-08-08_530x96](https://user-images.githubusercontent.com/315259/43825032-e647af04-9af3-11e8-93b5-42d042aa4f70.png)

The confirmation step for "Send" is required by the device to allow it to sign the transaction.
