### ISSUE TITLE
Tezos baking app can't be uninstalled from Ledger NanoS device

### ISSUE THREAD

**Issue by Arnaud97234** [LedgerHQ/ledger-live-desktop#1399]
#### Ledger Live Version and Operating System

- tested on Ledger Live **1.1.4**
- crypto app concerned : **tezos baking**
- Platform and version: **Ubuntu 18.04**

#### Expected behavior
Via Manager : Installing the tezos baking app on the device
Then I try to uninstall the tezos baking app
Success message
App should be uninstalled from device

#### Actual behavior

When trying to uninstall the Tezos baking app via Manager, a success message is displayed _"Tezos Baking has been uninstalled from your device"_

On the NanoS device the app is still present.

#### Steps to reproduce the behavior

Via manager, install tezos baking app then click uninstall button

**Comment by meriadec** [comment]
Does the app can be uninstalled with the Legacy manager?

**Comment by Arnaud97234** [comment]
Yes uninstall from Legagy Manager succeeded

**Comment by meriadec** [comment]
I confirm I reproduced the problem

**Comment by meriadec** [comment]
NB: to see the `Tezos Baking` app, developer mode needs to be activated

**Comment by valpinkman** [comment]
This issue comes from api side. It has been fixed. No further modifications needed here.

Closing this issue now
