### ISSUE TITLE
Ethereum history is broken

### ISSUE THREAD

**Issue by StayCoolDK** [LedgerHQ/ledger-live-desktop#1405]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.1.5
- Platform and version: Mac OS 10.13.6

#### Expected behavior

Show the correct history and value

#### Actual behavior

I just sent ETH to my account, while it's reflecting my balance it's not shown up in my transaction history despite multiple confirmations: 0x75f661909d51de254d9bd4b668578378c4d75f38fcf9118ffb44cb4de3fde8ec.
Meanwhile the history of my transactions has turned buggy. Not sure if this was before or after the transaction, or due to the update.

#### Steps to reproduce the behavior

Send ETH to ledger wallet.

<img width="742" alt="skaermbillede 2018-08-08 kl 21 04 33" src="https://user-images.githubusercontent.com/13338649/43858694-fa014f18-9b4e-11e8-8a11-b74287e0ae2a.png">

**Comment by gre** [comment]
Dup https://github.com/LedgerHQ/ledger-live-desktop/issues/1352
