### ISSUE TITLE
Enforce the checksum on the QR code decoding

### ISSUE THREAD

**Issue by fdv** [LedgerHQ/ledger-live-desktop#1406]
When using the QR code, we should refuse any address not having a checksum instead of just displaying a warning. 

The message should be "This address doesn't have automated checking and therefore can't be used with the QR code scanner" or something like this. Lea + support to display the warning.

**Comment by dasilvarosa** [comment]
"Couldn't scan this QR-code: auto-verification not supported by this address"

**Comment by meriadec** [comment]
What should we do in this scenario:

1. user scan QR code, adress don't have checksum, address is refused (`next` button is disabled, an error message is displayed)
2. the user click on the input, remove 1 character, and add it back

should we re-enable button or should we keep it disabled?
