### ISSUE TITLE
Automatically Move to Verification Step

### ISSUE THREAD

**Issue by pydlv** [LedgerHQ/ledger-live-desktop#1411]
When you are sending crypto, one of the steps is to connect your Ledger and open the appropriate app on the device. This is the "Device" stage. The next step is the "Verification" step, where you confirm the transaction on your Ledger. It would be nice to automatically move to the Verification step once the device has been plugged in and the application is opened (right now you have to click continue). I know this is a pretty insignificant change, but it would save me a couple of seconds every time I send crypto.

**Comment by EricLarch** [comment]
This could be a settings available when in "advanced user mode" (it is important to have these step by step actions for general users, as taking time and checking all steps is a best practice)

**Comment by gre** [comment]
We expect this to be fixed in context of a big rework that just got merged. we'll reopen in this does not fix in the next release #2596
