### ISSUE TITLE
Vertcoin add account bug

### ISSUE THREAD

**Issue by Kartereo** [LedgerHQ/ledger-live-desktop#1413]
#### Ledger Live Version and Operating System

- tested on Ledger Live **1.1.5**
- Platform and version: **Windows 10 Pro**

#### Expected behavior

Add vertcoin account, open wallet on nano s, install

#### Actual behavior

ledger live goes back to needing to connect nano s as soon as you open vertcoin on nano s

#### Steps to reproduce the behavior

Go to add account, vertcoin, click next, open vertcoin wallet on nano s
![ledgervtc1](https://user-images.githubusercontent.com/5624644/44004833-666ef2be-9e37-11e8-9800-9c12a7519667.jpg)
![ledgervtc2](https://user-images.githubusercontent.com/5624644/44004838-689952c8-9e37-11e8-9c86-01210981f2fe.jpg)

**Comment by ScoobyJD** [comment]
How can I get into my vertcoin wallet now that the chrome apps are gone?

**Comment by stevesbrain** [comment]
Normally works (i.e. I use it regularly). Are you running the latest version of vertcoin app?

**Comment by meriadec** [comment]
@ScoobyJD what is your firmware version (should be 1.4.2) + vertcoin app version (should be 1.2.8) ?

**Comment by meriadec** [comment]
nb: chrome apps are not gone yet ;) https://chrome.google.com/webstore/detail/ledger-wallet-bitcoin/kkdpmhnladdopljabkgpacgpliggeeaf

**Comment by dasilvarosa** [comment]
https://support.ledgerwallet.com/hc/en-us/articles/360007534774-Download-Ledger-Chrome-apps

**Comment by ScoobyJD** [comment]
Sorry. I forgot to add Ledger 1.4.2 MCU 1.5. Vertcoin was uninstalled and reinstalled once this bug occurred. Thanks guys, I usually would go to the top of the main site and find a tab there for the apps. Ledger has seemed to removed that from the main site.

**Comment by ScoobyJD** [comment]
Just went back in to check to see if anything had changed. Ledger just pushed an update to Ledger Live. I went to try vertcoin again and this is the only thing it is giving me.
![untitled](https://user-images.githubusercontent.com/5624644/44060302-41416436-9f22-11e8-827c-8c7318374828.jpg)

**Comment by ScoobyJD** [comment]
I just tried again and its been sitting like this for over 30 minutes.
![untitled](https://user-images.githubusercontent.com/5624644/44061671-6c891f94-9f27-11e8-86e6-a45fb862fae0.jpg)

**Comment by stevesbrain** [comment]
Hmm, definitely not experiencing what you're experiencing. Is your network flakey, or are you behind a firewall etc (i.e. at a work place)?

**Comment by ScoobyJD** [comment]
Whatever Windows 10 has setup. This is the only app on ledger live that does this to me. Bitcoin and Ethereum both load in with no issues.

**Comment by ScoobyJD** [comment]
Just went and turned windows firewall off for giggles and nothing has changed. When I use the bitcoin chrome app to view vertcoin everything works fine.

**Comment by stevesbrain** [comment]
Hmm, wonder if it's Windows specific - I'm only using Ledger Live on Linux, and haven't got a Windows machine to test with - sorry. Maybe another Windows user can chime in?

**Comment by ScoobyJD** [comment]
Actually I just came across a reddit about not using vertcoin addresses on ledger for mining. Could ledger have blocked me out somehow?

**Comment by stevesbrain** [comment]
Only other thing I could think would be maybe you have issues connecting to the blockchain explorer. I'm not sure if Ledger Live provides any options to change which explorer you are using, but, do you have a mobile phone with data on a different ISP? Perhaps you could try tethering to that and see if it makes any difference

**Comment by ScoobyJD** [comment]
I tried forcing my router to get a new IP address and I get the same result. I have messaged ledger we will see what they say.

**Comment by Kartereo** [comment]
Just wanted to come back and say that Ledger confirmed that it was too many transactions. They also told me that the Ledger Live app is optimized for larger transactions like the Ledger Bitcoin Chrome App. I retried the Chrome App the other day and it processed all the transaction history perfectly. Nothing to do now but just wait :-(

**Comment by stevesbrain** [comment]
@Kartereo I didn't realise these apps weren't designed for excessive transactions :/ Thanks for following up though. As an interim, you can also use electrum-vtc with the Ledger from memory :)

**Comment by gre** [comment]
Let's unify the issue into https://github.com/LedgerHQ/ledger-live-desktop/issues/1721

**Comment by Kartereo** [comment]
> @Kartereo I didn't realise these apps weren't designed for excessive transactions :/ Thanks for following up though. As an interim, you can also use electrum-vtc with the Ledger from memory :)

I can't seem to find electrum-vtc on here. Could you point us in the right direction for anyone who comes across this issue?

**Comment by Kartereo** [comment]
@stevesbrain I can't seem to find electrum-vtc on here. Could you point us in the right direction for anyone who comes across this issue?

**Comment by Kartereo** [comment]
@stevesbrain never mind, dont mind me; github filters were hiding it from me since it's a fork. ::shakes head::

**Comment by Nicholas109** [comment]
Hm, can't help but thanks for posting. Mind need to update [vertcoin](https://en.bitcoinwiki.org/wiki/Vertcoin) page on BitcoinWiki to inform other users how to cope with such issues when the solution is found.
