### ISSUE TITLE
Synchronization error and When I try to send Bitcoin: "Missin outputs"

### ISSUE THREAD

**Issue by ah2020b** [LedgerHQ/ledger-live-desktop#1421]
#### Ledger Live Version and Operating System

Ledger Live 1.1.6
- tested on Ledger Live **Nano S pepper**
- Platform and version: **Windows 10**

#### Expected behavior

Bitcoin wallet not sync and is impossible to withdrawn Bitcoin
#### Actual behavior
Synchronization error. When I try to send Bitcoin: "Missin outputs"

#### Steps to reproduce the behavior

![image](https://user-images.githubusercontent.com/30999942/44120245-b50155b0-a013-11e8-84f4-a73dbb512e8c.png)
![image](https://user-images.githubusercontent.com/30999942/44120264-bf0cc97c-a013-11e8-9472-9d4fda902482.png)

**Comment by gre** [comment]
We expect this to be fixed in context of a big rework that just got merged. we'll reopen in this does not fix in the next release #2596
