### ISSUE TITLE
Colored Accounts

### ISSUE THREAD

**Issue by KarmaEDV** [LedgerHQ/ledger-live-desktop#1424]
I wish for the possibility of assigning an optional color to an account (kinda like in the chrome apps). It will make the accounts list in the sidebar better and faster to be understood by visual grouping.

### Part of the application
1. Account edit dialog: needs a color picker
2. Account sidebar: shows the color before the currency symbol
3. Portfolio Account list: A) allows for filtering by color or even better B) account list is grouped by color by default

![ledger_live_edit_account_with_colors](https://user-images.githubusercontent.com/15261206/44170223-f8a7eb80-a0d6-11e8-90b4-a85d869dcc8d.jpg)

![ledger_live_sidebar_with_colors](https://user-images.githubusercontent.com/15261206/44170228-fc3b7280-a0d6-11e8-89fd-df4e99241bd7.jpg)

**Comment by juan-cortes** [comment]
Until this is done, which granted looks miles better than what I'm suggested, you can use emojis/unicode in the name of the accounts. Allowing you for a _cheerful_ look that I don't like but might serve your needs in the meantime.

![image](https://user-images.githubusercontent.com/4631227/44195734-40ac2a00-a13a-11e8-99d1-57ed3fa3fad3.png)

🔵🔴⚫⚪⭕

**Comment by gre** [comment]
I'm not sure this will address anytime soon, the decision in Ledger Live is to use each cryptocurrencies colors (e.g. bitcoin is orange, litecoin is grey, ethereum is blue, etc..).

Introducing another "coloring" concept on top of that would be confusing I feel.

As you said, naming your account is currently the supported way to go to differenciate between them.

**Comment by KarmaEDV** [comment]
Thanks @gre . Just two follow-ups:
- Would you be more open to the proposal if I were to say that it could be an optional "advanced-only" feature (maybe to be excplicitly enabled in the settings)? 
- What if I would implement it myself, could I have this marked as a "good-first-issue" and would you be willing to consider a merge request?
