### ISSUE TITLE
Make it more obvious that third party apps need third party clients

### ISSUE THREAD

**Issue by MortalKastor** [LedgerHQ/ledger-live-desktop#1427]
Some users get confused by not being able to create an account for third party apps they just installed from Ledger Live, and open support tickets.

#### Improvement proposal

- Make it more obvious on the app manager and/or on the account creation modal that third party apps need third party clients
- List which apps/currencies are concerned?
- Link to the required client?

#### Part of the application to improve

- Add/import account
- App manager

**Comment by gre** [comment]
#1130

**Comment by KMFDM29** [comment]
ONTOLOGY

**Comment by cthepot-ledger** [comment]
LL-2617/8
