### ISSUE TITLE
Support for showing countervalue in Danish Kroner

### ISSUE THREAD

**Issue by Fogh** [LedgerHQ/ledger-live-desktop#1433]
- [x] I have checked this feature was not yet requested.

#### Part of the application

It would be nice with support for showing the countervalue in Danish Kroner (DKK)

**Comment by gre** [comment]
we had to remove it because there is no BTCDKK pair today: https://github.com/LedgerHQ/ledger-live-desktop/issues/1331#issuecomment-409132496

**Comment by gre** [comment]
this can't be solved until such pair exist OR if we use another technique to calculate countervalues (today's intended approach is to directly use the pairs)
