### ISSUE TITLE
Changing the sorting algo in the manager

### ISSUE THREAD

**Issue by TamtamHero** [LedgerHQ/ledger-live-desktop#1447]
Ledger being coin-agnostic, the Manager should be build assuming that every existing coin will eventually be supported, even the smallest ones (which is thousands of coins).
Currently, the manager exposes apps sorted alphabetically to the user. This can be very confusing for the user, even though there is a search bar. 
Let's take an example: there are dozens of coins containing the name "ether". Even if the user types "ether" in the search bar, he will get all the results, sorted alphabetically. There is a 99% chance that this user wants the Ethereum app, but he will have to make a choice among dozens of copycats.
A simple fix to this problem is to sort coins by market cap, so the more popular coins appear first.

This fix will be crucial very soon, as the counter of small coins is exploding (next batch release is scheduled for the 4th of September, with lots of coins having confusing names).

**Comment by gre** [comment]
fixed in incoming release
