### ISSUE TITLE
isValidTransaction never called on 01-step-amount

### ISSUE THREAD

**Issue by juan-cortes** [LedgerHQ/ledger-live-desktop#1448]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.1.7
- Platform and version: Mac 10.14 Beta (18A365a)

#### Expected behavior

A bridge implementation should be able to define additional validation rules that should prevent the form from being submitted. For example, while implementing the Memo system from Stellar, I need to be able to check those fields too.

#### Actual behavior
`isValidTransaction` is never called so we can get to step 2 with potentially invalid transactions

#### Steps to reproduce the behavior
If needed I'll reproduce this again in the main branch but hopefully the screenshot of the current integration suffices to validate/dismiss this bug report. **I can make a PR to solve this no problem**, it's simply adding the call to `bridge.isValidTransaction` and including it in resolving `canNext`

**Update** Checked out master and tested this on the Ripple bridge, with the same result, a zero amount transaction that would break according to the code, let's you through, I proceed to make the PR

**Update 2** Decided we should drop `isValidTransaction` in favor of `checkCanBeSpent` which will be renamed to `checkValidTransaction` to be a bit more generic. PR updated

**Comment by gre** [comment]
yeah I think this is currently a dead code. 
`checkCanBeSpent` is the actual call being used instead of isValidTransaction that was too limited. we probably should drop isValidTransaction

**Comment by juan-cortes** [comment]
Updated PR @gre
