### ISSUE TITLE
LBRY Credits Support

### ISSUE THREAD

**Issue by kodxana** [LedgerHQ/ledger-live-desktop#1452]
- [ x] I have checked this feature was not yet requested.

Welcome! I'm here to ask about LBRY support in Ledger Wallet.
Project is very good and devs working hard on it, you can check it out on official website.
Thanks to lbry.found program I managed to buy my first Ledger.
But sad news is that Ledger not support LBRY yet (hope it can be fixed soon :) )
So here's my question what we need to do to make LBRY be supported via Ledger?

Regards,
kodxana
Member of LBRY

**Comment by finer9** [comment]
LBRY is one of the most active and transparent projects around.  Please do take a look at https://github.com/lbryio

**Comment by gre** [comment]
Thanks for the issue.
We're unifying integration requests into [#1560](https://github.com/LedgerHQ/ledger-live-desktop/issues/1560).

Please follow [#1560](https://github.com/LedgerHQ/ledger-live-desktop/issues/1560) for updates on what will be the process.
