### ISSUE TITLE
Deleting on unit selector (Ripple/Ethereum/etc) crashes app

### ISSUE THREAD

**Issue by juan-cortes** [LedgerHQ/ledger-live-desktop#1457]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.1.7
- Platform and version: Mac Mojave

#### Expected behavior
It should either ignore the empty or default to drop/xrp

#### Actual behavior
App crashes, it send an empty Unit to `formatCurrencyUnit`  from `@ledgerhq/live-common/lib/helpers/currencies` that throws the error when trying to access `.magnitude` from it. This also triggers an crash on Ethereum when doing the same thing and I assume on any other currency using a unit selector

#### Steps to reproduce the behavior
Launch app, click send on a ripple account, click on the selector for units, press delete.

![crash](https://user-images.githubusercontent.com/4631227/44629554-6f53ad00-a951-11e8-865c-7df17953afd2.gif)

**Comment by meriadec** [comment]
Thanks for reporting @juan-cortes :)
Will be fixed in next release.

**Comment by meriadec** [comment]
Wooops ! Didnt see that you already had pushed a fix, which is the same as me :)
Now it's merged. Thx.
