### ISSUE TITLE
Add more countervalue currencies please!! 

### ISSUE THREAD

**Issue by MrBistro** [LedgerHQ/ledger-live-desktop#1467]
In Settings-->General-->Countervalue. Please add more currencies and do not just have "the big ones". I would like to see the Swedish kroner (SEK) being added. So much easier to see value in your portfolio with your own countries currency.

**Comment by gre** [comment]
we currently stick to fiat currencies that have direct exchanges between this fiat and BTC.

If there is no pair from BTC to your fiat currency, we can't support it for now, this is our current tradeoff in how countervalues are calculated.

for instance, there is no longer any pair BTCSEK, e.g. the only one that appear in tradingview.com is MtGox :( 
<img width="711" alt="capture d ecran 2018-08-28 a 16 00 59" src="https://user-images.githubusercontent.com/211411/44728068-d3a27800-aadb-11e8-950f-abbef5d7aac1.png">


see also https://github.com/LedgerHQ/ledger-live-desktop/issues/1331
