### ISSUE TITLE
Correct mouse pointer everywhere

### ISSUE THREAD

**Issue by meriadec** [LedgerHQ/ledger-live-desktop#1468]
actually the `cursor: text` has "leaked" in place it shouldn't have :D
e.g: on last step receive flow, the "copy address" button has cursor text, or in onboarding, the choices cards have cursor text, etc.

**Comment by juan-cortes** [comment]
Seeing this has been self assigned to @meriadec does it mean it no longer needs someone to do it? Latest version I have still has this issue. I don't mind looking for those rogue cursors throughout the app

**Comment by meriadec** [comment]
Hey Juan, ahah you're right, that's one of the issue being delayed again and again because annoying but not critical :) I've not started on my side so yes it would be super appreciated !

**Comment by meriadec** [comment]
To me the best way to solve is to remove the `cursor text` we have at some top levels, make every cursor inherits from `cursor default`, then enable `cursor text` only on useful parts (when selecting text makes sense)

**Comment by juan-cortes** [comment]
Sounds like a plan! I'll look into it

**Comment by juan-cortes** [comment]
Anything else needed here since it's merged?

**Comment by meriadec** [comment]
Nope I think it's good for now! Thanks :rocket:
