### ISSUE TITLE
Support for Ethersocial (ESN)

### ISSUE THREAD

**Issue by hackmod** [LedgerHQ/ledger-live-desktop#1485]
- [x] I have checked this feature was not yet requested.

Please add Ethersocial Network(ESN), an ethereum clone chain like as Pirl / Akroma.

- ***merged*** https://github.com/LedgerHQ/ledger-app-eth/pull/21
- ***HOLD*** https://github.com/LedgerHQ/ledger-live-common/pull/74

cc: @magnalucus, @kimmyeonghun

**Comment by hackmod** [comment]
@gre Is there any additional information needed to be listed in the ledger live manager?

**Comment by hackmod** [comment]
@meriadec // thank you in advance 😃

**Comment by gre** [comment]
Thanks for the issue.
We're unifying integration requests into [#1560](https://github.com/LedgerHQ/ledger-live-desktop/issues/1560).

Please follow [#1560](https://github.com/LedgerHQ/ledger-live-desktop/issues/1560) for updates on what will be the process.
