### ISSUE TITLE
Crypto currency is converted at an overvalued rate for the last day

### ISSUE THREAD

**Issue by AlexKirsanoff** [LedgerHQ/ledger-live-desktop#1490]
Ledger Live 1.1.6-1.1.9
![2018-09-06_07-48-56](https://user-images.githubusercontent.com/31972512/45135759-c5beb800-b1a9-11e8-9153-266cd68d192d.png)
![2018-09-06_07-51-18](https://user-images.githubusercontent.com/31972512/45135760-c6574e80-b1a9-11e8-8cf0-f7dd16ca64b9.png)

Mac 10.11.6

Crypto currency is converted at an overvalued rate for the last day

I tried to clear the cache, change all Rate provider, Erase all Ledger Live data, reinstall ledger live app, roll back to old versions, but the balance remains overstated

**Comment by gre** [comment]
yes you are right, it seems the countervalues are not getting refreshed live and take the rate of the beginning of the (UTC) day.
looking into it.

**Comment by gre** [comment]
fixed
