### ISSUE TITLE
Corrupt UI elements in the "accounts" page

### ISSUE THREAD

**Issue by RyuzakiKK** [LedgerHQ/ledger-live-desktop#1494]
#### Ledger Live Version and Operating System

- tested on Ledger Live **1.1.9**
- Platform and version: **Arch Linux**

#### Expected behavior

UI elements to remain visible even after hovering the mouse over them

#### Actual behavior
![screenshot from 2018-09-07 12-11-47](https://user-images.githubusercontent.com/3227973/45213480-ec5b1c80-b297-11e8-9fdf-6998869a66f5.png)

The UI elements disappears if I move the mouse over them. This only happens if I'm in the "accounts" page. In all the other pages like "portfolio", "send" ecc.. this bug doesn't shows.

#### Steps to reproduce the behavior

- Add an account to ledger live
- Select the created account
- Move the mouse over the UI elements, like buttons and graph
- See them disappearing

**Comment by meriadec** [comment]
Seems like a video driver problem. Did you just updgraded your system? I already had similar problem after video driver update, which resolved after a reboot. If not.. there is not much we can do on our side: rendering is done by electron (baked by chromium).

**Comment by RyuzakiKK** [comment]
I tried a reboot just to be sure but the problem persists. I'll try to see if there is a similar bug already filed against electron.

**Comment by RyuzakiKK** [comment]
FTR: I tried again the old working 1.1.6 version and now it shows the same kind of problem. So apparently it's a regression with the mesa driver, not a ledger-live issue.

**Comment by gspe** [comment]
I have the same problem.
I've downloaded and tried other electron apps and I can see this kind of problems only with Ledger Live
