### ISSUE TITLE
Accounts with ~50+ transactions not able to sync.

### ISSUE THREAD

**Issue by titusz** [LedgerHQ/ledger-live-desktop#1495]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.1.10
- Platform and version: Windows 10

#### Expected behavior

Keep Account balances in sync

#### Actual behavior

Sync Timeout 

#### Steps to reproduce the behavior

Any UTXO/BTC based account with more than a hand full of transaction is not capable of synching. While the initial sync when adding an account with a history of transactions (50+) works (still takes ages) it is thereafter not able to sync because of timeouts.

![image](https://user-images.githubusercontent.com/278556/45216778-fe41bd00-b2a1-11e8-9832-3a8afdb9d5e5.png)

**Comment by jwbats** [comment]
I have [almost the same problem](https://github.com/LedgerHQ/ledger-live-desktop/issues/1506). Initial sync goes fine. It even picked up on a new incoming transaction. But after that: no more syncs for you, buddy!

**Comment by meriadec** [comment]
Tweaking the `SYNC_TIMEOUT` environment variable could be a quick workaround, waiting for a more global fix (default is `300000ms`, so 5 minutes):

```
export SYNC_TIMEOUT=600000
./ledger-live-desktop
```

**Comment by gre** [comment]
@titusz @jwbats could you check if the 1.1.11 have helped on this problem? thanks

**Comment by titusz** [comment]
No, unfortunately it did not help. Even with higher timeout sync does not finish and aborts with "Synchronization error".

**Comment by titusz** [comment]
Reinitializing did not solve the issue here. 
![image](https://user-images.githubusercontent.com/278556/46942395-89fef400-d06d-11e8-95f9-86939fb9711f.png)

**Comment by gre** [comment]
@titusz could you try again in 1.8.0? Thanks

**Comment by titusz** [comment]
With version 1.8.1 I do not get "Synchronization errors" but Synchronization still does not finish. Last time I tried it was synchronizing for 36 Minutes and than the application window froze.

**Comment by gre** [comment]
We expect this to be fixed in context of a big rework that just got merged. we'll reopen in this does not fix in the next release #2596
