### ISSUE TITLE
Support for graft (GRFT)

### ISSUE THREAD

**Issue by krosand** [LedgerHQ/ledger-live-desktop#1499]
- [x] I have checked this feature was not yet requested.

GRAFT is a retail-oriented payment blockchain and a decentralized alternative payment processing network that brings cryptocurrency to the point of sale and beyond.

Please add graft network, the project is very good and the developers are working hard, you can check the official website.
https://www.graft.network/

Regards,
Krosand,

**Comment by gre** [comment]
Thanks for the issue.
We're unifying integration requests into [#1560](https://github.com/LedgerHQ/ledger-live-desktop/issues/1560).

Please follow [#1560](https://github.com/LedgerHQ/ledger-live-desktop/issues/1560) for updates on what will be the process.
