### ISSUE TITLE
Sync Error: Internal Process Error 3221226505

### ISSUE THREAD

**Issue by jwbats** [LedgerHQ/ledger-live-desktop#1506]
#### Ledger Live Version and Operating System

- Tested on Ledger Live 1.1.10
- Platform and version: Windows 10

#### Expected behavior

Portfolio syncs successfully.

#### Actual behavior

Synchronization error. Internal process error 3221226505.

#### Steps to reproduce the behavior

1. Be me.
2. Use Ledger Live to view bitcoin.
3. https://snag.gy/VXC19R.jpg

The screenshot shows the sync error. It also shows 0 confirmations on a tx from hours ago, which has already received many confirmations.

Ledger Live picked up on the tx as soon as it was sent out to me. The tx has since then been replace-by-fee'd. The tx ledger refers to now no longer exists, since the rbf created a new tx. I was hoping a successful sync would solve this, but I can't sync anymore for some reason.

I see it updating Bitcoin’s USD price in real time. So why can’t it sync my transactions?

Earlier I was using a cable that turned out to be broken. It turned on my Nano S (so it seemed ok at first glance) but Ledger Live could not confirm that the Nano S was genuine. Then I used a brand new cable, which lets Ledger Live successfully confirm that the Nano S was genuine. So it's a small chance that it's somehow related to the cable.

Running as administrator did not help.

Adding Ledger Live to my BitDefender's "allowed applications", which is a list of application allowed to make changes to a list of protected directories, also did not help.

**Comment by meriadec** [comment]
Countervalues sync is separated from blockchain sync, so you still see your balance updating but not your txs. Those type of exit code make it possibly Windows specific (see https://github.com/LedgerHQ/ledger-live-desktop/issues/933, https://github.com/LedgerHQ/ledger-live-desktop/issues/1351), does it do the same on Linux/macOS? If yes, you may contact Ledger support, providing your xpub.

**Comment by TradeForProfit** [comment]
After reinstalling Ledger Liver (by advice of the Ledger Support team) towards version 1.1.7 DGB wallet wasn't working but synchronising worked fine.

With the new release of version 1.1.10 (windows 10 Ledger Liver desktop) the synchronisation problems fot DGB should be fixed when DGB app is unistalled and reinstalled and after clearing the cache. Unfortunately the issue becomes bigger after the update because suddenly Synchronization error. Internal process error 3221226505 is showing up.

Since the time I purchased the Ledger Nano S, the Ledger Live software has many issues that hasn't been fixed yet resulting in not be able to use the funds that have been sent towards the Ledger Live wallets.....

**Comment by meriadec** [comment]
@TradeForProfit and we're sorry for that, believe us! The `Internal process error 3221226505` is Windows specific, occuring on a little amount of users, and pretty hard to investigate in a short period of time (with team currently busy on mobile app). Also, as it involves our C++ libcore library, the debugging time is multiplied.

Here are the workarounds that you can use for now:
- use macOS or Linux (e.g Ubuntu 18.04 works well with Live)
- use the legacy Bitcoin chrome app to access your funds https://support.ledgerwallet.com/hc/en-us/articles/360007534774-Download-Ledger-Chrome-apps

Thanks for your patience

**Comment by TradeForProfit** [comment]
Hello Meriadec,

 

I tried to reset Ledger Live and was succesfull in synchronising many coins only DGB

isstill not synchronising unfortunately with followingprocessing error as shown below

 



 

Van: Meriadec Pillet [mailto:notifications@github.com] 
Verzonden: vrijdag 21 september 2018 10:25
Aan: LedgerHQ/ledger-live-desktop
CC: TradeForProfit; Mention
Onderwerp: Re: [LedgerHQ/ledger-live-desktop] Sync Error: Internal Process Error 3221226505 (#1506)

 

@TradeForProfit <https://github.com/TradeForProfit>  before that, can you try to reset Ledger Live ? (Settings > Help > Reset Ledger Live). Some users has reported to our support team this fixed the case.

**Comment by jemmy224** [comment]
I had the exact same error and was able to solve it clearing the cache folder (sqlite).

**Comment by rhoff1990** [comment]
@jemmy224 what did you do? just clearing the cache folder? 
Any other things i have to know? I already deleted ledger live and installed it again but that did not work,

**Comment by zdzieblowski** [comment]
Settings > Help > Clear Cache worked for me

**Comment by randnix** [comment]
I have this exact same problem -- exact same setup -- Windows 10, Ledger Nano S.   Settings > Help > Clear Cache do not work for me.

**Comment by gre** [comment]
Please try to remove the `sqlite` folder in user data folder (that can be opened from Settings>Help), we have recently identified a problem and implemented an "auto fix" logic that should improve this situation in the future (will be in a 1.20.0).

**Comment by randnix** [comment]
Thank you -- that worked


Rand Nix
IT Director

Wakefield Inspection Services, Inc.
1517 G Ave
Plano, TX 75074

t: +1 972-690-9015
m: +1 972-832-5593
e: rand@wiscontrol.com

skype: therandnix

www.wiscontrol.com<http://www.wiscontrol.com/>
________________________________

**Comment by gre** [comment]
We expect this to be fixed in context of a big rework that just got merged. we'll reopen in this does not fix in the next release #2596

**Comment by er-eis** [comment]
Getting this issue. Tried different USB cables, reinstalling Ledger Live, clearing cache through the GUI, manually deleting the cache files, restarting, checking for Windows and Ledger Live updates. Nothing's working. Windows desktop version 2.32.2

**Comment by DennisDyallo** [comment]
I still have this in 2.33.1

**Comment by ZBSCOIN** [comment]
Hello i have this 2.39.2 wallet Algo NanoX firmware 2.02 2.30 1.16 on Win10. Please help me bro
