### ISSUE TITLE
Display The BTC Sum Of Multiple Accounts

### ISSUE THREAD

**Issue by jwbats** [LedgerHQ/ledger-live-desktop#1507]
- [x] I have checked this feature was not yet requested.

The Chrome Ledger app displayed the sum of multiple BTC accounts just fine. Ledger Live doesn't seem to support this, so this is feature-regression.

#### Part of the application

Bitcoin wallet.

**Comment by meriadec** [comment]
Yep, totally legitimate request (relatable: https://github.com/LedgerHQ/ledger-live-desktop/issues/984, https://github.com/LedgerHQ/ledger-live-desktop/issues/985). There is no real difficulty to implement but subject is blocking on UX/UI side. The project currently focus on bugfixes, but features are coming :)

closing - discussion on #984
