### ISSUE TITLE
EOS Support for Ledger Live

### ISSUE THREAD

**Issue by wichtigwicht** [LedgerHQ/ledger-live-desktop#1513]
Haven't seen this on here.

Would love to have EOS on Ledger Live.

Thanks for the unbelievably great work so far.

**Comment by gre** [comment]
Thanks for the issue.
We're unifying integration requests into [#1560](https://github.com/LedgerHQ/ledger-live-desktop/issues/1560).

Please follow [#1560](https://github.com/LedgerHQ/ledger-live-desktop/issues/1560) for updates on what will be the process.
