### ISSUE TITLE
How do I send a transaction with zero ether?

### ISSUE THREAD

**Issue by AlexKirsanoff** [LedgerHQ/ledger-live-desktop#1514]
I urgently need to send transactions to a smart contract with zero amount from my ledger wallet. How can i do this?

**Comment by gre** [comment]
if it's urgent, you can use MyCrypto / MEW to do this, this is something the Ledger Live currently prevent to do (ZERO amount)

**Comment by AlexKirsanoff** [comment]
@gre I do not want to export my secret phrases anywhere. Are there any other ways?

**Comment by gre** [comment]
you are right and you should never ever use your seed on any software. MyCrypto/MEW don't require you to use it actually. It supports the Ledger device. see 

https://support.ledgerwallet.com/hc/en-us/articles/115005200009
or
https://support.ledgerwallet.com/hc/en-us/articles/360008268594

**Comment by AlexKirsanoff** [comment]
@gre Wow, thanks!
