### ISSUE TITLE
IOTA Support for Ledger Live Desktop

### ISSUE THREAD

**Issue by wichtigwicht** [LedgerHQ/ledger-live-desktop#1517]
I found neither an open nor a closed issue for the support of IOTA. If this request is already done, sorry.
So:

Please continue to be diligent and enable the support of IOTA on your excellent platform. :)

**Comment by gre** [comment]
Thanks for the issue.
We're unifying integration requests into [#1560](https://github.com/LedgerHQ/ledger-live-desktop/issues/1560).

Please follow [#1560](https://github.com/LedgerHQ/ledger-live-desktop/issues/1560) for updates on what will be the process.
