### ISSUE TITLE
Error 0x6f01

### ISSUE THREAD

**Issue by CE3506** [LedgerHQ/ledger-live-desktop#1519]
- Ledger Nano S 1.4.2, Bitcoin app Version 1.2.5
- Tested on Ledger Live 1.1.11
- Platform and version: Windows 10

I attempted to send bitcoin from a legacy bitcoin address to a segwit address. The ledger live program failed to allow me to verify the transaction details. Provided Error with 0x6f01. 

I have tried multiple USB ports, and restarted the program, computer, and Ledger Nano S. I am able to receive bitcoin without a problem. I was able to send bitcoin on Aug 25th, before the latest ledger live update.

**Comment by CE3506** [comment]
I performed the same steps today, and I was able to verify my transaction. I do not know what was different this time.

**Comment by gre** [comment]
ok thanks
 we're aware of this issue but not what creates it (hard to reproduce). closing in favor of #1386
