### ISSUE TITLE
Ledger Live - Allow Ledger Manager on your device prompt never shows up (API HTTP 522)

### ISSUE THREAD

**Issue by moodysalem** [LedgerHQ/ledger-live-desktop#1523]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.1.11
- Platform and version: Windows 10

#### Expected behavior
Ledger manager prompt should show up (I tried disconnecting and reconnecting to many different ports and even updating my USB driver)

#### Actual behavior
No prompt

#### Steps to reproduce the behavior

Reset ledger live settings
Connect ledger nano
check for genuine
prompt never shows
Skip step

Try manager tab
Prompt never shows
(Navigate to dashboard step succeeds, it gets stuck on waiting for me to accept prompt)

I can use the ledger nano on mycrypto.com so not sure what the heck is going on. 

Firmware: 
Security element 1.4.2
MCU 1.5

Pretty brutal experience maintaining this thing

**Comment by gre** [comment]
This is related to a server side incident that started this night. Service disruption on the manager api and countervalues api http://status.ledger.fr/

**Comment by moodysalem** [comment]
Maybe the resolution to the issue would be to remove the dependency on the manager API/countervalues API on connecting to the nano?  I did notice the counter values were not loading in the settings menu. Not sure why it needs internet connection to communicate with the nano. Anyway, it works now.

**Comment by gre** [comment]
I'm not sure to follow. only the access to Manager will need internet because it's opening a secure channel in order to install apps.
The countervalues api on the other hand, doesn't block the app to work (you can still import accounts, send and receive)

Thanks

**Comment by moodysalem** [comment]
I think there’s an issue here in that there’s no feedback given to the user that the connection issue is a result of a service disruption

I would also settle for a banner to indicate that there is a service disruption that might affect nano connectivity in the ledger live app.

FWIW I wasted close to an hour restarting and updating drivers and reconnecting before I filed this issue and I imagine it could easily affect other customers since there’s no UI feedback

**Comment by gre** [comment]
agreed we need more precision on what the error is and what impact it have on the app
