### ISSUE TITLE
Sorry, try again (API HTTP 522) Retry

### ISSUE THREAD

**Issue by CryptoSifu** [LedgerHQ/ledger-live-desktop#1524]
#### Ledger Live Version(latest update. can't get past setup and doesn't give version number on load screen) and Operating System (widows 10 home build 1803)

(Your app doesn't show version number when loading or during setup)

- tested on Ledger Live **version_here** (no version shown)
- Platform and version: **e.g. Mac 10.13.5 / Windows 10 / ..** (windows 10 home build 1803)

#### Expected behavior

(I should be able to check ledger manager on the device. never connects)

#### Actual behavior

(Error in subject line when trying to add device)

#### Steps to reproduce the behavior

(start app from fresh install and add new ledger nanos. won't connect app manager)

**Comment by gre** [comment]
should be fixed by now.
