### ISSUE TITLE
XLM

### ISSUE THREAD

**Issue by KMFDM29** [LedgerHQ/ledger-live-desktop#1532]
Please tell me what application to use for  XLM ?  Basic already installed.
![23-09-2018 174855](https://user-images.githubusercontent.com/41021204/45925472-3fe88e00-bf59-11e8-9c71-df03d42e4d17.jpg)

**Comment by gre** [comment]
I'm not sure to follow, the answer is in the screenshot?

**Comment by KMFDM29** [comment]
The app depicted in the screenshot is ALREADY INSTALLED.Where to get the wallet app?

**Comment by gre** [comment]
OH I get it now.
so for Stellar, it's a third party app and not yet integrated in Ledger Live, but you can use for instance https://stellarport.io/

**Comment by gre** [comment]
https://support.ledgerwallet.com/hc/en-us/articles/115003797194-Stellar-XLM-
