### ISSUE TITLE
PIRL Support

### ISSUE THREAD

**Issue by mkrufky** [LedgerHQ/ledger-live-desktop#1550]
- [X] I have checked this feature was not yet requested.

Please add support to Ledger Live for Pirl.  The Pirl Ledger app is already out in production.

I am willing to assist with infrastructure or in any other way.  Please contact me if there are questions.

Pirl has been supported in LedgerHQ/ledger-live-common since version v3.4.0

**Comment by gre** [comment]
Thanks for the issue.
We're unifying integration requests into [#1560](https://github.com/LedgerHQ/ledger-live-desktop/issues/1560).

Please follow [#1560](https://github.com/LedgerHQ/ledger-live-desktop/issues/1560) for updates on what will be the process.
