### ISSUE TITLE
Garlicoin Support

### ISSUE THREAD

**Issue by OddSoup** [LedgerHQ/ledger-live-desktop#1558]
Request to add support for Garlicoin within Ledger Live.

Website: https://www.garlicoin.io
Github: https://github.com/GarlicoinOrg/Garlicoin
CMC: https://coinmarketcap.com/currencies/garlicoin/
Reddit: https://www.reddit.com/r/garlicoin/

I have checked this feature was not yet requested.

**Comment by gre** [comment]
Thanks for the issue.
We're unifying integration requests into [#1560](https://github.com/LedgerHQ/ledger-live-desktop/issues/1560).

Please follow [#1560](https://github.com/LedgerHQ/ledger-live-desktop/issues/1560) for updates on what will be the process.
