### ISSUE TITLE
hash

### ISSUE THREAD

**Issue by yagitu** [LedgerHQ/ledger-live-desktop#1561]
please convert all base64 hashes in latest-xxx.yml files from base64 to hexadezimal, there is a mix of formats, its confusing

**Comment by meriadec** [comment]
Thoses hashes are generated by electron-builder at build time, encoding them `base64` (using [hashFile](https://github.com/electron-userland/electron-builder/blob/v20.14.7/packages/electron-builder-lib/src/publish/updateInfoBuilder.ts#L158) defaulting [to base64](https://github.com/electron-userland/electron-builder/blob/v20.14.7/packages/builder-util/src/hash.ts#L4)), and we have no control on that unfortunately. You can use this command to check the hash:

```
sha512sum <file> | cut -f1 -d\ | xxd -r -p | base64
```

Let's close this issue in favor of https://github.com/LedgerHQ/ledger-live-desktop/issues/942 which bring more general discussion around hashes & signatures.
