### ISSUE TITLE
Freeze and read from disk for 1-2min at max speed.

### ISSUE THREAD

**Issue by Transisto** [LedgerHQ/ledger-live-desktop#1564]
![image](https://user-images.githubusercontent.com/388716/46569595-7c3ac780-c925-11e8-914c-c50e81fe0265.png)

Screenshot show 1300MB/s
Anything I'm doing I have to wait for that read from disk to finish.

**Comment by gre** [comment]
thanks for the issue, that's valuable information and we'll need to look what is our bottleneck.

Does this happen during "Synchronizing..." ?

 I wonder if it's due to saving our app state (code around https://github.com/LedgerHQ/ledger-live-desktop/blob/develop/src/helpers/db/index.js ) or if it's deeper that than like maybe the sqlite database that is run by our internal C++ "lib-core".

**Comment by Transisto** [comment]
I don't understand what I'm posting but maybe that can help.


Frame | Module | Location | Address | Path
-- | -- | -- | -- | --
0 | FLTMGR.SYS | FltDecodeParameters + 0x193c | 0xfffff809086d66fc | C:\WINDOWS\System32\drivers\FLTMGR.SYS
1 | FLTMGR.SYS | FltDecodeParameters + 0x20d | 0xfffff809086d4fcd | C:\WINDOWS\System32\drivers\FLTMGR.SYS
2 | FLTMGR.SYS | FltRemoveOpenReparseEntry + 0x1019 | 0xfffff8090870b7c9 | C:\WINDOWS\System32\drivers\FLTMGR.SYS
3 | ntoskrnl.exe | NtReadFile + 0x44b | 0xfffff800030a50db | C:\WINDOWS\system32\ntoskrnl.exe
4 | ntoskrnl.exe | setjmpex + 0x6f83 | 0xfffff80002dcaa43 | C:\WINDOWS\system32\ntoskrnl.exe
5 | ntdll.dll | ZwReadFile + 0x14 | 0x7ffd1e3b9fb4 | C:\WINDOWS\SYSTEM32\ntdll.dll
6 | KERNELBASE.dll | ReadFile + 0xfa | 0x7ffd1a832bba | C:\WINDOWS\System32\KERNELBASE.dll
7 | ledger-core.dll | std::_Tree<std::_Tset_traits<unsigned int,std::less<unsigned   int>,std::allocator<unsigned int>,0> >::_Erase + 0x17192 | 0x7ffcb639b102 | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
8 | ledger-core.dll | std::codecvt_utf8<wchar_t,1114111,0>::do_encoding + 0x2d71e | 0x7ffcb63cc49e | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
9 | ledger-core.dll | std::codecvt_utf8<wchar_t,1114111,0>::do_encoding + 0x21f10 | 0x7ffcb63c0c90 | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
10 | ledger-core.dll | std::codecvt_utf8<wchar_t,1114111,0>::do_encoding + 0x21651 | 0x7ffcb63c03d1 | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
11 | ledger-core.dll | std::codecvt_utf8<wchar_t,1114111,0>::do_encoding + 0x393d1 | 0x7ffcb63d8151 | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
12 | ledger-core.dll | std::codecvt_utf8<wchar_t,1114111,0>::do_encoding + 0x224f5 | 0x7ffcb63c1275 | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
13 | ledger-core.dll | std::codecvt_utf8<wchar_t,1114111,0>::do_encoding + 0x67b32 | 0x7ffcb64068b2 | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
14 | ledger-core.dll | std::codecvt_utf8<wchar_t,1114111,0>::do_encoding + 0x6004d | 0x7ffcb63fedcd | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
15 | ledger-core.dll | std::_Tree<std::_Tset_traits<unsigned int,std::less<unsigned   int>,std::allocator<unsigned int>,0> >::_Erase + 0x13a9d | 0x7ffcb6397a0d | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
16 | ledger-core.dll | std::allocator<ledger::core::PreferencesChange>::allocate + 0x9a8 | 0x7ffcb635b0b8 | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
17 | ledger-core.dll | std::_Tree<std::_Tset_traits<std::basic_string<char,std::char_traits<char>,std::allocator<char>   >,std::less<std::basic_string<char,std::char_traits<char>,std::allocator<char>   > >,std::allocator<std::basic_string<char,std::char_traits<char>,std::allocator<char>   > >,0> >::erase + 0x759 | 0x7ffcb6361c79 | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
18 | ledger-core.dll | ledger::core::BitcoinLikeTransactionDatabaseHelper::inflateTransaction +   0x739 | 0x7ffcb62995f9 | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
19 | ledger-core.dll | ledger::core::BitcoinLikeTransactionDatabaseHelper::getTransactionByHash   + 0x149 | 0x7ffcb6298e19 | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
20 | ledger-core.dll | ledger::core::OperationQuery::inflateBitcoinLikeTransaction + 0x1f7 | 0x7ffcb6327287 | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
21 | ledger-core.dll | ledger::core::OperationQuery::inflateCompleteTransaction + 0x4c | 0x7ffcb632737c | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
22 | ledger-core.dll | ledger::core::OperationQuery::performExecute + 0x91c | 0x7ffcb632815c | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
23 | ledger-core.dll | std::vector<std::shared_ptr<ledger::core::api::Operation>,std::allocator<std::shared_ptr<ledger::core::api::Operation>   > >::operator= + 0x407 | 0x7ffcb6325127 | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
24 | ledger-core.dll | ??$_Call@AEAV<lambda_364bef3b283265410fe8a7b3c5265b02>@@$$V@_Invoker_functor@std@@SA?AV?$vector@V?$shared_ptr@VOperation@api@core@ledger@@@std@@V?$allocator@V?$shared_ptr@VOperation@api@core@ledger@@@std@@@2@@1@AEAV<lambda_364bef3b283265410fe8a7b3c5265b02>@@@Z   + 0x1f | 0x7ffcb632350f | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
25 | ledger-core.dll | ??$invoke@AEAV<lambda_364bef3b283265410fe8a7b3c5265b02>@@$$V@std@@YA?AV?$vector@V?$shared_ptr@VOperation@api@core@ledger@@@std@@V?$allocator@V?$shared_ptr@VOperation@api@core@ledger@@@std@@@2@@0@AEAV<lambda_364bef3b283265410fe8a7b3c5265b02>@@@Z   + 0x16 | 0x7ffcb6324026 | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
26 | ledger-core.dll | std::_Invoke_ret<std::vector<std::shared_ptr<ledger::core::api::Operation>,std::allocator<std::shared_ptr<ledger::core::api::Operation>   > >,<lambda_364bef3b283265410fe8a7b3c5265b02> & __ptr64> +   0x19 | 0x7ffcb6323879 | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
27 | ledger-core.dll | ?_Do_call@?$_Func_impl@V<lambda_364bef3b283265410fe8a7b3c5265b02>@@V?$allocator@H@std@@V?$vector@V?$shared_ptr@VOperation@api@core@ledger@@@std@@V?$allocator@V?$shared_ptr@VOperation@api@core@ledger@@@std@@@2@@3@$$V@std@@EEAA?AV?$vector@V?$shared_ptr@VOperation@api@core@ledger@@@std@@V?$allocator@V?$shared_ptr@VOperation@api@core@ledger@@@std@@@2@@2@XZ   + 0x26 | 0x7ffcb6325736 | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
28 | ledger-core.dll | std::_Func_class<ledger::core::Future<std::vector<std::shared_ptr<ledger::core::api::Account>,std::allocator<std::shared_ptr<ledger::core::api::Account>   > > >,ledger::core::Unit const & __ptr64>::operator() + 0x27 | 0x7ffcb6319de7 | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
29 | ledger-core.dll | std::vector<std::shared_ptr<ledger::core::AbstractWallet>,std::allocator<std::shared_ptr<ledger::core::AbstractWallet>   > >::operator= + 0x11b9 | 0x7ffcb6338aa9 | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
30 | ledger-core.dll | ??$_Call@AEAV<lambda_3a8917d6b2378ac47f9ae3862482f7d6>@@$$V@_Invoker_functor@std@@SA?AV?$vector@V?$shared_ptr@VBitcoinLikeOutput@api@core@ledger@@@std@@V?$allocator@V?$shared_ptr@VBitcoinLikeOutput@api@core@ledger@@@std@@@2@@1@AEAV<lambda_3a8917d6b2378ac47f9ae3862482f7d6>@@@Z   + 0x1f | 0x7ffcb633066f | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
31 | ledger-core.dll | ??$invoke@AEAV<lambda_769e0b3cdf0a7ab330fb007d6faba6b8>@@$$V@std@@YA?AV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@0@AEAV<lambda_769e0b3cdf0a7ab330fb007d6faba6b8>@@@Z   + 0x16 | 0x7ffcb6333c26 | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
32 | ledger-core.dll | std::_Invoke_ret<std::shared_ptr<ledger::core::BitcoinLikeBlockchainExplorer::Transaction>,<lambda_e149cbe4b93da0b823f1430f305fc4f0>   & __ptr64> + 0x19 | 0x7ffcb62610b9 | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
33 | ledger-core.dll | ?_Do_call@?$_Func_impl@V<lambda_5556333b6ad3bca08553c857ec79377b>@@V?$allocator@H@std@@V?$vector@V?$shared_ptr@VAmount@api@core@ledger@@@std@@V?$allocator@V?$shared_ptr@VAmount@api@core@ledger@@@std@@@2@@3@$$V@std@@EEAA?AV?$vector@V?$shared_ptr@VAmount@api@core@ledger@@@std@@V?$allocator@V?$shared_ptr@VAmount@api@core@ledger@@@std@@@2@@2@XZ   + 0x26 | 0x7ffcb6287326 | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
34 | ledger-core.dll | std::_Func_class<ledger::core::Future<std::vector<std::shared_ptr<ledger::core::api::Account>,std::allocator<std::shared_ptr<ledger::core::api::Account>   > > >,ledger::core::Unit const & __ptr64>::operator() + 0x27 | 0x7ffcb6319de7 | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
35 | ledger-core.dll | ledger::core::Try<std::vector<std::shared_ptr<ledger::core::api::Operation>,std::allocator<std::shared_ptr<ledger::core::api::Operation>   > > >::from + 0x5f | 0x7ffcb6326eef | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
36 | ledger-core.dll | std::vector<std::shared_ptr<ledger::core::api::Operation>,std::allocator<std::shared_ptr<ledger::core::api::Operation>   > >::operator= + 0x484 | 0x7ffcb63251a4 | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core.dll
37 | ledger-core-node.node | ledger-core-node.node + 0x6dd4e | 0x7ffcf24edd4e | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core-node.node
38 | ledger-core-node.node | ledger-core-node.node + 0x1af6 | 0x7ffcf2481af6 | C:\Program Files\Ledger   Live\resources\app.asar.unpacked\node_modules\@ledgerhq\ledger-core\build\Release\ledger-core-node.node
39 | node.dll | v8::internal::compiler::CommonOperatorBuilder::CreateFrameStateFunctionInfo   + 0x3480 | 0x7ffca2159f20 | C:\Program Files\Ledger Live\node.dll
40 | node.dll | icu_58::Collator::safeClone + 0x1643 | 0x7ffca2092623 | C:\Program Files\Ledger Live\node.dll
41 | node.dll | icu_58::Collator::safeClone + 0x541 | 0x7ffca2091521 | C:\Program Files\Ledger Live\node.dll
42 | node.dll | icu_58::Collator::safeClone + 0x42b | 0x7ffca209140b | C:\Program Files\Ledger Live\node.dll
43 | <unknown> | 0x1adae704421 | 0x1adae704421 |

**Comment by gre** [comment]
cc @KhalilBellakrid @pollastri-pierre

**Comment by KhalilBellakrid** [comment]
Thank you @Transisto for your analysis, we fixed the issue on `v1.2.5` of Ledger Live, if you ever have the chance to test again that would be awesome (so we can close the issue) ! 
Thank you in advance for your help !

**Comment by gre** [comment]
We assume this to be fixed
