### ISSUE TITLE
Library for Ledger Live

### ISSUE THREAD

**Issue by BalajiR21** [LedgerHQ/ledger-live-desktop#1575]
- I have checked this feature was not yet requested.

Need an library to connect Ledger Live with web applications(Website)

When I integrate ledger in my website , there is no way to connect this with my website. I need to connect website and ledger live using library.
Could you please create a library and provide asap.

**Comment by gre** [comment]
Thanks for the issue.

What feature would you need as an API?
Would #1236 solves it if it was supported or is there more advanced feature you need?

We don't have the bandwidth to implement this in Q4 but we accept pull requests and this is all open source.
Ultimately you can use ledgerjs libs ( https://github.com/LedgerHQ/ledgerjs ) on a web app.

**Comment by BalajiR21** [comment]
I need to transfer funds using ledger live through my website . But this is not possible using https://github.com/LedgerHQ/ledgerjs. This only provide accounts and signTransaction like that.

**Comment by gre** [comment]
So for this usecase I think #1236 would address it. Either supporting standard URI schemes and/or having our own.

**Comment by BalajiR21** [comment]
But i'm unable to get the response after the payment

**Comment by juan-cortes** [comment]
Unless I'm misunderstanding completely you want an integration that would connect the accounts that are managed by the device and your website. You'd need to write your own integration depending on the crypto you want to integrate, for example you can take a look at how [account viewer for stellar does this](https://github.com/stellar/account-viewer/blob/cd4c225a5d320f0906e5cf16518e07d44e491236/controllers/send-widget.controller.es6#L406)

Essentially you need a transport which is the communication layer between the device and an app api to talk to the crypto app on the device, in the previous example it used `@ledgerhq/hw-transport-u2f` and `@ledgerhq/hw-app-str`. So unfortunately this is not something that Ledger need to do for you, you need to learn how the system works and integrated it, all the pieces are likely there already.
