### ISSUE TITLE
Improve Identifier display in firmware update

### ISSUE THREAD

**Issue by dasilvarosa** [LedgerHQ/ledger-live-desktop#1576]
During a firmware update the Identifier is shown on the device and should be verified on the Manager. 

- Ledger Nano S and Ledger Blue only show the first 4 and last 4 characters of the Identifier: `[ABCD...1234]`.

- Ledger Live shows the entire string. This should be reduced to match the characters displayed on the device.
![](https://support.ledgerwallet.com/hc/article_attachments/360008515234/identifier.png)

**Comment by gre** [comment]
easy to fix. hard to test.

**Comment by juan-cortes** [comment]
This is done

**Comment by gre** [comment]
Thanks a lot
