### ISSUE TITLE
migrate to styled-components @ 4

### ISSUE THREAD

**Issue by gre** [LedgerHQ/ledger-live-desktop#1584]
it might be a quick win for performance. 

https://medium.com/styled-components/styled-components-v4-new-final-finalest-for-real-final-final-psd-fa4d83398a77
^ there is a codemod to automatically migrate codebase

**Comment by meriadec** [comment]
Started to work on it here: https://github.com/meriadec/ledger-live-desktop/tree/styled-components-v4

..but clearly not for next release. codemod didn't do anything (wtf?), and only fixing the global style handler and refs wasn't enough. There is still (at least) ~30 errors based on unwanted props getting into the DOM (didnt understood why), and we have to migrate CSS animations to the new syntax.

**Comment by gre** [comment]
ok. let's pause this from our side.
