### ISSUE TITLE
SSH/PGP Agent with Ledger Nano S possible to run on Windows?

### ISSUE THREAD

**Issue by peatrick** [LedgerHQ/ledger-live-desktop#1605]
Original issue [re: ledger-app-ssh-agent](https://github.com/LedgerHQ/ledger-app-ssh-agent) / help request can be found on the Trello boards, here:  https://trello.com/c/lzrZ7Vyv

This issue was originally marked as "Done" on the Trello boards, however I am unable to find clarification if it is possible to run _SSH/PGP Agent_ app with my Ledger Nano S under Windows.

Environment:  Windows 10 Professional (64-bit) v1809, Python v3.7 (64-bit)
```
Package    Version
---------- --------
cffi       1.11.5
libusb     1.0.22b1
pip        18.1
pycparser  2.19
setuptools 40.4.3
```

Steps to reproduce:
1. `>python -m pip install --upgrade pip`
_Successfully installed pip-18.1_ (from v10.0.1)
2. `>pip install --upgrade setuptools`
_Successfully installed setuptools-40.4.3_ (from v39.0.1)
3. `>pip install libusb`
_Successfully installed cffi-1.11.5 libusb-1.0.22b1 pycparser-2.19_

Above were steps to prepare my environment for _SSH/PGP Agent_ on my Ledger Nano S (Firmware 1.4.2), and below is the error I am presented with. Is this simply due to lack of support on Windows, or some other unknown issue/error on my part? Thank you in advance for your time and attention to my little matter.

Attached is the full error report:  https://pastebin.com/suP2x8eY
> `C:\WINDOWS\system32>pip3 install ledger-agent`

`Collecting ledger-agent
  Using cached https://files.pythonhosted.org/packages/a3/c9/ac7546d6168662af356493231ca8818bdf8ffd05238a68fe5085fd9e6358/ledger_agent-0.9.0.tar.gz`

`Collecting libagent>=0.9.0 (from ledger-agent)
  Using cached https://files.pythonhosted.org/packages/dc/77/e9c300e04dd449e726ebc153c15aff18c38b7dbb1704f985f4ddb881d6f8/libagent-0.12.0.tar.gz`

`Collecting ledgerblue>=0.1.8 (from ledger-agent)
  Using cached https://files.pythonhosted.org/packages/3c/62/39d9b29f5ada49a0ec595e275d5326dd9e6f94939138884506a4105dcedb/ledgerblue-0.1.21.tar.gz`

`Collecting backports.shutil_which>=3.5.1 (from libagent>=0.9.0->ledger-agent)
  Using cached https://files.pythonhosted.org/packages/a2/c4/fb76dfc7831416ec0832420abbd72d8fac262a44df2759deeaf75c8c0d70/backports.shutil_which-3.5.1-py2.py3-none-any.whl`

`Collecting ConfigArgParse>=0.12.0 (from libagent>=0.9.0->ledger-agent)
  Using cached https://files.pythonhosted.org/packages/77/61/ae928ce6ab85d4479ea198488cf5ffa371bd4ece2030c0ee85ff668deac5/ConfigArgParse-0.13.0.tar.gz`

`Collecting python-daemon>=2.1.2 (from libagent>=0.9.0->ledger-agent)
  Using cached https://files.pythonhosted.org/packages/99/2a/75fe6aa7086e838570f29899f674e7896a42be26d9fff33f90d990e599d2/python-daemon-2.2.0.tar.gz`

`Complete output from command python setup.py egg_info:`
`Traceback (most recent call last):`
`  File "<string>", line 1, in <module>`
`  File "C:\Users\user\AppData\Local\Temp\pip-install-ior08fpj\python-daemon\setup.py", line 34, in <module>`
`    level=0, fromlist=main_module_fromlist)`
`  File "C:\Users\user\AppData\Local\Temp\pip-install-ior08fpj\python-daemon\daemon\__init__.py", line 38, in <module>`
`    from .daemon import DaemonContext`
`  File "C:\Users\user\AppData\Local\Temp\pip-install-ior08fpj\python-daemon\daemon\daemon.py", line 19, in <module>`
`        import pwd
    ModuleNotFoundError: No module named 'pwd'`
`    ----------------------------------------`
`Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-install-ior08fpj\python-daemon\`

[pip3 install ledger-agent_error.txt](https://github.com/LedgerHQ/ledger-live-desktop/files/2516700/Python_error.txt)

**Comment by eastabrooka** [comment]
+1

**Comment by meriadec** [comment]
Hi @peatrick 

Would you mind re-creating the issue on the associed repo? I guess [ledger-app-ssh-agent](https://github.com/LedgerHQ/ledger-app-ssh-agent) but I'm not really used to python<->ledger env.

ledger-live-desktop is focused on the desktop electron app

**Comment by meriadec** [comment]
Aaaaand I just realized that the original issue was from >1month ago :p
hope u found a solution

**Comment by peatrick** [comment]
@meriadec so very sorry, sir I never did find a solution.  In fact, I just gave up.  I even failed on a couple Linux VMs because I didn't have the ability to pass through USB devices to the virtual machine, but I'm confident that set would have worked much better.

For now, I'll continue lying awake at night, dreaming of the day i can blow away my Windows desktop daily driver and replace it with a gorgeous Cinnamon desktop environment, or perhaps even Budgie or something fun.  I got so frustrated i completely removed Python from my Windows PC.  I half assumed it was my inexperience that was causing the issue(s), but felt better when someone else (@eastabrooka) was able to recreate the struggles I've had.  My apologies my report wasn't more thorough in nature, but I'm probably due for a freshie wipe & reload of Windows as it's been ~18 months, or so without a format.  Usually lucky if I get a full year without having to completely reinstall Windows.  Trying to keep most sketchy software to VMs these days in hopes of extending the life of this install/instance.

Thank you for your kind offer of assistance, wish I could provide what you need to troubleshoot this.
