### ISSUE TITLE
Add the rate R$ provider using the Bitcambio.com.br

### ISSUE THREAD

**Issue by jpereira** [LedgerHQ/ledger-live-desktop#1618]
Today we have only two R$ (Brazilian Reais) rate providers being "Mercado Bitcoin" and "Braziliex". 

Therefore can be good to include some extra providers as the www.bitcambio.com.br. The API documentation can be seen in https://blinktrade.com/docs/

fyi: @pinhopro

**Comment by gre** [comment]
this is not related to Ledger Live app itself but on our backend.
we will in the future improve our exchanges, you can also contact tech support to raise that.
