### ISSUE TITLE
Manager not displaying all available apps

### ISSUE THREAD

**Issue by pygeek** [LedgerHQ/ledger-live-desktop#1621]
#### Ledger Live Version and Operating System

- tested on Ledger Live **1.2.3**
- Platform and version: **MacOS 10.14.1**

#### Expected behavior

Apps added in 1.2.3 should be included in Manager's available app list
#### Actual behavior

IOTA, Aion (AION), Atheios (ATH), Banano, Callisto (CLO), Ethersocial (ESN), Ether1 (ETHO), GoChain (GO) are not available in Manager app list

#### Steps to reproduce the behavior
Install and run latest version of Ledger Live Desktop (1.2.3)  on MacOS 10.14.1.
Navigate to Manager
Authenticate Ledger device (Ledger Blue firmware 2.0)

**Comment by pygeek** [comment]
@amougel @gre Let me know if Ledger Blue is still being supported or if we need to write new firmware to get it up to speed with features supported by Ledger Nano.

**Comment by pygeek** [comment]
@amougel @gre Updating to Ledger Blue firmware 2.1.1 fixes this issue for all currencies except for IOTA.

**Comment by gre** [comment]
please contact tech support as it does not concern Ledger Live app itself but more the apps list server
