### ISSUE TITLE
Recovery Check app with passphrase

### ISSUE THREAD

**Issue by CryptoIOTA** [LedgerHQ/ledger-live-desktop#1640]
I understand that "recovery check" app can't be used to validate passphrase protected wallet.
Basically I'd like to validate my seed + passphrase on a hidden wallet of a Nano S.

**Comment by tookdrums** [comment]
You can verify your seed and passphrase by doing the following:

- Verify the 24 seed
- Then add a passphrase as temporary (not attached to a pin) 
- Open the bitcoin app
- Check that your coins are here.

**Comment by CryptoIOTA** [comment]
Got it!
 thank you!

Il 28.11.2018 15:18 tookdrums ha scritto: 

>
You can verify your seed and passphrase by doing the following: 
> 
> *
Verify the 24 seed
> * Then add a passphrase as temporary (not attached
to a pin)
> * Open the bitcoin app
> * Check that your coins are here.
>

> --
> You are receiving this because you authored the thread.
> Reply
to this email directly, view it on GitHub [1], or mute the thread [2].
 



Con OpenStar hai Giga, SMS e i minuti che vuoi da 4,99€ al mese, per sempre. Cambi gratis quando e come vuoi e in più hai 10€ di credito omaggio e 6 mesi di INFINTY! http://tisca.li/myopen
