### ISSUE TITLE
Balance

### ISSUE THREAD

**Issue by andreicel** [LedgerHQ/ledger-live-desktop#1648]
- [X] I have checked this feature was not yet requested.

Ledge live does not have all the applications, I believe it is very difficult to implement. I feel very difficult to know my balance in each currency that I have, since I have to install the applications in ledger, in live ledger, to verify the balance. For me it will, but for my wife it is very difficult. Especially when you have to uninstall an application to put another one because of the space limitation.
Even if you do not have all applications in the live ledger, you could display the balance easily by checking the address of each currency in the bip39 and consulting the explorer automatically, with only the balance of each one appearing, and you can disable it if you want. The Delta application is already doing something similar. The user enters the wallet number and the application monitors the statement.
In the case of the ledger it already has all addresses to verify.

**Comment by gre** [comment]
relates to https://github.com/LedgerHQ/ledger-live-desktop/issues/1734 and #1560
