### ISSUE TITLE
Need One-Click Solution to Upgrade from Legacy Account (e.g., "Litecoin 1 (legacy)")

### ISSUE THREAD

**Issue by nottoseethesun** [LedgerHQ/ledger-live-desktop#1658]
- [x] I have checked this feature was not yet requested.

Allow a menu option for accounts on legacy blockchain versions (they are marked like "Litecoin 1 (legacy)", or "Ethereum 1 (legacy)") to be upgraded with just a single click.  

Currently a new account has to be separately created and then the crypto units manually sent, which is a chore and also introduces unnecessary room for error.  

Instead, the Ledger Live should just do that as a one-click option.

#### Part of the application

"Accounts"

**Comment by gre** [comment]
A MAX feature would help. Maybe later it would be great to consider chosing an account instead of an address in the Send flow.

**Comment by gre** [comment]
I'm not sure we need to automate it all ("one click") because not that common usecase I feel, but I agree there are room for improvement on making that easier. Also technically it's ok if you still use legacy. I mean it still works and it's not going to be later removed (it's not a deprecation)

**Comment by nottoseethesun** [comment]
@gre  - Regarding "Choose Account":  Great idea on choosing an account instead of an address in the "Send" flow: If it hasn't already been suggested, I encourage you to create a feature request for that.

@gre - Regarding the present feature suggestion, "Auto-Upgrade", here is a good description of why, from a Reddit user:

> Switching to the new path format will mean that more stuff "just works" - you'll be able to switch to Trezor or back, and your addresses will "just match" without you having to find "advanced options". But it does have the obvious disadvantage that you have to move all your coins/Etheremon/CryptoKitties to the new address.

   - https://www.reddit.com/r/ledgerwallet/comments/92w2qx/what_does_legacy_mean_exactly_in_connection_to_an/

**Comment by cthepot-ledger** [comment]
add account and send max will solve the issue

**Comment by peteski22** [comment]
> 
> 
> add account and send max will solve the issue

Is there some kind of KB article for this? I'm not sure what it means, and I guess people aren't likely to play around with their wallets in case they lose funds into the .. ether :)
