### ISSUE TITLE
2FA Login for Ledger Live Client

### ISSUE THREAD

**Issue by nlebowitz** [LedgerHQ/ledger-live-desktop#1662]

**Comment by Luuk2016** [comment]
Why would you like to have 2FA in the Ledger Live app.
At the app startup you can have a login with password, if you send a transaction you already need to confirm on the Ledger device.

**Comment by nlebowitz** [comment]
Right, I was thinking for when your ledger isn't connected, so that someone who might be able to figure out your password can't see which assets you have and how many.

**Comment by Luuk2016** [comment]
Ah ok, i thing that its possible but that it costs a lot of work to implement.

**Comment by dasilvarosa** [comment]
@nlebowitz If you're that concerned about your privacy, you could delete your accounts after using the app. This is related to issue https://github.com/LedgerHQ/ledger-live-desktop/issues/954. Some sort of privacy mode might be added later which does not preserve accounts after logging out.
