### ISSUE TITLE
Horizen (ZEN) Send modal error: "Transaction <txId> not found."

### ISSUE THREAD

**Issue by nscarlson** [LedgerHQ/ledger-live-desktop#1666]
#### Ledger Live Version and Operating System

- Tested on Ledger Live **1.2.6**
- Ledger Nano S
- Platform and version: **MacOS Mojave 10.14.1**

#### Expected behavior

While in the Send modal after setting up the Details step, Live should send the sign request to my Ledger, and the device should then request my confirmation of the destination address, and the send/fee amount.

#### Actual behavior

The Send modal errors like this at the Details step:
<img width="575" alt="screen shot 2018-11-23 at 18 37 43" src="https://user-images.githubusercontent.com/3528679/48972889-18618080-eff1-11e8-8e1a-4673ab1f19d6.png">

The Confirmation step errors like so:

<img width="606" alt="screen shot 2018-11-23 at 18 41 42" src="https://user-images.githubusercontent.com/3528679/48972740-9cfecf80-efee-11e8-96b8-b2a696ddc96f.png">

I can consistently send about 0.5 to 1 ZEN at a time without the error.  One transaction of 20 ZEN successfully went through after retrying several times, and I have been unable to send an amount greater than 20.1111 ZEN.  About 4 or 5 unique txIds have been displayed yesterday and today.

#### Steps to reproduce the behavior
The screenshots above explain the behavior.  I can provide more details if relevant.

**Comment by nscarlson** [comment]
It _appears_ the error is coming from: https://github.com/LedgerHQ/lib-ledger-core/blob/e328d5e87d3dbf2f6eee7ee39dad7ea870494e66/core/src/wallet/bitcoin/explorers/LedgerApiBitcoinLikeBlockchainExplorer.cpp#L161-L162

**Comment by nscarlson** [comment]
It appears the issue "resolve itself" and I'm now able to broadcast transactions from my Ledger normally.  Closing.

For reference, the issue number opened with support was `231668`.

**Comment by meriadec** [comment]
thanks for the follow up @nscarlson, I informed support team
