### ISSUE TITLE
I am not able to install it on Ubuntu 14.04

### ISSUE THREAD

**Issue by elderapo** [LedgerHQ/ledger-live-desktop#1671]
#### Ledger Live Version and Operating System

- tested on Ledger Live **ledger-live-desktop-1.2.6-linux-x86_64**
- Platform and version: **Ubuntu 14.04.5 LTS**

#### Expected behavior

Should correctly install an app.

#### Actual behavior

```bash
root@xyz:~/Downloads# ./ledger-live-desktop-1.2.6-linux-x86_64.AppImage 
/tmp/.mount_ledger3IGFWq/app/ledger-live-desktop: /lib/x86_64-linux-gnu/libkeyutils.so.1: version `KEYUTILS_1.5' not found (required by /tmp/.mount_ledger3IGFWq/usr/lib/libkrb5.so.3)
```

#### Steps to reproduce the behavior

```bash
./ledger-live-desktop-1.2.6-linux-x86_64.AppImage
```

**Comment by meriadec** [comment]
Hey, this is normal, Ubuntu is supported since version 16.10 (see [install instructions](https://support.ledgerwallet.com/hc/en-us/articles/360006395553-Download-and-install-Ledger-Live)).
Older versions can have libraries incompatibilities.
