### ISSUE TITLE
Synchronisation Error

### ISSUE THREAD

**Issue by maslovsa** [LedgerHQ/ledger-live-desktop#1682]
#### Ledger Live Version and Operating System

- tested on Ledger Live v1.2.6
- Platform and version: mac os 10.14.2 (18C52a)

#### Expected behavior

Sync well. Show balances in USD.

#### Actual behavior

https://monosnap.com/file/3op9vwx2ik6lGoEbiMUN8I1BdvGECR

#### Steps to reproduce the behavior

Open app. Input password.

**Comment by maslovsa** [comment]
@meriadec 
no Proxy.
Tested on Wifi and Ethernet Cable.

Pressed "Refresh" several times.

**Comment by meriadec** [comment]
I guess Wifi/Ethernet are on the same network, but does it still happening on a different one? (can't reproduce on our side)
