### ISSUE TITLE
Could not connect to device Ubuntu

### ISSUE THREAD

**Issue by skyrbs** [LedgerHQ/ledger-live-desktop#1689]
#### Ledger Live Version and Operating System

- tested on Ledger Live **ledger-live-desktop-1.2.6-linux-x86_64**
- Platform and version: **e.g. Ubuntu  16.04 LTS.**

#### Expected behavior

I am stuck at the same point every time "Oops, couldn’t connect to device".

I restarted my PC, change internet connect, re-downloaded ledger live, Change USB Port, Plug in Plug Out but still not working for me. For details please check the screenshot.
![ledger2](https://user-images.githubusercontent.com/13250381/49510686-fdbfbf00-f8ae-11e8-996d-81efd03507f3.png)
![ledger1](https://user-images.githubusercontent.com/13250381/49510687-fe585580-f8ae-11e8-8584-2e0585b7dfa2.png)

**Comment by meriadec** [comment]
Can you check this: https://github.com/meriadec/nanos-linux-install-instructions/blob/master/README.md

**Comment by skyrbs** [comment]
> Can you check this: https://github.com/meriadec/nanos-linux-install-instructions/blob/master/README.md
Thanks for your instructions. It is working.

If anyone facing this issue run  below command...

sudo wget -q -O - https://raw.githubusercontent.com/LedgerHQ/udev-rules/master/add_udev_rules.sh | sudo bash

**Comment by meriadec** [comment]
yep :+1: . it's specified on our support page https://support.ledgerwallet.com/hc/en-us/articles/115005165269-Fix-connection-issues
