### ISSUE TITLE
Electron Cash splitting tool(BCH)

### ISSUE THREAD

**Issue by KMFDM29** [LedgerHQ/ledger-live-desktop#1694]
Not open  splitting wallet,  As it is told in the instruction. Opens the same wallet - hardware wallet.
![07-12-2018 054246](https://user-images.githubusercontent.com/41021204/49608962-dc152380-f9e5-11e8-9e24-bb05e117748c.jpg)
![07-12-2018 054335](https://user-images.githubusercontent.com/41021204/49608963-dc152380-f9e5-11e8-8d36-1698f7867227.jpg)

**Comment by gre** [comment]
Please contact tech support ( https://support.ledgerwallet.com/hc/en-us ) because here is the development repository of Ledger Live.
Thanks
