### ISSUE TITLE
ZClassic

### ISSUE THREAD

**Issue by KMFDM29** [LedgerHQ/ledger-live-desktop#1695]
Where to get the application  ZClassic?
![07-12-2018 233645](https://user-images.githubusercontent.com/41021204/49651006-bfc2c680-fa79-11e8-8964-5c0d29ecab36.jpg)

**Comment by meriadec** [comment]
you can find it in the Ledger Live manager

![capture](https://user-images.githubusercontent.com/315259/49654927-6a66c500-fa39-11e8-8326-ba11aecb3424.png)

**Comment by meriadec** [comment]
this is now fixed https://www.ledger.com/pages/supported-crypto-assets
thx for reporting
