### ISSUE TITLE
Bitcoin custom fee is calculating incorrectly

### ISSUE THREAD

**Issue by the-metalworker** [LedgerHQ/ledger-live-desktop#1714]
#### Ledger Live Version and Operating System

- tested on Ledger Live **Ledger Live 1.2.7**
- Platform and version: **Linux Mint 18.3**

#### Expected behavior

I entered the custom fee 5 sat/byte for a BTC transaction.

#### Actual behavior

The transaction actually paid 7.5 sat/byte. (For privacy reasons I don't want to link to the exact transaction, but the size in bytes and fee paid equals to 7.5 sat/byte.)

#### Steps to reproduce the behavior

Enter custom fee. Notice that the fee paid may actually be different than the fee entered.

**Comment by rdbr** [comment]
I can confirm that the custom fee is calculated incorrectly when using Segwit addresses.

I set a custom fee of 10 sat/B:
`10 sat/B -> 14.6 sat/vB, Segwit discounted: 9.76 sat/B`

And another transaction with a custom fee of 8 sat/B:
`8 sat/B -> 11.7 sat/vB, Segwit discounted: 7.839 sat/B`

So it appears to apply the custom fee to the resulting Segwit size, while the custom fee should be equal to the sat/vB.

**Comment by gre** [comment]
this should have been fixed.
