### ISSUE TITLE
Issue with Debian Jessie 8

### ISSUE THREAD

**Issue by Furiacs** [LedgerHQ/ledger-live-desktop#1715]
I had some problems to put Ledger Live running on Debian Jessie 8 and I like to share some info.

Even added all udev rules and running normally all ledger's chrome apps, Ledger Live was not recognizing my Ledger Device on "genuineness check" process.

After a lot of research, I found a incompatibility issue with my version of GLIBCXX and resolve the issue this way:

1) Downloaded: https://packages.debian.org/stretch/amd64/libstdc++6/download;
2) Extracted .deb file to Ledger Live AppImage path;
3) Defined one more LD_LIBRARY_PATH before run: 
`LD_LIBRARY_PATH=LEDGER-LIVE-PATH/libstdc++6_6.3.0-18+deb9u1_amd64/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH ./ledger-live-desktop-1.2.7-linux-x86_64.AppImage`

I hope to help anyone with the same problem.

**Comment by meriadec** [comment]
:+1: thanks for reporting & providing workaround

**Comment by TranceEX** [comment]
> I had some problems to put Ledger Live running on Debian Jessie 8 and I like to share some info.
> 
> Even added all udev rules and running normally all ledger's chrome apps, Ledger Live was not recognizing my Ledger Device on "genuineness check" process.
> 
> After a lot of research, I found a incompatibility issue with my version of GLIBCXX and resolve the issue this way:
> 
> 1. Downloaded: https://packages.debian.org/stretch/amd64/libstdc++6/download;
> 2. Extracted .deb file to Ledger Live AppImage path;
> 3. Defined one more LD_LIBRARY_PATH before run:
>    `LD_LIBRARY_PATH=LEDGER-LIVE-PATH/libstdc++6_6.3.0-18+deb9u1_amd64/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH ./ledger-live-desktop-1.2.7-linux-x86_64.AppImage`
> 
> I hope to help anyone with the same problem.

this solution doesn't work in version 1.3.2.

**Comment by gre** [comment]
I think we have fixed this situation since the issue was created.
