### ISSUE TITLE
shamir secret sharing app for ledger

### ISSUE THREAD

**Issue by thedavidmeister** [LedgerHQ/ledger-live-desktop#1722]
- [ x ] I have checked this feature was not yet requested.

i would like to be able to setup an m of n seed for my ledger using shamir secret sharing using a new, dedicated application on the ledger

i found this repo: https://github.com/oed/seedsplit

and these reddit threads:

- https://www.reddit.com/r/ledgerwallet/comments/65b1zi/secure_your_seed_with_seedsplit/
- https://www.reddit.com/r/ledgerwallet/comments/67dtte/why_isnt_the_backup_seed_encrypted/
- https://www.reddit.com/r/ledgerwallet/comments/75z38d/safe_way_to_store_the_seed_words/
- https://www.reddit.com/r/ledgerwallet/comments/6ez4qs/ledger_nano_s_seed_utility_app_released/
- https://www.reddit.com/r/ledgerwallet/comments/8yzpcg/help_with_seed_splitting_ideas/
- https://www.reddit.com/r/ledgerwallet/comments/77zd29/how_to_create_nofm_backup_of_seed/
- https://www.reddit.com/r/ledgerwallet/comments/6e4a9i/best_way_to_encrypt_recovery_seed_words/
- https://www.reddit.com/r/ledgerwallet/comments/a6vked/seed_splitting_worksheet_employing_shamir_secret/

but all the options offered require setting up an airgapped device and running 3rd party unaudited code

it makes sense to me that m of n seeds be able to be generated by the ledger itself, using audited code, without the seed needing to leave the device

without this option we must choose between a risky technical process or a physical risk in the storage of the seed

an official m of n seed would facilitate much more secure physical setups for many more users

i understand that this is a fairly advanced feature for most people, so probably shouldn't be the default behaviour, but would help others sleep better at night :)

#### Part of the application

new application for ledger

**Comment by Transisto** [comment]
I'm very supportive of this concept and had planed to push every wallet to offer the same.

/ledger-live-desktop/ is just a client and not where this should be posted.

This would happen inside the device itself and I think should be posted here https://github.com/LedgerHQ/ledger-nano-s/issues

**Comment by thedavidmeister** [comment]
@Transisto ok thanks, i've moved this issue across to the other repo
