### ISSUE TITLE
Typo in the currency name when creating a Ripple (XRP) address

### ISSUE THREAD

**Issue by JazzBashara** [LedgerHQ/ledger-live-desktop#1727]
Typo in the currency name when creating a Ripple (XRP) address, shows 'Bitcoin' instead of 'XRP'

#### Ledger Live Version and Operating System

- tested on Ledger Live: 1.2.7
- Platform and version: Windows 10

![image](https://user-images.githubusercontent.com/1304367/50550950-83017e00-0c79-11e9-8521-15a31ffb939c.png)

**Comment by Luuk2016** [comment]
The strange thing is that it appears to all assets except for Bitcoin.
If you check [this](https://github.com/LedgerHQ/ledger-live-desktop/blob/eb6501de1d3810a81daffe9da546d8f88187d70f/static/i18n/en/app.json#L140) line you notice that they only made it for BTC.

**Comment by juan-cortes** [comment]
Current develop branch has that fixed https://github.com/LedgerHQ/ledger-live-desktop/blob/develop/static/i18n/en/app.json#L140 so the next version will have it fixed I'd assume.
