### ISSUE TITLE
Add support for Wasabi Wallet addresses

### ISSUE THREAD

**Issue by JazzBashara** [LedgerHQ/ledger-live-desktop#1743]
Future idea to add support for Wasabi Wallet addresses.
https://www.wasabiwallet.io/

**Comment by kirillkovalenko** [comment]
The address format wassabi wallet uses called [Base32 address format for native v0-16 witness outputs](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki). This issue is basically a duplicate of #1051.
