### ISSUE TITLE
Unable to manage Ledger device with Live app after upgrade to 1.3.0 on Win10

### ISSUE THREAD

**Issue by becausetheypayme** [LedgerHQ/ledger-live-desktop#1749]
#### Ledger Live Version and Operating System

- tested on Ledger Live Ledger Live v1.3.0
- Platform and version: Windows 10 (1803)

#### Expected behavior

Open Live, click Manager, connect Ledger device, authenticate PIN, go to device dashboard, approve Manager connection, manage device.

#### Actual behavior

Open Live, click Manager, connect Ledger device, authenticate PIN, go to device dashboard, wait for approve prompt...sometimes prompts, sometimes doesn't. Even when prompt intermittently appears, clicking the check mark (right button), nothing happens and the progress spinner on the "Allow Ledger Manager" prompt on the Live app continues to spin, as if nothing has happened.

#### Steps to reproduce the behavior

Open Live, click Manager, connect Ledger device, authenticate PIN, go to device dashboard, wait for approve prompt...sometimes prompts, sometimes doesn't. Even when prompt intermittently appears, clicking the check mark (right button), nothing happens and the progress spinner on the "Allow Ledger Manager" prompt on the Live app continues to spin, as if nothing has happened.

Note: This was experienced after an update of Live to 1.3.0. Once encountered, rebooted system and opened only Live to try again. Encountered same result.

**Comment by Luuk2016** [comment]
Probably the same issue, see issue #1748 
There is a server problem, Ledger Live isn't the problem.

**Comment by Luuk2016** [comment]
See Ledger's reply on Twitter:
https://twitter.com/LedgerHQ/status/1085607408150298629

**Comment by becausetheypayme** [comment]
> 
> 
> See Ledger's reply on Twitter:
> https://twitter.com/LedgerHQ/status/1085607408150298629

Yep. Just ran across the tweet myself. Thanks!
