### ISSUE TITLE
Bitcoins on the testnet show a value

### ISSUE THREAD

**Issue by Luuk2016** [LedgerHQ/ledger-live-desktop#1752]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.3.0
- Platform and version: Windows 10/macOS Mojave

#### Expected behavior

Bitcoins on the testnet have no value, so it should'nt display a value.

#### Actual behavior

Bitcoins on the Testnet display the normal BTC price.
This can be pretty annoying if you have other accounts.

#### Steps to reproduce the behavior
* Add a BTC testnet account to ledger live
* Receive some BTC on the testnet.

**Comment by juan-cortes** [comment]
We are aware of this, it's currently using the BTC value for the fiat calculation, I personally agree it should show either zero or unavailable since they have no value.

**Comment by gre** [comment]
Yeah we could easily shortcut it in live-common. If currency.isTestnetFor then you returns 0 in the calculation function.

**Comment by Luuk2016** [comment]
Would it be something that i can easily change with a PR?

**Comment by meriadec** [comment]
@Luuk2016 returning `0` [in the `getRate` function](https://github.com/LedgerHQ/ledger-live-common/blob/42c156870e22f39e6232cdf0f366272780725645/src/countervalues/index.js#L128-L134) if the `pair.from` currency has a `isTestnetFor` should do the trick

**Comment by Luuk2016** [comment]
Created a [PR](https://github.com/LedgerHQ/ledger-live-common/pull/135)
Sorry if i am totally wrong, my JS knowledge isnt't that great. 😞

**Comment by gre** [comment]
Fixed by now.
