### ISSUE TITLE
Could not add ETC account (unknown error 0x6804)

### ISSUE THREAD

**Issue by rumatoest** [LedgerHQ/ledger-live-desktop#1753]
#### Ledger Live Version and Operating System
- Ledger Nano S
- tested on Ledger Live 12.7 and 1.30
- Platform and version: Windows 10 64bit and Ubuntu 18.04 64bit
- ETC and ETH apps v1.1.8
- Secure element 1.5.5 MCU 1.7

#### Expected behavior

ETC account should be added to ledger live

#### Actual behavior
unknown error (0x6804)
please reconnect your device

BTW Looks like when I'm try to add ETC Account with ETH app it works without any issues.
And after that I'm able to acquire "receive address" for ETC account via ETC app.

There are several bugs here:
- why I'm able to add ETC account using ETH app
- why I can not add ETC account using ETC app

#### Conclusion
Because this is happens on different OS with different cables and on different USB ports I can consider it as definitely software bug.

![ledger-etc](https://user-images.githubusercontent.com/1499231/51379317-30044380-1b20-11e9-8631-da460666b794.png)

**Comment by Luuk2016** [comment]
Just tried the same, can confirm that its not working.

**Comment by rumatoest** [comment]
@juan-cortes I've tried to use myetherwallet.com and it gives me error with same code Invalid status 6804
And it is strange because myetherwallet asks to choose derivation (at leas for ETH)

**Comment by rumatoest** [comment]
I was not able to chose any derivation, it fails during connect.
BTW same happens with MyCrypto application for PC is works with ETH app and does not want to connect to ETC app

**Comment by gre** [comment]
@btchip will release a new ETC app that will solve this problem

**Comment by gre** [comment]
The fix is to happen in the ETC app. We will release a new version of ETC app that will correct this glitch.

**Comment by gre** [comment]
Let's continue the discussion on https://github.com/LedgerHQ/ledger-app-eth/issues/55 as there is nothing we can do
