### ISSUE TITLE
Incorrect calculation of total to debit for BTC send

### ISSUE THREAD

**Issue by moarmarmalade** [LedgerHQ/ledger-live-desktop#1758]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.3.0 (Linux Appimage, from https://github.com/LedgerHQ/ledger-live-desktop/releases, sha512sum verified)
- Platform and version: Devuan GNU/Linux ascii, amd64 (like Debian Stretch, but w/o systemd)
- Device: Ledger Nano S with firmware 1.4.2 and Bitcoin app. 1.3.2

#### Expected behavior

When trying to send 0.025 BTC from BTC (std. i.e. segwit) account (with standard fee 4sat/B) , the
"Total to debit" field on the send menu should display something like "0.02500976 BTC (USD 90.27)".

#### Actual behavior

The "Total to debit" on the send menu shows "0.81889819 BTC (USD 2,955.81)"

#### Steps to reproduce the behavior

Simply run the appimage 1.3.0 from command line and then prepare a BTC send transaction so that the send menu appears. (This can be done without the Ledger device connected.)

If the bitcoin address field is blanked, the menu (i.e. the "Total to debit") returns to correct behavior, and if the address field is filled out again the problem (i.e. the incorrect amount in the "Total to debit") returns.

Note: The problem described above persists with ledger-live 1.3.0 even if I delete and then reimport my BTC account (on ledger-live). The ledger-live Linux Appimage version 1.2.7 shows the expected (correct) behavior for this account on the platform listed above, and the expected (correct) behavior is also displayed for this account with ledger-live version 1.3.0 on Mac OSX. 

Perhaps this issue is already known to the Ledger team, see this [reddit post](https://old.reddit.com/r/ledgerwallet/comments/aiw6sj/ledger_live_adding_a_55_fee_to_all_btc/).

A workaround seems to be clearing the cache since this restores the correct behavior.

Edit: Some clarifications.
Edit2: Info about address field dependence.
Edit3: Added reddit post link.
Edit4: Remark about clearing the cache as a workaround.

**Comment by gre** [comment]
we expect this fixed in upcoming release
