### ISSUE TITLE
hsr - Something went wrong. Please retry or contact us. ledger live

### ISSUE THREAD

**Issue by onur1980** [LedgerHQ/ledger-live-desktop#1768]
hi,

i installed the latest version of firmware/ledger live and hcash app. 

i try to transfer my hsr to the desktop hcash wallet. because there is no way to make a sign message on ledger live app. yesterday i transfer 0.5 hsr successfully. but today i can't transfer the rest of them . it gave the error. could you please help.

thanks.

**Comment by gre** [comment]
can you try to remove the account manually and import it again? the coin interruption support makes the synchronization to stop, it's a glitch that #1767  will fix

**Comment by tpkeeper** [comment]
does ledger support the new hcash? the hcash looks like upgrage , and we can not  use the old version
@gre

**Comment by onur1980** [comment]
No they didn’t support. But I want to transfer my hsr to desktop wallet in
order to make swap and signed message.

28 Oca 2019 Pzt, saat 11:01 tarihinde tpkeeper <notifications@github.com>
şunu yazdı:

**Comment by tpkeeper** [comment]
Please support the new hcash , I don`t want to loss my hcsah!! @gre

**Comment by gre** [comment]
First we want to solve any potential bug in doing the swap from HShare (HSR).

Support of HyperCash (HC) itself is another subject and not up to frontend team to decide, please contact tech support to raise that.

**Comment by tpkeeper** [comment]
here is swap link. pls follow it . @onur1980 
https://swap.h.cash

**Comment by gre** [comment]
Can you try again @onur1980 ? our explorer was de-synchronized.

You will have to remove and add again the account before to make sure the synchronization happens (our next release will fix this need)

**Comment by onur1980** [comment]
When you will make new release? Yesterday I removed and add the account
already. There is few time to make swap process

28 Oca 2019 Pzt, saat 15:59 tarihinde Gaëtan Renaudeau <
notifications@github.com> şunu yazdı:

**Comment by gre** [comment]
Just to be clear:

yesterday we had two bugs:

- live no longer automatically sync for HSR, only way to sync it is the by adding the account.
- HSR explorer was desynchronized. any transaction after December 11, 2018 was not detected by the live resulting of error at the end of Send

after today's fix, we only have the first bug, so you might still need to remove and re-add in case you have an error.

the release that will fix this first bug will be shipped tomorrow as Prerelease and a few days later as Release.

**Comment by onur1980** [comment]
So tonight I should retry by removing and adding accounts and apps again ?

28 Oca 2019 Pzt, saat 16:04 tarihinde Gaëtan Renaudeau <
notifications@github.com> şunu yazdı:

**Comment by onur1980** [comment]
i made the transfer to the desktop wallet now. it gave the error on the last step. 
"Sorry, try again (API HTTP 524)
Please retry. Interacting with Ledger's API server went wrong."

but it made the transfer. i didn't understand. and also the balance not refreshed on ledger. i guess there is another bug.

**Comment by onur1980** [comment]
i made the swap now. when i will get the new hc? do you know that?

**Comment by gre** [comment]
the balance don't refresh until you do again the remove/readd account. as sync is stopped. should be fixed in incoming release

**Comment by gre** [comment]
@FabriceDautriat will know better about HC
