### ISSUE TITLE
Ledger Live  update 

### ISSUE THREAD

**Issue by KMFDM29** [LedgerHQ/ledger-live-desktop#1771]
I have Ledger Live version 1.3.0 and Windows 7 now.If I update to the latest version of Ledger Live, will it stop working on Windows 7?

**Comment by Luuk2016** [comment]
Well if you want to be sure you can always try it.
If Ledger Live 1.3.0 is not working on your computer you can switch back to the version where it was working.

**Comment by KMFDM29** [comment]
I didn't say it didn't work on Ledger Live 1.3.0.I want to make a new update and try to find out which one will work on Windows 7.

**Comment by gre** [comment]
please contact tech support
