### ISSUE TITLE
ledger live turbo tax feature 

### ISSUE THREAD

**Issue by mypiedpiper** [LedgerHQ/ledger-live-desktop#1774]
just spitballing here but it would be nice to get a turbo tax feature like what coinbase has, so you know what you owe on your crypto portfolio, through trades, spot price, a simple excel document so you know

**Comment by gre** [comment]
do you know standard for these format? I've seen this https://github.com/picksco/harmony

**Comment by gre** [comment]
I consider this a dup of https://github.com/LedgerHQ/ledger-live-desktop/issues/1167 , discussion to continue out there
