### ISSUE TITLE
Sending BTC attempts to send negative amount after wallet address is entered

### ISSUE THREAD

**Issue by grantholle** [LedgerHQ/ledger-live-desktop#1782]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.3.2
- Platform and version: Mac 10.14.2

#### Expected behavior

Allow me to send the amount I have entered.

#### Actual behavior

It appears that it's calculated what I'm trying to send as `amount - 1`, which in turn doesn't allow me to complete the transaction/send.

#### Steps to reproduce the behavior

![ledger2](https://user-images.githubusercontent.com/1189456/52174850-2bed4c80-27d5-11e9-8616-cfa29925dd0c.gif)

**Comment by gre** [comment]
This is fixed in upcoming version 1.3.4

it's in prerelease if you want to try out. https://github.com/LedgerHQ/ledger-live-desktop/releases
