### ISSUE TITLE
Parse Insufficient funds message

### ISSUE THREAD

**Issue by clintnetwork** [LedgerHQ/ledger-live-desktop#1792]
Hi,

Maybe you can parse this message, display as json is not very user friendly.

![image](https://user-images.githubusercontent.com/5221349/52320557-493a3a80-29d0-11e9-8a52-58b2bb764437.png)

Cheers

**Comment by gre** [comment]
We shouldn't parse it but we should make it better on server side I think.

**Comment by gre** [comment]
This should be fixed now
