### ISSUE TITLE
[Linux] Detect udev config and inform user

### ISSUE THREAD

**Issue by meriadec** [LedgerHQ/ledger-live-desktop#1810]
To help users in the process of connecting their device to LL, we should be able to detect incorrect (or at least missing) configuration, point out what to update, and eventually propose to update them automatically (would require root privileges).

**Comment by gre** [comment]
good idea

**Comment by meriadec** [comment]
Yeah.. sounds shady to ask that indeed :smile:

**Comment by gre** [comment]
do you have some hints on how we could smartly detect this BTW?

because a device is either here or not 🤔 not sure how we can smartly detect that it's plugged but misconfigured. or maybe just a generic message for connection problems that link to the support wiki?

**Comment by meriadec** [comment]
a simple start can be to just detect presence of `/etc/udev/rules.d/20-hw1.rules` (and `/usr/lib/udev/rules.d/71-hw1.rules` for user that installed [`btchip-udev`](https://aur.archlinux.org/packages/btchip-udev/)). we could even parse the file, check stuff, even check user groups by executing `bash` or something. a bit like what's described in the [support article](https://support.ledger.com/hc/en-us/articles/115005165269-Fix-connection-issues). root privileges are only for executing the install script.

**Comment by Beanow** [comment]
Some other detection method. If `lsusb -d 2c97:` comes back non-empty but we're not able to connect yet, there's likely a udev rules problem.
