### ISSUE TITLE
[ETH] Add option to export extended public key

### ISSUE THREAD

**Issue by waterdrop01** [LedgerHQ/ledger-live-desktop#1817]
**ETH feature request**

Given Ledger has access to the mnemonic/seed/extended private key, AND that Ledger/MEW/Metamask are all HD wallets (deriving only one ETH address but still HD wallets), there should be an option to export the `extended public key` so that users could easily import the xpubkey into **watch only** wallets.

That's something very common with Bitcoin, that is gaining traction in Ethereum.

Cross posted on [MEW](https://github.com/MyEtherWallet/MyEtherWallet/issues/687) and [MM](https://github.com/MetaMask/metamask-extension/issues/3964) githubs.

Thank you for you feedback on this!

**Comment by gre** [comment]
This will probably be shipped when we move to a new implementation of ETH in next iteration. ETA 2 months from now

**Comment by gre** [comment]
In current implementation accounts no longer have xpubs for Ethereum, we only keep the fresh address on our side so it would not be possible to allow this.
Ethereum's status quo is still that 1 Account = 1 Address and i don't see this changing anytime soon (at the same that fees are super expensive).
Unless you have other information?
