### ISSUE TITLE
Add more filters to available filters

### ISSUE THREAD

**Issue by Luuk2016** [LedgerHQ/ledger-live-desktop#1818]
- [x] I have checked this feature was not yet requested.

Currently you can view "week", "month", and "year".
Wouldn't it be nice to also have "day" and maybe 2 or 3 years?
Now you cant see values in the graph that are older than a year.

#### Part of the application

Graphs/Dashboard/Accounts

**Comment by gre** [comment]
Definitely

**Comment by ibiscp** [comment]
Totally agree, more options like google stocks would be really nice.

<img width="641" alt="Screen Shot 2020-03-14 at 00 37 04" src="https://user-images.githubusercontent.com/19699606/76669502-2d6a7600-658c-11ea-8188-6820bd74266a.png">

**Comment by cthepot-ledger** [comment]
Duplicate of #1942
