### ISSUE TITLE
getVarint called with unexpected parameters when sending Stealth

### ISSUE THREAD

**Issue by Kryptoxic** [LedgerHQ/ledger-live-desktop#1824]
#### Ledger Live Version and Operating System

Tested on Ledger Live 1.4.1
Windows 10

#### Expected behavior

The Ledger Nano S should show the amount of XST being sent along with the address that it is being sent to.

#### Actual behavior

The screen on my Ledger Nano S does not show the address and amount to be sent at all and also, the Ledger Live application show an error message after a while saying "getVarint called with unexpected parameters".

#### Steps to reproduce the behavior

Simply open up the Stealth account and attempt to send some XST. Upon reaching the screen where the message asks me to verify the transaction on my Ledger device, the screen does not display the amount to be sent and the address it is going to be sent to and the Ledger Live application will show the error message as stated above.

**Comment by Kryptoxic** [comment]
Update:

I tested this with the new 1.5.0 update and the issue still persists.

**Comment by myselfmyself** [comment]
Same.  They mentioned to me a few months ago that they believed the update would fix the problem; has not been fixed.  Coins still stuck.  Sent them into the ledger just fine, but now cant get them out.  Someone please look into this and fix this for your customers/users.

**Comment by Kryptoxic** [comment]
Ticket 271821 has been opened with Ledger to nudge them about this issue again. Waiting for their reply. Will update once they replied to my ticket

**Comment by myselfmyself** [comment]
Thank you.  We can update each other.  The more people hassling them to solve this issue, the better.
________________________________

**Comment by gre** [comment]
We'll take a look at this ASAP.

**Comment by myselfmyself** [comment]
Thank you, please keep us posted
________________________________

**Comment by Kryptoxic** [comment]
> We'll take a look at this ASAP.

Thank you for replying. If you would like, you can pick up on my support ticket as well which is ticket 271821

**Comment by myselfmyself** [comment]
still awaiting updates.  have you guys looked into this yet?  Would really like to send my coins off the ledger.
________________________________

**Comment by myselfmyself** [comment]
Please fix so we can access our coins

**Comment by myselfmyself** [comment]
Please offer us a solution.
________________________________

**Comment by myselfmyself** [comment]
Still no updates and no solutions offered.  Problem for over three months now.  Can someone not take the time to look into this for the community?  Please?

**Comment by Kryptoxic** [comment]
> Still no updates and no solutions offered. Problem for over three months now. Can someone not take the time to look into this for the community? Please?

Yeah I tried to send XST after the 1.7.0 and still the same issue. When will ledger resolve this? I want to move my XST asap

**Comment by Kryptoxic** [comment]
Hey @myselfmyself , just wanted to update you on some news that I heard from ledger on their slack. They have done some work on this issue and had a pull request opened.

https://github.com/LedgerHQ/lib-ledger-core/pull/195

Unfortunately, it is still not working for me on 1.7.0 still

**Comment by myselfmyself** [comment]
Thank you.  Hopefully this fixes it once they roll out this solution.
________________________________

**Comment by myselfmyself** [comment]
Has this been resolved yet, or a date estimated for resolution?

**Comment by Kryptoxic** [comment]
I haven't had the chance to try sending XST on 1.8.0 yet, have you tried it @myselfmyself ?

**Comment by myselfmyself** [comment]
I've not, no.  I'll give it a try tomorrow and see if it works.
________________________________

**Comment by gre** [comment]
I don't think 1.8.0 have fixed the situation, we're still looking actively at it, see last statement: https://github.com/LedgerHQ/lib-ledger-core/pull/195#issuecomment-487521141

**Comment by Kryptoxic** [comment]
> I don't think 1.8.0 have fixed the situation, we're still looking actively at it, see last statement: [LedgerHQ/lib-ledger-core#195 (comment)](https://github.com/LedgerHQ/lib-ledger-core/pull/195#issuecomment-487521141)

I see, do you need to get in contact with Stealth's lead dev? I told them about the pull request and the lead dev said that the change has been made a few months ago

**Comment by myselfmyself** [comment]
Can we get an estimated time of completion?

This is starting to feel a bit like a run-around.  :/  Funds frozen for 5 months now and with the Stealth developer already saying they fixed the problem two months ago, that sounds a bit concerning to me that Ledger still has not worked the solution...
________________________________
