### ISSUE TITLE
Display ethereum address

### ISSUE THREAD

**Issue by GregTheGreek** [LedgerHQ/ledger-live-desktop#1835]
- [ x ] I have checked this feature was not yet requested.

Currently you can only see the unique name chosen for a given account (on the left nav). When you click an account from the left nav, it opens the account specific dashboard view. Even on this view you cannot see the associated ethereum address, the only option is to click a existing transaction and view the to/from.

I am requesting that the ethereum address be displayed somewhere on the screen. More than happy to make a contribution myself to add it in.

#### Part of the application

Accounts Dashboard

**Comment by juan-cortes** [comment]
You can see the account's address by following the Receive flow for thay account, ensuring the authenticity and validity of the address displayed by confirming on the device.

https://support.ledger.com/hc/en-us/articles/360006444193-Receive-crypto-assets

**Comment by GregTheGreek** [comment]
That doesn't solve the problem because you need to have the device connected. There should be a quick view of the ethereum address.

For example, in `ledger-live-desktop/src/components/AccountPage/AccountHeader.js` it would be convenient to have something like:

Note: I went through your commons repo as well as most of this repo. I know `account` object doesn't actually store the address, so it won't be as straight forward as below, but simply inserting it below the account.name would be great..

```
class AccountHeader extends PureComponent<Props> {
  render() {
    const { account } = this.props
    return (
      <Box horizontal align="center" flow={2} grow>
        <Box color={account.currency.color}>
          <CryptoCurrencyIcon currency={account.currency} size={24} />
        </Box>
        <Box grow>
          <CurName>{account.currency.name}</CurName>
          <AccountName>
            <Ellipsis>{account.name}</Ellipsis>
          </AccountName>
          <curName>{account.address}</CurnName>
        </Box>
      </Box>
    )
  }
}
```

**Comment by gre** [comment]
You want to display the address for which purpose? To identify the account visually or to actually use the address somewhere?

For the first reason, for now you could rename your account to something else.
For the second reason, the Receive flow is the way to go and we want users to go through the secure way. NB you don't need the device to see the address, you can say you don't have the device in the receive flow.

The device being the source of trust, the UI has been build in that way.
The risk of displaying directly the address on the account is that many users could start using that with copy and paste, and won't verify it on-device.

**Comment by GregTheGreek** [comment]
I wasn't aware of the `dont have device` option...

I guess that will have to work for now

**Comment by GregTheGreek** [comment]
The main reason is to visually identify

**Comment by fuorissimo** [comment]
I have the same request. I need to see on each app, my default, my public key. I've already risked more times than I'm wrong
