### ISSUE TITLE
Digi-ID for authenticating with Ledger

### ISSUE THREAD

**Issue by ChillingSilence** [LedgerHQ/ledger-live-desktop#1836]
#### Proposal:
Use Digi-ID by DigiByte as an option to authenticate with, instead of a password
This can be used for the encryption of the data just as the password is currently.

#### Part of the application:
Login / authentication time

#### Impact:
Using a password is generally considered the most simple and insecure method of authentication. Digi-ID by DigiByte is able to be used as either a compliment or a replacement for secure 2FA authentication, and would be an ideal "drop-in" solution for the authentication screen
![ledger-login](https://user-images.githubusercontent.com/162461/53452320-da5b7900-3a85-11e9-9c2a-a2255cceb401.jpg)

Instead, I would suggest implementing Digi-ID support to be used, optionally, in-place of a password, or to compliment it as a second-factor for additional security.

Digi-ID is far more secure than plain passwords, or TOTP. Given many Ledger users will also likely have the likes of the DigiByte app on their Android / iOS device, or Coinomi also is supported as an authenticator too. There is a broad user-base who would no doubt appreciate the additional security and ease-of-use here, coupled with the fact there is nothing the end-user then needs to remember, especially given there is no "reset password" functionality (The user must delete / re-setup which is time-consuming).

The DigiByte team would be happy to provide guidance / assistance on the implementation should the Ledger team have any questions.

This was previously suggested under #1048 however it appears it was not explained well enough, nor was it's purpose / functionality understood by the person closing the issue.

**Comment by Fingyz** [comment]
I would love to see the implementation of Digi-ID into the Ledger Live platform. A Digi-ID login option would be a huge security benefit and the ease of use would greatly enhance your end users experience.
