### ISSUE TITLE
Bech32 Sendability

### ISSUE THREAD

**Issue by nopara73** [LedgerHQ/ledger-live-desktop#1842]
- [x] I have checked this feature was not yet requested.

There is a similar issue open (https://github.com/LedgerHQ/ledger-live-desktop/issues/1051), but that is about Bech32 integration, this feature request is about Bech32 sendability, which is a simple non-controversial request.

#### Part of the application

Address parsing.

#### Reward

I'd like to also offer ~0.1BTC reward, which will be a Wasabi coinjoin output to whoever implements it here and get his implementation merged.

**Comment by 2pac1** [comment]
This is needed.
Why is Ledger slacking instead of pushing the bar?

**Comment by nopara73** [comment]
This is awesome @gre! I'd like to pay out the bounty. Could you email me with an address? adam.ficsor73@gmail.com

If you prefer PGP: https://github.com/zkSNACKs/WalletWasabi/blob/master/PGP.txt

**Comment by nopara73** [comment]
The bounty has been paid out: https://www.smartbit.com.au/tx/9d313ff6cd0d7a2c5dd98bd06d09ec97f17f36271ad826cd50a872f7973cb072
