### ISSUE TITLE
getVarint called with unexpected parameters - Stealth, XST - problem for three months now

### ISSUE THREAD

**Issue by myselfmyself** [LedgerHQ/ledger-live-desktop#1848]
<img width="1021" alt="Screen Shot 2019-03-08 at 3 43 51 PM" src="https://user-images.githubusercontent.com/45702322/54055291-97eb1800-41ba-11e9-8734-8e6144b9cd1e.png">

Still no resolution.  Spoke with Ledger Support 3 months ago.  Still not resolved.  I have a ton of coins sitting here that I cannot transfer.  No solutions whatsoever.  Tried deleting apps, reinstalling, turning on dev mode and adding apps, turning off dev mode and sending, wiping ledger, downloading latest software, etc etc.  Nothing works.

Please resolve this issue.

**Comment by Kryptoxic** [comment]
I have this same issue as well which I opened an issue. It's issue #1824

**Comment by myselfmyself** [comment]
Going on four months now, still no resolution.  Please resolve.

**Comment by myselfmyself** [comment]
Looks like no one is assigned to fix the problem, either.  This will be the last time I support or use Ledger and will ensure I forward all of this to friends and family who are interested in purchasing a product if this is not resolved.  This is getting to be a bit absurd.
