### ISSUE TITLE
Bug: Error calculating fees

### ISSUE THREAD

**Issue by filcardoso** [LedgerHQ/ledger-live-desktop#1849]
Steps to reproduce:

Create account in Ledger Live and sent 0.00010000 from bitcoin wallet. 
After a few moments, and after fees, the amount of 0.00009604 arrived to my Ledger Live wallet.

Then I tried to send back what I received, and got the following:

- after selecting 0.00003900 to send, gives a total to debit of 0.00004126 (fee: 226 sats)

- after selecting 0.00003940 to send, gives a total to debit of 0.00004166 (fee: 226 sats)

- after selecting 0.00003950 to send, gives a total to debit of 0.00009604 (fee: 5654 sats) --> My Full Balance!

The fee is 25x higher just for sending 10 extra sats.
Also, the fees are more than the actual value i'm trying to send.

**Comment by gre** [comment]
Thanks for the issue, we'll try to reproduce on our end and investigate what is wrong.

Can you confirm that you are on Ledger Live 1.5.0 ?

thanks

**Comment by filcardoso** [comment]
just updated, and the problem persists.

Thank you.

**Comment by gre** [comment]
Can you attempt a clear cache after this update? Thanks

**Comment by filcardoso** [comment]
I cleared the cache.(went to settings -> hit Clear -> wait a few seconds -> input my password to login -> and tried again)

The same happened.

I have another account with 0.01298558.

If I insert the amount 0.0129008, the total to debit becomes 0.01290454 (fee 374 sats)

If I put 1 more sat (0.01290081), the total to debit becomes my full balance 0.01298558 (fee 8477 sats)

**Comment by filcardoso** [comment]
Just tried it on the newly released Android app with support to Nano S, and the calculation is exactly the same as I described in the previous posts.

**Comment by gre** [comment]
@filcardoso can you check if the bug is still present on LL 1.7.0? (probably do a clear cache to be sure)

Thanks

**Comment by filcardoso** [comment]
Short answer: Bug is still present.

Long answer:
I cleared the cache (settings -> help -> Clear Cache)

Strange thing happened after. I input the destination address, and the following error appeared in the amount field:  "Account 1, for wallet '<random numbers>_bitcoin_cash': doesn't exist"

I changed account and the other gave me this error, also in the amount field:
"There is no UTXO on this account."

I figured its something to do with clearing the cache.

I hit Clear Cache again, and it stopped happening.

But the original bug calculating the fee is still present.

**Comment by filcardoso** [comment]
Hi @gre !
You closed this a month ago. 
In which version of the app will it be released?
Just tested on Ledger Live 1.12.0 and on Android and the problem persists. 
Thanks.

**Comment by gre** [comment]
mmh the bug was presumably fixed in 1.12.0.
On which currency is it still an issue?

**Comment by filcardoso** [comment]
I tried with bcash
