### ISSUE TITLE
Show more details when sending funds (total to debit = funds to send + fees)

### ISSUE THREAD

**Issue by filcardoso** [LedgerHQ/ledger-live-desktop#1850]
- [x] I have checked this feature was not yet requested.

To improve User Experience, Instead of just showing Total to debit, it should also show:

- how much is being sent
- the fees being applied
- what will remain in the wallet

Something like this:

![change UX](https://user-images.githubusercontent.com/1909093/54089531-b7707500-4361-11e9-88d7-dfe51f7c6e19.png)

#### Part of the application

Send Form

**Comment by gre** [comment]
The UX has been improved since then :)
