### ISSUE TITLE
Wrong Device or Passphrase Error When Attempting to Send/Receive ANY Crypto Asset

### ISSUE THREAD

**Issue by 1jjhollywood** [LedgerHQ/ledger-live-desktop#1851]
#### Ledger Live Version and Operating System

- tested on Ledger Live **version_here**
- Platform and version: **e.g. Mac 10.13.5 / Windows 10 / ..**

**Comment by 1jjhollywood** [comment]
Have the latest firmware (v1.3.7) and Ledger Live (v1.5.0) along with original passphrase. Am on desktop Windows 10 using the desktop version of Ledger Live. Any attempts to SEND or RECEIVE ANY ASSET results in an error reading: 
"Wrong device or passphrase for [whatever asset]...."

![Ledger Nano S Error](https://user-images.githubusercontent.com/28660782/54098907-fcf66780-438c-11e9-86d2-3fbf4b0d65e5.JPG)

I need to be able to access my wallets and crypto assets and am quite concerned. Could you please assist? I have heard others stating they were unable to receive help, some for the same type of issue, and this is quite serious. Thank you most kindly.

**Comment by 1jjhollywood** [comment]
The situation with my Ledger Nano S has now gotten worse in the process of troubleshooting and trying to be able to send. After having restored, uninstalled, reinstalled....I finally cleared the cache and then deleted the ADVANCED LOGS and then....MY DIGIBYTE was GONE!! The Seed Phrase restore did not work either. I saw another person with this same issue, and this is wholly unacceptable. What would cause this behavior? Please help....

**Comment by gre** [comment]
This error means the account you try to send from is not associated with your device seed/passphrase.

Are you sure your device is using the same seed? If you try to import again the account, do you see it being scanned?

**Comment by 1jjhollywood** [comment]
This is the original device and original seed phrase it came with. Could it
possibly be that Digibyte wallet which was holding the assets (which were
there before deleting the Advanced Logs) was a LEGACY wallet, and Ledger
Live appears to not have support for Legacy but only Segwit. All I know is
that I have restored the Ledger a couple times previously using the exact
same seed phrase and never lost assets before. Of course, I also had not
tried sending or receiving for some time, and this whole issue started with
the "Wrong device or passphrase for..." when attempting to send/receive ANY
asset. MADDENING....

**Comment by 1jjhollywood** [comment]
I do not see a way to enter a wallet address, especially as I now have zero assets in the Ledger Nano S. I have a record of at least a couple of the old legacy wallet addresses sent from the Digibyte wallet app to the Ledger over a year ago. Again, the Digibyte was present in my wallet before I simply deleted the Advanced Log files.

**Comment by gre** [comment]
can you send your logs to our tech support at https://support.ledger.com/hc/en-us/requests/new and ping me with a support id? thanks

**Comment by 1jjhollywood** [comment]
I submitted ticket 272513 with the existing log files I now have. Thank you
so much!

**Comment by 1jjhollywood** [comment]
I had put a handful of DGB on a Digibyte wallet just to see if I could add an actual LEGACY wallet or specify an address but I could not do so. So you will see several DGB there now.

**Comment by gre** [comment]
problem has been solved. feel free to contact our tech support for any other problems. thanks

**Comment by LQ84j** [comment]
I'm getting the exact same error when trying to open Decred app on my Ledger Nano S. Please help.
