### ISSUE TITLE
"invalid side for accountid" 

### ISSUE THREAD

**Issue by Transisto** [LedgerHQ/ledger-live-desktop#1864]
![image](https://user-images.githubusercontent.com/388716/54472613-66b5ad80-47a1-11e9-84b6-9598df79ef65.png)

Not clear what should be done.

**Comment by gre** [comment]
How did you reproduce this problem? 

seems error come from https://github.com/LedgerHQ/ledger-live-common/blob/98482fcb1893efc15bc51dc18c3d82da8121a3d7/src/account.js#L185

but i'm really curious how this could ever happen.


I imagine to fix it you will need to remove accounts and import them again from the device.

**Comment by Transisto** [comment]
Updated to latest version and now get this

![image](https://user-images.githubusercontent.com/388716/54472680-d5473b00-47a2-11e9-8c9a-6bedbd7d1768.png)

**Comment by gre** [comment]
Can you try to do a Clear Cache in Settings>Help ?

**Comment by gre** [comment]
I suspect there is a glitch that made the migration scripts not working for you (or maybe you rollbacked to an old version from a new one at some point in time?) and that the data you have are not correctly migrated. 

You might have to Reset and reimport the accounts.
