### ISSUE TITLE
When firmware updating the internal error

### ISSUE THREAD

**Issue by SelenaDior** [LedgerHQ/ledger-live-desktop#1868]
#### Ledger Live Version and Operating System

- tested on Ledger Live **version_here**
**1.6**
- Platform and version: **e.g. Mac 10.13.5 / Windows 10 / ..**
**Windows 10 x64 Ver 1809**
#### Steps to reproduce the behavior

![Capture](https://user-images.githubusercontent.com/10289924/54583079-46b80100-49d0-11e9-8504-11d11751dc40.PNG)

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue.

could you send your logs to our support team and mention this github issue? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏  basically you can press Ctrl+E just after the error occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.netlify.com/logsviewer )

we'll continue the investigation through this support. Thanks.
