### ISSUE TITLE
How to open the 'send modal' by URL Scheme?

### ISSUE THREAD

**Issue by Paulsky** [LedgerHQ/ledger-live-desktop#1893]
- [x] I have checked this feature was not yet requested.

I would like to open the  Ledger Live Desktop (and Mobile) app by URL Scheme and set the values in the 'send' modal. It's kind of this request: https://github.com/LedgerHQ/ledger-live-desktop/issues/1236 . Except I **don't** want to open Ledger Live by a 'standard' URL scheme. I would like to open Ledger Live explicit. I know I can open Ledger Live with ledgerhq:. That's really awesome. But is it possible to open the 'Send' view and set the currency and amount with it? For example like this: 

ledgerhq:?currency=bitcoin&address=1ABCDeFgHiJk4LmNoPQrS4uVWWX12yy3a4&amount=0.001.

 I have checked this file; https://github.com/LedgerHQ/ledger-live-common/blob/master/src/currencies/CurrencyURIScheme.js for the names of the parameters.

For a simple example, please check this CodePen: https://codepen.io/Paulsky/pen/wZwYrp

Thank you in advance!

**Comment by Mvfaassen** [comment]
Hi,

just wanted to ask if there is any update in regards to this issue?
Would like to support the Ledger wallet in full on our platform: coinrequest.io and currently it unfortunately can open the wallet.

**Comment by cthepot-ledger** [comment]
Hi, you can use https://github.com/LedgerHQ/ledger-live-desktop/blob/develop/DEEPLINK.md
