### ISSUE TITLE
Password manager integration

### ISSUE THREAD

**Issue by talkingravens** [LedgerHQ/ledger-live-desktop#1901]
Apart from being a great hardware wallet, I think adding the possibility to be used as a password manager as well would be a very practical idea. Have you discussed integration of such feature in Ledger Live app? 

Thank you

**Comment by gre** [comment]
There is an app called Password that can be installed on the Nano, is that what you are looking for? 

https://steemit.com/security/@jonklinger/how-to-use-the-ledger-nano-as-a-password-manager

**Comment by talkingravens** [comment]
Thank you for your reply. I did not know about that. I will take a look at it.
