### ISSUE TITLE
Wasabi wallet support

### ISSUE THREAD

**Issue by kravens** [LedgerHQ/ledger-live-desktop#1911]
- [ v] I have checked this feature was not yet requested.

Recently Trezor has started to work on support in the privacy oriented Wasabi wallet from zkSNACKs (https://wasabiwallet.io/) and Ledger can’t stay behind in this movement towards a more private Bitcoin network!
#### Part of the application

This feature requires support for bech32 addresses as requested in #1842. Live should allow signing transactions in other wallets as per BIP-174 (https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki) partially signed transactions that should be finalized using the Ledger HW wallets.

**Comment by 2pac1** [comment]
Ledger needs to support wasabi like yesterday.
Why was not this done already?

**Comment by kravens** [comment]
We are actively working on it here: https://github.com/zkSNACKs/WalletWasabi/pull/1341
Already can succesfully load and receive on Bech32 using Wasabi!

**Comment by gre** [comment]
bech32 is supported in `develop` branch using Experimental flag "Experimental Native Segwit"

will be shipped in next release
