### ISSUE TITLE
Internal paths are not resolved consistently due to handling of trialing slashes 

### ISSUE THREAD

**Issue by lmlsna** [LedgerHQ/ledger-live-desktop#1932]
#### Ledger Live Version and Operating System

- tested on Ledger Live **1.7.0**
- Platform and version: **Ubuntu 18.04 amd64**

#### Expected behavior

Paths to a directory should be treated as the same path whether a trailing slash is present or not.

#### Actual behavior

I have 2 different preferences directories inside of `.config/Ledger Live/sqlite`:
- `preferences_v2___ledger_live_desktop__preferences.db`
- `preferences_v2___ledger_live_desktop____preferences__.db`

It appears that the name of this directory is created from several variables, one of which is apparently another path that is converted to a filename by replacing all `/` with `__` in [this bit of code](https://github.com/LedgerHQ/ledger-live-desktop/blob/bf9983632a1d41b342eeff8edf844600a199def5/src/helpers/implement-libcore.js#L175).

This would be fine as long as the directory was normalized before doing this string manipulation. It appears this PathResolver function would resolve `.config`, `.config/`, and any permutation of `.config////` as all different files even though they all reference the same folder.

#### Steps to reproduce the behavior

![Screenshot from 2019-04-12 12-55-40](https://user-images.githubusercontent.com/30895125/56064355-b21e9580-5d26-11e9-9649-6c5c4bd2aad1.png)

I opened once from terminal, once from GUI? Maybe?

**Comment by gre** [comment]
could you try to remove the sqlite folder and see if it happens again? (they are completely restored by Ledger Live from the main app.json data)
