### ISSUE TITLE
past 4 months, no one assigned to resolve the problem, same problem, still, cannot send XST; coins are STUCK on Ledger.  GetVariant called.

### ISSUE THREAD

**Issue by myselfmyself** [LedgerHQ/ledger-live-desktop#1933]
Same issues as before.  Still not resolved after opening two tickets and answering all questions over the last four months.

Can someone please assign a person to resolve this issue?

Coins are stuck.  Would have been safer to leave them on an exchange had I known this would be a problem (and one that would never be corrected).

I will no longer refer anyone to use a Ledger until this is resolved. My funds are essentially frozen.  There is no work-around to retrieve the coins.  Please address this as soon as possible.

"Get Variant called with unexpected parameters."

**Comment by gre** [comment]
https://github.com/LedgerHQ/lib-ledger-core/pull/195

**Comment by myselfmyself** [comment]
How do I implement that?  Or is this something they are working on doing?

**Comment by gre** [comment]
We're waiting this pull request to be merged and then we'll bump that library on our side. I'm not sure what would be the ETA but hopefully soon. Sorry you had to wait that long,.. apparently XST transactions serialisation had breaking changed so that's why it stopped working.

**Comment by myselfmyself** [comment]
Thank you.  Can you update me when the fix is in, please, so I can try again?
________________________________

**Comment by myselfmyself** [comment]
Has this been resolved yet?  or an estimated date for resolution?

**Comment by myselfmyself** [comment]
Still no resolution.  Would really like to access my coins.

Any updates on an ETA?
________________________________

**Comment by gre** [comment]
We're in contact with XST developers and they should get back to us ASAP

**Comment by myselfmyself** [comment]
Thank you.  Please keep us updated and let us know when it's resolved.  I'll follow up again next week.
________________________________

**Comment by myselfmyself** [comment]
Have you heard from the XST devs?  Any word on an update/fix to this problem?  Thank you.
________________________________

**Comment by gre** [comment]
Yes, there will be a fix delivered soon, this needs an update of the XST app as well as an update of LedgerLive.
The optimistic ETA is 2 weeks.

**Comment by myselfmyself** [comment]
Thanks for the response.  I'll reach out again in the coming weeks to see if there's a solution.
________________________________

**Comment by myselfmyself** [comment]
Any updates yet?  Thanks.
________________________________

**Comment by gre** [comment]
a fix will be present in an incoming release but we're investigating on a bug that seems to remain in the XST app so it might gets relayed.

**Comment by myselfmyself** [comment]
Any updates yet?

Going on six months now with frozen funds...
________________________________

**Comment by myselfmyself** [comment]
I heard from the Stealth developers and they said that they've already fixed things on their end and that they're waiting for Ledger to make the update.  Apparently its in ya'lls hands now
________________________________

**Comment by myselfmyself** [comment]
Here's the new problem.

Even if you guys patch a fix, Bittrex won't allow trading in just a few weeks (pretty much the only market to trade XST on).  So then what?  This fix needs to be expedited before Bittrex closes trading for US customers.  :/
