### ISSUE TITLE
Overall graph time period

### ISSUE THREAD

**Issue by gre** [LedgerHQ/ledger-live-desktop#1942]
**Add the ability to go above the year to see longer graphs.**

## Technical notes:

- that means asking more dates to countervalues API. Some changes needed in live-common. For a given currency we can infer the afterDay to use by using the older operation
- if oldest operation of the chart is under 365 days, the graph can fallback on the year mode
- it might be recommended switching to week for the granularity of the graph for performance, the same way we later could use hourly for week mode
- it should fix that old operation uses a wrong countervalue rate

**Comment by spogulis** [comment]
This is so simple yet very needed. Without looking in the code, it probably is not that hard to implement this. How to escalate so that this falls into backlog?

**Comment by gre** [comment]
We are reworking countervalues this summer so this should happen.

**Comment by gre** [comment]
Fixed in 2.29.0
