### ISSUE TITLE
Ungodly sync times

### ISSUE THREAD

**Issue by hito** [LedgerHQ/ledger-live-desktop#1949]
Why does Ledger Live take such an ungodly amount of time to sync, or straight up fail to sync when multiple VINs are being used for coins/tokens using the UTXO transaction system?

**I don't really have time to check the codebase presently or I'd happily contribute** but this app fails on the usability level at so many points:

* Slow sync times.
* Literally no ability to select what address you want to send from _(an account to select from, which is a grouping of addresses, is not acceptable. Selecting a specific address within an account is.)_
* No "send max" button.

I'd assume Ledger is running their own full-nodes that they have exposed via some kind of API instead of using say `btc.com` or whatever to query people's address balances. That's good because Ledger can ensure that those full-nodes are running correctly. What I don't understand is if it takes me say 100ms to query `btc.com` or `anyothercoinexplorer.com` for any coin, BTC, ETH, ZEN, etc why does Ledger take more than some small factor of 100 ms to tell me my address' balance if it's not running a full local node? Surely Ledger's infrastructure (assuming this is how it's done) can handle these requests? If not give us the option to determine balances from other APIs as you do for us choosing which pricing oracle we want to use.

I can query the balance for all my BTC addresses in about 100 ms. Same for ETH. Same for ZEN. Ledger Live takes about 5 minutes to update the balances, and straight up fails for ZEN entirely because of the volume of uncleared UTXOs I have over those addresses.

I don't understand what's going on behind the scenes here but it's a bit silly that the Ledger can have such excellent security, and its companion app Ledger Live can be so horrifically terrible to use.

This app has so much potential to enable good UX for crypto, I am fine with working around these quirks for now but I think others who see the state of this app thus far will either be confused or disappointed that simple features: quick balance checking, sending the max amount, having the freedom to choose where you send from aren't there.

**Comment by gre** [comment]
Let's try to keep one issue per topic please.

- Send Max feature was logged in #905 and is planned for Q2. 
- Ability to select inputs is very interesting idea, let's discuss it in another issue. We'll internally brainstorm on what could be the UI and where are the technical part to work on, no ETA for this but it's typically something we would accept PR from community.

## about the sync


### general overview of architecture & perf challenges

Now, regarding synchronization, it involves many parts, starting from the network:
- full nodes are running in our server and exposed through our "explorers" APIs. There are load balancing and replications challenge there on the infrastructure level, but also potential algorithm performance to improve at the backend level. This is a continuous improvement subject for our infra and backend teams. (maybe @luchenyuxx can comment with more detail.)
- https://github.com/LedgerHQ/lib-ledger-core is our internal C++ library that Ledger Live is using to communicate with explorers. Basically, it's doing all the synchronisation work for accounts, doing the HTTP queries. There are potential things to improve at this level, I've recently discussed with the team to audit more where are our current bottlenecks. (maybe @KhalilBellakrid can comment with more detail.)
- On the frontend level now, there are general UI performance (overall perf can impact the sync perf itself) and sync strategies to improve (when doing the syncs, how triggering them,..). There are also what I call "perceived" performance to improve.

### next build will have better performance

In the next 1.8.0 build, we're going to ship improvements regarding both the overall UI performance (graphs were not optimized) as well as parallelization of the synchronisation: before 1.8.0 we were only doing one account synchronisation at a time, from this incoming 1.8.0 we'll do multiple sync at same time, so if you have multiple accounts, it should be almost as fast as just having one (contrary to before it was linearly slower, ~ proportional to number of accounts).

### in Q2

We're going to ship in Q2 some other features that will improve performance and perceived performance / better visibility of the synchronisation status. For instance, we're soon going to ship an "accounts" screen that will also allow you to see which account is taking time, etc..



Hope it makes sense.

**Comment by hapklaar** [comment]
Just tried 1.8.0 to see if I would be able to add my ZCash account again, but still nothing. It just gets stuck at synchronizing and eventually times out. I see no improvement in sync of other account either if I'm honest...

**Comment by gre** [comment]
Let's unify the issue into https://github.com/LedgerHQ/ledger-live-desktop/issues/1721

**Comment by DatDraggy** [comment]
So, is there any workaround to get Ledger Live syncing again? For me it just doesn't stop syncing. Already tried clearing the cache. I also have quite a few TXs on ZEN because of node rewards.

**Comment by DatDraggy** [comment]
ok using the android app it syncs after 5 seconds of waiting. My Live on the desktop must be bugged then.
