### ISSUE TITLE
ERC20 Token Request 

### ISSUE THREAD

**Issue by twinklevoss** [LedgerHQ/ledger-live-desktop#1959]
Token Name: Gemini dollar
Token Symbol: GUSD
Contract: 0x056Fd409E1d7A124BD7017459dFEa2F387b6d5Cd
Decimals: 2

**Comment by gre** [comment]
yes, it will be part of the ERC20 token supported when we implement ERC20 feature (i've double check and it was already in our list). 

closing the issue, for ERC20 issue, see #970

**Comment by guylando** [comment]
@gre Hi, where is that ERC20 tokens list and how can one submit there additional new tokens?

**Comment by pbennett** [comment]
I have the same ask - I'd like to see the compound protocol tokens added (ie: cDAI) [ideally w/ 'full' support of that contract - which is trivial to show current balance from].
