### ISSUE TITLE
Account - Visual bugs on account page for account having balance with many decimals

### ISSUE THREAD

**Issue by Arnaud97234** [LedgerHQ/ledger-live-desktop#1962]
#### Ledger Live Version and Operating System

- tested on Ledger Live **1.8.0**
- Platform and version: **Mac 10.14**

#### Expected behavior

- Filters value should fit accounts graph pane.
- Account Balance value should fit details pane

#### Actual behavior

Default application window size (smallest) :
Visual bug on Account screen for account's *balance having many decimals* :
-  Filters (Week, Month, Year) exceed graph pane.
![Screenshot 2019-04-30 at 11 44 13](https://user-images.githubusercontent.com/13007150/56955016-8f6ee800-6b40-11e9-8f7f-cae961a27f1a.png)

- Overlaying graph in order to show balance for a specific date : Balance exceeds details block.
![Screenshot 2019-04-30 at 11 44 31](https://user-images.githubusercontent.com/13007150/56955115-c80ec180-6b40-11e9-8977-731e8fc56524.png)

#### Steps to reproduce the behavior
- Select an Account with balance containing many decimals

**Comment by juan-cortes** [comment]
Before we make the community do something blindly, let's agree on a solution. For instance, the tootltip could probably grow to accommodate all the digits, but it can also crop them. As for the title, do we ellipse, what is the desired look, so as to help the one implementing it?

**Comment by gre** [comment]
IMO it's ok to not even have it grow, just `...` is ok because it's obviously insignificant amounts 🤔
same for the title. If you have really extreme case you better change units to make it display correctly, we're not going to fix all crazy cases. e.g. what if I have 10000000 DOGE coin and i chose to display as satoshis.

**Comment by gre** [comment]
Fixed in develop branch. ETA end of May
