### ISSUE TITLE
API HTTP 404 Allow Ledger Manager on your device 

### ISSUE THREAD

**Issue by rocketr0n** [LedgerHQ/ledger-live-desktop#1972]
#### Ledger Live Version and Operating System

- tested on Ledger Live **1.8.0**
- Platform and version: **Windows 10 **

hi guys,

I am not sure if this is a bug or a problem on my device, 

I have a ledger early version, i havent used it in about 1.5 years, its running on v1.2 and 1.0 MCU.

the problem is when i try to access the manager I keep getting a API HTTP 404 error,

anyone know what is wrong ?

thanks
![Capture](https://user-images.githubusercontent.com/20015187/57184788-9ab37200-6eb8-11e9-8f71-75edec82f0bf.PNG)

**Comment by gre** [comment]
Can you try on Ledger Live 1.7.0? Thanks

**Comment by rocketr0n** [comment]
thank you I will try 1.7.0 and report back

**Comment by rocketr0n** [comment]
> Can you try on Ledger Live 1.7.0? Thanks

hi, version 1.7.0 just updates  to  1.8.0 when i run it ?

**Comment by rocketr0n** [comment]
ok I got it working, next question, how can I update this ? I see no option to update?

thanks

**Comment by gre** [comment]
@rocketr0n Upgrade from Nano S 1.2.0 is not supported, please contact our tech support. https://support.ledger.com/hc/en-us/requests/new

**Comment by djameleddin06** [comment]
Hi
The program has been set by the administrator
![error-5](https://user-images.githubusercontent.com/38100523/59196940-52126700-8b90-11e9-907b-79d88cb4497a.png)
