### ISSUE TITLE
Can't reach the skip genuine button

### ISSUE THREAD

**Issue by BlackienBad** [LedgerHQ/ledger-live-desktop#1979]
I can't get in my settings

- tested on Ledger Live 1.8.0
- Platform and version: *Windows 10 64 bit

#### Expected behavior

I got stuck on the update on my ledger, so I tried everything, I got out of ledger live and I can't get in again, when I try to check for genuine device it should skip it after the bootloader is detected
#### Actual behavior

Never actually detect the bootloader so I can't skip it and solve the bug, it really annoying

#### Steps to reproduce the behavior

Get stuck on the bootloader, uninstall ledger live and get where you need to connect to a new device, and then you may get stuck like me
To solve this, you just need a skip button that is not based on the bootloader but on some kind of delay or even always there

![5563b0ee6f3f677ad3ed524376253823](https://user-images.githubusercontent.com/22733639/57526582-120c5a00-732e-11e9-803b-b73be49772e8.png)

**Comment by gre** [comment]
Good catch, in next release we'll get the repair tool accessible from here..

in the meantime, you can do this: 

```
SKIP_ONBOARDING=1 /path/to/Ledger\ Live
```

**Comment by BlackienBad** [comment]
In which file should i put it?
@gre

**Comment by BlackienBad** [comment]
Ok I read the Setup section of read me, so I should clone the code, put that in like getisgenuin command(?) and compile, right?

**Comment by gre** [comment]
you can just run the Ledger Live software with an environment variable. I'm not sure if you are on Windows, Linux, or Mac, but for instance on mac you do:

```
SKIP_ONBOARDING=1 /Applications/Ledger\ Live.app/Contents/MacOS/Ledger\ Live
```

**Comment by BlackienBad** [comment]
![aee6f724c6f67a510064a660aed45068](https://user-images.githubusercontent.com/22733639/57528995-13408580-7334-11e9-82f7-60cb32782d7f.png)
Something like this? @gre

**Comment by BlackienBad** [comment]
![01358da05c4982130323793dbca9d3e0](https://user-images.githubusercontent.com/22733639/57529730-e9885e00-7335-11e9-9b59-f47a9ccd5da8.png)

**Comment by BlackienBad** [comment]
Ok, never mind it actually worked, thank you very much @gre

**Comment by gre** [comment]
ETA of the fix to arrive in prod: end of May. Workaround solution shared above.
You can also attempt to long press for 10s the left button of nanoS before plugging it. That boots the device in bootloader and LedgerLive allows to skip onboarding in that case .

**Comment by mahalamobile** [comment]
Hi, have windows 10 64, home edition, i cant get past the check geniune part too. please help

![ledhger s](https://user-images.githubusercontent.com/7688360/58427498-165fa380-80a0-11e9-9b8a-eaa360ba52de.png)

**Comment by mahalamobile** [comment]
ledger nano s, and desktop ledger live, downladed today off site
