### ISSUE TITLE
Ledger live Ethereum gas limit broken

### ISSUE THREAD

**Issue by OpSecChainFailure** [LedgerHQ/ledger-live-desktop#1981]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.8.0
- Platform and version: Windows 10

#### Expected behavior

To set the proper gas limit while sending an Ethereum transaction.

#### Actual behavior

Gas limit is always **21000** even when changing it, transactions which require a higher gas limit will always time out.

![Gas limit was set to 36000](https://i.imgur.com/7NNvYq8.png)

Gas limit was set to 36000 but ends up as 21000

**Comment by gre** [comment]
mmh good point, i suspect we shipped a bug in 1.8.0 with this & i think https://github.com/LedgerHQ/ledger-live-desktop/pull/1978 will fix it

**Comment by gre** [comment]
ETA of the fix in prod: end of May. Mitigation: use mycrypto or myetherwallet (or LL 1.7.0)
