### ISSUE TITLE
Show cumulative balances for each cryptocurrency

### ISSUE THREAD

**Issue by 12345abcdef** [LedgerHQ/ledger-live-desktop#1983]
It would be very beneficial if there was an easy way to see how much of each cryptocurrency you have assuming you have multiple accounts for each cryptocurrency. 

The Chrome app showed this in the top right corner but currently there's no feature for this on Ledger Live.

**Comment by mightyx** [comment]
I agree, currently the ledger live app lags a lot of common features. Is there any roadmap available?

**Comment by gre** [comment]
As we are reworking the accounts, we are also preparing something to address this, ETA is probably a few weeks/months.
