### ISSUE TITLE
Update ledger nano s does not work after downgrade ledger live to 1.7, stuck on update screen

### ISSUE THREAD

**Issue by dboaro** [LedgerHQ/ledger-live-desktop#1985]
#### Ledger Live Version 1.8 and windows 8

- tested on Ledger Live **ledger live 1.7  AND ledger live 1.8**
- Platform and version: ** Windows 8**

**Comment by voobscout** [comment]
yes, what's going on with that?

**Comment by gre** [comment]
we'll need more detail. Please contact ledger support.

- Ledger Live 1.8.0 is known to not support upgrading from 1.3.1 and that bug is now fixed in our develop branch. we'll get a 1.9.0 by the end of may that fixes it (and also improve the UX)
- Ledger Live 1.7.0 does support upgrading/repairing from 1.3.1 so there is no known problem on our side.

any other problem, if not enough detail / pre-investigation need to go through ledger support. Thanks.

**Comment by dboaro** [comment]
Hi,

<!-- downgrade to ledger live 1.7 and move forward from previously stuck Bootloader screen message on nano S. On Ledger 1.7, it started update process and move from bootloader screen to Update screen on ledger nano S, it got stuck this time on ''update'' message on nano S screen and on ledger live 1.7 it kept stuck on 'connect your device' screen in ''manager'' tab at step 1, loading ''connect and unlock your ledger device'', it doesn't move from there. I than tried up grade to ledger live 1.8 version, stuck in same scenario, ledger live 1.8 in ''manager'' tab, keep on screen ''connect your device'' step 1 ''connect and unlock your ledger device'', I had disconnect and reconnect usb cable on ledger nano S but still showing the message 'update' on screen. Can't move from there.

See picture attached.
![update screen stuck](https://user-images.githubusercontent.com/50568081/57702087-b0046b00-7633-11e9-98a2-87a0ba155383.jpg)

**Comment by dboaro** [comment]
<!-- downgrade to ledger live 1.7 and move forward from previously stuck Bootloader screen message on nano S. On Ledger 1.7, it started update process and move from bootloader screen to Update screen on ledger nano S, it got stuck this time on ''update'' message on nano S screen and on ledger live 1.7 it kept stuck on 'connect your device' screen in ''manager'' tab at step 1, loading ''connect and unlock your ledger device'', it doesn't move from there. I than tried up grade to ledger live 1.8 version, stuck in same scenario, ledger live 1.8 in ''manager'' tab, keep on screen ''connect your device'' step 1 ''connect and unlock your ledger device'', I had disconnect and reconnect usb cable on ledger nano S but still showing the message 'update' on screen. Can't move from there.
![update screen stuck](https://user-images.githubusercontent.com/50568081/57702184-e80bae00-7633-11e9-9427-dfca3606869f.jpg)

**Comment by dboaro** [comment]
hi<!-- downgrade to ledger live 1.7 and move forward from previously stuck Bootloader screen message on nano S. On Ledger 1.7, it started update process and move from bootloader screen to Update screen on ledger nano S, it got stuck this time on ''update'' message on nano S screen and on ledger live 1.7 it kept stuck on 'connect your device' screen in ''manager'' tab at step 1, loading ''connect and unlock your ledger device'', it doesn't move from there. I than tried up grade to ledger live 1.8 version, stuck in same scenario, ledger live 1.8 in ''manager'' tab, keep on screen ''connect your device'' step 1 ''connect and unlock your ledger device'', I had disconnect and reconnect usb cable on ledger nano S but still showing the message 'update' on screen. Can't move from there.
![update screen stuck](https://user-images.githubusercontent.com/50568081/57702257-138e9880-7634-11e9-905a-08b53d572816.jpg)

**Comment by Tracol** [comment]
>Ledger Live 1.8.0 is known to not support upgrading from 1.3.1 and that bug is now fixed in our develop branch. we'll get a 1.9.0 by the end of may that fixes it (and also improve the UX)

@gre i'm still on 1.3.1 on my ledger, should I then wait for 1.9.0 to be shipped to upgrade the firmware ? That way I avoid rolling back on my ledger live version

**Comment by dboaro** [comment]
And what should I do with my stuck update screen Ledger nano S here till there?

My funds are on air, bought this to be on the secure side but left behind! Not felling very well with that Sir!

**Comment by dboaro** [comment]
And what should I do with my stuck Ledger here till there?

My funds are on air, bought this to be on the secure side but left behind!
Not felling very well with that Sir!
*__________________________*

*BOARO, Darlan*

+86 18602143764

**Comment by gre** [comment]
@Tracol we plan to ship a 1.8.1 to address this earlier. Sorry for inconvenience

**Comment by Tracol** [comment]
@gre no worries, I didnt upgrade the firmware and managed to transfer my funds so i'm ok 👍
