### ISSUE TITLE
Update ledger nano s does not work after downgrade ledger live to 1.7, stuck on update screen

### ISSUE THREAD

**Issue by dboaro** [LedgerHQ/ledger-live-desktop#1990]
#### Ledger Live Version 1.8 and windows 8

- tested on Ledger Live **ledger live 1.7  AND ledger live 1.8**
- Platform and version: ** Windows 8**

## Steps to reproduce the behavior--downgrade to ledger live 1.7 and move forward from previously stuck Bootloader screen message on nano S. On Ledger 1.7, it started update process and move from bootloader screen to Update screen on ledger nano S, it got stuck this time on ''update'' message on nano S screen and on ledger live 1.7 it kept stuck on 'connect your device' screen in ''manager'' tab at step 1, loading ''connect and unlock your ledger device'', it doesn't move from there. I than tried up grade to ledger live 1.8 version, stuck in same scenario, ledger live 1.8 in ''manager'' tab, keep on screen ''connect your device'' step 1 ''connect and unlock your ledger device'', I had disconnect and reconnect usb cable on ledger nano S but still showing the message 'update' on screen. Can't move from there.
![update screen stuck](https://user-images.githubusercontent.com/50568081/57725602-ef4ab000-7663-11e9-919b-a0c414491c71.jpg)

**Comment by gre** [comment]
Please go to Settings > Help > Repair in LedgerLive 1.7 

If it doesn't work, please go through ledger support. Thanks
