### ISSUE TITLE
Can't withdraw any crypto - Wrong device or passphrase

### ISSUE THREAD

**Issue by NelsonEU** [LedgerHQ/ledger-live-desktop#1999]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.8.0
- Platform and version: Mac 10.14 

#### Expected behavior

Tried to withdraw some BTC

#### Actual behavior

Error:

Wrong device or passphrase for 'Bitcoin'
Please use the device or passphrase for the selected account

####

I don't know what I can do to fix it... I've always used the same ledger and it was working fine with Chrome Apps. This is the first time I try to withdraw with Ledger Live.

Thanks for your help !

**Comment by NelsonEU** [comment]
I think this BTC account was created with a previous passphrase (I reset it since then, but I still have the old one accessible).

What can I do to use this account with the new passphrase ? Or is there another solution ?

**Comment by gre** [comment]
You need to unlock the device with the same seed/password than this account to being able to verify address on device / send transaction.
