### ISSUE TITLE
Empty balance on another computer

### ISSUE THREAD

**Issue by NelsonEU** [LedgerHQ/ledger-live-desktop#2000]
Hi everyone !

#### Ledger Live Version and Operating System

- tested on Ledger Live 1.8.0
- Platform and version: Mac 10.14

#### Expected behavior

Computer 1: I downloaded Ledger Live, and deposit a few BTC on it
Computer 2: I download Ledger Live, I should see my BTC balance

#### Actual behavior

Computer 1: I downloaded Ledger Live, and deposit a few BTC on it
Computer 2: Same, but I can't see my account. If I had one, it has an empty balance

What should I do to be able to access my account from computer 2 ? I have to give back computer 1 tomorrow so it's very frustrating... 

Thanks a lot for your help, I'm a bit desperate here...

**Comment by gre** [comment]
are you using the same device / same seed on the two computers?

**Comment by NelsonEU** [comment]
I am using the same device. Not quite sure about seed... What is the seed ?

Please excuse my incompetence, it's all very new to me.

**Comment by gre** [comment]
if you import account on computer 1 and 2 with a same device, on both side you should have the same accounts (accounts are associated to a seed, the 24 words). If it's not the case that's a bug and we would like to know the detail. Please also contact our ledger support that can provide more help / will ask questions to have more detail for us to investigate.

Thanks
