### ISSUE TITLE
Custom fee with Segwit addresses still wrong

### ISSUE THREAD

**Issue by rdbr** [LedgerHQ/ledger-live-desktop#2001]
When using Segwit addresses and using a custom fee, Ledger Live still calculates the wrong fee to use and doesn't compensate for the discount. A month ago I posted my findings in #1714 but it didn't get picked up.

The mempool is getting filled, so it's important to accurately send transactions with the correct fee. You want to set the fee to the correct `sat/vB` without overpaying when using a site like https://jochen-hoenicke.de/queue to find out the best fee

**Comment by gre** [comment]
@KhalilBellakrid are you aware of this issue? Thanks

**Comment by rdbr** [comment]
I have fixed it in my pull request: https://github.com/LedgerHQ/lib-ledger-core/pull/240

The `estimateSize` calculation was wrong and everyone who uses SegWit with Ledger Live has been paying too much for transactions. Maybe this will clear up the mempool :wink:

**Comment by gre** [comment]
that's awesome! btw do you know if it would covers native segwit too? :) cheers

**Comment by rdbr** [comment]
The estimation function uses constants to derive the size of segwit and non-segwit transactions. The original code doesn't really explain all of the constants, but it doesn't cover native segwit with a special case. I didn't change the constants, but fixed the calculation.

As I stated in my pull-request, I think the constants should be re-evaluated and tested against real transactions of the types, because the max-estimate might be too low.

**Comment by rdbr** [comment]
The pull request got merged and Native Segwit was added:
https://github.com/LedgerHQ/lib-ledger-core/pull/240
https://github.com/LedgerHQ/lib-ledger-core/pull/246

Whenever the develop branch gets merged to master, it should be fixed
