### ISSUE TITLE
Firmware update instructions are incorrect.

### ISSUE THREAD

**Issue by MicahZoltu** [LedgerHQ/ledger-live-desktop#2016]
#### Ledger Live Version and Operating System
Windows 10

#### Expected behavior
When doing a Ledger Firmware update, the on-screen instructions are correct.

#### Actual behavior
![image](https://user-images.githubusercontent.com/886059/58228669-02473980-7d62-11e9-8a35-1da617baff37.png)
In reality, I needed to hold the button down until the `Bootloader` screen appeared.  If you hold down the button waiting for a `Processing` screen, you will be waiting forever and nothing will happen until you release the button.

#### Steps to reproduce the behavior
Update ledger Firmware with Ledger live and try to follow the on-screen instructions.

**Comment by gre** [comment]
Good catch, this is already fixed in our develop branch, will be shipped in the 1.9.1 that we should prerelease today and release next week.

thanks
