### ISSUE TITLE
Feature Request: Be able to change ethereum network from mainnet to ropsten/rinkeby/others

### ISSUE THREAD

**Issue by guylando** [LedgerHQ/ledger-live-desktop#2021]
Correct me if I am wrong but it seems right now that ledger live only works in ethereum mainnet. Would be useful for testing the ledger to be able to perform tests with ledger live on testnets such as ropsten. Most if not all popular wallets allow to change network.

**Comment by gre** [comment]
Yes. Ethereum currency will use mainnet. To allow this feature, we will have another currency that will be available after you go to *Settings > Experimental* and check **Developer Mode**. 

At the moment, only Bitcoin Testnet is available. In a near future, we'll allow to have `Ethereum Ropsten` in that list so you can import your accounts as well. **ETA ~ 1 month.**

We want to clearly split it at the currency level to avoid confusions (Ethereum currency in Ledger Live intrinsically means mainnet, other network can be delivered by introducing another currency choice).

We plan to have Ropsten and we do not plan yet to have other testnets, but it could still happen in the future (but it means the backend & infra have a server ready)

**Comment by guylando** [comment]
Thanks for the information!

**Comment by drptbl** [comment]
@gre Hey, is this feature available? I have developer mode enabled but can't see any ETH testnet apps available for install.
