### ISSUE TITLE
total balance 0

### ISSUE THREAD

**Issue by dawids85** [LedgerHQ/ledger-live-desktop#2022]
#### Ledger Live Version and Operating System

- tested on Ledger Live **version_here**
- Platform and version: **e.g. Mac 10.13.5 / Windows 10 / ..**

**Comment by dawids85** [comment]
i have a problem with 1.8.1 
one time i have a normal balance. in another time i have 0 balance
what is going on ?

**Comment by gre** [comment]
This is likely related to one of the Rate Provider that is set either in General or in one of the Currencies settings of your app. You can try another settings to fix the issue. In the future we aim to ship something similar to #1875 to make it easier to see what is wrong.

GitHub issue will need more detail, please contact our tech support.
