### ISSUE TITLE
Loading apps not working in Ledger Live

### ISSUE THREAD

**Issue by GreyWalz** [LedgerHQ/ledger-live-desktop#2023]
#### Ledger Live Version and Operating System

- tested on Ledger Live **version_here**
- Platform and version: **e.g. Mac 10.13.5 / Windows 10 / ..**

**Comment by GreyWalz** [comment]
logged into Manager on Ledger live, the apps wont load... just spinning wheels, 2 days in a row?????

**Comment by GreyWalz** [comment]
keeps saying my internet is not connected and its CONNECTED !!

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue.

could you send your logs to our support team and mention this github issue? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏  basically you can press Ctrl+E just after the error occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.netlify.com/logsviewer )

**Comment by GreyWalz** [comment]
Hi I pressed control E after the error occurred and saved the jsn log, but I went in there to look at it and I cant open it????

**Comment by GreyWalz** [comment]
I wouldn’t have a clue how to do what your asking.. I pressed Control E and saved it., but then it said the file was corrupted would not open.. so I clicked on the other link you sent and it came up, but I have no idea how to get that to you, I cant save it???
