### ISSUE TITLE
View Transaction History/Currently Stored Amount of Currency on Nano X

### ISSUE THREAD

**Issue by DeepSeaDelight** [LedgerHQ/ledger-live-desktop#2024]
- [☑️] I have checked this feature was not yet requested.

It would be a nice feature to show the currently stored amount of any given currency on the device and perhaps view the last 10 transactions performed on the device, if possible.

#### Part of the application

Upon first entering into an app, the amount stored could be shown initially, along with the standard "Application is ready" message.

Another option could be added to "Show Transaction History".

**Comment by gre** [comment]
Thanks for the feature request.

mmh, I don't see how this can technically works, the Nano does not access the the blockchain data so can't trustfully display any amount/transactions. It's only a mean to derive address and sign transactions.

So I would say it's out of scope of what the device solves (also out of scope of Ledger Live itself).
