### ISSUE TITLE
"Add Account" to Ignore Specific Accounts?

### ISSUE THREAD

**Issue by Dviros** [LedgerHQ/ledger-live-desktop#2028]
Hi!
As part of my investigation process, I need to create an account per activity.
Is it possible to create a "one time wallet"  \ ignore specific accounts and not import them in the future?

Thanks again for all your hard work.
Dvir

**Comment by gre** [comment]
You can uncheck what you don't want to import?

**Comment by Dviros** [comment]
Hey @gre ,
That's correct, however I'm suggesting something else - hiding the account (can be a local setting, not something on the API side) from the list.
