### ISSUE TITLE
Ledger Live - Not Responding (after leaving open for an extended period of time)

### ISSUE THREAD

**Issue by Urgo** [LedgerHQ/ledger-live-desktop#2034]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.9.1 to 1.15.0
- Platform and version: Windows 10

#### Expected behavior

Open Ledger Live and leave it running for several hours while doing other things.  Come back to it and it should still work just fine.

#### Actual behavior

The issue that I am getting is after leaving the app running for an extended period of time and coming back to it Ledger Live is in a hung state and windows reports it is "Not Responding".  The only option is to force close it and try again.

Not sure if it is related to this or not, but in 1.8.0 the following was announced in the release notes "Blockchain synchronization now has parallelization, syncing multiple accounts at once."

Thinking this may have something to do with it? Or could be unrelated.

#### Steps to reproduce the behavior

- Open up any version of Ledger Live from 1.8.0 to 1.15.0
- Type password to log in
- Leave the app running in the background and use pc for a couple of hours
- Come back to Ledger Live and it looks like the screen shot below.

![Ledger Live (Not Responding) 2019-05-29 01 11 08](https://user-images.githubusercontent.com/911614/58531218-9294dc80-81af-11e9-9979-72f99a310873.png)

In attempt to troubleshoot I have used the "clear cache" option, but have not reset ledger live.

**Comment by Urgo** [comment]
Sometimes doesn't even have to be several hours.  In the time it took me to look in the settings/help menu to see what "clear cache" and "reset ledger live" were called it went into a "not responding" state again.

**Comment by gre** [comment]
what's your CPU/ram memory?

could you look at Windows task manager to see which process is blocked during this time (and provide a screenshot? so we can see the cpu usages/ memory)

How many accounts do you have added / is there a lot of transactions?

thanks

**Comment by Urgo** [comment]
Running this on a dual xeon e5-2697 v2 @ 2.6ghz w/ 64gb of ram. CPU usage right now is 6% and memory is 41% and Ledger Live is not responding again (after leaving it up for 10 minutes maybe?)

I have 9 accounts in ledger live (2xbtc, eth, bch, etc, zec, zen, ltc, and kmd) and around 200 transactions between them.

![image](https://user-images.githubusercontent.com/911614/58743275-5d30fe80-83fc-11e9-8d79-4aa0f295d5f5.png)

**Comment by gre** [comment]
did you turn your computer in sleep mode during that time?

**Comment by Urgo** [comment]
My computer is on 24/7, never goes into sleep mode

**Comment by Gentoshi** [comment]
I'm also running into this same issue.

**Comment by Urgo** [comment]
I can replicate this every single time I use the application too. Sometimes it might be just a couple minutes, sometimes its much longer, but if I leave it open long enough it always going into the "not responding" state.

Is it safe to revert to a version older then 1.8.0 (without needing to reset up everything in the app) so that I can test if it still happens with that?  From my experience it was version 1.8.0 that introduced this bug.

**Comment by gre** [comment]
reverting to 1.8.0 should work with the same data set.

**Comment by Urgo** [comment]
> reverting to 1.8.0 should work with the same data set.

1.8.0 was when the issue started. Would need to revert to 1.7.0. Would that be safe?

**Comment by gre** [comment]
I think so. I can't guarantee reverting still works but what's sure is you can always restore your accounts with the device.

**Comment by JReming85** [comment]
I figured out my issue with this...

App would freeze as soon as I would open it... 1/4 of the ledger process would not respond and nothing in Microsoft's DebugDiag.

I reset my ledger live twice now, first time it froze after I was getting ready to add a ETH account, got to the point of import but decided not to, hit cancel and next thing I know it froze.

Installed 1.7, reset live data and re added minus ETH and its working like a charm

**Comment by Urgo** [comment]
Just wanted to update that I never did do the roll back.  I still keep upgrading to the newer versions hoping it will fix this, but still freezes up after being loaded for a while as of version 1.14.0

**Comment by kwaichangdave** [comment]
Has anyone solved this problem yet with ledger live not responding after a few hours or less in windows 10?

**Comment by Urgo** [comment]
> Has anyone solved this problem yet with ledger live not responding after a few hours or less in windows 10?

I'm still experiencing the issue as of version 1.15.0

**Comment by kwaichangdave** [comment]
I may have discovered a fix for this issue. In my version 1.15.0, I went to settings and clicked on experimental features. I then scrolled down to experimental USB and enabled this feature. It states: "Alternative USB implementation that might help solve USB issues". My desktop-live app has been open for 24 hours with no issues for the first time in several months.

**Comment by gre** [comment]
@kwaichangdave thanks a lot. that information is very valuable to us and we will invite more users to test this approach.

**Comment by JReming85** [comment]
@kwaichangdave I used to use that so my nano would get past the first check, but after awhile it started always failing the second check (app open check).

If you start having problems, you may want to see if thats an issue for you.

**Comment by kwaichangdave** [comment]
> I may have discovered a fix for this issue. In my version 1.15.0, I went to settings and clicked on experimental features. I then scrolled down to experimental USB and enabled this feature. It states: "Alternative USB implementation that might help solve USB issues". My desktop-live app has been open for 24 hours with no issues for the first time in several months.

At about 30 hours into the test, live-desktop froze up once again. Back to the drawing board.

**Comment by Urgo** [comment]
I tried enabling "Experimental USB" as well. No dice.  Still freezes up.

**Comment by JReming85** [comment]
If it helps, I am looking at all the crash/hang reports and this comes up as the “fault module”

 

```4d9259be-1a29-429e-9ac2-59a1e72d0e33.tmp.node```

 

With 1 of 2 exception codes (in order of times occurred)

1 - 0xc0000005 - Access Violation

2 - 0xc000041d - An unhandled exception was encountered during a user callback.

**Comment by Urgo** [comment]
I don't want to jinx it but 1.19.2 might have finally solved this issue for me.  Will update again but its been open for the longest its been in a very long time without crashing.

**Comment by Urgo** [comment]
It seems like while this isn't 100% fixed, it is 99% fixed for me at least now.  It's been 7 days since I've been leaving Ledger Live open 24/7 and typically around 1-2 days it does freeze up but since this was happening after minutes or hours previously I'll consider this a major improvement and even good enough for me at least.

@Gentoshi @kwaichangdave @JReming85  are things improved for you as well or did I just get lucky?

**Comment by gre** [comment]
We expect this to be fixed in context of a big rework that just got merged. we'll reopen in this does not fix in the next release #2596
