### ISSUE TITLE
More consistent cursors throughout the app

### ISSUE THREAD

**Issue by juan-cortes** [LedgerHQ/ledger-live-desktop#2035]
Reviving https://github.com/LedgerHQ/ledger-live-desktop/issues/1468 we need to revisit all the ctas and make sure they are consistent. At this point I don't know if a cta is supposed to use pointer or not. It's pretty bad right now:

- Accounts screen, cards use pointer
- Portfolio screen, rows use arrow
- Settings button, arrow
- Dismiss a banner?, pointer
- Sidemenu items, arrow
- External links, pointer
- Period tabs, pointer
- Dropdown, arrow
- Checkboxes, pointer

etc

Annoying but low priority. First, agree on what we should use, then maybe someone (or me) can tackle it. Please (ノಥ,_｣ಥ)ノ彡┻━┻

**Comment by meriadec** [comment]
revival of https://github.com/LedgerHQ/ledger-live-desktop/issues/1468 ? :smile:

**Comment by josokinas** [comment]
Was the [Electron issue](https://github.com/LedgerHQ/ledger-live-desktop/issues/901) fixed though?
