### ISSUE TITLE
Application window doesn't work correctly with 2 monitors.

### ISSUE THREAD

**Issue by seleniumforest** [LedgerHQ/ledger-live-desktop#2037]
#### Ledger Live Version and Operating System

win 10 pro 1803, ledger live 1.8.1

#### Expected behavior

Application should be on active monitor when 2nd is disabled

#### Actual behavior

Application expands to inactive monitor

#### Steps to reproduce the behavior

1. Open Ledger live, move window on the 2nd monitor.
2. Click minimize window
3. Press win + p and choose "PC Screen only"
4. Try to expand ledger live from taskbar

this doesn't work with other apps, only with ledger live

**Comment by gre** [comment]
this is related to the OS, nothing we can do
