### ISSUE TITLE
Ledger Live 1.9.1 and Binance Chain App

### ISSUE THREAD

**Issue by osse2** [LedgerHQ/ledger-live-desktop#2039]
Hello,

I just updated the Ledger Live Version to 1.9.1. I use Windows 10/64 with Ledger Nano X, latest Firmware.
Now I cant find the Binance Chain App in the Manager anymore (Developer Mode is enabled).
I wonder if you guys have the same problem?

**Comment by gre** [comment]
Binance Chain App is not available yet for the Nano X. Should be soon.
