### ISSUE TITLE
AUTOMATIC APP INSTALLATION AFTER SEED USE

### ISSUE THREAD

**Issue by fuorissimo** [LedgerHQ/ledger-live-desktop#2044]
Suppose that i donate my Nano S, with SEED, after my dead.
Suppose also that Nano S is damaged, and who received my donation, need to use SEED on a new hardwallet.

Problem: who received seed, can't know wich type of cryto i have and so, can't know wich app install. The risk to lost some crypto, is very very high.

The solution is to add a feature that after insert seed on Nano, are installed by default on live desktop/hardware, all app that own crypto.

Please consider some solutions about this. I have donate my ledger to my sons.

regards

**Comment by gre** [comment]
Please contact ledger support, questions are beyond Ledger Live github project.

https://support.ledger.com/hc/en-us

**Comment by fuorissimo** [comment]
It's about Ledger Live, because the only way to have APP installed, after SEED use, is by Ledger Live. Only Ledger Live, can check crypto stored on SEED and so, install APP necessary.

I think is a really important thing, because in this way, all user, after SEED use, are ready to go, just after start Ledger Live.

Thanks
