### ISSUE TITLE
MEW DON'T WORK ON NANO X

### ISSUE THREAD

**Issue by fuorissimo** [LedgerHQ/ledger-live-desktop#2045]
![Cattura di schermata (1044)](https://user-images.githubusercontent.com/35644089/58754514-17df0080-84d2-11e9-9c42-e6354c9b3c1f.png)

NANO X don't work on MEW, using FIREFOX, CHROME, OPERA.
NANO S work fine.

Some issue occur on Nano X connect to MEW

IMPORTANT - Please add ERC20 ON LIVE DESKTOP. Is really important.

**Comment by Zizaerion** [comment]
I was able to log in successfully on a ledger nano x using chrome and brave browsers fully updated.  Operating system is windows 10 1903.  you have to have the eth app open before you select the device.  eth app version is also 1.2.7.  I believe they are working on integrating erc20 into ledger live currently and hopefully it'll be released soon.  I'd also recommend using the mycrypto desktop app for managing ETH and erc20 in the meantime.

**Comment by fuorissimo** [comment]
I use Windows 8.1 and Nano X on CHROME, FIREFOX, OPERA, on MEW, DON'T WORK. 
With the same configuration, NANO S, work (only on Chrome).

Without erc20 native managing, for me, Ledger, is very poor because i habe about 10 erc20 token

**Comment by gre** [comment]
not related to ledger-live-desktop.

see https://github.com/LedgerHQ/ledgerjs/issues/306
