### ISSUE TITLE
SYNC APP ON DIFFERENT LEDGER 

### ISSUE THREAD

**Issue by fuorissimo** [LedgerHQ/ledger-live-desktop#2046]
Hello, i use two LEDGER.

NANO X on my hands
NANO S kackup (with seed) of Nano x and kept in a bank safe with seed
NANO S will be donate, when i die
At today, both have same app installed

Suppose that on NANO X i add/remove app, who receive in donation Nano S, how can have it upgraded, with same app?

The way are two:
- using SEED (as i request in another issue), that import ALL app with crypto inside, in automatic
- connecting Nano S to a  new Live desktop installation, that  (as i request in another issue) check all crypto owned and syncronize Live Desktop and Nano S, importing missing app on both

In this way, Nano X in my hands, will be sincronize to my NANO S (and all other with my seed)

Without these features, who receive in donation seed or Nano backup hardware, lost many crypto

**Comment by gre** [comment]
Please contact ledger support, questions are beyond Ledger Live github project.

https://support.ledger.com/hc/en-us

**Comment by fuorissimo** [comment]
Actually I think it's about Ledger Live, because the only way to have different, synchronized devices is by going from Ledger Live

**Comment by fuorissimo** [comment]
> 
> 
> Please contact ledger support, questions are beyond Ledger Live github project.
> 
> https://support.ledger.com/hc/en-us

Actually I think it's about Ledger Live, because the only way to have different, synchronized devices is by going from Ledger Live
