### ISSUE TITLE
Question about Ledger Live and supported assets

### ISSUE THREAD

**Issue by clintnetwork** [LedgerHQ/ledger-live-desktop#2074]
Hi,

Sorry to throw an issue for my question, but I think its an important point, ledger support an increbile numbers of assets but ledger support only 15/20 coins, why this is also disproportionate ?

And do you do something to increase the number of supported assets ?

(and where its possible to fund the future ledger live token's implementation ?)

Thank you !

**Comment by MortalKastor** [comment]
As you can see in #2057 ERC20 token support is in the work and will bring a lot of new assets to Ledger Live.

> Sorry to throw an issue for my question

Github is not the right place for general questions, but Reddit, Twitter, Facebook or our support team are.
