### ISSUE TITLE
No Aeternity account when I want to add AE's account

### ISSUE THREAD

**Issue by TomaszWaszczyk** [LedgerHQ/ledger-live-desktop#2079]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.5.5
- Platform and version: Ubuntu 18.04

#### Expected behavior

I want to be able to add AE account

#### Actual behavior

Lack of AE account

**Comment by gre** [comment]
Aeternity is not supported by Ledger Live yet. you need to use a third party app at the moment https://support.ledger.com/hc/en-us/articles/360013043413-Aeternity-AE-

Please follow #1560 for updates on what will be the process.
