### ISSUE TITLE
Ledger Nano X adding accounts don't pass the unlock

### ISSUE THREAD

**Issue by clintnetwork** [LedgerHQ/ledger-live-desktop#2085]
Hi,

I received the new ledger nano X today and i try to add some accounts in ledger live (I reset all ledger live data before) and sometimes, some coins dont works, I try to exit the coin application, so the check passed, but after i go in the application and the check go back.

So I cannot create some accounts :/

![image](https://user-images.githubusercontent.com/5221349/59455183-f0622f00-8e13-11e9-9c45-a019581afde8.png)

Thank you

**Comment by gre** [comment]
can you try to Ctrl+R on the live but stay on the DGB app on the device?
We're aware of a bug on Windows (on the usb detection) and working on fixing it.

**Comment by clintnetwork** [comment]
Okey so it works with Ctrl+R, but it's very borring to add a lots of accounts, I hope you will fix this bug quickly.

I close because you know the bug
