### ISSUE TITLE
Cannot send XST (Stealth) from Ledger.  Six months now.

### ISSUE THREAD

**Issue by myselfmyself** [LedgerHQ/ledger-live-desktop#2088]
Guess I'll continue posting this issue until it's resolved.

Still not resolved.  First presented the problem at the end of December 2018.  

No resolution from Ledger Support.  No resolution from Tweeting.

XST developers have already replied to me and said they repaired the issue on their end and they're waiting on Ledger to implement.

**Comment by gre** [comment]
Please stick to the issue #1933 
Fix is getting worked on.
