### ISSUE TITLE
XRP: sending transfer with a memo

### ISSUE THREAD

**Issue by ihomp** [LedgerHQ/ledger-live-desktop#2095]
- [x] I have checked this feature was not yet requested.

In XRP any transaction can have a set of memos attached.
In xrp community it's got very popular to send memos with transactions.

specs are here:
https://xrpl.org/rippleapi-reference.html#transaction-memos

Apps like xrptipbot, bithomp-tools or hardware wallet Secalot supporting sending transaction with memos.

It's just an extra parameter in transaction json. it should be easy to add.
Support for only plain/text memos would be a good start.

#### Part of the application

Ledger Live: sending XRP. 
JS lib: allow to sign transactions with memos in them.

**Comment by adelineu** [comment]
@ihomp It seems the feature is already implemented. The only problem is that the _Tag_ field doesn't show up. If you try to use the tab key to navigate between fields it's going to show up at the bottom (_seems to be just a UI problem_). credit: [found it here](https://www.reddit.com/r/Ripple/comments/ay7csl/sending_xrp_to_binance_with_ledger_live_no_tag/)

**Comment by gre** [comment]
no, the tag is not the same as the memo.

destination tag is used in XRP protocol as complementary to the recipient.

**Comment by cthepot-ledger** [comment]
https://github.com/LedgerHQ/ledger-live-desktop/pull/3170
