### ISSUE TITLE
"Wrong device or passphrase error" using Live with Ledger Nano S

### ISSUE THREAD

**Issue by 8red8** [LedgerHQ/ledger-live-desktop#2104]
I'm using Windows 10. I updated to Ledger Live 1.8.1 & the firmware Secure Element 1.5.5 & MCU 1.7. Whenever I try to send coins, I get this error message "Wrong device or passphrase error". Any suggestions?

#### Ledger Live Version

- Ledger Live **version_here**

**Comment by gre** [comment]
Please reach to Ledger support if it still happens.
