### ISSUE TITLE
Address verification on Ledger Nano S

### ISSUE THREAD

**Issue by ibiscp** [LedgerHQ/ledger-live-desktop#2107]
The addresses are too big for Ledger Nano S screen, and the speed is also too fast.

I saw that for some cryptos it shows only the beginning and the end, omitting the middle part, what makes it much simpler and user friendly. Isn't it possible to do it for all of them? And what are the risks of it?

Another idea would be to navigate through the address using the buttons and confirm it pressing both at the same time, or even some kind of 'checksum' of the address on the device and Ledger Live and simplify it to only 6 digits for example.

What do you think?

**Comment by gre** [comment]
This is not something LedgerLive can fix. Please raise this to our tech support.
The nanoS have a small screen and that's probably the current trade-off, NanoX have a bigger screen and allow to show everything.
