### ISSUE TITLE
Rate provider pricing is inaccurate

### ISSUE THREAD

**Issue by OpSecChainFailure** [LedgerHQ/ledger-live-desktop#2122]
#### Ledger Live Version and Operating System
Ledger Live 1.10.0

- tested on Ledger Live Windows 10

**Rate provider pricing is inaccurate:**
Doesn't matter which exchange you select all data is wrong. 

Selected in this case: "Bitstamp Ltd."
![KanaUndetectedKebabs](https://user-images.githubusercontent.com/1304367/59957971-a32f2e80-949f-11e9-8d67-374dfe0e7e9c.png)

Actual prices as we speak:
![SubjectivePassingsUnpin](https://user-images.githubusercontent.com/1304367/59957989-e8ebf700-949f-11e9-82e4-030f1fafcc22.png)

Used to work just fine before.

**Comment by gre** [comment]
Backend issue. Fixed now. We're looking at better stability for the future.
