### ISSUE TITLE
LEDGER LIVE - Crypto price, wrong

### ISSUE THREAD

**Issue by fuorissimo** [LedgerHQ/ledger-live-desktop#2123]
Hi, it looks like the prices are not updated over the weekend
![Cattura di schermata (1104)](https://user-images.githubusercontent.com/35644089/59966808-bedb1900-9521-11e9-9a86-5e83be6f13d5.png)

**Comment by gre** [comment]
https://status.ledger.com/
https://twitter.com/Ledger/status/1142465433351708673?s=19

**Comment by fuorissimo** [comment]
Thank you so much
