### ISSUE TITLE
Add a warning when rate providers send wrong data

### ISSUE THREAD

**Issue by d-rez** [LedgerHQ/ledger-live-desktop#2134]
- [X] I have checked this feature was not yet requested. (well, as well as I could although #2122  seems related... maybe?)

Looks like users are getting confused when a rate provider gives no/bad/bogus data about coin value and the app just shows 0 as value (or backend data is wrong?)

A feature to show a warning when it's not possible to fetch proper data from an exchange/rate provider for some accounts, with a suggestion to try another one or try later would probably fix this

#### Part of the application

Portfolio and Accounts section

**Comment by OpSecChainFailure** [comment]
To add on this issue should definitely create some sort of fallback (to another rate provider) when a certain exchange is offline/fails to fetch the data.

Currently Bitfinex is offline so no rates, leaves users in Ledger Live in confusion.

![image](https://user-images.githubusercontent.com/1304367/60178112-f0eac480-981a-11e9-8020-b7da465f582a.png)

**Comment by gre** [comment]
@OpSecChainFailure fixed in develop, so will be in next release.
0 value is also about to be fixed in our backend.
