### ISSUE TITLE
Oops something went wrong - currency with id undefined not found

### ISSUE THREAD

**Issue by Soolan** [LedgerHQ/ledger-live-desktop#2146]
#### Ledger Live Version and Operating System

- tested on Ledger Live **1.9.1** 
- Platform and version: **Ubuntu 18.04**

#### Expected behavior

Loading the app and showing the balance screen

#### Actual behavior

Please see the screenshot:
![Screenshot from 2019-06-28 16-25-43](https://user-images.githubusercontent.com/3588122/60329008-064e2300-99c2-11e9-8c2a-b273c48111fb.png)

#### Steps to reproduce the behavior

1. Connect the Nano Ledger S
2. Enter the password
3. Run the Ledger Live app

**Comment by gre** [comment]
i would recommend to Reset and reimport the accounts. we suspect a bug in our migration scripts #2145

**Comment by Soolan** [comment]
The reset button, just reset the UI.
I would be deeply appreciated if you walk me through re-import process.
