### ISSUE TITLE
Nano S - Unable to withdraw/receive crypto

### ISSUE THREAD

**Issue by BACKHER** [LedgerHQ/ledger-live-desktop#2158]
I cannot send or receive crypto on my Ledger Nano S anymore.
I have updated the firmware and cleared cache and reloaded Ledger Live
I have restored the device with the original seed words.
The Ledger Live shows the accounts and amounts but when trying to send/receive it
gives me the "wrong device" error message.
I have researched and tried all instructions Ledger and users give and still does not work.
Any other solutions to try? Thanks!

**Comment by gre** [comment]
- remove accounts of the currency affected by the problem
- clear cache
- readd accounts

**Comment by gre** [comment]
Please go through tech support if it didn't work. Thanks
