### ISSUE TITLE
Make moving from ledger live to electrum easier

### ISSUE THREAD

**Issue by haukehess** [LedgerHQ/ledger-live-desktop#2167]
Right now it seems hard if not impossible to recover wallets in electrum from an ledger nano s which had all the wallets configured in ledger live. I raised the gap limit in electrum to discover more adresses but my wallets still showed 0 BTC balance. I don't want to expose my 24 word seed to electrum to check if this discovers my balances, because I only trust nano s with my private keys and want to stick to this paranoia.

For someone who would like to use electrum personal server to get rid of dependencies to some server farms not controlled by myself, this is no easy to bridge problem.

**Comment by gre** [comment]
I don't understand how this is related to Ledger Live Desktop. It's for Electrum to make it easier to import nano s accounts if it's not yet the case.
