### ISSUE TITLE
Incorrect wallet balance with bech32

### ISSUE THREAD

**Issue by plengkeek** [LedgerHQ/ledger-live-desktop#2170]
#### Ledger Live Version and Operating System
- tested on Ledger Live 1.10.2
- Platform and version: Windows 10

#### Expected behaviour
Wallet balance is updated to correct amount after new transaction

#### Actual behaviour
The balance history and the current balance that is displayed behaves as it is not aware of previous transactions. Example:
+1BTC
-0.1BTC
+0.05BTC

Displayed available balance 0.05BTC with the history graphs only showing a peak at the last transaction date. Clearing the cache in the app will fix the issue and properly display the balance

#### Steps to reproduce the behaviour
This happens when using the native segwit bech32 adress. For me just sending or receiving a transaction will cause this issue.

**Comment by gre** [comment]
Thanks for the bug report.
This is a known bug (and documented in the release notes), this is now fixed in our develop branch and will be fixed in next release.
