### ISSUE TITLE
Remaining known issues with ERC20 implementation

### ISSUE THREAD

**Issue by gre** [LedgerHQ/ledger-live-desktop#2172]
Below are listed known issues with ERC20 experimental implementation in Ledger Live 1.11.0 that should be fixed soon. **checked items are only fixed in our develop branch, not yet in 1.11.0.**

- [x] **some ERC20 tokens show a wrong balance.** for instance instead of seeing 10000 you see 0.0000000000121 (scientific notation issue ~~in current backend~~)
- [x] Ledger Live Mobile app does not yet support ERC20.
- [ ] some token might be missing. Please contact us if you see important ones missing (we do not yet have a way to see the actual list)
- [x] UX: No current way to see the tokens supported / select a token to receive.
- [x] UX: as accounts need to be "updated" (aka re-added) to benefit the update, we are going to make a dedicated flow to have a better UX.

**Comment by 01BTC10** [comment]
I tested ledger-live-desktop-1.11.0-linux-x86_64.AppImage and can confirm that I now see my chainlink tokens but the balance is wrong.

**Comment by gre** [comment]
@01BTC10 thanks for feedback.

> Tokens are also missing from the asset distribution.

can you explain more? this is what supposed to happen:

<img width="747" alt="Capture d’écran 2019-07-11 à 10 07 31" src="https://user-images.githubusercontent.com/211411/61033413-c0328f80-a3c3-11e9-8504-b4e82abca229.png">

**Comment by 01BTC10** [comment]
> @01BTC10 thanks for feedback.
> 
> > Tokens are also missing from the asset distribution.
> 
> can you explain more? this is what supposed to happen:
> 
> <img alt="Capture d’écran 2019-07-11 à 10 07 31" width="747" src="https://user-images.githubusercontent.com/211411/61033413-c0328f80-a3c3-11e9-8504-b4e82abca229.png">

Sorry I see it now. I probably missed it because the balance is wrong and below 0.

**Comment by brent-riva** [comment]
@gre any chance we could get an updated build of the pre-release with the latest bug fixes?

Specifically regarding: #2176, #2181, and #2173

**Comment by knuxel** [comment]
That would be awesome! 😁 (Ledger Live 1.12.0 on macOS 10.14.6)
<img width="773" alt="image" src="https://user-images.githubusercontent.com/1543778/61936664-7c2bb700-af8d-11e9-95f0-6203d04c5aad.png">

**Comment by Tommatheussen** [comment]
Same issue as @knuxel here:
<img width="735" alt="image" src="https://user-images.githubusercontent.com/13683094/61948994-b2772f80-afa9-11e9-9584-d9b429082c30.png">
Don't get me wrong, I'd like this to be true, but I'm afraid it's not 😂 
Additional information:
https://ethplorer.io/address/0x8d75959f1e61ec2571aa72798237101f084de63a
that is the contract adress

**Comment by PierrickGT** [comment]
In order to test the new ERC20 feature, I've re-added my Ethereum account without deleting it, only in order to update it. Most of the ERC20 tokens I have synced except for Maker DAO (MKR).
Is it a known bug? I'm on Ledger Live 1.12.0 and macOS 10.14.5

**Comment by gaardiolor** [comment]
I'm running Ledger Live 1.13.2 on windows. 

Just added my tokens, looks like Ledger Live detected all of them and sees the correct Amount. But under 'Portfolio' there is no Price (-), Distribution (empty) and Value (-) listed for those tokens. I have restarted Ledger live, doesn't help.

When I'm going to Settings > Crypto Assets, for 2 tokens (BET and GSE) the Rate provider dropdown  is empty (only shows greyed out 'Select an exchange'). 

For LPT instead of the dropdown it displays 'API HTTP 400'.

**Comment by gre** [comment]
we're improving the UX on the token rate provider.
i'll inform the team for TUSD
