### ISSUE TITLE
API HTTP 404 , Both in 1.7.0 version and Latest version 1.11.0

### ISSUE THREAD

**Issue by jaysiddik** [LedgerHQ/ledger-live-desktop#2197]
<img width="497" alt="Screenshot 2019-07-17 at 9 22 41 AM" src="https://user-images.githubusercontent.com/19870236/61382267-14f56f00-a8ca-11e9-826e-02f5bd095da5.png">

**Ledger Live** : 1.11.0 

> Initially tried Ledger Live Version:  1.7.0 

**Current firmware** : 1.4.1

I have a good internet connection , i dont know whats the issue, its been a while since i updated my firmware. i already been asked by support team to use **1.7.0** to update the firmware. but the **issue with boot loader screen** was there in my ledger device. but it was recommend to update to latest **1.11.0** so the boot loader issue will get solved. but now i'm struck with **API error 404**

**Comment by gre** [comment]
@jaysiddik could you contact our techsupport? it's the central point where we handle things. We do not provide support over Github.

Thanks.

**Comment by jaysiddik** [comment]
i didn't get any response , thats the reason. i'm contacting via **Github**
