### ISSUE TITLE
No Balance on Bech32, Mycelium and Electrum are working OK

### ISSUE THREAD

**Issue by TS32423** [LedgerHQ/ledger-live-desktop#2212]
Helle Ledger Team,

In fact the new Bech32 is a great new feature in Ledger Live. I used my 24 words to store BTC on both Segwit and Native Segwit Accounts. When I use Mycelium both accounts are showed correctly and the summary of both are displayed and I see all transactions. When I use Electrum also both accounts are working with the same 24 word seed.
But when I add a new Bech32 account in Ledger Live (Version 1.11.0 or 1.12.0) this account showes Zero Balance (0.0) , but when I fetch a new receive Bech32 address it showed the correct first Bech32 Address for this account, and this address already have a balance. This is not correct and it must be in issue.

Best Regards,
Thomas.

**Comment by dasilvarosa** [comment]
Hi, 
Could you please try to clear the cache (Settings > Help) or remove the account and add it back again in Ledger Live?
If it still does not work, please submit a support ticket (support.ledger.com). Thanks

**Comment by TS32423** [comment]
Hi,
clearing the cache did not sove the problem. Even a complete reinstall after manual deleting the User Profile for Ledger Live did not.

(Windows 10 Home on a Laptop and a stationary PC)
