### ISSUE TITLE
[BUG] Storage shrinking over time

### ISSUE THREAD

**Issue by MisterTicot** [LedgerHQ/ledger-live-desktop#2219]
#### Ledger Live Version and Operating System

Ledger Live 1.11.0, Xubuntu 19.04

#### Actual behavior

I just reset my Ledger nano S & it was possible to install 6 apps (Bitcoin, Ethereum, Litecoin, Ripple, Stellar, Litecoin). After installing & removing apps a few time, one week later, I can only install Bitcoin+Ethereum+Stellar.

As the apps/firmware are still the same, this shows that storage management of Ledger nano S is still buggy. This is a usability flaw so I think it needs to be dealt with in a timely fashion.

Two times, the app installation process stopped before finishing − so I suspect some temporary files are still there and need to be cleaned.

#### Expected behavior

It should be possible to install the same set of apps over time.

#### Steps to reproduce the behavior

Not sure about that. I suppose you could try to install & remove apps and see if storage did shrink. If it didn't, you could try to cut the app installation process, for exemple by kiling Ledger Live, and see if it reproduces the bug. It probably will as this problem happened two times on two devices for me.

**Comment by MisterTicot** [comment]
It would be nice is someone can take on that one. I think that's a major issue with the device. I hope you guys don't leave it this way just so sell more units...

**Comment by gre** [comment]
Hi @MisterTicot ,

Unfortunately this is not related to Ledger Live itself but more the firmware of the nano S.
Regarding Ledger Live, we're planning on having a better manager soon but it's not going to solve the underlying cause that the devices have very limited storage capacity.

Please contact our tech support to raise this. Thanks
