### ISSUE TITLE
Shows zero installed apps

### ISSUE THREAD

**Issue by antonioribeiro** [LedgerHQ/ledger-live-desktop#2220]
#### Ledger Live Version and Operating System

- Legder Nano S
- Tested on Ledger Live 1.12.0
- Platform and version: macOS 10.14.5

#### Expected behavior

Open Leger Live an see all my installed apps.

#### Actual behavior

Shows none installed and let me uninstall no apps. I'm trying to upgrade firmware and it says I have no more space left and I need to uninstall some apps, but I cannot uninstall them while the trash button is disabled.

#### Steps to reproduce the behavior

Not sure if you can reproduce that, but I was using Legder Manager. Once I opened my Nano S on Legder Live, I cannot see any installed apps anymore, not even in Legder Manager.

**Comment by juan-cortes** [comment]
Can you tell us which firmware version of the device, if this is the case we must be filtering the compatible apps wrong somehow

**Comment by antonioribeiro** [comment]
Here's what it shows:

Secure Element: 1.4.2
MCU: 1.5

**Comment by juan-cortes** [comment]
In our current implementation, the trash icon (uninstall) shouldn't be disabled ever, you could trigger an uninstall for an app that you haven't installed if I recall correctly. Can you send a screenshot of your manager screen to see what exactly is happening?

**Comment by antonioribeiro** [comment]
Yeah, you are right, trash button is grey but clickable. So I deleted the Bitcoin app, it said it was successfully deleted, then I tried to reinstall and got this:

![image](https://user-images.githubusercontent.com/3182864/62403263-66f0f280-b562-11e9-8c07-8ed0f7909638.png)

One of two things happened here (to me):

1. It was not uninstalled
1. Bitcoin app is bigger so it cannot install because we need more space.

One example of a fine working installed app, which's not showing as "installed" in the manager list is Stellar:

![image](https://user-images.githubusercontent.com/3182864/62403280-91db4680-b562-11e9-8284-97df1a464b72.png)

If I go to the [account viewer](https://www.stellar.org/lumens/wallets/) I'm able to connect to the wallet, sign in with Legder and see my lumens. It tells me that somehow the browser (Chrome Version 76.0.3809.87 64-bit) is able to reach the app, but Legder Live is not?

Well, I just gave up, uninstalled all apps, upgraded to 1.5.5 and it is now working fine.

**Comment by antonioribeiro** [comment]
Installed apps are supposed to show as installed in the Ledge Live? Bitcoin and Stellar are both installed, but:

![image](https://user-images.githubusercontent.com/3182864/62403722-ad941c00-b565-11e9-8262-71471da804a6.png)

**Comment by juan-cortes** [comment]
There is currently no indicator of whether an app is installed on device from the live side. You can check the installed apps on the device itself. My suggestion would be to uninstall all apps and then install them again starting with bitcoin

**Comment by antonioribeiro** [comment]
So, if got that right, Live is not supposed to show the installed state? Not even in Legder Nano X with one hundred apps?

So it's working as it should.

And this is exactly what I just did. Uninstalled all apps (but OpenPGP, which was not in the Live list of apps). Updated the firmware, then installed Bitcoin.

**Comment by juan-cortes** [comment]
That's feature will be added eventually, but for now you are correct, there's no indicator

**Comment by gre** [comment]
Yeah hopefully the ux will soon get better. That trash is not disable, you can click it to uninstall apps on the device.
