### ISSUE TITLE
Send/receive NIM (Nimiq) from the Ledger Live app 

### ISSUE THREAD

**Issue by rraallvv** [LedgerHQ/ledger-live-desktop#2254]
- [X] I have checked this feature was not yet requested.

To be able to send and receive NIM in the Nimiq blockchain from the Ledger Live app. 

#### Part of the application

Nimiq would be listed in the drop down list of available coins in the sections "Accounts > Add Accounts", "Send", "Receive" on the Ledger Live app where it's currently missing.

![Screen Shot 2019-08-07 at 12 14 26 PM](https://user-images.githubusercontent.com/1840524/62639282-39fb6180-b90d-11e9-8a09-418d94657f2c.png)

**Comment by MortalKastor** [comment]
Here is not the right place for asset integration requests, please see pinned issue #1560
