### ISSUE TITLE
Update is not working

### ISSUE THREAD

**Issue by jonathansmirnoff** [LedgerHQ/ledger-live-desktop#2257]
#### Ledger Live Version and Operating System

- tested on Ledger Live **1.8.1**
- Platform and version: **Mac 10.14.5**

#### Expected behavior

I can update the app

#### Actual behavior

I was notified that there was an update, I downloaded it but when I click on `install now` it doesn't work.

#### Steps to reproduce the behavior

1. Get version *1.8.1*
2. Download the update
3. Click on Install Now

**Comment by gre** [comment]
I'm afraid this was a bug in Ledger Live 1.8.x on Mac.

Two choices for you:

- you click Install Now **once** and you manually quit and reopen Ledger Live.
- you manually download the update.


Nothing we can fix because it was a bug present only in the 1.8.x past releases.
