### ISSUE TITLE
Ledger Live - Ubuntu fails

### ISSUE THREAD

**Issue by anonranger** [LedgerHQ/ledger-live-desktop#2291]
Adding new ledger nano to ledger live fails: step "Navigate to the dashboard on your device" hangs forever #1493 and fails.

I tried sudo su, chmod +x [app]

It worked one time and then fails.

This need to be resolved. Device used Ledger Nano S

**Comment by gre** [comment]
Have you set up the udev rules?

**Comment by cthepot-ledger** [comment]
Please try with the latest version. If does not solve your situation please contact support on support.ledger.com
