### ISSUE TITLE
Wrong Device or Passphrase when send ETH Crypto Asset

### ISSUE THREAD

**Issue by KKSSCHOI** [LedgerHQ/ledger-live-desktop#2296]
Dear Ledger Support,

Previously, I received only by receiving ETH in my account using Nano Ledger S.
In order to send ETH this time, when I connect Nano Ledger S, it happen an error message as shown below.
**Oops, long device for 'Ethereum 1'
The connected device is not attached with the account you selected.**

![image](https://user-images.githubusercontent.com/54551597/63714684-4853e380-c810-11e9-8fbf-d183e85c1af8.png)

**Wrong Device or Passphrase for 'Ethereum 1'
Please use the device or passphrase for the selected account**

![image](https://user-images.githubusercontent.com/54551597/63715150-3292ee00-c811-11e9-9a76-d06d163c5454.png)

Actually, I can check my balance with my original account. 
https://ethplorer.io

I already have used restore from recovery 24 passphrase.
But it was not recovered.
Strangely, All kinds of virtual currency(BTC, XRP, LTC) are working except Ethereum.
I can see synchronized account in mobile but it can not send.

I have tx code and from and to address.
Could you plz help it? 
I think It is not connect with my original address with Nano S.
There is new address for ETH

#### Ledger Live Version and Operating System

- tested on Ledger Live **1.13.2**
- Firm Ware **1.5.5**
- Platform and version: **Windows 10**

#### Expected behavior

I want to get my original account which are connected with Nano Ledger S.
I can send my crypto asset.

#### Actual behavior

I have this error message. I try to solve this problem asking ledger support.
But it is not still can not solve yet. I never change my device, 24passphrase and PIN.
Ledger Live is synchronized my balances correctly.

#### Steps to reproduce the behavior

Please provide me with the solution for issue 1851, 2047 as I seem to have exactly the same problem.

**Comment by gre** [comment]
Can you contact tech support via https://support.ledger.com/ to provide more information like logs? GitHub is public so it is not the good place.

Thanks

**Comment by VTB21** [comment]
Hi All, 

Is this issue resolved?

I am facing same issue and see same error message.

Regadrs,

V

**Comment by FrankP01** [comment]
> Hi All,
> 
> Is this issue resolved?
> 
> I am facing same issue and see same error message.
> 
> Regadrs,
> 
> V

Hello I will advise you contact the ledger support team on telegram it’s active and helpful, they will be happy to help you. here is there user @ledgerteam

**Comment by gre** [comment]
https://support.ledger.com/ is the main Ledger support, specifically for such issue.
