### ISSUE TITLE
Linux AppImage doesn't have Icon 

### ISSUE THREAD

**Issue by KipK** [LedgerHQ/ledger-live-desktop#2300]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.13.2
- Platform and version: *Ubuntu 19.04

#### Expected behavior

App should display an Icon in Nautilus, dock, and Applications Menu.

#### Actual behavior

No icon displayed but default one.
Could be related to this issue: https://github.com/electron-userland/electron-builder/issues/748

**Comment by Svarto** [comment]
same problem, did you find a solution?

**Comment by cthepot-ledger** [comment]
https://github.com/LedgerHQ/ledger-live-desktop/pull/2954

**Comment by gre** [comment]
hopefully fixed by now.
