### ISSUE TITLE
Ledger Live, won't show after I open it

### ISSUE THREAD

**Issue by MaTthyU** [LedgerHQ/ledger-live-desktop#2306]
#### Ledger Live Version and Operating System

- tested on latest Ledger Live
- Windows 10

After I open the app as I normaly would, it just won't apper on any of my screens. I tried reinstalling the app, unplugging all screens except one, update whatever I could but nothing helped.

So after I open the app, nothing will pop up as I said, but if I start clicking furiusly on it, then i can see its outline blink in the corner of my screen...

Attached image shows, that Ledger Live is running
![legerBug](https://user-images.githubusercontent.com/54773934/64078842-4abaaf80-cce0-11e9-9200-772eb98fceb5.png)

**Comment by pbondoer** [comment]
That's a strange issue.

Could you try clicking on the window, and immediately after (without doing anything else in between) pressing `Windows key` + `Up arrow` on your keyboard?

This is a keyboard shortcut in Windows 10 which will maximize the window and hopefully bring it up. I suspect it may be outside of the screen bounds, which is why you cannot see it anywhere. Let me know if the window shows up on your screen after that.

**Comment by MaTthyU** [comment]
Yeah, I know right?

I have tried many times, believe me. I am not sure if I am able to fully describe what's happening so i decided to capture it. Hope it helps.

https://youtu.be/CKj6y5ululs

**Comment by MaTthyU** [comment]
Tried many things, finally got it resolved.
So if you encountered this problem, this is what worked for me.

Uninstall LL, force delete all files associated with LL, reinstall GPU driver. 
Only force delete did not worked. I don't know why would GPU cause problems like this, anyways, time to close this issue. 

My thank You, belongs to anyone who thought about solution.

**Comment by yannickvidal** [comment]
I had the exact same problem tonight. If that can help someone, I managed to fix it by:
- clicking the Ledger Live icon in the taskbar (to open the app somewhere on the screen even though it's not visible)
- pressing ALT+space to bring the Move, Size, Minimise, Maximize menu on the current window
- click Maximise, the LL window then appeared full screen
- drag the window somewhere to force the minimised version to be visible on the screen

(I tried plugging a second monitor and using windows key+arrow to move the hidden window around but that didn't work)

**Comment by r4nta** [comment]
> * g

This helped me. Thanks!

**Comment by natilus** [comment]
Clutch. Hell yeah.

**Comment by Bosco-2019** [comment]
Thank you @yannickvidal this helped me just now 👍

**Comment by mlamias** [comment]
I had a similar issue and I'm pretty sure it's related to the fact that I have 8 monitors and I had last displayed ledger live on my right most monitor and then closed the monitor, disconnected the monitors from my laptop and then tried re-launching the application.  When I do so, Ledger Live seems to flicker quickly and I can see the left most edge of the Ledger Live app briefly.  To resolve this, I simply had to issue the keyboard command in Windows to maximize the window.  After doing so the screen maximized and re-centered on my main (and now only) screen.  Here's how to do it:

1.  Make sure you closed out of Ledger Live.
2. Launch Ledger Live 
3. Press the Windows Key (Low left next to my Alt key) + the Up arrow on the keyboard.

I hope this helps others.  I think this solution is similar to the one offered by @yannickvidal, but is slightly different.

**Comment by xiand3r** [comment]
Thanks a lot to all ! It's a strange bug
