### ISSUE TITLE
Portfolio does not correctly reflect token/coin counter value in fiat

### ISSUE THREAD

**Issue by wojo** [LedgerHQ/ledger-live-desktop#2326]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.14.0 on macOS, iOS 1.4.0 (45)
- Platform and version: macOS 10.14.6, iOS 12.4.1

#### Expected behavior

Balances on the portfolio screen should include USDT ERC20 tokens. They do total up correctly on the iOS application, but on macOS they do not

#### Actual behavior

On macOS, the Value column for USDT ERC20 tokens is blank, perhaps because there isn't a countervalue match but it is tether, so it's a 1:1 match to USD. The total portfolio value is also missing the value of the USDT value, and the line is sorted to the bottom as if it had zero value.

On iOS, although the total is correct (oddly enough), the portfolio Asset Distribution page doesn't show the USD value in the asset like it does for other coins that countervalue to USD, so it's sorted to the bottom.

#### Steps to reproduce the behavior

Construct a portfolio with normal coins that countervalue to USD, but also make sure you have a balance of USDT mixed in.

**Comment by gre** [comment]
I don't think it's a mobile vs desktop problem but more a settings problem. Please check what is set in settings > crypto assets , for the USDT ETH pair.

Thanks

Side note: 1:1 of USDT to USD is not guaranteed, so we still will calculate the countervalue

**Comment by wojo** [comment]
@gre I did check the settings, and there is no entry available for USDT to USD under the Rates tab on iOS and the section on macOS. Perhaps that's the root of the issue.

However, there is still a difference between mobile and desktop with the same exact accounts and settings as highlighted above.

Good point on always checking countervalue for USDT!

**Comment by gre** [comment]
@wojo you should have an entry for USDT to ETH. and one for ETH to USD. Ledger Live is using these two pairs to calculate the USDT to USD rate because there are more chance to have pairs like this (USDT->ETH->USD). So maybe something is wrong on the USDT to ETH pair 🤔 

current implementation have tradeoffs and we might look to better approach of offering rates in the future.

**Comment by wojo** [comment]
@gre USDT to USD shows "No exchange found". Looks like we are honing in on the issue.

I understand about the pairing of USDT->ETH->USD being more available, makes sense!

For the difference between mobile and desktop I resynced all my settings and it seems I can't reproduce that any longer. That is good as it matches what the issue seems to be on all platforms, I must have had something else wrong when trying to reproduce it.

**Comment by etienne-napoleone** [comment]
Same here, "No exchange found"

**Comment by RuChiang** [comment]
Hi, Im encountering similar problems.
After depositing USDT ERC-20 into my ledger account, no balances under the ETH account showed up (should be shown as tokens under ETH if I understand things correctly). 
I also verified the fund got sent to the address provided my ledger live app on Etherscan.

Please assist. I cannot do any operation on the funds not as they don't show up in the app

**Comment by Gdocal** [comment]
please fix the issue

**Comment by gre** [comment]
we are reworking countervalues api to have a bette precision on this matter. stay tuned.

**Comment by gre** [comment]
Hello, we have completely reworked the way countervalues work (as part of other problems we had with them). We have opened a beta testing program in order to know if our rework fully works for you, we invite users that want join the beta to follow instruction available in https://github.com/LedgerHQ/ledger-live-desktop/releases/tag/2.16.0-countervalues-beta-0
