### ISSUE TITLE
Dynamic exception type: soci::sqlite3_soci_error\nstd::exception::what: sqlite3_statement_backend::loadOne: UNIQUE constraint failed: bitcoin_inputs.

### ISSUE THREAD

**Issue by DenJ0hn** [LedgerHQ/ledger-live-desktop#2333]
[ledgerlive-logs-2019.09.10-17.52.53-8b2da9c25d47bdc8148d9ab128dad69086fd7fe2.txt](https://github.com/LedgerHQ/ledger-live-desktop/files/3596612/ledgerlive-logs-2019.09.10-17.52.53-8b2da9c25d47bdc8148d9ab128dad69086fd7fe2.txt)
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.14.0
- Platform and version:  MacOS 10.14.6

#### Expected behavior

Wallets should sync and not give an error.

#### Actual behavior

Wallet sync gives an error and won't continue: Dynamic exception type: soci::sqlite3_soci_error\nstd::exception::what: sqlite3_statement_backend::loadOne: UNIQUE constraint failed: bitcoin_inputs.

#### Steps to reproduce the behavior

Open Ledger Live, let the wallets sync. At a certain moment, the wallet gave above error. Logfiles are attached. I cleared the cache and it appears that the wallets are now syncing.

**Comment by DavidFens** [comment]
Any progress on this one? I have exactly the same issue with adding a Digibyte account. I had the very same account and it was working until a week ago when I have updated to the newest version of Ledger Live 1.18.2. After sync error I have deleted cache, removed the Digibyte account and reinstall Digibyte app on Ledger nano S. Now I cannot anymore add Digibyte account.

**Comment by DavidFens** [comment]
I have installed version 1.15.0 and when trying to add DGB account throws the following error

Dynamic exception type: soci::sqlite3_soci_error
std::exception::what: sqlite3_statement_backend::prepare: table
bitcoin_outputs has 8 columns but 7 values were supplied (RUNTIME_ERROR)

I could not found more recent version here on github (you have only source code and not the appImage) except of course the latest 1.18.2 non working version. If I am not mistaken it was still working in 1.17 version if not even in 1.18.0.

**Comment by DavidFens** [comment]
This issue is still valid in the newest version of Ledger 1.19.1 (pre-release)

Wallet sync gives an error and won't continue: Dynamic exception type: soci::sqlite3_soci_error\nstd::exception::what: sqlite3_statement_backend::loadOne: UNIQUE constraint failed: bitcoin_inputs.uid

**Comment by Trophonix** [comment]
I'm having the same issue with DigiByte and DogeCoin in the latest Ledger Live.

**Comment by Whalerus** [comment]
Same here with Litecoin account.

**Comment by DavidFens** [comment]
OK. Here is the 'solution'. It seems that there were some changes in the SQLite database and there was not correct database upgrade done during the app update. What you need to do is:

1. Remove all the accounts that you have problems with
2. close Ledger Live application and navigate to the root folder of Ledger user data. On Linux is usually under /home/USER NAME/.config/Ledger Live (not sure about the Windows and Mac - On Windows is probably under C:\Users\USER NAME\AppData\Local or Roaming)
3. Then remove sqlite folder and start Ledger live again.
4. Add the previous deleted accounts
alternatively 
1. In Ledger live go to Settings > Help > Clear cache
2. You might be prompted to manually delete the sqlite folder (as was in my case).

<sarcasm on> Thanks Ledger for the outstanding support </sarcasm off>

**Comment by DavidFens** [comment]
OK. Here is the 'solution'. It seems that there were some changes in the SQLite database and there was not correct database upgrade done during the app update. What you need to do is:

1.   Remove all the accounts that you have problems with
2.    close Ledger Live application and navigate to the root folder of Ledger user data. On Linux is usually under /home/USER NAME/.config/Ledger Live (not sure about the Windows and Mac - On Windows is probably under C:\Users\USER NAME\AppData\Local or Roaming)
3.   Then remove sqlite folder and start Ledger live again.
4.   Add the previous deleted accounts

    alternatively
    
1.    In Ledger live go to Settings > Help > Clear cache
2.    You might be prompted to manually delete the sqlite folder (as was in my case).

< sarcasm on > Thanks Ledger for the outstanding support </sarcasm off>

**Comment by gre** [comment]
Team is actively investigating on this. Sadly some bugs are harder than others.

**Comment by Whalerus** [comment]
> alternatively
In Ledger live go to Settings > Help > Clear cache
You might be prompted to manually delete the sqlite folder (as was in my case).
> 
This method worked for me without problems. :)

**Comment by Trophonix** [comment]
I tried clearing cache several times and I reinstalled Live entirely. Still no fix. Problem affects my PIVX, Digibyte, and Dogecoin wallets as of now... I've been forced to use a third-party application (beta.shapeshift.io) to access my coins properly

**Comment by Trophonix** [comment]
Please fix :( 

This bug prevents me from using dogecoin, digibyte, pivx...

**Comment by gre** [comment]
We expect this to be fixed in context of a big rework that just got merged. we'll reopen in this does not fix in the next release #2596
