### ISSUE TITLE
No Access to ledger-manager with Nano S (Sorry, try again (websocket error))

### ISSUE THREAD

**Issue by cilahn** [LedgerHQ/ledger-live-desktop#2341]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.14
- Platform and version: Manjaro Linux / Windows 10

#### Expected behavior

Opening Ledger Live Desktop and Navigate to Manager, unlock Ledger Nano S. Confirm access on device. Than install an app

#### Actual behavior

The last Step "Allow Ledger Manager on your device" dies with Error: Sorry, try again (websocket error)
![image](https://user-images.githubusercontent.com/3306778/64907007-96605680-d6ed-11e9-9069-008a4f0c78fb.png)

#### Steps to reproduce the behavior

Enter Live Desktop, try to access "Manager"

#### Non working Fixes:
- Tried 3 differrent USB Cables
- Test with 2 different Ledger Devices
- Even booted into native Windows <yuck> 10 with same behavior

#### What still works
Accessing a Web Wallet (i.e. https://wallet.callisto.network/)
Accessing an Account in Ledger Live

**Comment by legorado** [comment]
Same behavior here, 
with kernel 5.2.14 and 4.19.72-1 at actual arch linux. Nothing changed. After automatic update of AppImage to V1.14.0 even manually downloaded 1.13.2 and 1.12.0 are having the same behavior.

I'll try to get the backup of my ~/.config/Ledger \Live/ and start directly with 1.13.2

**Comment by cilahn** [comment]
Problem seems to be fixed automagically. I didn't changed a bit and today it started working on three different machines again. Internet was not degraded on my side. Could it be that something in the cloud git stuck?
Case can be closed.

**Comment by cryptochrome** [comment]
FIX YOUR SHIT, LEDGER
YOUR FUCKING DEVICE DOES NOT WORK!

**Comment by bocekm** [comment]
I had the same issues but after following the recommendations in https://support.ledger.com/hc/en-us/articles/115005165269-Fix-connection-issues I made it to work by disconnecting from a VPN.

**Comment by 4k4xs4pH1r3** [comment]
@cilahn + @stefanv + @cryptochrome + @bocekm + @legorado  Hello this is happening to me, I'm not using any vpn, please your help, when I try to fix MCU firmware in not genuine appear this error Repair Your Ledger device, Sorry try again (websocket error), please Your help fixing it and guide to find a solution in team.

![image](https://user-images.githubusercontent.com/32862241/128565101-ee6e0b41-564c-411e-aafa-5603574ca12c.png)
