### ISSUE TITLE
ERC-20 Holo (HOT) - Bug

### ISSUE THREAD

**Issue by ElvisPresly** [LedgerHQ/ledger-live-desktop#2344]
Hi. Ledger Live misspelled token HOT (ERC-20)

Ledger Live Thinks it 's **Hydro Protocol (HOT)** https://coinmarketcap.com/currencies/hydro-protocol/

And actually I own **Holo (HOT)** https://coinmarketcap.com/currencies/holo/

Therefore, the exchange rate is not displayed correctly.

**Comment by ElvisPresly** [comment]
@gre I would like to switch the exchange, but i see only Huobi
Binance is not on the list, but it trades there

**Comment by maackle** [comment]
Related: https://github.com/LedgerHQ/ledger-live-desktop/issues/2524
