### ISSUE TITLE
wallet empty after restoring

### ISSUE THREAD

**Issue by brimbl** [LedgerHQ/ledger-live-desktop#2352]
Hi,

i have received this transaction, but after restoring my wallet it's empty:( Could you help me please? Thank you!
https://m.oxt.me/transaction/7151be789d39f1cd96f5395f881ebf94a232c5bd6f9e1d2d8fdc055ee66ee1f3

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. 

This issue can happen for various reasons. We prefer to investigate such issues via contacting our customer support team.

could you send your logs to our support team and mention this github issue? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏  basically you can press Ctrl+E just after the problem occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.now.sh/logsviewer )
