### ISSUE TITLE
.Appimage file in Ubuntu not working

### ISSUE THREAD

**Issue by Folderguion** [LedgerHQ/ledger-live-desktop#2357]
Hello, in Ubuntu after download .appimage file, I apply the settings to make the file executable. However after double click nothing happen. Also tryed via terminal with your command line but it's not working. Nothing happen, the application doesn't open. Anyone can help with a step by step solution?

**Comment by meriadec** [comment]
Hello! Can you precise exactly what is happening when you are launching it from the terminal? Here is the expected output:

![1570000507](https://user-images.githubusercontent.com/315259/66024817-2aeff480-e4f5-11e9-8736-530f84ed1801.png)

```
$ chmod +x ledger-live-desktop-1.15.0-linux-x86_64.AppImage 
$ ./ledger-live-desktop-1.15.0-linux-x86_64.AppImage 
Ledger Live 1.15.0
Checking for update
Update for version 1.15.0 is not available (latest version: 1.15.0, downgrade is disallowed).
```

**Comment by Folderguion** [comment]
Hello, thanks for the answer. Is like nothing happen, look: 

![captura_terminal](https://user-images.githubusercontent.com/56049149/66067869-cceefb80-e54c-11e9-85d2-883e3bbab630.png)

**Comment by Folderguion** [comment]
Sorry, this is a better image

![captura_terminal_2](https://user-images.githubusercontent.com/56049149/66068719-67037380-e54e-11e9-9002-f5d8d540b541.png)

**Comment by meriadec** [comment]
Ye, so you did `chmod` (aka change permission of the file)
But not you need to run the app :p

```
$ ./ledger-live-desktop-1.15.0-linux-x86_64.AppImage 
```

**Comment by Folderguion** [comment]
Oh sorry. After that I get the following:

./ledger-live-desktop-1.15.0-linux-x86_64.AppImage
/tmp/.mount_ledgerUDS9vn/ledger-live-desktop: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

**Comment by meriadec** [comment]
Here is what I get after googling your error

https://askubuntu.com/questions/836142/error-while-loading-shared-libraries-libgtk-x11-2-0-so-0-no-such-file-or-direc

Can you try?

**Comment by Folderguion** [comment]
Hey, you helped me even if not with the correct solution :)

Look, I didn't understood so well why I should install Electron - from your previous link - , so searching for another solution, found simply to type this: apt-get install libgtk2.0-0

After this, Ledger Live loaded properly, but with the following error message: 
Gtk-Message: Failed to load module "canberra-gtk-module"

Following instructions in some other thread, and just did this:  apt-get install libcanberra-gtk-module

Now Ledger Live is loading perfectly and without error messages. 

THANKS for the help anyway!

**Comment by meriadec** [comment]
Glad you figured out! Closing :)
