### ISSUE TITLE
Mac - 100% CPU

### ISSUE THREAD

**Issue by jwchong** [LedgerHQ/ledger-live-desktop#2363]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.15.0
- Platform and version: MacOS Mojave 10.14.6 (18G103)

#### Expected behavior

All Ledger Live processes should have low CPU usage.

#### Actual behavior

Ledger Live Internal 100% CPU
Ledger Live Helper 37% CPU
Ledger Live 11% CPU

#### Steps to reproduce the behavior

I have created about 12 accounts.
Open Ledger Live then login, the CPU will hit to 100% while synchronising, and it will take more than 10 or 15 minutes to fully synchronise, sometimes some accounts will fail to synchronise after taking too long time.

I have then tried remove and reinstall Ledger Live, and Reset Ledger Live. With empty Ledger Live, CPU usage is back to normal after login because nothing needs to synchronise. I then add back some BTC accounts, while synchronising, CPU hit about 60%. After sync successfully, I then try to send BTC but the "Total to Debit" at the bottom of Send Page non-stop spinning and CPU 100% again.

<img width="795" alt="Screenshot 2019-10-08 at 1 29 39 AM" src="https://user-images.githubusercontent.com/24342851/66335771-484a1600-e96e-11e9-9e5b-ab8d08b784f5.png">

<img width="507" alt="Screenshot 2019-10-08 at 2 21 03 AM" src="https://user-images.githubusercontent.com/24342851/66337993-cd372e80-e972-11e9-909d-562a53db2609.png">

**Comment by gre** [comment]
Did you receive a lot of transactions on one of the account?
We are currently reworking completely the way that form is working (with simplifications and performance focus) and we hope this will address the problem. (Ctx #2289 )
We have also plans to increase performance of sync as well as offering a solution to accounts that received many txs.

**Comment by jwchong** [comment]
I think there are many transactions in the account too. Great that your team is doing a complete solution for this. Is there any estimated time for the fix?
Can you suggest a workaround while we wait for your solution?

**Comment by gre** [comment]
We expect this to be fixed in context of a big rework that just got merged. we'll reopen in this does not fix in the next release #2596
