### ISSUE TITLE
Problem APP Android new version , ETH synchronize Error

### ISSUE THREAD

**Issue by yvjos** [LedgerHQ/ledger-live-desktop#2377]
Hi, my account ETH in app Android not add, error ETH syncronize. (app version 1.5.0 and ETH 1.2.10) my system android 9 spanish phone Moto G7 Power)

Thank you
![error](https://user-images.githubusercontent.com/38862524/66703521-84b8a180-ece1-11e9-8aa6-c68a6f5f02d7.png)

**Comment by yvjos** [comment]
This is Crazy.... I test now in Moto G6 and work fine.....%$"$$.... I see in Moto G6 about app is 1.5.0 (1048623) and in my Moto G7 in about is 1.5.0 (3145775) and not work (problem synchronize ETH account)...... What is the different????

**Comment by yvjos** [comment]
Where I download manual this version 1.5.0 (1048623) (not in googlePlay)???

**Comment by yvjos** [comment]
Ready.. I got the app 1.5.0 (1048623) from the G6 with Apk extractor. I put it in my G7 and installed. Now works fine. Please the development team of Ledger release a new version to correct this problem.

**Comment by gre** [comment]
Relevant repository would be https://github.com/LedgerHQ/ledger-live-mobile

you can also contact our Ledger support. thanks
