### ISSUE TITLE
Pull QR Code from screen instead of webcam

### ISSUE THREAD

**Issue by mustjustbe** [LedgerHQ/ledger-live-desktop#2378]
- [x] I have checked this feature was not yet requested.

In the Windows Desktop Ledger Live application, when sending any asset you can add a recipient with a QR code. The button to look for a QR code opens up my webcam to look for the code. I do not see any option to find a QR code in any other way. I would much rather it use my screen to find the QR code.

#### Part of the application

Most people I have to assume are looking to send to a QR code that is on their computer screen?  Currently the button next to the input box for Recipient opens my webcam, creates a box to center the QR code in while fuzzing out the surrounding area of the video feed.

I think the same mechanism using the screen display instead would be more useful, but being able to select the Input would be the best outcome. If you can, or only want to, have a predetermined input it is a hard choice. Because you can copy and paste, but if you have a physical QR code to scan there is no easy way to input the code.

So I believe having the ability to choose would be best.

The same function of creating a box on your screen where the QR code needs to be centered, and distorting the rest of the screen mildly would be a good system for scanning the display for a QR code.

Only entering recipients while sending a asset.

**Comment by gre** [comment]
I don't think this is technically possible to capture the screen programmatically especially across the 3 OS.
I'm curious to know what are the usecase around why you have a qrcode on screen in the first place. It sounds like the exchange recipient should provide you a address to paste as well.
One idea we could do is to select a file as an image input, still a bit overkill to me.
