### ISSUE TITLE
Ledger Live Desktop ETH Account won't synchronize

### ISSUE THREAD

**Issue by skobi6** [LedgerHQ/ledger-live-desktop#2379]
- Ledger Live 1.15.0
- Platform and version: Windows 10

#### Expected behavior

ETH account update/synchronize with the actual balance.

#### Actual behavior

Multiple error messages.
![Account Update](https://user-images.githubusercontent.com/56503862/66713755-c16fc000-ede9-11e9-9067-2f0f870fa373.PNG)
![Account_Update](https://user-images.githubusercontent.com/56503862/66713757-ca609180-ede9-11e9-98d5-b8117552f0dc.PNG)
![Error1](https://user-images.githubusercontent.com/56503862/66713758-cdf41880-ede9-11e9-9326-e00f025a0e48.PNG)
![Error2](https://user-images.githubusercontent.com/56503862/66713760-cfbddc00-ede9-11e9-9dbd-bf419876cd20.PNG)
![Error 3](https://user-images.githubusercontent.com/56503862/66713763-d2203600-ede9-11e9-8aff-3e9bacb393aa.PNG)
![Network_Down](https://user-images.githubusercontent.com/56503862/66713764-d3e9f980-ede9-11e9-838c-b14c5d5b1f7c.PNG)

**Comment by yvjos** [comment]
hi, remove the app eth in hardware, retry install app ETH and add account in LedgerLive.

**Comment by skobi6** [comment]
Hi - I uninstalled ETH and installed then added a new account but does not recognize any balance.

![image](https://user-images.githubusercontent.com/56503862/66724325-acce0f00-ee5f-11e9-9e27-5d7e616c3540.png)

First ETH account is the new one.  3rd line is the ETH account that I'm trying to synchronize.

Thanks for your help.
