### ISSUE TITLE
Error in downloading application

### ISSUE THREAD

**Issue by frank0183773** [LedgerHQ/ledger-live-desktop#2384]
Hello there,

After an off crypto period, I have retrieved my ledger from the attic and would like to update it once again (via using Ledger Live). Nevertheless, when I try to download ledger live on my mac (version 10.15), an error pops up which states:

<img width="449" alt="Screenshot 2019-10-15 at 19 02 45" src="https://user-images.githubusercontent.com/56603415/66856194-fbc19480-ef84-11e9-8e9a-63f3165bcba4.png">

I would like to get some clarification on this topic and on how I will be able to get the ledger live application going. 

Best regards,

Frank

**Comment by gre** [comment]
fixed since then.
