### ISSUE TITLE
[bug] All accounts gone from Ledger Live

### ISSUE THREAD

**Issue by Luuk2016** [LedgerHQ/ledger-live-desktop#2402]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.15.0
- Platform and version: macOS Catalina (10.15)

#### Expected behavior

Accounts that were added should be shown after unlocking Ledger Live.

#### Actual behavior

When opening and unlocking Ledger Live all accounts are gone.
Configured settings like the password and language are intact.

Whats really strange is that the xpub keys of the accounts are still in the app.json file.
This problem happened 3 times and only occures on my Macbook Pro.

Thanks in advance ;)

**Comment by dm8885555** [comment]
I have exactly the same issue.  Windows 10.  Ledger Live v. 1.20.0 ... happened after update on 26 Dec 2019
