### ISSUE TITLE
ERC20 Countervalue missing

### ISSUE THREAD

**Issue by gaardiolor** [LedgerHQ/ledger-live-desktop#2404]
#### Ledger Live Version and Operating System
- tested on Ledger Live  1.15.0
- Platform and version: Windows 10 / IOS

#### Expected behavior
The value (in the currency defined in Settings > General > Countervalue) of my ERC20 tokens displayed in Ledger Live

#### Actual behavior
The value of ERC20 tokens  is not being displayed for my ERC20 tokens. Examples are:
Tokens that have Settings > Crypto Assets > Rate provider is 'No exchange found':
- BET
- GSE
- LPT

Tokens not even listed at Settings > Crypto Assets:
- TUSD 

Should be fairly easy to fix ? Other tokens have HitBTC as a rate provider, HitBTC also has BET, TUSD. I see Ledger Live also has support for Bit-Z as a rate provider, they have GSE. Poloniex has LPT.

#### Steps to reproduce the behavior
Get one of the tokens listed above, and observe they are not being rated.

**Comment by cthepot-ledger** [comment]
Duplicate of #2326
