### ISSUE TITLE
error: ENOENT, node_modules\usb\build\Release\usb_bindings.node not found in...

### ISSUE THREAD

**Issue by dslutej** [LedgerHQ/ledger-live-desktop#2417]
#### Ledger Live Version and Operating System

ledger-live-desktop-1.15.0-win
Windows 10.

#### Expected behavior

Program starts. 

#### Actual behavior

![image](https://user-images.githubusercontent.com/22919263/67414741-fd620c80-f5c3-11e9-822f-825f8956bfea.png)

Pressing OK yields spinning thingie forever:

![image](https://user-images.githubusercontent.com/22919263/67414811-17035400-f5c4-11e9-910d-6ccf3f115bfd.png)

#### Steps to reproduce the behavior

Try to start the program. Cannot.

**Comment by dslutej** [comment]
reinstalled. now works.

**Comment by dslutej** [comment]
Feel free to close, or if I can help with logs or something.

**Comment by dslutej** [comment]
I got this again today. Reinstalling helped. Annoying. :/

**Comment by gre** [comment]
We expect this to be fixed in context of a big rework that just got merged. we'll reopen in this does not fix in the next release #2596
