### ISSUE TITLE
Reduce white space usage for better utilization of screen space

### ISSUE THREAD

**Issue by dslutej** [LedgerHQ/ledger-live-desktop#2418]
See attached screenshot; there is a lot of screen space used for void. Also, the screenshot is taken with smallest possible window size which is (imho) too big. Maybe add configuration setting  to reduce padding. 

#### Part of the application

GUI

![image](https://user-images.githubusercontent.com/22919263/67423712-0ad3c280-f5d5-11e9-9154-c02945d76b05.png)

**Comment by gre** [comment]
the space before dashboard and right to the amount is actually used in some sitatuation.

I'll forward the rest to designers but it's general padding to not having something too crowded I guess.

We could probably optim more for smaller window.

**Comment by Zaczero** [comment]
My feedback is that the current amount of padding is good enough. It looks very minimalistic/modern. Saving every possible bit of space is good if you want to fit as much data as possible but I don't really think that it's a case with ledger-live software.

**Comment by dslutej** [comment]
Depends on intended use case for the software I guess, is it a one-for-all solution for power users and newbs, as advertised on ledger homepage, or something else? 

Personaly, I prefer high information density over scrolling when it comes to financial apps.

**Comment by juan-cortes** [comment]
We definitely have room to show more information on wider windows, and even on smaller screens now that we can collapse the sidebar. This is something we have present but I don't believe is a matter of just removing whitespace
