### ISSUE TITLE
Mac Desktop Live : API Http 503 error in Manager

### ISSUE THREAD

**Issue by shivamsk** [LedgerHQ/ledger-live-desktop#2425]
#### Ledger Live Version and Operating System

- tested on Ledger Live **Nano S - Firmware version 1.5.5**
- Platform and version: **e.g. Mac 10.12.6**

#### Issue

Not able to install apps in Manager. 
Got this Error in the screenshot when opening the Manager for searching apps to install. 

#### Steps to reproduce the behavior
1. Open Ledger Manager. 
2. It will wait for a minute and then the error pops up. 
<img width="1264" alt="Screen Shot 2019-10-28 at 3 09 24 AM" src="https://user-images.githubusercontent.com/6972611/67642304-6c2ac700-f930-11e9-95ae-afd2be8fe631.png">

**Comment by gre** [comment]
this was a temporary infra problem. now fixed. thanks
