### ISSUE TITLE
Chrome OS support for Ledger Live

### ISSUE THREAD

**Issue by jn17three** [LedgerHQ/ledger-live-desktop#2455]
I purchased a DELL Chromebook for the purpose of downloading and using Ledger Live for my new Nanoledger S.  Have since found out that you don't provide support for Chrome OS. 

I need to now find a way to use a Linux OS on the Chromebook. 

The specs of my Chromebook are small: 

Chromebook 13 (3380) Laptop Intel Celeron C3855 Processor
4GB Memory;32GB SSD, 13.3'' HD Non-Touch LCD;-;E5
45W AC Adapter, Type C;Primary 4-Cell 56W/HR Battery;US Int Dell KB216

Is there a 'lite' version of Ubuntu that is compatible with Ledger Nano S which I could boot directly using a live USB image to run Ledger Live on my Chromebook??

I am not experienced in using Linux and am having to try and work out how to do all of this. I bought the Ledger Nano S many months ago but haven't been able to use it because I am struggling to work out how to use it on the Chromebook.

Any guidance and instructions on the best linux distro to download, and whether I can use it from a live bootable USB and still retain data on the Ledger Live would be MUCH appreciated. 

Thank you

**Comment by gre** [comment]
unfortunately this can't happen if Electron does not support it as it's our current tech stack. we have no ETA to support this.

https://github.com/electron/electron/issues/12712

**Comment by tester2011** [comment]
Any progress? I also need to use my Ledger Nano S on a Chromebook.

**Comment by nueknack** [comment]
lost my SGB moving it to the nano s [ is etherium a scam ]?
