### ISSUE TITLE
Synchronization Error: Internal Process Error 3221226505 (v1.18.2)

### ISSUE THREAD

**Issue by dslutej** [LedgerHQ/ledger-live-desktop#2466]
#### Ledger Live Version and Operating System

V1.18.2
windows 10

#### Expected behavior

Synchronizes.

#### Actual behavior

![image](https://user-images.githubusercontent.com/22919263/68884883-64cb3200-0714-11ea-9c58-47c338255039.png)

Restarting software did not help.

#### Steps to reproduce the behavior

Possibly triggered by a large (as in lot of inputs, 50 inputs) Zcash SEND operation moments before issue started.

**Comment by dslutej** [comment]
ZCash transaction recorded on blockchain with 6+ confirmations. Not syncing in Ledger Desktop.

**Comment by dslutej** [comment]
Ledger Mobile is fine. Interestingly though, initial attempt to do the same 50 input transaction crashed Ledger Mobile.

**Comment by dslutej** [comment]
"level": "error",
        "message": "Internal process error (3221226505)",
        "name": "InternalError",
        "pname": "renderer",
        "stack": "Error\n    at createCustomErrorClass (C:\\Program Files\\Ledger Live\\resources\\app.asar\\node_modules\\@ledgerhq\\errors\\lib\\helpers.js:28:17)\n    at deserializeError (C:\\Program Files\\Ledger Live\\resources\\app.asar\\node_modules\\@ledgerhq\\errors\\lib\\helpers.js:61:26)\n    at EventEmitter.c (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/renderer.js:16:812938)\n    at emitTwo (events.js:131:20)\n    at EventEmitter.emit (events.js:214:7)",
        "timestamp": "2019-11-14T20:56:33.877Z"

**Comment by dslutej** [comment]
Reinstalling Ledger Live Desktop did not help.

**Comment by dslutej** [comment]
Removed all accounts except BTC natsegwit. Error goes away. Started re-adding. BTC seg OK, Eth OK. LTC boom.

![image](https://user-images.githubusercontent.com/22919263/68968973-1d13db80-07e4-11ea-8beb-362ec369ba18.png)

**Comment by dslutej** [comment]
Removed LTC. Added XRP OK. **ZCash BOOM.**

![image](https://user-images.githubusercontent.com/22919263/68969102-7e3baf00-07e4-11ea-8536-76d974b594f5.png)

**Comment by dslutej** [comment]
Uninstalled Ledger Live. Removed all left-over data. Reinstalled. Now works again.

**Comment by gre** [comment]
We expect this to be fixed in context of a big rework that just got merged. we'll reopen in this does not fix in the next release https://github.com/LedgerHQ/ledger-live-desktop/pull/2596

**Comment by DennisDyallo** [comment]
I still have this error in 2.33.1
