### ISSUE TITLE
"Internal Process Error 3221226505" then stuck on synchronizing... (Stratis)

### ISSUE THREAD

**Issue by NikolarnTV** [LedgerHQ/ledger-live-desktop#2469]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.18.2
- Platform and version: Windows 10
Ledger Nano S is the device in question.

#### Expected behavior

Should synchronize and add all accounts from my Ledger Nano S

#### Actual behavior

![image](https://user-images.githubusercontent.com/23565141/68992511-abcc3b00-086c-11ea-8acc-d41c15999116.png)

#### Steps to reproduce the behavior

So, i did a clean install of Ledger Live, updated the firmware on my Ledger Nano S, deinstalled all the apps, installed them back again, i've synchronized the Bitcoin app without any issues, the second i tried adding a Stratis account, first of all i couldn't get into it, it kept bringing me back to "Unlock your Ledger device", after multiple tries i kept getting the "Internal Process Error 3221226505" and now i'm simply stuck on Synchronizing...

I was doing everything properly.

**Comment by NikolarnTV** [comment]
Now i got this:
![image](https://user-images.githubusercontent.com/23565141/68992568-5b091200-086d-11ea-9713-dd3c995e0b7f.png)

**Comment by NikolarnTV** [comment]
![image](https://user-images.githubusercontent.com/23565141/68992652-77f21500-086e-11ea-932e-ff2ff42de4f4.png)
![image](https://user-images.githubusercontent.com/23565141/68992650-7294ca80-086e-11ea-8a17-d9295c3686a3.png)

This answers my question i guess. The timing is perfect haha.

**Comment by NikolarnTV** [comment]
Well, i'm back on:
![image](https://user-images.githubusercontent.com/23565141/68992888-cce35a80-0871-11ea-87a9-402204cf2e6f.png)

And now that i got it to work it's stuck again:
![image](https://user-images.githubusercontent.com/23565141/68992892-d66cc280-0871-11ea-9b05-c28845c03bd7.png)

**Comment by gre** [comment]
We expect this to be fixed in context of a big rework that just got merged. we'll reopen in this does not fix in the next release https://github.com/LedgerHQ/ledger-live-desktop/pull/2596
