### ISSUE TITLE
Unable to view Receive address because device disconnects

### ISSUE THREAD

**Issue by 4NobleTruths** [LedgerHQ/ledger-live-desktop#2471]
#### Ledger Live Version and Operating System

- tested on Ledger Live **ledger-live-desktop-1.18.2-linux-x86_64 and previous version**
- Platform and version: **Debian 9 VM on Qubes R4.0**
- Device: NanoS with latest firmware.

#### Expected behavior

This is in the dialog to connect device and open coin app to get the receiving address.
So, the expected behavior is that I get the receive address on PC and on NanoS.

#### Actual behavior

This dialog appears, after Nano is unlocked and connected.
![ledger1](https://user-images.githubusercontent.com/7483645/69003964-dcf74a80-0902-11ea-9acd-69e7d73aa7be.png)

Then when the Nano buttons are pressed to enter the coin app, as the dialog instructs, the dialog changes to this:

![ledger2](https://user-images.githubusercontent.com/7483645/69003984-35c6e300-0903-11ea-84da-4c2b3528b21e.png)

Remains this way indefinitely.
Relevant system log entries attached.

[ledgerNano.log](https://github.com/LedgerHQ/ledger-live-desktop/files/3855299/ledgerNano.log)

#### Steps to reproduce the behavior

Restart Ledger LIve app.
Reconnect to this machine and try to receive address for any coin app.

I tried removing all the coin apps and reinstalling them through Ledger Live Manager.
That works without any problems.
So, the machine makes a connection with the Nano successfully.

Tried all the other steps on this page:
https://support.ledger.com/hc/en-us/articles/115005165269-Fix-connection-issues
 
This and another NanoS work as expected on Ubuntu based machine with same  Ledger cable.

**Comment by juan-cortes** [comment]
@meriadec wdyt?

**Comment by gre** [comment]
@4NobleTruths can you try to use "Experimental USB" to see if it improve the situation? Thanks

**Comment by 4NobleTruths** [comment]
@gre Thanks.
Same problem with Experimental USB.

**Comment by gre** [comment]
We expect this to be fixed in context of a big rework that just got merged. we'll reopen in this does not fix in the next release https://github.com/LedgerHQ/ledger-live-desktop/pull/2596

**Comment by initCCG** [comment]
We have a similar setup and several ledgers. Gave up on using them with Qubes, until now when we needed to use U2F from them to log in.
After the big rework, even latest  Ledger Live doesn't detect the Ledgers at all.
Websites also don't, but dedicated U2F keys from other manufacturers work ok on same devices.

**Comment by 4NobleTruths** [comment]
It finally works again, after only 2 years since this was closed! Well done!
