### ISSUE TITLE
Easy, normal gpg signature, or similar

### ISSUE THREAD

**Issue by nottoseethesun** [LedgerHQ/ledger-live-desktop#2525]
- [ x] I have checked this feature was not yet requested: It has been requested, but the issue(s) were closed, and the feature is not available (e.g., https://github.com/LedgerHQ/ledger-live-desktop/issues/942 )

Provide a normal gpg signature, or rough equivalent, such as at: https://electrum.org/#download 

I understand that for Windows and macOS, the os tool for signing is used, but for Linux, there is currently nothing available for ledger-live.

#### Part of the application

The application would be satisfactorily verified to not be malware.

**Comment by gre** [comment]
https://ledger-live-tools.now.sh/lld-signatures

**Comment by adrelanos** [comment]
I am wondering how to interpret closing this ticket with comment `https://ledger-live-tools.now.sh/lld-signatures`. Does that mean "we have `openssl` signatures, use that instead"?

`https://ledger-live-tools.now.sh/lld-signatures` provides instructions how to verify ledger live using `openssl`.

This ticket was a request to implement `gpg` signatures. Having `gpg` signatures, which is the de-facto standard for Linux, would be great!

Can closing this ticket be interpreted as refusal to provide `gpg` signatures for ledger live downloads?

Certainly nobody has a right to `gpg` signatures, however confirmation would be appreciated to avoid any chance of miscommunication.
