### ISSUE TITLE
Sync Error on new Update

### ISSUE THREAD

**Issue by AlexandrinhoX** [LedgerHQ/ledger-live-desktop#2552]
Hello,
today I installed the wallet update 1.19.2 and since now I can´t synchronize my wallet anymore.
It´s actually "Synchronizing" for 4 hours now.
Windows 10 x64

Any ideas on how to solve that?

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. We prefer to investigate such issues via contacting our customer support team.

could you send your logs to our support team and mention this github issue? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏  basically you can press Ctrl+E just after the error occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.netlify.com/logsviewer )
