### ISSUE TITLE
BUG: Internal process error (null)

### ISSUE THREAD

**Issue by Kartereo** [LedgerHQ/ledger-live-desktop#2555]
#### Ledger Live Version and Operating System

Ledger Live 1.19.2
Pop!OS 19.10 eoan (u-dev rules active)

#### Expected behavior

It should have searched and then added Bitcoin to Ledger Live

#### Actual behavior

Internal process error (null)

#### Steps to reproduce the behavior

Open Ledger Live
Click Accounts
Click Add accounts
Select Bitcoin
Click Continue and open Bitcoin app on Nano X
Click Continue
then....
![Screenshot from 2019-12-11 16-02-09](https://user-images.githubusercontent.com/5624644/70660574-8692d880-1c30-11ea-81c9-bc4b74f7d8cc.jpg)

I have also removed the app image and reinstalled and the same issue occurs. The last two updates have not worked for the app image.

**Comment by gre** [comment]
We expect this to be fixed in context of a big rework that just got merged. we'll reopen in this does not fix in the next release #2596
