### ISSUE TITLE
PROBLEM! Allow Ledger Manager on your Nano X

### ISSUE THREAD

**Issue by volkmar-guido-hable** [LedgerHQ/ledger-live-desktop#2561]
A seemingly epidemic problem is to permit Ledger Manager on Nano X. - Ledger Live **1.19.2**

One possible solution is to
1. connect Nano x by USB cable, not Bluetooth
2. enter your Nano x PIN
3. go to Ledger Manager, -> Settings, -> Help and hit the 'Clear Cache' button
4. Restart Nano x
5. Restart Ledger Manager

Problem should be fixed.

**Comment by gre** [comment]
We expect this to be fixed in context of a big rework that just got merged. we'll reopen in this does not fix in the next release https://github.com/LedgerHQ/ledger-live-desktop/pull/2596
