### ISSUE TITLE
Archlinux dependency gconf

### ISSUE THREAD

**Issue by oberon-manjaro** [LedgerHQ/ledger-live-desktop#2579]
The package currently available from the Arch User Repository uses the provided appimage for installation of the binary:
https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=ledger-live-bin
The installed package for some reason still depends on deprecated **gconf**:
```
ledger-live-desktop: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```
While a legacy package of **gconf** is still available in the AUR, it will of course be desirable to get rid of this outdated dependency.
Now since neither the source code directly seems to reference gtk, nor does current **electron** still depend on **gconf** I wonder where the actual link to the library is still being created.
My guess is this happens at some point during creation of the appimage, anyway...?
Could you maybe shed some light into how we can remove gconf as a dependency?

Thank you in advance.

**Comment by MortalKastor** [comment]
gconf is indeed a dependency from the older version of Electron we currently use.
We currently are working on migrating to the latest version which should fix the issue.

**Comment by oberon-manjaro** [comment]
Ok. Very good. Thank you for your reply.

**Comment by AndydeCleyre** [comment]
@MortalKastor 

Before I open a new issue, is this the same or similar case for `python2`? The README says "Python v2.7.10 (used by node-gyp to build native addons)" while node-gyp says it can use "Python v2.7, v3.5, v3.6, or v3.7"

**Comment by MortalKastor** [comment]
@AndydeCleyre you're absolutely right, node-gyp finally supports python 3 since October, and `lib-ledger-core-node-bindings` has been updated accordingly last month, so there is no requirement for python2 anymore, I'll update the README.

Thanks for the heads-up!
