### ISSUE TITLE
Ledger Live 1.20.0 doesn't recognize my NANO S

### ISSUE THREAD

**Issue by 0815pascal** [LedgerHQ/ledger-live-desktop#2580]
#### Ledger Live Version and Operating System

- tested on Ledger Live **1.20.0**
- Platform and version: **Mac 10.15.2 / Windows 10**
- Ledger Nano S Firmware: 1.5.5 / MCU 1.7

#### Expected behavior

I wanted to receive Bitcoin and used the receive button.

#### Actual behavior

 It prompts me to connect and unlock my ledger, which I did but it just doesn't recognize my ledger, it's stuck on that screen. 
#### Steps to reproduce the behavior

I have read somewhere in a reddit forum that uninstalling ledger live and installing version 1.7.0 helps – which indeed did! I could create a receive address again. However, ledger live then updated manually to version 1.20.0 where I'm having the same problem again. I then tried to clear all the data from ledger live and initialize my ledger again, however now I'm stuck at the genuity check with exact the same problem again. 

<img width="732" alt="Bildschirmfoto 2020-01-15 um 23 31 28" src="https://user-images.githubusercontent.com/11842633/72477182-43a7c000-37ef-11ea-8471-bfff8f3e0b7d.png">

**Comment by Zizaerion** [comment]
If you can, I'd try to enable the experimental usb setting under the Experimental settings.  If you can't get the device to be recognized, that's helped the majority of people.

**Comment by 0815pascal** [comment]
Thanks but unfortunately this doesn't solve the problem for me.

**Comment by Zizaerion** [comment]
is that on macOS or windows that the experimental usb setting doesn't work?  On windows and linux mint I haven't had a problem.  Not sure about macOS though.  On windows, I would check to make sure that drivers are up-to-date also.

**Comment by Jemel7** [comment]
I have been MONTHS trying to withdraw my bitcoin from my Nano s.  Ledger Support of no help. 

 I did a test withdrawal about 10 days ago with no problem.  

I have Mac OS.   The Nano S is definitely communicating with Ledger Live.  However, I get stuck at "Application is Ready" as the message on the Nano.  I cannot confirm the transaction on the Nano.  

I have installed and uninstalled Ledger Live.  I have gone through the process on two different desktops.

**Comment by Luuk2016** [comment]
> I have been MONTHS trying to withdraw my bitcoin from my Nano s. Ledger Support of no help.
> 
> I did a test withdrawal about 10 days ago with no problem.
> 
> I have Mac OS. The Nano S is definitely communicating with Ledger Live. However, I get stuck at "Application is Ready" as the message on the Nano. I cannot confirm the transaction on the Nano.
> 
> I have installed and uninstalled Ledger Live. I have gone through the process on two different desktops.

If you are already waiting months to withdraw some BTC, why don't you just try Electrum?

**Comment by gre** [comment]
Can you retry on Ledger Live 2.0.0 ?
Thanks

**Comment by 0815pascal** [comment]
It seems to work now :) at least I managed to initialize the ledger and I even could install a new version of the Bitcoin app via the manager (I always had issues with the manager). However, when I tried to make a transaction to an exchange, the connection two the Ledger was two times "lost". Only in the third time it worked. I cannot make much sense of this – does it mean that there might be an issue with my USB cable?

**Comment by gre** [comment]
That's very curious issue. It could be a faulty cable yes, I had a few cables like that in the past, also it can be issues on the USB port (computer OR nano S).

could you send your logs to our support team and mention this github issue? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏  basically you can press Ctrl+E just after the problem occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.now.sh/logsviewer )

**Comment by 0815pascal** [comment]
Sure, will do when it occurs the next time – thank you!

**Comment by Jemel7** [comment]
For those of you who responded to my concerns mentioned above, thanks.  I will spare you the details of the on-going saga.  With Ledger support taking 8 days to respond with boiler plate answers to questions I did not ask, I was exasperated.  

I found a local consultant.  He was supportive via email initially. Still no success. And then I visited his office for 90 minutes when he finally admitted that he could not solve the issue.  In fact, he did have the answer (I will share in a moment), but for some reason it did not work.  For hardware, together we used the original nano s, a fresh nano s, a Trezor (all mine), two different usb cables, 4 different usb ports and 3 computers.  For software, we both used ledger live and Electrum.

And finally to the solution ... When I got back home, I downloaded the electrum wallet on my secondary computer.  (I had downloaded, installed, uninstalled, several times on my primary computer.)  I decided to "start fresh" and that seemed important to my state of mind, even if not to the technology.  I set an Electrum wallet up with my 24 seed words.  And I withdrew my Bitcoin.  Drum Roll Please!

My next step is to put the 2 nanos and the trezor in a bag and smash them with a hammer.

**Comment by gre** [comment]
@Jemel7 I'm sorry for the bad experience, we need more detail to understand the root cause of the problem.

all: Please ack that we have an ongoing situation for Linux too that we are working on solving #2670

**Comment by Jemel7** [comment]
Not a chance.

No more time on nano S.

**Comment by cemmdlll** [comment]
I have the same problem

**Comment by cemmdlll** [comment]
I need to go to my sign in page of my ledger live and dtart the update all over again. How can I do that?

**Comment by sruocco-i2r** [comment]
Using Linux Mint 19.3 (Ubuntu-based) with kernel 5.4.0-58-generic. Ledger Live 1.19 -> Manager would NOT recognize my inserted Ledger S and X. No matter how many udev rules I tweaked and reloaded. Eventually I downloaded Live 1.18 (downgrade) and it immediately recognized X (S to try).

**Comment by randomisresistance** [comment]
> Using Linux Mint 19.3 (Ubuntu-based) with kernel 5.4.0-58-generic. Ledger Live 1.19 -> Manager would NOT recognize my inserted Ledger S and X. No matter how many udev rules I tweaked and reloaded. Eventually I downloaded Live 1.18 (downgrade) and it immediately recognized X (S to try).

Same here, works with 2.18 but not with 2.19

**Comment by MatthewCochrane** [comment]
Same here, 2.19 isn't working.  I don't have 2.18 lying around but 2.7.0 worked fine.

**Comment by vishwatiwari** [comment]
I also had same issue. Ledger device was asking pin but ledger live could not recognize it.  I tried many cables but most of them were charging only cables and I was not aware of this. Finally one data transfer cable of Samsung worked.

**Comment by alereisan** [comment]
impossible to connect Ledger Live 2.21.3 Desktop MAC to Ledger Nano S

**Comment by mlinniee** [comment]
Hi, I have the same problem right now. Been trying to get my assets out of my ledger but it doesnt seem like its seeing the connection. I does light up and let my enter my PIN but after that nothing happens. Can anyone help? I have tried previous versions and all the other steps but nothing seem to work.

Thanks in advance!

**Comment by mfulz** [comment]
I've the same issue on arch linux last working version is 2.29 starting from 2.30 the ledger device isn't recognized anymore.

**Comment by franco999** [comment]
I don't know if this issue is the right place for this, but I need to fix it.

After upgrading Ledger Live to **v2.35** and Nano S firmware **v2.0** from Linux Mint 20 (Kernel 5.11), it no longer lets me access my device from Linux. However, from my Android device the USB connection works.
 
I have searched for some solution, tried installing older versions and development versions (2.36), deleted configuration files and nothing worked for me.

Any solution?

![ledger live](https://user-images.githubusercontent.com/12088580/144941439-9ca7280c-d0c1-40f7-9fe6-b9a5742095db.png)
