### ISSUE TITLE
Sync theme with Windows

### ISSUE THREAD

**Issue by Zaczero** [LedgerHQ/ledger-live-desktop#2583]
- [x] I have checked this feature was not yet requested.

Ledger live's theme selection should have a possibility to sync with current Windows settings. Right now you can change the theme but having it change automatically would be a welcome feature.

There is a registry entry for that:
CURRENT_USER Software\Microsoft\Windows\CurrentVersion\Themes\Personalize\AppsUseLightTheme
When the *AppsUseLightTheme* value is 1 then Windows is in light mode. 0 is for dark mode.

#### Part of the application

Settings > General > Theme

**Comment by gre** [comment]
We expect this to be fixed in context of a big rework that just got merged. we'll reopen in this does not fix in the next release https://github.com/LedgerHQ/ledger-live-desktop/pull/2596
