### ISSUE TITLE
Theme being applied with delay after starting the app

### ISSUE THREAD

**Issue by Zaczero** [LedgerHQ/ledger-live-desktop#2585]
#### Ledger Live Version and Operating System

- tested on Ledger Live **1.20.0**
- Platform and version: **latest Windows 10**

#### Expected behavior

When starting the application and using one of the dark themes the theme should be visible instantly and not after few seconds in (i'm talking about the loading screen). Maybe the theme value should not be contained inside user config and rather some external file/registry so it can be fetched a lot earlier before the UI is even active.

#### Actual behavior

There is like 0.7 second delay while starting the app when the load screen is using the default light theme and not the custom user-one.

#### Steps to reproduce the behavior

1. Set Settings > General > Theme to Dark or Dusk
2. Exit Ledger Live
3. Start Ledger Live again
4. Stare patiently on the loading screen and get blinded by this beautiful light theme

**Comment by gre** [comment]
We expect this to be fixed in context of a big rework that just got merged. we'll reopen in this does not fix in the next release https://github.com/LedgerHQ/ledger-live-desktop/pull/2596
