### ISSUE TITLE
Ledger Live Linux not working - fixed !!!

### ISSUE THREAD

**Issue by lamart1** [LedgerHQ/ledger-live-desktop#2660]
I tried Ledger Live and it was not working, no resposne. I run it through terminal and saw "error while loading shared libraries: libgtk-x11-2.0.so.0" ... this fixed it "sudo apt install libgtk2.0-0:i386
"  https://askubuntu.com/questions/836142/error-while-loading-shared-libraries-libgtk-x11-2-0-so-0-no-such-file-or-direc

**Comment by gre** [comment]
ok thanks :) this might be useful for other users if they search this issue. I suspect however that this issue will be fixed in our upcoming release that have upgraded Electron and Chromium.
