### ISSUE TITLE
Zcash Transaction Failure - Script evaluated without error but finished with a false/empty top stack element

### ISSUE THREAD

**Issue by michaelhly2** [LedgerHQ/ledger-live-desktop#2665]
#### Ledger Live Version and Operating System

Device: Ledger Nano S
Firmware: 1.4.2 
Ledger Live Version: 1.20.0
Platform and version: Mac 10.14.5

#### Expected behavior

Should properly sign and send transaction.

#### Actual behavior
The server could not handle your request. Please try again at a later moment. 
```
{"result":null,"error":{"code":-26,"message":"16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element)"},"id":5260411}
```
#### Steps to reproduce the behavior
Go through the standard steps to send Zcash transaction via Ledger Live.

### Note
I can't find my recovery phrase and can only access my coins through my PIN right now. Cannot upgrade device firmware to 1.6.0 without risk of losing funds.

**Comment by michaelhly2** [comment]
Update on this issue. How come ledger live will only let me install Zcash version 1.2.11? I read that there exists a version 1.3.17 [here](https://www.reddit.com/r/ledgerwallet/comments/ek5h0t/ledger_nano_x_wallet_error_when_sending_zcash/).

**Comment by michaelhly2** [comment]
I updated the Bitcoin App to 1.3.2 and then reinstalled Zcash app (still 1.2.11), now it won't let me confirm the transaction on my device. 

Log: https://gist.github.com/michaelhly2/ed96a5485f9b7892d4c5b6fc5b78383c#file-ledgerlive-logs-2020-03-05-20-10-40-f44c4a5a1824be56f8239de1cc6080b4cf3a31fd-json

**Comment by michaelhly** [comment]
@btchip Can you help me?

**Comment by michaelhly2** [comment]
@btchip Can you help me with this?

**Comment by cthepot-ledger** [comment]
Kindly open a ticket with Customer Support. I'm assuming this has been fixed on your side. If you have found your recovery phrase kindly upgrade the firmware for a tentative fix
