### ISSUE TITLE
cannot send xtz due to malformed field while getting fees

### ISSUE THREAD

**Issue by JorisM** [LedgerHQ/ledger-live-desktop#2666]
#### Ledger Live Version and Operating System
- tested on Ledger Live **1.20.0** and **2.0.0**
- Platform and version: **Fedora 31**

#### Expected behavior

I want to send some xtz to an address

#### Actual behavior

I get the following error: 

    Failed to get fees from network, no (or malformed) field "result" in response
#### Steps to reproduce the behavior

![image](https://user-images.githubusercontent.com/294174/75884943-ee1e8580-5e25-11ea-89a0-f5377f3803ee.png)

**Comment by gre** [comment]
Thanks for the issue,

we are aware of the situation in our explorers and are working on fixing it.
