### ISSUE TITLE
Looks like it just wasn't only me, Linux 19 mint Trina user here, Linux pooped out on me in everyway everyone else described their issues.  

### ISSUE THREAD

**Issue by JamesSeeley27** [LedgerHQ/ledger-live-desktop#2676]
The problem I'm having now is, after I did the update to I wouldve hoped, stopped the endless syncrohnization and finally update.  It gave me the error log, so I decided to just restart anyway, I've downloaded on version on my moms windows 10 to check if everything is ok, it all loaded fine, SO there's BIG connectivity issues going on with Ledgers new update for linux.  And I tried following command line protocol, my computer picked up NONE of your suggestions. 

#### Ledger Live Version

- Ledger Live **version_here**

**Comment by gre** [comment]
Probably due to #2670

**Comment by JamesSeeley27** [comment]
Still being worked on?  Will keep the Linux Ledger live community informed?  My linux mint updates are fine, this all started when I just chose to sensibly update.  What should I do in the mean time?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by gre** [comment]
as said in https://github.com/LedgerHQ/ledger-live-desktop/issues/2670#issuecomment-594809280 , you can stay on 1.20.0 (and don't apply the update). We are investigating on this.

**Comment by JamesSeeley27** [comment]
I already did all that.  And I did a reset.  So wait I guess, while investigation is on going?  Cause primarily when I try to do recovery phrase, or new device, it tries to verify authenticity of device.  So I'm assuming it's ledger just not picking it up correct?  Give me some peace of mind here at least.

Much appreciated,
I love your guys product!  Beats Trezor, lol.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by gre** [comment]
Just to be clear the problem is independent of the ledger device itself (your device and funds are fine). it is related to the GLIBC version that Ledger Live software depends on, it seems our last build requires >= 3.4.26 but we will try to make sure it works with older version of GLIBC. It impacts account synchronisation and device connection.

Yes you can stay on 1.20.0 and wait for a fix. We are actively working at solving this situation. Sorry for inconvenience.

**Comment by JamesSeeley27** [comment]
These logs attached prove, that consecutively that a phishping scam must have apprehened the key to my ledger somehow, through Metamask, and I cannot reintegrate my old ethereum account at all for the last two days. It keeps saying this. These snapshots are over two days, first done during my sleep agaisnt my will, and my ledger was disconnected and laptop turned off. I've lost access to potentially 3k of crypto. Please help!!!!![IMG_20201023_220959_9.jpg]T

Synchronization errorSome accounts could not be synchronized.Learn more

I had everything on that one account. Please HELP!!! THIS IS ALL I HAD. [IMG_20201023_211318_4.jpg][IMG_20201023_211400_4.jpg]

Sent with [ProtonMail](https://protonmail.com) Secure Email.
