### ISSUE TITLE
How do I activate KickToken price?

### ISSUE THREAD

**Issue by proaktiv** [LedgerHQ/ledger-live-desktop#2679]
#### Ledger Live Version

- Ledger Live 2.0.0

I trade KickToken and want to see the current price in my Ledger Live. Why did you deactivate the price for everyone? You'd better implement an option where users can choose whether to see the kick price or not.

**Comment by gre** [comment]
We might offer a user feature to re-activate disabled token, but no ETA for now.

We are more likely to offer a way to let our users **blacklist** token in the future if this kind of situation happen again in the future. If KICK is ever tradable and have the announced market value we can consider re-adding it =)
