### ISSUE TITLE
[Windows] Ledger Live 2.0.0 and 2.0.1 fails to boot with Internal Process Error – ledger-core-node.node load fail

### ISSUE THREAD

**Issue by gre** [LedgerHQ/ledger-live-desktop#2680]
**N.B.** this issue only track **Windows**, for Linux, please check status on https://github.com/LedgerHQ/ledger-live-desktop/issues/2670

![](https://user-images.githubusercontent.com/61806005/75931751-8dde1280-5e2a-11ea-87f7-d049efbf1519.jpg)

underlying reason is it can't seem to load `ledger-core-node.node` file.

We are investigating on it. We know it happens for a few users.

### Providing logs could help us

could you send your logs (SAVE on the error screen) to our support team and mention this github issue? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏  ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.now.sh/logsviewer )

### Technical investigation are welcomed

Ideally we need to identify what is the "common denominator" (is it special computer? related to the OS? related to an antivirus? related to accounts you could have before upgrading?). We usually need a way to reproduce the problem so we can understand what bug there is to fix.

---

One thing you can attempt is to remove (or rename) the folder of the "Ledger Live" user data. The folder that is saved by Ledger Live at **`%APPDATA%\Roaming\Ledger Live`** (NB: which is not the installation folder) – it should work if you paste that in a file browser. Otherwise if you see hidden files, it's usually under `C:\Users\<username>\AppData\Roaming\Ledger Live` )

**Comment by franci** [comment]
Same error in Ubuntu after Ledger Live update

**Comment by gre** [comment]
@franci 

This issue can happen for various reasons. We prefer to investigate such issues via contacting our customer support team.

could you send your logs to our support team and mention this github issue? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏  basically you can press Ctrl+E just after the problem occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.now.sh/logsviewer )

**Comment by kushothyleoma** [comment]
I have the same problem happened 2 days ago. Any updates? thanks

**Comment by gre** [comment]
**This is our highest priority of bug to fixed.** Sadly, this issue went completely unnoticed during our internal QA testing as well as our beta program testing. It seems to affect only a few users. Anyone technical is welcomed to try to help on this topic because our current struggle is that no one in the team can reproduce the issue (we tried on various computers and we were not able to reproduce the issue)

Ideally we need to identify what is the "common denominator" (is it special computer? related to the OS? related to an antivirus? related to accounts you could have before upgrading?). We usually need a way to reproduce the problem so we can understand what bug there is to fix.


One thing you can attempt is to remove (or rename) the folder of the "Ledger Live" user data. The folder that is saved by Ledger Live at **`%APPDATA%\Roaming\Ledger Live`** (NB: which is not the installation folder) – it should work if you paste that in a file browser. Otherwise if you see hidden files, it's usually under `C:\Users\<username>\AppData\Roaming\Ledger Live` )

Thanks

**Comment by kushothyleoma** [comment]
Hey i uninstalled the app and deleted the Ledger Live folder in appdata. I
reinstalled ledger live and i get the same error. I think it was because i
did not update windows before the 2.0.0 update :( i will try on a different
PC

**Comment by kushothyleoma** [comment]
Hey i tryed on a different PC Windows 10 64bit. I updated the firmware on
my ledger nano s from 1.5.5. to 2.0.0 reinstalled the apps and accounts.
Now everything seems to be working fine :) thanks for your help!! Maybe the
PC is was using before had an update bug?

**Comment by yelllowsin** [comment]
Having the same issue here on Win 7 x64. Tested on both 2.0.0 and 2.0.1. Any fix for this?

![image](https://user-images.githubusercontent.com/7217595/76163592-22e05480-6126-11ea-9879-ad3cd1fc231a.png)

```
Internal process error (1)
Error
    at createCustomErrorClass (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:9690:17)
    at deserializeError (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:9723:25)
    at EventEmitter.handleCommandEvent (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:257937:61)
    at EventEmitter.emit (events.js:215:7)
    at Object.onMessage (electron/js2c/renderer_init.js:2181:16)
```

```
redux failed: Cannot read property 'store' of null
TypeError: Cannot read property 'store' of null
    at ConnectFunction (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:560:70)
    at Ih (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157157:98)
    at si (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157177:273)
    at ri (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157177:103)
    at pi (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157176:178)
    at gk (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157269:63)
    at fk (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157233:22)
    at Zj (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157232:362)
    at Lj (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157226:216)
    at file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157124:115
```

**Comment by yelllowsin** [comment]
Where can i find a link to download an old version that works? I need version 1.x.

**Comment by 13albra** [comment]
@yelllowsin 
https://github.com/LedgerHQ/ledger-live-desktop/releases/tag/v1.20.0

**Comment by yelllowsin** [comment]
@13albra Thank you bro, that worked for now.

**Comment by LordCube24** [comment]
Hi, the same problem..had it on win7ult 64 and win10pro 64, so i think it is not the windows problem...

**Comment by gre** [comment]
Again I would like to remind that we need to identify what is the "common denominator":
- is it special computer? any special setup on this computer we need to be aware of?
- related to the OS?
- related to an antivirus or firewall?
- related to accounts you could have before upgrading?).
- is there any specific thing we need to know about your **filesystem**, especially on which disk is installed ledger live. is it NTFS? do you have space in your username? do you have accents or non ascii character in your user name?

We usually need a way to reproduce the problem so we can understand what bug there is to fix.

**Comment by kilo666** [comment]
brand new and fresh install of win10 x64 on a lenovo laptop
no active AV or firewall apart from win10 defender etc
cannot even start the program as admin or normal user, can restart Ledger Live but then the app does not recognise nano S (tried with 2 duplicate nano s' - one with firmware 1.4.1, other with 1.4.2.  MCU 1.5

**Comment by kilo666** [comment]
Internal process error (1)
Error
    at createCustomErrorClass (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:9690:17)
    at deserializeError (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:9723:25)
    at EventEmitter.handleCommandEvent (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:257937:61)
    at EventEmitter.emit (events.js:215:7)
    at Object.onMessage (electron/js2c/renderer_init.js:2181:16)
redux failed: Cannot read property 'store' of null
TypeError: Cannot read property 'store' of null
    at ConnectFunction (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:560:70)
    at Ih (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157157:98)
    at si (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157177:273)
    at ri (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157177:103)
    at pi (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157176:178)
    at gk (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157269:63)
    at fk (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157233:22)
    at Zj (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157232:362)
    at Lj (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157226:216)
    at file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157124:115

**Comment by ledgeruser2** [comment]
I had the same problem. Just bought my x and s and got this from the start. Still had this problem as of an hour ago. But now it works. Someone humor me and try this....
Restart your computer FIRST (because once it crashes I have seen stuck processes).
Go to default apps in settings and hit reset (try it even if you have never changed your default apps)
Run ledger.
If this wasn't it, I made changes in Firefox that should have nothing to do ledger, so i'm stumped.

**Comment by ledgeruser2** [comment]
I had the same problem. Just bought my x and s and got this from the start. Still had this problem as of an hour ago. But now it works.
I have not yet figured out how I made it go away.

**Comment by PatrickH83** [comment]
Hello,

I have the same problem!
When I deinstall 2.0.1 and install an older Version again, my Password is not working.

**Comment by gre** [comment]
@PatrickH83 this is expected. the v2 is not retrocompatible if you go back to v1. to install older version, you need to Reset (the user data folder).


everyone else, could you please answer the question I shared above? also one question, regarding the specific issue, this is due to loading a specific file. Could you help us checking what this file permission is?

- right click on Ledger Live icon, Open folder location
- in the folder, resources > app.asar.unpacked > node_modules > @ledgerhq > ledger-core > build > Release , do you see a file “ledger-core-node.node” ?
- if you right click and open Properties and go to Security section, what are the file permissions?

**Comment by kilo666** [comment]
> 
> 
> @PatrickH83 this is expected. the v2 is not retrocompatible if you go back to v1. to install older version, you need to Reset (the user data folder).
> 
> everyone else, could you please answer the question I shared above? also one question, regarding the specific issue, this is due to loading a specific file. Could you help us checking what this file permission is?
> 
>     * right click on Ledger Live icon, Open folder location
> 
>     * in the folder, resources > app.asar.unpacked > node_modules > @LedgerHQ > ledger-core > build > Release , do you see a file “ledger-core-node.node” ?
> 
>     * if you right click and open Properties and go to Security section, what are the file permissions?

read and execute = allow
read = allow

remainder are unchecked and clear

**Comment by MapleCoin** [comment]
Same problem.
I have a brandnew Lenovo with Win 10 64bit.
No antivirus at all but Ledger Live won't work

Should I install an older version?

**Comment by reb850** [comment]
> 
> 
> > 
> 
> @gre
> 
> > everyone else, could you please answer the question I shared above? also one question, regarding the specific issue, this is due to loading a specific file. Could you help us checking what this file permission is?
> > ```
> > * right click on Ledger Live icon, Open folder location
> > 
> > * in the folder, resources > app.asar.unpacked > node_modules > @LedgerHQ > ledger-core > build > Release , do you see a file “ledger-core-node.node” ?
> > 
> > * if you right click and open Properties and go to Security section, what are the file permissions?
> > ```
> 
> read and execute = allow
> read = allow
> 
> remainder are unchecked and clear

@gre 
Mine are exactly the same 

I uploaded my logs a few days ago.

**Comment by madjicc** [comment]
Hello

I have the same problem, more synchronization and my nano s key is no longer recognized.

 My config: windows 10 family 64 bits, avast antivirus.
ledger-core-node.node  permissions  read and execute = allow      read = allow

**Comment by mkjmkjmkj** [comment]
> @PatrickH83 this is expected. the v2 is not retrocompatible if you go back to v1. to install older version, you need to Reset (the user data folder).
> 
> everyone else, could you please answer the question I shared above? also one question, regarding the specific issue, this is due to loading a specific file. Could you help us checking what this file permission is?
> 
> * right click on Ledger Live icon, Open folder location
> * in the folder, resources > app.asar.unpacked > node_modules > @LedgerHQ > ledger-core > build > Release , do you see a file “ledger-core-node.node” ?
> * if you right click and open Properties and go to Security section, what are the file permissions?

File is present:
-rwxr-xr-x 1 root root 75821024 Feb 28 15:45 ledger-core-node.node

**Comment by Blazms** [comment]
Hi, I have the same problem
When I logged in my ledger live there was an option to install, just like sometimes is to update, I don't know what for was this window open with option to install something?
I clicked on install, because I thought it's something important to do and after this happened.
I contacted support few times and didn't get any answer

**Comment by leopold1881** [comment]
> > 
> 
> @gre
> 
> > everyone else, could you please answer the question I shared above? also one question, regarding the specific issue, this is due to loading a specific file. Could you help us checking what this file permission is?
> > ```
> > * right click on Ledger Live icon, Open folder location
> > 
> > * in the folder, resources > app.asar.unpacked > node_modules > @LedgerHQ > ledger-core > build > Release , do you see a file “ledger-core-node.node” ?
> > 
> > * if you right click and open Properties and go to Security section, what are the file permissions?
> > ```
> 
> read and execute = allow
> read = allow
> 
> remainder are unchecked and clear

same

**Comment by tensaibbqchicken** [comment]
> > 
> 
> @gre
> 
> > everyone else, could you please answer the question I shared above? also one question, regarding the specific issue, this is due to loading a specific file. Could you help us checking what this file permission is?
> > ```
> > * right click on Ledger Live icon, Open folder location
> > 
> > * in the folder, resources > app.asar.unpacked > node_modules > @LedgerHQ > ledger-core > build > Release , do you see a file “ledger-core-node.node” ?
> > 
> > * if you right click and open Properties and go to Security section, what are the file permissions?
> > ```
> 
> read and execute = allow
> read = allow
> 
> remainder are unchecked and clear

Same as well

**Comment by Blazms** [comment]
Hi,

Thanks for reply.
I just checked and it was already like this.
read and execute = allow

read = allow

remainder are unchecked and clear


So still same, doesn't work, every time I open and close ledger live app,
have to restart computer to open it again and click few times to open.

Is it possible to go back to ledger live 2.0.0 before was good?

If I install ledger live in different computer, would it work?

Please if you can help me, because I can't access my funds and support also
didn't answer.

Thank you









V pet., 13. mar. 2020 21:45 je oseba Leopold Chow <notifications@github.com>
napisala:

**Comment by Blazms** [comment]
Hi,

Thanks for reply.
I just checked and it was already like this.
read and execute = allow

read = allow

remainder are unchecked and clear


So still same, doesn't work, every time I open and close ledger live app,
have to restart computer to open it again and click few times to open.

Is it possible to go back to ledger live 2.0.0 before was good?

If I install ledger live in different computer, would it work?

Please if you can help me, because I can't access my funds and support also
didn't answer.

Thank you




V pet., 13. mar. 2020 21:52 je oseba tensaibbqchicken <
notifications@github.com> napisala:

**Comment by Coingraph** [comment]
i have same problem too i use  windows 10 64bt  The problem is that I cannot transfer or receive any currency  Even there are transfers I haven't received that haven't been in the wallet for more than 4 days  please help me    thanks

**Comment by Mohitmalhotra20** [comment]
> Having the same issue here on Win 7 x64. Tested on both 2.0.0 and 2.0.1. Any fix for this?
> 
> ![image](https://user-images.githubusercontent.com/7217595/76163592-22e05480-6126-11ea-9879-ad3cd1fc231a.png)
> 
> ```
> Internal process error (1)
> Error
>     at createCustomErrorClass (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:9690:17)
>     at deserializeError (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:9723:25)
>     at EventEmitter.handleCommandEvent (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:257937:61)
>     at EventEmitter.emit (events.js:215:7)
>     at Object.onMessage (electron/js2c/renderer_init.js:2181:16)
> ```
> 
> ```
> redux failed: Cannot read property 'store' of null
> TypeError: Cannot read property 'store' of null
>     at ConnectFunction (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:560:70)
>     at Ih (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157157:98)
>     at si (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157177:273)
>     at ri (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157177:103)
>     at pi (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157176:178)
>     at gk (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157269:63)
>     at fk (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157233:22)
>     at Zj (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157232:362)
>     at Lj (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157226:216)
>     at file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157124:115
> ```
> 
> When i restart the app it loads, but it can't verify that my ledger is genuine. Something is wrong here, also the app hangs when i close it, running in the background.

Its happeing with me also. From past 5 days i am trying but nothing working. Showing same above error.
![image](https://user-images.githubusercontent.com/62139076/76675223-1f911100-65dd-11ea-88b3-13de116487ba.png)

**Comment by gre** [comment]
At the moment unfortunately we still haven't found the reason of the bug. What we know is this happens on a few % of windows computers, we have in our offices exactly the same computers setup and only one of them reproduced it, but we didn't identified yet what is the trigger of this issue. Any help on this is welcomed.

At the moment, the way you can have a functional Ledger Live it to go back and stay on 1.20.0 until we find a fix and communicate here.

**Ledger Live 1.20.0** It can be downloaded on https://github.com/LedgerHQ/ledger-live-desktop/releases/tag/v1.20.0

**Comment by Mohitmalhotra20** [comment]
Thanks for the update. Let me do this and try to access.

Cheers!
Mohit

**Comment by Giffygods** [comment]
Hi all
Had the same problem with latest ledger live update 2.0.1...just as it's been mentioned multiple times above...
ThinkPad with up to date Win 10 64bit...
And even after deleting ledger live from appdata/roaming...and then installing old version 2.0.0 ...I would then get this same failure message popup...
Only fix for me was pop in a old ssd that I conveniently cloned/upgraded from a couple of weeks ago...V2.0.1 working fine...
Won't be installing ledger live updates until this is sorted out, not How I wanted to spend two hours of my evening...
I reported fault to ledger help desk...

**Comment by Giffygods** [comment]
Amendment to above....old version 2.0.0 now working fine, as before, prior to update issues..

**Comment by kilo666** [comment]
> At the moment unfortunately we still haven't found the reason of the bug. What we know is this happens on a few % of windows computers, we have in our offices exactly the same computers setup and only one of them reproduced it, but we didn't identified yet what is the trigger of this issue. Any help on this is welcomed.
> 
> At the moment, the way you can have a functional Ledger Live it to go back and stay on 1.20.0 until we find a fix and communicate here.
> 
> **Ledger Live 1.20.0** It can be downloaded on https://github.com/LedgerHQ/ledger-live-desktop/releases/tag/v1.20.0

ok going back to 1.20 works! now I can access my coins and sell them before the crash - oh wait!

**Comment by Bust563** [comment]
Here I am (window7 / 64bit) and I have the same problems mentioned above with version 2.0.1.
I already opened the ticket and sent the logs to the support center.
Please can anyone write instructions to get back to 1.20.0 as I would not want to go wrong.
Which folder exactly should be deleted before running 1.20.0?
What to do after installation. Will my password be accepted, what will happen to the accounts and balance? 
What to do after logging in after installing version 1.20.0?
I really don't want to mess something up ... and I urgently need access to my accounts!
And next time, I'll read the forums well before installing new versions, and you in the Ledger look out for the future, because it's money involved, and staying blocked is not a very nice feeling, especially not in moments like we are facing this days...!
Sorry for the grammar butt english is not my mother language.
If you can post it here will be nice,...maybe also helpful for someone else.
Thanks in advance for the help...

**Comment by Giffygods** [comment]
> Here I am (window7 / 64bit) and I have the same problems mentioned above with version 2.0.1.
> I already opened the ticket and sent the logs to the support center.
> Please can anyone write instructions to get back to 1.20.0 as I would not want to go wrong.
> Which folder exactly should be deleted before running 1.20.0?
> What to do after installation. Will my password be accepted, what will happen to the accounts and balance?
> What to do after logging in after installing version 1.20.0?
> I really don't want to mess something up ... and I urgently need access to my accounts!
> And next time, I'll read the forums well before installing new versions, and you in the Ledger look out for the future, because it's money involved, and staying blocked is not a very nice feeling, especially not in moments like we are facing this days...!
> Sorry for the grammar butt english is not my mother language.
> If you can post it here will be nice,...maybe also helpful for someone else.
> Thanks in advance for the help...

Busted....your funds are always safe on hardware wallet...the problems with the ledger live interface...
I'm not the most technical here....
As you mentioned your running live on the officially unsupported Win 7....let's not go into that as I indeed also run another copy of ledger live on a Windows 7 laptop as a backup I suppose...
Why don't you do a Windows system restore to a date prior to the ledger live update...then ledger live will be as before and sync...
Also it might to prodent to get hold of another cheap laptop, and install fresh copy of win 10, install all updates....and then install the old version of ledger live on in v2.0.0, it can be downloaded from GitHub..
The software will talk you through how to add a ledger wallet that has previously been set up....

**Comment by thevictor13** [comment]
> Again I would like to remind that we need to identify what is the "common denominator":
> 
> * is it special computer? any special setup on this computer we need to be aware of?
> * related to the OS?
> * related to an antivirus or firewall?
> * related to accounts you could have before upgrading?).
> * is there any specific thing we need to know about your **filesystem**, especially on which disk is installed ledger live. is it NTFS? do you have space in your username? do you have accents or non ascii character in your user name?
> 
> We usually need a way to reproduce the problem so we can understand what bug there is to fix.

Same issue here.

* Nothing special, brand new install of Windows 10 1909.
* Might be, but as said this is a pristine Windows install
* No antivirus/firewall apart from the built-in one
* Fresh install, no leftovers
* A bog standard NTFS partition as the installer created it, yes I do have a space in my username, but the user folder is a truncated - 5 char - version of it, without spaces (again, as windows creates it, nothing special).

**Comment by gre** [comment]
could any of you try to install "Redistributable Microsoft Visual C++ 2015"?

On our side this has fixed the issue. We're now looking at a way to address the issue even without having to install that.

Thanks

**Comment by WFAHM** [comment]
> Could any of you attempt to install "Visual C++ Redistributable for Visual Studio 2015"?
> 
> On our side this was confirmed to fix the present bug. We're now looking at a way to address the issue even without having to install that.
> 
> Thanks

This is the only thing that worked for me. Thanks!

**Comment by Bust563** [comment]
> 
> 
> Could any of you attempt to install "Visual C++ Redistributable for Visual Studio 2015"?
> 
> On our side this was confirmed to fix the present bug. We're now looking at a way to address the issue even without having to install that.
> 
> Thanks

Hi,
I installed "Visual C ++ Redistributable for Visual Studio 2015" as you suggested and now everything is working fine again!

Many thanks!

**Comment by mvj8016** [comment]
installed "Visual C ++ Redistributable for Visual Studio 2015 worked for some above

please in simple terms for those of us who have minimal computer knowledge, HOW IS THIS DONE STEP BY STEP ON A WINDOWS 8 LAPTOP? 

many thanks in advance for any help on this. I need to get ledger live working.

**Comment by jibeee** [comment]
> please in simple terms for those of us who have minimal computer knowledge, HOW IS THIS DONE STEP BY STEP ON A WINDOWS 8 LAPTOP?

Download and install https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by AzsumsiAzBG** [comment]
> 
> 
> Could any of you attempt to install "Visual C++ Redistributable for Visual Studio 2015"?
> 
> On our side this was confirmed to fix the present bug. We're now looking at a way to address the issue even without having to install that.
> 
> Thanks

Has done it and finally It's working..

**Comment by sevenKNG** [comment]
good day when installing the Visual C ++ package for Visual Studio 2015 for WINDOWS 10 x64, the Ledger Live 2.0.1 application starts and syncs = the NANO s device = is tied up and running normally.

**Comment by sevenKNG** [comment]
приложение https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by LanselotTartaros** [comment]
only thing special about my setup, my timezone was off an hour and my computer would not automatically update the time. I updated this and since the update before and after I have changed the timezone same issue.

Internal process error (1)
Error
    at createCustomErrorClass (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:9690:17)
    at deserializeError (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:9723:25)
    at EventEmitter.handleCommandEvent (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:257937:61)
    at EventEmitter.emit (events.js:215:7)
    at Object.onMessage (electron/js2c/renderer_init.js:2181:16)
redux failed: Cannot read property 'store' of null
TypeError: Cannot read property 'store' of null
    at ConnectFunction (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:560:70)
    at Ih (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157157:98)
    at si (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157177:273)
    at ri (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157177:103)
    at pi (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157176:178)
    at gk (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157269:63)
    at fk (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157233:22)
    at Zj (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157232:362)
    at Lj (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157226:216)
    at file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157124:115

**Comment by Dav3ledger** [comment]
Still happening... Any news on when this will be fixed??

**Comment by petpatpot** [comment]
The only way to fix this error is to download and install:
https://aka.ms/vs/16/release/vc_redist.x64.exe

However, support does not inform about this. Now, when the market situation is so tense, the lack of access to the wallet disqualifies it completely.

**Comment by Blazms** [comment]
What is this?

**Comment by petpatpot** [comment]
Can not you read?  Ledger is not a toy for large children, but a portfolio
for storing value.  If it fails in the situation we have on the market, it
does not meet its purpose.
Sincerely
Pet

niedz., 22 mar 2020, 10:09 użytkownik Blazms <notifications@github.com>
napisał:

> What is this?
>

**Comment by Blazms** [comment]
Ohh really, then fuck you how about that?

V ned., 22. mar. 2020 10:26 je oseba petpatpot <notifications@github.com>
napisala:

**Comment by gre** [comment]
To fix this issue, you need to install "Visual C++ Redistributable for Visual Studio 2015"

a fix will be delivered in our next release but it will essentially install that redistributable.

**Comment by mvj8016** [comment]
gre .... shd I Download and install https://aka.ms/vs/16/release/vc_redist.x64.exe to fix the problem now or shd I wait for the new release, and if so, when will that be? thanks for your response. is the download and install safe? Many thanks, Mvj8016

**Comment by mvj8016** [comment]
gre ...... when you say "To fix this issue, you need to install "Visual C++ Redistributable for Visual Studio 2015" is that the same as  Download and install https://aka.ms/vs/16/release/vc_redist.x64.exe. I'm not a tech guy so thanks for your anticipated reply ....... mvj8016

**Comment by gre** [comment]
Status: the bug has been fixed and will be deployed in our next release. Unfortunately 2.1.0 will be cancelled because that release is detected by some anti-virus (false positive). We have another fix in the pipe that fixes that false positive.

**Please follow this troubleshooting to solve it for now:**

https://support.ledger.com/hc/en-us/articles/360012598060

**Comment by Giffygods** [comment]
Ok, this "internal Process error" problem with ledger live V2.0.1 is apparently in hand....And we are working in testing times...
But I will still like to add, that I've tried two updates to this dodgy version 2.0.1 on two different X230 laptops...
And now I've tried a fresh install of 2.0.1 on a fresh install, stand alone, Win10 fully  updated B50-10 laptop...
All three laptop's hit this "Internal Process Error".  So am I just unlucky that 3 out of 3 completely different builds, hit this strange 1 in 20 error....
Come on ledger, who dropped the ball here...
![IMG_20200410_130151360](https://user-images.githubusercontent.com/62184248/78989864-bb566400-7b2c-11ea-93e7-03b33f69dbd6.jpg)

**Comment by gre** [comment]
https://support.ledger.com/hc/en-us/articles/360012598060-Ledger-Live-crashes-after-update

**Comment by adriEzeMartinez** [comment]
same issue here with my new Nano S, in centos7
