### ISSUE TITLE
Ability to Downgrade Ledger's Ethereum App to 1.1.4

### ISSUE THREAD

**Issue by michaelhly2** [LedgerHQ/ledger-live-desktop#2688]
- [x] I have checked this feature was not yet requested.

I recently upgraded my Ledger Wallet's Ethereum App to 1.1.8. Now I can't sign certain transactions via the browser:
https://github.com/LedgerHQ/ledger-app-eth/issues/85
https://github.com/LedgerHQ/ledger-app-eth/issues/87

Please allow me to downgrade my Ethereum App to 1.1.4.

**Comment by gre** [comment]
After checking with @btchip , this issue is very likely related to your (Windows?) usb drivers. Make sure they are up to date. https://support.ledger.com/hc/en-us/articles/115005165269-Fix-connection-issues

**Comment by gdelgado** [comment]
This was fixed as per the Reddit post below.

https://www.reddit.com/r/ledgerwallet/comments/fe6w6s/ledger_wallet_team_please_help_me/
