### ISSUE TITLE
Ledger Live Version  2.0.1erro problema sincronização

### ISSUE THREAD

**Issue by wetui** [LedgerHQ/ledger-live-desktop#2699]
#### Ledger Live Version and Operating System

- tested on Ledger Live **version_here**
- Platform and version: **e.g. Mac 10.13.5 / Windows 10 / ..**

**Comment by gre** [comment]
This is probably due to https://github.com/LedgerHQ/ledger-live-desktop/issues/2680

there is not enough information provided in this github issue to analyze (we don't even know the OS)
