### ISSUE TITLE
Ledger Live 2.0.1 Desktop app fades to white on open

### ISSUE THREAD

**Issue by getsnoopy** [LedgerHQ/ledger-live-desktop#2749]
#### Ledger Live Version and Operating System

- tested on Ledger Live **2.0.1**
- Platform and version: **Windows 10 1909**

#### Expected behaviour

The screen should not fade to white when the app is opened.

#### Actual behaviour

The screen fades to white after the Ledger Live logo is zoomed & faded. It seems like the opacity of all the elements on the screen is being set to 0, since the elements seem to be present. For example, the passphrase text box is there when I hover over it, and my cursor changes to a type cursor. Pressing `Ctrl + R` (refresh) seems to fix the issue.

#### Steps to reproduce the behaviour

See this [video](https://recordit.co/aD3RPL3TqG).

**Comment by gre** [comment]
This is a known bug that will be fixed in our upcoming version (ETA 1 week, prerelease version probably today)
