### ISSUE TITLE
Ledger Live shows wrong total balance

### ISSUE THREAD

**Issue by Buttaa** [LedgerHQ/ledger-live-desktop#2755]
#### Ledger Live Version and Operating System

- Ledger Live **v2.0.1**
- Platform and version: **Windows 10**

Shows **incorrect total balance** even though it calculates it correctly for the coins individually. 
Also see here [[reddit]](https://www.reddit.com/r/ledgerwallet/comments/foasvs/still_wrong_total_balance_of_ledger_live_on_win_10/)

**Comment by Luuk2016** [comment]
Got the same problem :(

**Comment by gre** [comment]
A fix is on the way. Should be delivered on next release.

**Comment by Luuk2016** [comment]
Thanks for the fix @gre and the LL team :)
I think that this issue can be closed now.

**Comment by Buttaa** [comment]
fixed
