### ISSUE TITLE
Ledger Live Update 2.0.1 Oops, something went wrong ..................

### ISSUE THREAD

**Issue by Patrickbit82** [LedgerHQ/ledger-live-desktop#2769]
[Ledger Live Update 2.0.1 Oops, something went wrong ..................

Oops, something went wrong
You may try again by restarting Ledger Live. Please export your logs and contact Ledger Support if the problem persists.

As already described, several have this problem with windows 10. I tried everything and uninstalled ledger live and reinstalled. As described, renaming the folder etc. But the Ledger Live software simply does not start. And if it does start because I get a restart when the error message is displayed, the software only synchronizes. But there is no way to send or receive bitcoins, because he recognizes the ledger.
Can anyone help me here where this problem has solved?

**Comment by gre** [comment]
please check https://github.com/LedgerHQ/ledger-live-desktop/issues/2680
