### ISSUE TITLE
Cant open app Ledger Live in W10

### ISSUE THREAD

**Issue by james913** [LedgerHQ/ledger-live-desktop#2848]
#### Ledger Live Version  and Operating System
- tested on Ledger Live **2.0.1**
- Platform and version: **Windows 10.**

#### Expected behavior

Open the App.

#### Actual behavior

When i dowload and install the application, i try executed but show error.
If i select option "Restart", the application run normally but does not connect with ledger.

#### Steps to reproduce the behavior
Only dowload the application and execute. 

![image](https://user-images.githubusercontent.com/32298911/79006077-9f68b780-7b58-11ea-8127-4665c1c05b89.png)

**JSON:**
[
   {
      "type":"db",
      "level":"debug",
      "message":"📁  read app:user",
      "pname":"main",
      "timestamp":"2020-04-10T16:28:37.311Z"
   },
   {
      "level":"info",
      "message":"Internal process 5260 ended with code 1",
      "pname":"main",
      "timestamp":"2020-04-10T16:24:46.788Z"
   },
   {
      "level":"error",
      "message":"I.e: :19)",
      "pname":"main",
      "timestamp":"2020-04-10T16:24:46.754Z"
   },
   {
      "level":"error",
      "message":"I.e: s2c/asar.js:717:26)\r\n    at Function.Module._load (electron/js2c/asar.js:717:26)\r\n    at Module.require (internal/modules/cjs/loader.js:853",
      "pname":"main",
      "timestamp":"2020-04-10T16:24:46.753Z"
   },
   {
      "level":"error",
      "message":"I.e: n/js2c/asar.js:149:18)\r\n    at Module.load (internal/modules/cjs/loader.js:816:32)\r\n    at Module._load (internal/modules/cjs/loader.js:728:14)\r\n    at Module._load (electron/j",
      "pname":"main",
      "timestamp":"2020-04-10T16:24:46.753Z"
   },
   {
      "level":"error",
      "message":"I.e: dings\\bindings.js:121\r\n        throw e;\r\n        ^\r\n\r\nError: No se puede encontrar el módulo especificado.\r\r\n\\\\?\\E:\\Ledger\\Ledger Live\\resources\\app.asar.unpacked\\node_modules\\@ledgerhq\\ledger-core\\build\\Release\\ledger-core-node.node\r\n    at process.func (electron/js2c/asar.js:140:31)\r\n    at process.func [as dlopen] (electron/js2c/asar.js:140:31)\r\n    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)\r\n    at Object.func (electron/js2c/asar.js:140:31)\r\n    at Object.func [as .node] (electro",
      "pname":"main",
      "timestamp":"2020-04-10T16:24:46.752Z"
   },
   {
      "level":"error",
      "message":"I.e: E:\\Ledger\\Ledger Live\\resources\\app.asar\\node_modules\\bin",
      "pname":"main",
      "timestamp":"2020-04-10T16:24:46.751Z"
   },
   {
      "type":"db",
      "level":"debug",
      "message":"📁  write windowParams:MainWindow.positions",
      "pname":"main",
      "timestamp":"2020-04-10T16:24:44.621Z"
   },
   {
      "type":"db",
      "level":"debug",
      "message":"📁  write app:settings",
      "pname":"main",
      "timestamp":"2020-04-10T16:24:44.506Z"
   },
   {
      "level":"info",
      "message":"spawned internal process 5260",
      "pname":"main",
      "timestamp":"2020-04-10T16:24:44.189Z"
   },
   {
      "level":"info",
      "message":"cleaning processes on demand",
      "pname":"main",
      "timestamp":"2020-04-10T16:24:44.170Z"
   },
   {
      "type":"db",
      "level":"debug",
      "message":"📁  read app:accounts",
      "pname":"main",
      "timestamp":"2020-04-10T16:24:43.290Z"
   },
   {
      "type":"db",
      "level":"debug",
      "message":"📁  read app:user",
      "pname":"main",
      "timestamp":"2020-04-10T16:24:43.288Z"
   },
   {
      "type":"db",
      "level":"debug",
      "message":"📁  read app:countervalues",
      "pname":"main",
      "timestamp":"2020-04-10T16:24:43.285Z"
   },
   {
      "type":"db",
      "level":"debug",
      "message":"📁  read app:settings",
      "pname":"main",
      "timestamp":"2020-04-10T16:24:43.238Z"
   },
   {
      "type":"db",
      "level":"debug",
      "message":"📁  read app:settings",
      "pname":"main",
      "timestamp":"2020-04-10T16:24:41.615Z"
   },
   {
      "type":"db",
      "level":"debug",
      "message":"📁  read windowParams:MainWindow",
      "pname":"main",
      "timestamp":"2020-04-10T16:24:40.844Z"
   }
]

**Comment by gre** [comment]
@james913 please follow https://support.ledger.com/hc/en-us/articles/360012598060-Ledger-Live-crashes-after-update 

thanks
