### ISSUE TITLE
Add support for litecoin bech32

### ISSUE THREAD

**Issue by mautematico** [LedgerHQ/ledger-live-desktop#2857]
- [x] I have checked this feature was not yet requested.

There is already support for bitcoin bech32 (both sending and receiving); this request is to include similar level of support for Litecoin, specially receiving.

**Comment by gre** [comment]
@KhalilBellakrid is everything ready in libcore and device side to allow this? thanks

**Comment by KhalilBellakrid** [comment]
> @KhalilBellakrid is everything ready in libcore and device side to allow this? thanks

Yes it is ready !

**Comment by gre** [comment]
we'll look at this asap.

**Comment by mautematico** [comment]
I hacked into app.json and can confirm that libcore address derivation and transaction sync works as expected, both on latest desktop and Android releases 😅

**Comment by gre** [comment]
I forgot to close this PR. It's fixed since ~ a year ago.
