### ISSUE TITLE
Where are the signed hashes for releases?

### ISSUE THREAD

**Issue by sipsorcery** [LedgerHQ/ledger-live-desktop#2877]
This [article](https://support.ledger.com/hc/en-us/articles/360013383899) on the main Lledger.com site mentions signed hashes being available for downloads. Whereabouts can I find the hashes?

The link in the article goes to a comment on an issue in this github repo.

**Comment by MikeD10375** [comment]
Kinda strange and sophomoric a security company hasn't been doing this for GPG verification all along...

**Comment by gre** [comment]
Actually we do sign our binaries with multi signature setup, this is especially important for securing electron updates (something that I don't think a lot of Electron app do today, even in crypto apps, we in fact had to fork Electron Builder to make it work properly as shown by this PR that is still pending and that probably only us uses https://github.com/electron-userland/electron-builder/pull/4308#issuecomment-599193647 )

**We'll try to improve the visibility of this documentation but it's all here => https://ledger-live-tools.now.sh/lld-signatures**

**Comment by MikeD10375** [comment]
> Actually we do sign our binaries and even with a multi signature setup (done with Nano devices!), this is especially important for securing electron updates (something that I don't think a lot of Electron app do today, even among crypto apps, we had to fork Electron Builder to make it work properly as shown by this PR that is still pending and that probably only us uses [electron-userland/electron-builder#4308 (comment)](https://github.com/electron-userland/electron-builder/pull/4308#issuecomment-599193647) )
> 
> **We'll try to improve the visibility of this documentation but it's all here => https://ledger-live-tools.now.sh/lld-signatures**

Thanks for the reply. The page you referenced is currently not working for the current software release. Also, is it possible to make the link for the page in a more visible location on the Ledger.com website and/or on the github releases page?

**Comment by jonathancross** [comment]
[The page](https://ledger-live-tools.now.sh/lld-signatures) is now working for me, however this is not really fixing the problem.

Your [download page](https://www.ledger.com/ledger-live/download/) states _"Beware of fake Ledger Live applications. Only download the application from this page."_ -- but a fake / compromised website would surly show the same message.  So what is being solved here?  **_We want a way to verify the software without relying on a website._**

Checking signatures using openssl as you suggest assumes we know the correct key (which we don't).
The benefit of GPG keys is that we have ways to verify the correct key without trusting a website.

I have personally met with Nicolas Bacca and verified his gpg key fingerprint IRL.
If he signed releases (or his key cross-signed your gpg release key) -- then I would not need to trust any website to truthfully present the correct pubkey.  Furthermore, through the OpenPGP Web Of Trust, there can be many paths to verifying a key without meeting in person, especially when the owner takes responsibility for cross signing with others and advertising the correct key at conferences, keybase, etc.

**Comment by jonathancross** [comment]
@btchip Since I don't think anyone will be changing this process of using openssl rather than gpg, can you please post a gpg signature (with key `0x683D7938DF5515CE`) here stating that this is the correct pubkey for ledgerlive releases?
```
-----BEGIN PUBLIC KEY-----
MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEN7qcsG6bogi1nkD3jnMWS813wWguYEcI
CRcijSvFskSFjHB5la4xUt+Omb2t6iUwop+JRy+EUhy0UQ9p/cPsQA==
-----END PUBLIC KEY-----
```
Thanks!

**Comment by gre** [comment]
also you can check history of this https://github.com/LedgerHQ/ledger-live-desktop/blame/develop/src/main/updater/ledger-pubkey.js

**Comment by jonathancross** [comment]
Fantastic, thanks @btchip !
```
gpg: Signature made Wed Nov 18 18:27:13 2020 CET
gpg:                using RSA key BAE88B19F6E323236DEB1AC7683D7938DF5515CE
gpg:                issuer "nicolas@ledger.fr"
gpg: Good signature from "Nicolas Bacca (Ledger) <nicolas@ledger.fr>"
Primary key fingerprint: BAE8 8B19 F6E3 2323 6DEB  1AC7 683D 7938 DF55 15CE
```

**Comment by jonathancross** [comment]
> also you can check history of this https://github.com/LedgerHQ/ledger-live-desktop/blame/develop/src/main/updater/ledger-pubkey.js

Thanks @gre, but where is your gpg pubkey for `0x7B66B85F042E5451`?
I checked 4 keyservers.
Is it cross-signed with other devs?

**Comment by adrelanos** [comment]
[publish Ledger developer OpenPGP (gpg) key on ledger.com](https://github.com/LedgerHQ/ledger-live-desktop/issues/3601)

**Comment by jonathancross** [comment]
Ping @gre ?

**Comment by jonathancross** [comment]
@gre we need your PGP pubkey in order to verify [this commit](https://github.com/LedgerHQ/ledger-live-desktop/pull/1862/commits/41f3f6d42bb47ae665d77870566da18f5a998217).

**Comment by gre** [comment]
I have just sent it to http://hkps.pool.sks-keyservers.net/pks/lookup?search=0x7B66B85F042E5451&fingerprint=on&op=index , sorry for this.

**Comment by adrelanos** [comment]
> I have just sent it to **http**://hkps.pool.sks-keyservers.net/pks/lookup?search=0x7B66B85F042E5451&fingerprint=on&op=index , sorry for this.

(Bold in quote is mine.)

Insecure. That's a http link. Not http**s** (TLS). And it's a third party server. Ok additionally but not good as exclusive source of the key.

gpg key servers should not be used anyhow. Quote https://gist.github.com/rjhansen/67ab921ffb4084c865b3618d6955275f

> Robert J. Hansen <rjh@sixdemonbag.org>. I maintain the GnuPG FAQ and unofficially hold the position of crisis communicator. This is not an official statement of the GnuPG project, but does come from someone with commit access to the GnuPG git repo.

> **High-risk users should stop using the keyserver network immediately.**

Much better to provide public keys on official ledger homepage. (And/or other good sources, whatever that might be.)

**Comment by gre** [comment]
I pushed it from my terminal to gpg key server as was asked on this thread but yeah we probably can also all our keys as complementary to https://www.ledger.com/ledger-live/lld-signatures

**Comment by sipsorcery** [comment]
Can anyone on this thread verify that the `ledger-live-desktop-2.36.3.sha512sum.sig` from https://live.ledger.tools/lld-signatures is good?

I've been unable to get a successful verification on two different Ubuntu VM's.

````
$ openssl version
OpenSSL 1.1.1  11 Sep 2018
$ cat ledger-live-desktop-2.36.3.sha512sum
70e4748f68bb949cc048c9db1b2887a865625e25ed071355f24c36e9d0796d4d5aa56ac359fd7636cd3a522fc206985c514e5be17125d1f0e30b3a7b92dbdabf
$ openssl dgst -sha512 -verify ledgerlive.pem -signature ledger-live-desktop-2.36.3.sha512sum.sig ledger-live-desktop-2.36.3.sha512sum
Verification Failure
````

````
$ openssl version
OpenSSL 1.1.1f  31 Mar 2020
$ cat ledger-live-desktop-2.36.3.sha512sum
70e4748f68bb949cc048c9db1b2887a865625e25ed071355f24c36e9d0796d4d5aa56ac359fd7636cd3a522fc206985c514e5be17125d1f0e30b3a7b92dbdabf
$ openssl dgst -sha256 -verify ledgerlive.pem -signature ledger-live-desktop-2.36.3.sha512sum.sig ledger-live-desktop-2.36.3.sha512sum
Verification Failure
````
