### ISSUE TITLE
TRX Display Issues in Ledger Live

### ISSUE THREAD

**Issue by richance** [LedgerHQ/ledger-live-desktop#2902]
#### Ledger Live Version and Operating System

Tested on Leder Live 2.3.2
Windows 10

#### Expected behavior

I want to see my full TRX amount in Ledger Live

#### Actual behavior

1) I send some TRX from a wallet to Ledger Live TRX address. The amount does not show up in Ledger Live, but on Tronscan it is already completed and confirmed. (also checked the right address and the trx are already credited right in tronscan)

2) The UI of TRX Amount in ledger live periodically shows a 0 TRX balance every 2 minutes or so. So every 2 minutes it is 0 and then the full amount.

#### Steps to reproduce the behavior

It seems like Ledger Live is having problems to fetch data from the Tronscan or trongrid datasource and also new incoming transactions are not shown.

I also tried to claim rewards from voting. The smart contract went through but even after confirmation I am not seeing the amount in the TRX total.

**Comment by gre** [comment]
there is an ongoing incident in trongrid.io on European servers, hopefully it will be fixed soon.
