### ISSUE TITLE
Unable to add TRX account

### ISSUE THREAD

**Issue by hopkinskong** [LedgerHQ/ledger-live-desktop#2904]
#### Ledger Live Version and Operating System

- tested on Ledger Live **2.3.2**
- Platform and version: **Windows 8.1**

#### The Issue

Adding the account returns the following error:
![image](https://user-images.githubusercontent.com/2718385/81471910-32177780-9227-11ea-90d0-a99671ac4336.png)

**Comment by gre** [comment]
We have probably fixed it. Could you try again in latest Ledger Live? Thanks
