### ISSUE TITLE
Portfolio balance chart longer than 1 Year.

### ISSUE THREAD

**Issue by rheos** [LedgerHQ/ledger-live-desktop#2922]
- [x] I have checked this feature was not yet requested.

I've been using my ledger long than a year. Why does the ledger history chart have a limit of 1Y ? Why not 2 or 3 years? Or to whatever date you first started using it?

#### Part of the application

Portfolio balance chart

**Comment by gre** [comment]
it's in our pipe yeah. kinda related https://github.com/LedgerHQ/ledger-live-desktop/issues/1488

**Comment by cthepot-ledger** [comment]
Duplicate of #1818
