### ISSUE TITLE
Unable to spend unconfirmed funds

### ISSUE THREAD

**Issue by NicolasDorier** [LedgerHQ/ledger-live-desktop#2924]
### Description

I am reporting on behalf of somebody.
This person received a transaction 4 or 5 days ago for low fee and still not confirmed.
The transaction appears in his transaction list, however he seems to be unable to spend this funds (not available in the send screen).

#### Ledger Live Version and Operating System

Ledger Live 2.3.2
Mac OS Catalina

#### Expected behavior

Unconfirmed funds should be spendable.

#### Actual behavior

Unconfirmed funds are not spendable.

#### Steps to reproduce the behavior

* Receive a low fee transaction on the ledger when mempool get big
* Check that you received the transaction in the Transactions list.
* Try to send it out.

**Comment by NicolasDorier** [comment]
The transaction now completely disappeared.

**Comment by cthepot-ledger** [comment]
@NicolasDorier Thanks for reporting the issue. You can allow to spend unconfirmed funds in the send flow. There's also coin control.
