### ISSUE TITLE
Let LL memorize the installed hw wallet app version

### ISSUE THREAD

**Issue by Luuk2016** [LedgerHQ/ledger-live-desktop#2930]
- [x] I have checked this feature was not yet requested.

It would be a nice feature to let Ledger Live memorize the installed app version.
Now you need to periodically check if the app is up to date.
If LL knows what version you have the app can give a notification when a new version is available.

#### Part of the application

Ledger Manager

**Comment by gre** [comment]
It's already doing that and checking when you start Ledger Live. Do you mean it also should recurrently check while open? I'm not sure to understand the request

**Comment by gre** [comment]
Ok I obviously misread as you probably where speaking about Manager apps. That's a good idea, one of the tricky part is when you use more than one device at a time. An idea that we might start to put in place is that anytime you go to a device flow and we see the app is outdated, we could also warn there. We'll discuss internally

**Comment by gre** [comment]
I forgot to update this task but it was implemented.
