### ISSUE TITLE
No Icon showing in menu bar for Ledger Live on Ubuntu

### ISSUE THREAD

**Issue by chrisengel** [LedgerHQ/ledger-live-desktop#2932]
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.3.2
- Platform and version: Ubuntu 20.04 LTS

#### Expected behavior

I expect there to be a Ledger Live icon displaying on the menu when Ledger Live is minimised

#### Actual behavior

There is a blank space in place of an icon

#### Steps to reproduce the behavior

Open Ledger Live and look in the applications menu

![image](https://user-images.githubusercontent.com/12490915/82711868-e6cd8200-9c86-11ea-9426-4b60dd449f9f.png)

**Comment by jesscalvin** [comment]
but if i may ask your ledger live works perfectly

**Comment by TrackRunny** [comment]
Exact same issue, someone please check this out. I have no icon on the appimage either. The app works fine, just a little annoying. 

Ledger live: 2.5.0
Operating system: Kubuntu 20.04 LTS

**Comment by jesscalvin** [comment]
Are you active now .. I could guide you on fixing

**Comment by TrackRunny** [comment]
Yes, could you please comment a solution to this issue here?

**Comment by jesscalvin** [comment]
Are you using an android or an IOS

**Comment by TrackRunny** [comment]
> Are you using an android or an IOS
I'm using Linux, which uses the .appimage version of the program.

**Comment by jesscalvin** [comment]
Ok, that’s even much better... do you have a WhatsApp number or Telegram

**Comment by gre** [comment]
Please keep the discussion here, we do not offer WhatsApp / Telegram assistance and any help on the current issue is welcomed for contribution. Thanks.

**Comment by cthepot-ledger** [comment]
Duplicate of #2300
