### ISSUE TITLE
Bug in iOS 2.3.0 Ledger Live version. Infinite sync when adding a tezos account and app quits.

### ISSUE THREAD

**Issue by logart89** [LedgerHQ/ledger-live-desktop#2938]
iOS 2.3.0 Ledger Live version using Ledger X 2.2.5 tezos wallet app. 

In Accounts when i click in + symbol to add an account, then i choose tezos, then it says is synchronizing with an infinite loop animation and then the Ledger Live app crashes. I have the ledger x tezos wallet app 2.2.5 open while doing all that. Still will crash. 

Also a feature request can you guys add 44'/1729'/0'/1 derivation path? I really need this! Thank you very much.

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. 

`44'/1729'/0'/1'` is detected if you create `44'/1729'/0'/0'`
Either you can create that /0' or you might want to use the app you were using in the first place to create this `44'/1729'/0'/1'` / move the funds to a more standard path.

I'm not sure why you are experience the crash but please contact our tech support with logs.
This issue can happen for various reasons. We prefer to investigate such issues via contacting our customer support team.

could you send your logs to our support team and mention this github issue? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏  basically you can press Ctrl+E just after the problem occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.now.sh/logsviewer )
