### ISSUE TITLE
Sending XRP not possible

### ISSUE THREAD

**Issue by Stifab** [LedgerHQ/ledger-live-desktop#2943]
Ledger Live Version 2.3.2
Problem: When trying to send XRP the following message occurs:
Certificate has expired. Something went wrong. Please retry or contact us

**Comment by Stifab** [comment]
![Unbenannt](https://user-images.githubusercontent.com/66169824/83334063-412c9b00-a2a4-11ea-8c31-8270820e5e73.PNG)

**Comment by gre** [comment]
this looks like an issue on ripple.com servers, it seems it's back, could you check again now or a bit later? thanks

**Comment by Stifab** [comment]
thank you, but the issue is still not fixed. Please help

**Comment by jesscalvin** [comment]
hello, had same issue with my ripples days back but now its all resolved... Are you still having same issue

**Comment by Stifab** [comment]
caused me a lot of problems and money, meanwhile it is working again.
What is the compensation for that?

Von meinem iPhone gesendet

**Comment by jesscalvin** [comment]
ok,cool
was going to write a private message on how it could be set up and no issue would derive , cause most of this happens due to the version of ledger you are using and probably you are having a bug issue..... Glad its working perfectly now.
