### ISSUE TITLE
Please Add Verge support to ledger live

### ISSUE THREAD

**Issue by dave90dave** [LedgerHQ/ledger-live-desktop#2963]
Hi,
When is Verge support being added to ledger live?
Regards
Dave

**Comment by rblaine95** [comment]
Hi Dave
Please refer to the pinned issue: Support [a crypto asset] directly in Ledger Live - #1560

**Comment by gre** [comment]
https://github.com/LedgerHQ/ledger-live-desktop/issues/1560
