### ISSUE TITLE
Rework the "receive dialog"

### ISSUE THREAD

**Issue by Flydancer** [LedgerHQ/ledger-live-desktop#2997]
The receive dialog is just annoying so please add:

- A "generate new Address" button in the dialog
Why? Because it's not showing a new one until you have received something on the addresses so I can't create multiple addresses for different purposes in a row.

- Show the receiving address in the last step again
Why? If you forgot to copy it in the second step, you have to reopen the whole dialog after veryfication

- Labels for addresses!!

**Comment by gre** [comment]
- First request is an existing GitHub issue
- Second feedback: the current implementation is trying to make user do it securely, there are some malware that replace the content of copy paste, the idea and rationale has been explained in https://github.com/LedgerHQ/ledger-live-desktop/issues/2675#issuecomment-594767406 : it's not impossible we improve that section but we need to drive a secure usage of how you verify your address
- this also is an existing GitHub issue
