### ISSUE TITLE
Tezos staking on binance gives no reward

### ISSUE THREAD

**Issue by mauroaccornero** [LedgerHQ/ledger-live-desktop#3062]

**Comment by richance** [comment]
Hey @mauroaccornero I am facing the same problem. What was your solution?

**Comment by mauroaccornero** [comment]
> Hey @mauroaccornero I am facing the same problem. What was your solution?

I found two possible solution at moment: 
1) keep tezos on binance to get stake rewards 
2) change baker from ledger live.
