### ISSUE TITLE
build fails linux x86_64 v5.7.8, node v12.18.2, yarn v 1.22.4, python 3.8.3, gcc 9.3.0

### ISSUE THREAD

**Issue by arduent** [LedgerHQ/ledger-live-desktop#3077]
#### Ledger Live Version and Operating System

ledger-live-desktop 2.8.0, Linux 5.7.8 x86_64

- tested on Ledger Live **version_here** 2.8.0
- Platform and version: **e.g. Mac 10.13.5 / Windows 10 / ..** Linux x86_64 v5.7.8

#### Expected behavior

since all specified dependencies are met, yarn start should start the program according to the documentation

#### Actual behavior

naida:~/Downloads/ledger-live-desktop-2.8.0$ yarn
yarn install v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > styled-components@5.1.0" has unmet peer dependency "react-is@>= 16.8.0".
warning " > eslint-plugin-import@2.20.2" has incorrect peer dependency "eslint@2.x - 6.x".
warning "eslint-plugin-jest > @typescript-eslint/experimental-utils > @typescript-eslint/typescript-estree > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > eslint-plugin-react@7.19.0" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0".
warning " > eslint-plugin-react-hooks@4.0.0" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0".
[5/5] Building fresh packages...
[1/15] ⢀ node-hid
[2/15] ⢀ usb-detection
[3/15] ⢀ @ledgerhq/ledger-core
[10/15] ⢀ electron
error /home/waitman/Downloads/ledger-live-desktop-2.8.0/node_modules/usb-detection: Command failed.
Exit code: 127
Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: /home/waitman/Downloads/ledger-live-desktop-2.8.0/node_modules/usb-detection

naida:~/Downloads/ledger-live-desktop-2.8.0$ yarn start
yarn run v1.22.4
$ cross-env NODE_ENV=development node ./tools/main.js
fatal: not a git repository (or any of the parent directories): .git
child_process.js:669
    throw err;
    ^

Error: Command failed: git rev-parse --short HEAD
fatal: not a git repository (or any of the parent directories): .git

    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at Object.<anonymous> (/home/waitman/Downloads/ledger-live-desktop-2.8.0/tools/main.js:15:4)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  status: 128,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 66 61 74 61 6c 3a 20 6e 6f 74 20 61 20 67 69 74 20 72 65 70 6f 73 69 74 6f 72 79 20 28 6f 72 20 61 6e 79 20 6f 66 20 74 68 65 20 70 61 72 65 6e 74 20 ... 19 more bytes>
  ],
  pid: 15453,
  stdout: <Buffer >,
  stderr: <Buffer 66 61 74 61 6c 3a 20 6e 6f 74 20 61 20 67 69 74 20 72 65 70 6f 73 69 74 6f 72 79 20 28 6f 72 20 61 6e 79 20 6f 66 20 74 68 65 20 70 61 72 65 6e 74 20 ... 19 more bytes>
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

$ uname -a
Linux naida 5.7.8-0-edge #1-Alpine SMP PREEMPT Thu, 09 Jul 2020 20:39:52 UTC x86_64 Linux

$ node -v
v12.18.2
$ yarn -v
1.22.4
$ python3 --version
Python 3.8.3
$ gcc --version
gcc (Alpine 9.3.0) 9.3.0

#### Steps to reproduce the behavior

yarn
yarn start

![Screenshot from 2020-07-14 18-24-28](https://user-images.githubusercontent.com/47302729/87482381-4731cd80-c5ff-11ea-85a3-7a473323a538.png)
![Screenshot from 2020-07-14 18-24-07](https://user-images.githubusercontent.com/47302729/87482383-47ca6400-c5ff-11ea-8097-1a9f012a4913.png)

**Comment by arduent** [comment]
I think electron is currently an issue since it seems to be downloading pre-compiled binaries linked against glibc. I believe the electron issue will soon be resolved, maybe.

**Comment by abouzia** [comment]
Any solution?
