### ISSUE TITLE
Cosmos: Incorrect historical balance after claiming rewards

### ISSUE THREAD

**Issue by dslutej** [LedgerHQ/ledger-live-desktop#3090]
#### Ledger Live Version and Operating System

Ledger Live Desktop 2.8.0 (also Android current version).
Windows 10.

#### Expected behavior

Claiming rewards increases the balance. 

#### Actual behavior

See all transactions for this account: 
![image](https://user-images.githubusercontent.com/22919263/88327822-c3c35b00-cd27-11ea-80b7-68c44450ad7a.png)

But look at the graph. Current balance is ok but it appears as the account had more Atoms BEFORE claiming the rewards. 

![image](https://user-images.githubusercontent.com/22919263/88328207-6085f880-cd28-11ea-8cf3-67ca7fa674cc.png)

**Comment by cthepot-ledger** [comment]
Please contact support on support.ledger.com
