### ISSUE TITLE
[Discussion] Those ads are getting a little too far.

### ISSUE THREAD

**Issue by Zaczero** [LedgerHQ/ledger-live-desktop#3098]
I've just installed the latest update of Ledger Live and the first thing I saw is this big popup banner where previously was my total portfolio balance. There are few things which I don't really like in that.

1. It's the first thing you see when starting the app
2. It's at the same position where the total balance was (muscle memory)
3. It does not fit well with the dark theme
4. It contains ads?
5. You can't really close it permanently
6. Ledger isn't free? I paid for this :D

I was fine with you adding the "Buy crypto" button on the sidebar, but I feel like this is just too much. For me I feel like the Ledger company is getting greedy.

But hey, there is an X button. Oh you fool, it closes the popup only for the current instance of the app. Whenever restarted I have to close it again. When you add such a "feature" at least make it optional. I already paid a premium for the Nano X :-) Don't make me start developing an Ad-Block for Ledger Live.

This is the same level of bs as all those streaming services which you have to pay for and then you get those 3/4 minute long unskippable ads.

![200728205307_Ledger_Live_0ce7db](https://user-images.githubusercontent.com/10835147/88708713-5bec8600-d114-11ea-80cd-0c1305f08de1.png)

#### Ledger Live Version

- Ledger Live 2.9.0

**Comment by gre** [comment]
Ledger Live aim to offer many features in one app and this is one way to promote these features. To me it can be very interesting if we make it smarter (like contextual to your accounts) for instance, we have content that mentions you can "Delegate on Tezos" but only appearing if you have Tezos. I think it can be really helpful for users that don't know such feature is possible.. This banner always existed if you had Tezos, we simply generalized it and unified it.

That said, I shared your feedback internally. We can always refine the visibility of this banner. You see ads where I see just the potential of more content (like more documentation around https://www.ledger.com/academy/ ) / other dynamic content. Maybe i'm wrong and we can always refine to make it better and less intrusive. We read your feedbacks.

**Comment by juan-cortes** [comment]
https://github.com/LedgerHQ/ledger-live-desktop/pull/3099

**Comment by Zaczero** [comment]
> 
> 
> #3099

This came faster than expected, good work!

**Comment by My1** [comment]
> this is one way to promote these features

just make sure it'll stay just that and not as some on reddit are fearing, external ads.

**Comment by juan-cortes** [comment]
https://github.com/LedgerHQ/ledger-live-desktop/pull/3099 has now been merged and is due to be included in the next release. The _ads_ will not get out of control, we care what our user base thinks about the product. Closing the discussion for now 👋
