### ISSUE TITLE
Republic Protocol does not have value / price

### ISSUE THREAD

**Issue by marbew** [LedgerHQ/ledger-live-desktop#3100]
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.8
- Platform and version: Linux Ubuntu desktop 20.04

#### Expected behavior

It should show the price associate and the value in the right column.

#### Actual behavior

It does have an empty field for value and for price columns.

#### Steps to reproduce the behavior

Just open the ledger-desktop app on Linux Ubuntu.

**Comment by cthepot-ledger** [comment]
Duplicate of #2326
