### ISSUE TITLE
Not syncing older Horizen Addresses

### ISSUE THREAD

**Issue by JReming85** [LedgerHQ/ledger-live-desktop#3101]
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.9.0 + past 2 versions
- Platform and version: Windows 10

#### Expected behavior

Show full Horizen balance

#### Actual behavior

Hasnt updated for over a month, even though I can see it sent on block chain

#### Steps to reproduce the behavior

I have 14 zen addresses, which are getting weekly payments but are not showing in Ledger.
I can view them on the blockchain with no issue

**Comment by cthepot-ledger** [comment]
Please contact support on support.ledger.com
