### ISSUE TITLE
Wrong Tezos balance

### ISSUE THREAD

**Issue by neves-0** [LedgerHQ/ledger-live-desktop#3102]
#### Ledger Live Version and Operating System

- tested on Ledger Live **2.9.0**
- Platform and version: **Arch Linux with kernel 5.7.11-arch1-1, french locales**

#### Expected behavior

Correct balance is displayed for my Tezos account.

#### Actual behavior

Ledger Live is not displaying the real staking balance of my Tezos account.

#### Steps to reproduce the behavior

Start Ledger Live.

I have 59,151.593699ꜩ on this account, but Ledger Live thinks I have 59 151 593 699ꜩ. I tried to clear the cache to force a resync, without success. Maybe Ledger can send me the difference in ꜩ to fix this bug?

![image](https://user-images.githubusercontent.com/48542895/89031625-2671b380-d333-11ea-9350-00084978f301.png)

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. 

This issue can happen for various reasons. We prefer to investigate such issues via contacting our customer support team.

Are you in contact with our support team?

Thanks
