### ISSUE TITLE
This chart of Bitcoin have some weird distorted spices on the top - doesn't seems correct.

### ISSUE THREAD

**Issue by ilyaLibin** [LedgerHQ/ledger-live-desktop#3103]
#### Ledger Live Version and Operating System

MacOS 10.14.6
app version 2.9.0

![image](https://user-images.githubusercontent.com/12880486/89157556-60ca9300-d575-11ea-853f-0670f2ff74c5.png)

**Comment by dasilvarosa** [comment]
Closing this one in favor of: https://github.com/LedgerHQ/ledger-live-desktop/issues/3122
