### ISSUE TITLE
Firmware upgrade on brand new Ledger Nano S failed from 1.3.x to 1.6.x with API HTTP 404 

### ISSUE THREAD

**Issue by kali-777** [LedgerHQ/ledger-live-desktop#3118]
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.9.0
- Platform and version:  Windows 10 / ..2004 Build

#### Expected behavior

Successful firmware upgrade

#### Actual behavior

After successful setup Recovery phrase/PIN, App said new Firmware, so i tried to upgrade, all looked good, bootloader/firmware updated on Device, but then in App i got API HTTP 404, now the Device stuck on "Update" Repair also do NOT possible Ledger device: UNKNOWN_ERROR (0x6984)

#### Steps to reproduce the behavior

Logs
{"type":"cmd.ERROR","data":{"status":404,"url":"https://manager.api.live.ledger.com/api/get_osu_version?livecommonversion=13.3.1","method":"POST","name":"LedgerAPI4xx","message":"API HTTP 404","stack":"Error\n    at new CustomError (C:\\Program Files\\Ledger Live\\resources\\app.asar\\node_modules\\@ledgerhq\\errors\\dist\\index.cjs.js:18:22)\n    at makeError (C:\\Program Files\\Ledger Live\\resources\\app.asar\\node_modules\\@ledgerhq\\live-common\\lib\\network.js:28:54)\n    at C:\\Program Files\\Ledger Live\\resources\\app.asar\\node_modules\\@ledgerhq\\live-common\\lib\\network.js:89:22\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async C:\\Program Files\\Ledger Live\\resources\\app.asar\\node_modules\\@ledgerhq\\live-common\\lib\\api\\Manager.js:202:7\n    at async Object.getLatestFirmwareForDevice (C:\\Program Files\\Ledger Live\\resources\\app.asar\\node_modules\\@ledgerhq\\live-common\\lib\\manager\\index.js:69:13)"},"level":"info","message":"✖ CMD getLatestFirmwareForDevice error","pname":"renderer","timestamp":"2020-08-12T09:26:35.098Z"},{"type":"cmd.ERROR","data":{"status":404,"url":"https://manager.api.live.ledger.com/api/get_osu_version?livecommonversion=13.3.1","method":"POST","name":"LedgerAPI4xx","message":"API HTTP 404","stack":"Error\n    at new CustomError (C:\\Program Files\\Ledger Live\\resources\\app.asar\\node_modules\\@ledgerhq\\errors\\dist\\index.cjs.js:18:22)\n    at makeError (C:\\Program Files\\Ledger Live\\resources\\app.asar\\node_modules\\@ledgerhq\\live-common\\lib\\network.js:28:54)\n    at C:\\Program Files\\Ledger Live\\resources\\app.asar\\node_modules\\@ledgerhq\\live-common\\lib\\network.js:89:22\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async C:\\Program Files\\Ledger Live\\resources\\app.asar\\node_modules\\@ledgerhq\\live-common\\lib\\api\\Manager.js:202:7\n    at async Object.getLatestFirmwareForDevice (C:\\Program Files\\Ledger Live\\resources\\app.asar\\node_modules\\@ledgerhq\\live-common\\lib\\manager\\index.js:69:13)"},"level":"warn","message":"✖ CMD getLatestFirmwareForDevice error","pname":"internal","timestamp":"2020-08-12T09:26:35.096Z"},{"error":{"status":404,"url":"https://manager.api.live.ledger.com/api/get_osu_version?livecommonversion=13.3.1","method":"POST","name":"LedgerAPI4xx","message":"API HTTP 404","stack":"Error\n    at new CustomError (C:\\Program Files\\Ledger Live\\resources\\app.asar\\node_modules\\@ledgerhq\\errors\\dist\\index.cjs.js:18:22)\n    at makeError (C:\\Program Files\\Ledger Live\\resources\\app.asar\\node_modules\\@ledgerhq\\live-common\\lib\\network.js:28:54)\n    at C:\\Program Files\\Ledger Live\\resources\\app.asar\\node_modules\\@ledgerhq\\live-common\\lib\\network.js:89:22\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async C:\\Program Files\\Ledger Live\\resources\\app.asar\\node_modules\\@ledgerhq\\live-common\\lib\\api\\Manager.js:202:7\n    at async Object.getLatestFirmwareForDevice (C:\\Program Files\\Ledger Live\\resources\\app.asar\\node_modules\\@ledgerhq\\live-common\\lib\\manager\\index.js:69:13)"},"level":"warn","message":"Command error:","pname":"internal","timestamp":"2020-08-12T09:26:35.095Z"},{"type":"network-error","message":"404 POST https://manager.api.live.ledger.com/api/get_osu_version?livecommonversion=13.3.1 (635ms): API HTTP 404","data":{},"level":"debug","pname":"internal","timestamp":"2020-08-12T09:26:35.094Z"},{"type":"warn","message":"API HTTP 404","level":"info","pname":"renderer","timestamp":"2020-08-12T09:26:34.588Z"},{"type":"network-error","message":"404 POST https://manager.api.live.ledger.com/api/get_osu_version?livecommonversion=13.3.1 (616ms): API HTTP 404","data":{},"level":"info","pname":"renderer","timestamp":"2020-08-12T09:26:34.588Z"},{"type":"network","message":"POST https://manager.api.live.ledger.com/api/get_osu_version?livecommonversion=13.3.1","data":{"data":{"device_version":10,"version_name":"1.6.0-osu","provider":1}},"level":"debug","pname":"internal","timestamp":"2020-08-12T09:26:34.459Z"}

**Comment by kali-777** [comment]
Please do NOT say i should contact a customer support! I think its BUG in SW, because i followed all the instructions, BUT then SW give HTTP 404 NOT found for the Ledger own Web-Site, SO in this case WHY the whole Wallet got corrupt/"useless"?!

**Comment by gre** [comment]
This has been fixed and everything should be back to normal on latest release of live (2.9.0)

https://support.ledger.com/hc/en-us/articles/360003117594-Troubleshoot-firmware-update

**Comment by kali-777** [comment]
Sounds "great", however i used the latest v2.9.0, as i wrote the beginning  :((
**tested on Ledger Live 2.9.0**

**Comment by gre** [comment]
Sorry I was not enough precise: this has been fixed **on our backend** and it is not related to a Ledger Live release. There were just missing data in our API.

**Comment by greg7mdp** [comment]
I have the exact same issue now using live 2.18.0. I also tried 2.19.0, different windows machines, different USB port, running live as administrator. Nothing works!

**Comment by greg7mdp** [comment]
I have: Ledger device: UNKNOWN_ERROR (0x6984). Plugging the device in bootloader mode, live detects it and offers to update it, displays an update progress bar, but then all I get is live getting stuck on the update and a blinking ledger icon on the device screen.
