### ISSUE TITLE
Weird spikes on the charts

### ISSUE THREAD

**Issue by ThomasTL** [LedgerHQ/ledger-live-desktop#3122]
#### Ledger Live Version and Operating System
- Tested on **_Ledger Live Desktop 2.9.0_**
- Platform and version:  **_Windows 10_**

#### Expected behavior
Charts should not be showing weird spikes.

#### Actual behavior
Charts are showing weird spikes

#### Steps to reproduce the behavior
Please find below the screenshots where these weird spikes can be seen. You can see that the spikes appear at the same location regardless the crypto for which the chart is displayed which made me think it is a bug in Ledger Live.
* **BTC**
![image](https://user-images.githubusercontent.com/8722814/90305435-56a18080-def5-11ea-907b-ed2a62e61de8.png)
* **ETH**
![image](https://user-images.githubusercontent.com/8722814/90305438-6620c980-def5-11ea-94b9-d5aa4cf5629b.png)
* **Rates**
![image](https://user-images.githubusercontent.com/8722814/90305442-789b0300-def5-11ea-9066-086ed5caa397.png)

**Comment by cappadaan** [comment]
Same issue here

Ledger Live Version and Operating System

    Tested on Ledger Live Desktop 2.9.0
    Platform and version: MacOS

<img width="1352" alt="Screenshot 2020-08-18 at 09 09 41" src="https://user-images.githubusercontent.com/25279400/90481787-a3be6600-e132-11ea-9335-451a4c7c3976.png">

The spikes always start at the 1st day of the month

**Comment by AdrianEddy** [comment]
I have the same issue 
![image](https://user-images.githubusercontent.com/3849067/90870946-9c999100-e39a-11ea-8558-632bcf6a2951.png)

**Comment by chadhamre** [comment]
Still a problem. Please fix this.
<img width="1013" alt="Screen Shot 2020-10-06 at 9 24 56 PM" src="https://user-images.githubusercontent.com/1864797/95287315-729d1080-081a-11eb-8b71-93546fc2e13e.png">

**Comment by bruno-t-de-renzo** [comment]
Same here, though for first days of October the same behaviour doesn't happen, only for previous months
Ledger Live for Mac 2.14.0

**Comment by gre** [comment]
we're working on better countervalues. we will share more about it next week.

**Comment by gre** [comment]
Hello, we are aware of this issue and to solve this we have completely reworked the countervalues (as part of other problems we had with them). We have opened a beta testing program in order to know if our rework fully works for you, we invite users that want join the beta to follow instruction available in https://github.com/LedgerHQ/ledger-live-desktop/releases/tag/2.16.0-countervalues-beta-0

**Comment by bruno-t-de-renzo** [comment]
Hello @gre, how are you?
I would love to enter the beta program, but it involves adding my e-mail to a Google Spreadsheet. No thanks, I'll wait until it is released. I was expecting a bit more care with data storage, specially after all the recent news on the leaked database from Ledger.
Thanks for the response anyways 😉

**Comment by janzilka** [comment]
Same issue 
Ledger Live 2.14.0 (arm64-v8a 125) on Android

**Comment by danielhw2** [comment]
Same issue...
Ledger Live 2.15.0
Windows 10 2004 (build 19041.572)

**Comment by jfgrissom** [comment]
Same issue v2.16.0

**Comment by danielhw2** [comment]
The new V2.17.1 version still broken... =/

**Comment by gre** [comment]
The fix is planned for 2.18.0. ETA 1 week.

**Comment by loadmi** [comment]
Between the fact that i found threads discussing this fairly big bug since July while still present now in December and how Ledger handles our private data i'm really not sure if staying with this company is a wise idea. What the hell is going on lately?

**Comment by janzilka** [comment]
@toadmi 
This is what I was thinking to myself. If they have such a retention of this level of problem, how is it with cryptography, security and privacy in the critical sections of the code? 

BTW - does anybody know about an alternative cold storage HW/SW with better integration ? Isn't this a marget gap to close?
