### ISSUE TITLE
XRP received from AccountDelete transaction not shown in account history 

### ISSUE THREAD

**Issue by JamesGDiaz** [LedgerHQ/ledger-live-desktop#3126]
[*] I have checked this feature was not yet requested.

DESCRIPTION: I deleted an XRP account (not the one used with my Ledger) using the [recently released ](https://xrpl.org/accountdelete.html) ammendment to the XRP. I see the received balance and the txID shows up on the ledger explorer but is not shown in my account history as a received payment.

#### Part of the application

XRP account management.

**Comment by cthepot-ledger** [comment]
@JamesGDiaz Thanks for reporting a bug. Could you use our [customer support](https://support.ledger.com/hc/en-us) to communicate your issue, if still ongoing?
