### ISSUE TITLE
Portfolio balance is not formatted correctly

### ISSUE THREAD

**Issue by WordmanEric** [LedgerHQ/ledger-live-desktop#3127]
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.9.0
- Platform and version: Mac 10.15.6

#### Expected behavior

I should always see two digits after the decimal point, even if the second digit is a zero.

#### Actual behavior

Sometimes I see only one digit after the decimal.

#### Screenshots:
![new bal](https://user-images.githubusercontent.com/29806839/90541055-125dec80-e150-11ea-9ddb-4c7093972fc2.jpg)
![new bal 2](https://user-images.githubusercontent.com/29806839/90541108-23a6f900-e150-11ea-93e3-ccbaa25b4587.jpg)

**Comment by gre** [comment]
Thanks for the ticket. This has been fixed in https://github.com/LedgerHQ/ledger-live-common/pull/825 and will be available in next version
