### ISSUE TITLE
Issue with Aeternity version 0.4.1

### ISSUE THREAD

**Issue by Shiningheaven** [LedgerHQ/ledger-live-desktop#3131]
#### Ledger Live Version and Operating System

- tested on Ledger Live **version_here**
- Platform and version: **e.g. Mac 10.13.5 / Windows 10 / ..**

#### Expected behavior

Not able to use ledger while sending aeternity 
#### Actual behavior
0.4.1 version 

For Ledger nano x it freezes durning the fees screen 
And ledger nano s it doesn't proceed further after the address screen 
#### Steps to reproduce the behavior

Not able to send aeternity out from ledger.

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. 

This issue can happen for various reasons. We prefer to investigate such issues via contacting our customer support team.

could you send your logs to our support team and mention this github issue? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏  basically you can press Ctrl+E just after the problem occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.now.sh/logsviewer )
