### ISSUE TITLE
Add Support for Kin in desktop app

### ISSUE THREAD

**Issue by mocolicious** [LedgerHQ/ledger-live-desktop#3134]
The kin app for ledger allows use of kin but it is required that you use their website my kin wallet in order to use this feature.  Requesting support for the use of kin in Ledger live desktop app additionally.
#### Part of the application

Portfolio, Send, Receive, and Assets.

**Comment by gre** [comment]
please contact our official support to request adding more crypto assets in Ledger Live. They are not directly managed on this Ledger Live Github repository but you can request it to our custom support and/or contact us on our Ledger Slack Devs (if you are a developer and have access).

Thanks.
