### ISSUE TITLE
Add support for Fio protocol.

### ISSUE THREAD

**Issue by w-canvas** [LedgerHQ/ledger-live-desktop#3157]
Please add support for Fio (Foundation For Interwallet Operability) protocol via the ledger live app.

Ability to store receive and send tokens, addresses and domains as well as make fio requests send crypto from fio address and receive crypto to fio addresses.

**Comment by web-cdn** [comment]
I second this. This will make sending and receiving crypto lot easier.

**Comment by cthepot-ledger** [comment]
Thanks for the feedback. We have not planned to integrate FIO In the short/middle term.
