### ISSUE TITLE
Support Binance Smart Chain Accounts

### ISSUE THREAD

**Issue by cryptopolisrex** [LedgerHQ/ledger-live-desktop#3181]
- [X] I have checked this feature was not yet requested.

Currently there is no way ( I know of) to check the status / balance of accounts on the Binance Smart Chain in ledger live. Would be nice to add. 

#### Part of the application

Accounts

**Comment by akanass** [comment]
Totally agree with this one and Binance Chain account as well like this we will able to see balance for BEP2 and BEP20 tokens

**Comment by leeweezee777** [comment]
Yes please implement this.  This filthy girl has jumped onto Binance Smart Chain.
