### ISSUE TITLE
Add support for Uniswap ERC-20 token

### ISSUE THREAD

**Issue by bleiva** [LedgerHQ/ledger-live-desktop#3186]
- [*] I have checked this feature was not yet requested.

Currently there is no support for this new token.

https://etherscan.io/token/0x1f9840a85d5af5bf1d1762f925bdaddc4201f984

Thanks!

**Part of the application**

Accounts

**Comment by tigsobango** [comment]
I wholeheartedly agree. Need this token ASAP please :)

Thank you!

**Comment by cthepot-ledger** [comment]
Thanks for your request. 2.14 will include UNI
