### ISSUE TITLE
Pricing/Value for TRC-20 Tokens

### ISSUE THREAD

**Issue by eatdostacos** [LedgerHQ/ledger-live-desktop#3188]
- [x] I have checked this feature was not yet requested.

It would be very useful to add the pricing for certain TRC-20 tokens on the accounts and portfolio pages. Currently, under Tron on the accounts page, some of the common TRC-20 tokens I hold are shown, but no price is shown for them. USDT is one of my tokens that is pretty common, but it doesn't have the price shown. Thanks for your consideration.
-New happy Nano X user
#### Part of the application
Accounts/Portfolio

**Comment by jbnjohnathan** [comment]
I would like this too!

**Comment by domashno** [comment]
Also adding TERC 20 BTC please.

**Comment by gre** [comment]
the challenge to me is that, how can we guarantee that these tokens indeed reflect the value of their equivalent?
We saw examples in the past, e.g. USDT or DAI that shows it was not always equal to their equivalent (USD).

If exchanges don't offer a way to get countervalues of "TRC20 BTC", we could still allow to map it to "BTC" but it could be a bit false.

( cc @FabriceDautriat we can discuss more internally too )

**Comment by eatdostacos** [comment]
@gre Not sure how easy to implement this is, but the data could be pulled from JustSwap since that is where almost all of the TRC20 tokens are traded.

**Comment by gre** [comment]
This was implemented for some TRC tokens (BTT, USDT). feel free to contact our techsupport team if you think more tokens should have countervalues.
unfortunately at the moment we'll be limited to what our API provides ( e.g. https://countervalues.live.ledger.com/daily/BTT/USD ) but we can always add more over time.

Thanks

**Comment by domashno** [comment]
also would be great if you can add JustSwap functionality which is human friendly with fewer fees and very fast transactions.Do not forget JustLend too.
Moving something on ethereum network is damn expensive and dead slow!!! As your customer, I would love to have Tron services alternative to ethereum's.
