### ISSUE TITLE
Signed releases

### ISSUE THREAD

**Issue by Demi-Marie** [LedgerHQ/ledger-live-desktop#3193]
- [X] I have checked this feature was not yet requested.

Releases should be signed by Ledger, ideally with a key whose hash accompanies each Ledger device

#### Part of the application

Packaging

**Comment by dasilvarosa** [comment]
@Demi-Marie it's already the case. Please check all relevant information here: https://ledger-live-tools.now.sh/lld-signatures. (We're working on implementing this page into our official ledger.com website, so please don't pay attention to this temporary environment).
