### ISSUE TITLE
Tezos balance in fiat is wrong (billions of $ instead of thousands)

### ISSUE THREAD

**Issue by denver-s** [LedgerHQ/ledger-live-desktop#3217]
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.13.0
- Platform and version: Windows 10 (same happens on iOS app).

#### Expected behavior

Fiat value should be converted correctly.

#### Actual behavior

Value converted in fiat (USD/EUR) is wrong.

![image](https://user-images.githubusercontent.com/31325316/95257101-1ccd6600-0824-11eb-9e6c-1dd0b260f47d.png)

#### Steps to reproduce the behavior

Open Ledger Live and go to "Portfolio" window.

**Comment by cthepot-ledger** [comment]
@denver-s I was not able to reproduce this bug. Could you double check if you have still have the issue? 
We will release a significantly better version of our countervalue system

**Comment by denver-s** [comment]
@cthepot-ledger It seems to be fixed in the "Portfolio" section but not in the "Accounts":

<img width="630" src="https://user-images.githubusercontent.com/31325316/97541750-f6838c00-19c5-11eb-8e21-9d0c6ba87da3.png">

**Comment by denver-s** [comment]
@cthepot-ledger the problem persists in v2.16

**Comment by cthepot-ledger** [comment]
@denver-s thanks we shall look into it

**Comment by cthepot-ledger** [comment]
@denver-s the issue may be coming from our core lib interpreting numbers falsely - it would be helpful if you could open a support ticket on https://support.ledger.com/, attach logs to it and share your ticket id for our reference.

**Comment by cthepot-ledger** [comment]
Please try on latest version.
