### ISSUE TITLE
Support for WAVES

### ISSUE THREAD

**Issue by BurnyBoi** [LedgerHQ/ledger-live-desktop#3234]
Currently sending, receiving, and staking WAVES requires another app (I use waves.exchange). Being able to do this inside Ledger Live seems like it would be a great fit with the other crypto that is able to be staked.

**Comment by gre** [comment]
please contact our official support to request adding more crypto assets in Ledger Live. They are not directly managed on this Ledger Live Github repository but you can request it to our custom support and/or contact us on our Ledger Slack Devs (if you are a developer and have access).

Thanks.
