### ISSUE TITLE
Infinite synchronize account

### ISSUE THREAD

**Issue by maximereynders** [LedgerHQ/ledger-live-desktop#3237]
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.14.0 MacOS & 2.13.0 Android
- Platform and version: MacOS 10.12.6 & Android 10

#### Expected behavior

Account should refresh correctly.

#### Actual behavior

My account syncs and then pauses indefinitely (Desktop & mobile app).

Since I sent a USDT transaction which was never confirmed in the app. My account never refreshed again. So I'm block with a bad balance and I can't withdraw more (my account contains 0.31 ETH and shows 0.14 ETH in the app https://etherscan.io/address/0x6d840cc45084a6e1c353f0b329d50b8625fc6fe8) .

#### Steps to reproduce the behavior

As you can see here, my account syncs then pauses (same behavior on Android) -> 

<img width="741" alt="Capture d’écran 2020-10-14 à 14 19 25" src="https://user-images.githubusercontent.com/26227871/95987924-63c0ea00-0e28-11eb-9d0a-ae37a0405d75.png">
<img width="729" alt="Capture d’écran 2020-10-14 à 14 19 40" src="https://user-images.githubusercontent.com/26227871/95987931-66bbda80-0e28-11eb-919e-1d7cc9f9e48a.png">

Here the transaction which causes problem (I suppose) (https://etherscan.io/tx/0x54d429c1f6e6320a417f02870973cd458fcb98f3baf165a520ff30f9995a22fb)

As you can see it's blocked in unconfirmed status 

<img width="740" alt="Capture d’écran 2020-10-14 à 14 22 07" src="https://user-images.githubusercontent.com/26227871/95988110-ae426680-0e28-11eb-9aa4-a400f4b7bc4a.png">

<img width="498" alt="Capture d’écran 2020-10-14 à 14 29 20" src="https://user-images.githubusercontent.com/26227871/95988778-afc05e80-0e29-11eb-9bd5-01fb2c5c9b8d.png">

When I'm trying to synchronize my accounts to create a new one for instance I have an error here are the logs 

[ledgerlive-logs-2020.10.14-14.50.07-f6e507ec.json.zip](https://github.com/LedgerHQ/ledger-live-desktop/files/5378257/ledgerlive-logs-2020.10.14-14.50.07-f6e507ec.json.zip)

Thank you for your help !

**Comment by gre** [comment]
Could you tell us if it's still the case in 2.16 ?
A clear cache (settings / help) might help otherwise

**Comment by gre** [comment]
if it still happens, please continue with our official tech support team. closing for now.
