### ISSUE TITLE
Its show me one transaction multi times 

### ISSUE THREAD

**Issue by MHSanaei** [LedgerHQ/ledger-live-desktop#3255]
#### Ledger Live Version and Operating System

- tested on Ledger Live Ledger Live 2.14.0
- Platform and version: Windows 10

#### Expected behavior

it should just show it to me one time

#### Actual behavior

when i receive or send money with usdt trc20 

#### Steps to reproduce the behavior

![2020-10-24_1-19-04](https://user-images.githubusercontent.com/33454419/97057868-203d4d00-1599-11eb-9de2-c2ce7deb7279.png)

**Comment by gre** [comment]
@MHSanaei do you still experience this issue in v 2.16 ?

Thanks

**Comment by MHSanaei** [comment]
problem solved thanks
