### ISSUE TITLE
Debian 10 Ledger Live Desktop v2.14.0 crash after start

### ISSUE THREAD

**Issue by qrisjin** [LedgerHQ/ledger-live-desktop#3259]
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.14.0
- Platform and version: GNU/Linux Debian 10

#### Expected behavior

Start/execute AppImage with --no-sandbox parameter

#### Actual behavior

Crashed:

Internal process killed by signal (SIGSEGV)
Error
    at createCustomErrorClass (file:///tmp/.mount_ledger8tq0YW/resources/app.asar/.webpack/renderer.bundle.js:10832:19)
    at deserializeError (file:///tmp/.mount_ledger8tq0YW/resources/app.asar/.webpack/renderer.bundle.js:10860:35)
    at EventEmitter.handleCommandEvent (file:///tmp/.mount_ledger8tq0YW/resources/app.asar/.webpack/renderer.bundle.js:313177:59)
    at EventEmitter.emit (events.js:228:7)
    at Object.onMessage (electron/js2c/renderer_init.js:114:818)

#### Steps to reproduce the behavior

[ledgerlive-logs-2020.10.27-15.10.26-f6e507ec.zip](https://github.com/LedgerHQ/ledger-live-desktop/files/5447948/ledgerlive-logs-2020.10.27-15.10.26-f6e507ec.zip)

**Comment by clinta** [comment]
Same problem on Manjaro. Tested Version 2.16.0 and 2.17.1.

**Comment by clinta** [comment]
Still seeing this issue on 2.29.0. I've removed `~/.config/Ledger Live` and unplugged my ledger from the computer while starting ledger-live, still the same crash.

```
Ledger Live 2.29.0
(node:735968) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
init
Checking for update
spawned internal process 736206
Update for version 2.29.0 is not available (latest version: 2.29.0, downgrade is disallowed).
internal process 736206 got killed by signal SIGSEGV
(node:735968) UnhandledPromiseRejectionWarning: Error: Process not running
    at /tmp/.mount_ledgersfUke3/resources/app.asar/.webpack/main.bundle.js:3351:16
    at new Promise (<anonymous>)
    at InternalProcess_InternalProcess.stop (/tmp/.mount_ledgersfUke3/resources/app.asar/.webpack/main.bundle.js:3349:12)
    at App.<anonymous> (/tmp/.mount_ledgersfUke3/resources/app.asar/.webpack/main.bundle.js:3435:20)
    at App.emit (events.js:327:22)
(node:735968) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:735968) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```


[ledgerlive-logs-2021.06.10-11.19.16-5d17fec.json.txt](https://github.com/LedgerHQ/ledger-live-desktop/files/6632655/ledgerlive-logs-2021.06.10-11.19.16-5d17fec.json.txt)

**Comment by cthepot-ledger** [comment]
Please try the latest version. If it does not solve your situation please contact support on support.ledger.com.

**Comment by clinta** [comment]
This is still occurring for me on 2.30.0.
