### ISSUE TITLE
Add support for Helium (HNT) coin

### ISSUE THREAD

**Issue by jbnjohnathan** [LedgerHQ/ledger-live-desktop#3268]
- [X] I have checked this feature was not yet requested.

I would like native support for the Helium (HNT) crypto coin in the Ledger Live desktop and phone app.
Due to the Helium Network gaining traction many are now owners of this currency, and I for one would like to secure and use it with Ledger as easily as BTC and other currencies.

There is already an CLI application that can be found here: https://developer.helium.com/blockchain/ledger-hardware-wallet but its far from as easy to use. Nowhere near with for example BTC. This difficulty to use is preventing me to moving over my HNT assets to my Ledger device. 

Ledger Live app for Desktop and phone.

**Comment by maco2035** [comment]
This would be amazing! It would actually make use of my ledger!

**Comment by jackoat** [comment]
Ledger, make this happen! Please.

**Comment by Criptomata** [comment]
HNT is currently used in the real world for Proof of Coverage and other rewards for LoraWAN & IOT applications currently being deployed globally. Here's a current map of deployed devices for your reference: https://network.helium.com/coverage. Honestly, I would rather use Ledger to store my HNT as I deploy these sites but it is not formally supported by your team. Please prioritize as I do not like using a wallet on a mobile device due the inherent risks.

**Comment by cvolkernick** [comment]
adding my support for this. Have had a ledger sitting on my desk for awhile now not getting much use; have been hesitant to fully entrust my HNT to a patch solution but will definitely reconsider using as my main store when this goes official!

**Comment by Dmoney626** [comment]
Yes, please make this happen

**Comment by NttRAdmin** [comment]
Yes, please!

**Comment by neon-foundry-j** [comment]
This would be a lovely addition to have native support for the S & X beyond using the CLI. Documentation has now gone missing on the Helium developer site which makes me less confident in using that solution. Please consider, HNT is growing.

**Comment by gre** [comment]
please contact our official support to request adding more crypto assets in Ledger Live. They are not directly managed on this Ledger Live Github repository but you can request it to our custom support and/or contact us on our Ledger Slack Devs (if you are a developer and have access).

Thanks.

**Comment by NttRAdmin** [comment]
Can you give us a link....???

**Comment by m39869** [comment]
On Helium Website, doc mentions
"As of version 2.1.1, the Helium Ledger application is currently PENDING REVIEW by the Ledger team. The application is scheduled for security review and we hope to hear about the results by end of Q3 2021."
Q3 has passed and we don't see the support!

Ledger could you please add HNT coin support, please?

**Comment by MrTw3ek** [comment]
Yes!!! Need this!

**Comment by Blueforcer** [comment]
+1

**Comment by Deojuvente** [comment]
Whty is this still not done?

**Comment by ps350** [comment]
+1
