### ISSUE TITLE
Ledger Live Desktop (Windows) doesn't show balance

### ISSUE THREAD

**Issue by Seba200086** [LedgerHQ/ledger-live-desktop#3269]
Ledger Live (Windows) shows 0 (zero) balance on Bitcoin account.

I already tried to clear cache, reinstall, even reset app, tried to remove and add Bitcoin accounts, tried to synchronize on 2 separate networks (4G and cable) - still showing zero balance, no history of received/sent BTC.
App is up to date (2.15.0).
On my phone (LL on Android) seems to be ok - balance and history are fine.

I've no idea what else I should do... Any help appreciated!

![LL](https://user-images.githubusercontent.com/60579173/97922829-5d55cc00-1d5d-11eb-863b-03aa2c91f26b.JPG)

**Comment by jonsamwell** [comment]
Seeing the same issue

**Comment by gre** [comment]
There were a temporary Infra issue yesterday night. Please try again.

**Comment by Seba200086** [comment]
Yes, it's working now.
However, those kind of issues are not nice, at all. I didn't open LL wallet for a while and yesterday I've almost get a heart attack - WTF?! 0 BTC? 😮 
Glad that I had Android app as well...
