### ISSUE TITLE
Updating on Fedora/Gnome doesn't update the desktop application, and the app can't be opened.

### ISSUE THREAD

**Issue by Foxh0und** [LedgerHQ/ledger-live-desktop#3299]
#### Ledger Live Version and Operating System

<!-- 2.16.0->

- tested on Ledger Live **2.16.0**
- Platform and version: **Fedora 33/Gnome 3.38**

#### Expected behavior
The app image under `~/.local/share/applications/appimagekit-ledger-live-desktop.desktop ` should update the Exec line with the new executeable AppImage

#### Actual behavior
The aforementioned Exec line is not updated, therefore when you launch the application from the launcher, it won't find the AppImage and doesn't open.

#### Steps to reproduce the behavior
1. Install a previous version of Ledger Live
2. Update it.

![image](https://user-images.githubusercontent.com/5959163/99604857-916a0600-2a5a-11eb-8902-672f708f6db7.png)

**Comment by gre** [comment]
need more details. please contact our tech support on official support.ledger.com
