### ISSUE TITLE
Cannot interact with Ledger apps after firmware upgrade

### ISSUE THREAD

**Issue by sanchopansa** [LedgerHQ/ledger-live-desktop#3303]
#### Ledger Live Version and Operating System

- Tested on Ledger Live **2.16.0**
- Platform and version: **Ubuntu 18.04**
- Ledger: **Ledger Nano X**
- Secure Element: **1.2.4-5**
- Microcontroller: **2.10**
- Bootloader: **1.4**

#### Expected behavior

Be able to generate new addresses and send transactions

#### Actual behavior

I am unable to send transactions (e.g. using the Bitcoin or Ethereum apps) or to generate addresses. MetaMask also cannot communicate with the device (transactions do not appear on the Ledger and MetaMask timeouts).

As best as I can tell, this happened following a firmware update to 1.2.4-5 yesterday (I'm using the Ledger on a daily basis and hit this issue for the first time today).

#### Steps to reproduce the behavior

This happens for **all** operations I attempt on the Ledger Nano X apps at the moment. Please see the attached screenshots. Note that the device is visible in the Manager, however I'm unable to execute any actions using the applications on the Ledger. I'm also attaching the logs from Ledger Live.

#### Finale
I need to urgently exercise an ETH call option, which expires in less than 24 hours. Please tell me that I would be able to do so, without importing my seed phrase into a software wallet.

![Screenshot from 2020-11-20 16-10-46](https://user-images.githubusercontent.com/1084884/99809487-09175e00-2b4b-11eb-8692-2f94c24b5c31.png)
![Screenshot from 2020-11-20 16-12-03](https://user-images.githubusercontent.com/1084884/99809584-28ae8680-2b4b-11eb-8023-863fef768dfa.png)
[ledgerlive-logs-2020.11.20-16.14.00-116cda52.zip](https://github.com/LedgerHQ/ledger-live-desktop/files/5574029/ledgerlive-logs-2020.11.20-16.14.00-116cda52.zip)

**Comment by DevToby1337** [comment]
Also happens for me.
OS: Kubuntu 20.04
Ledger Live: 2.16.0
Device: Leder Nano X
Secure Element: 1.2.4-5
Microcontroller: 2.10
Bootloader: 1.4

**Comment by sanchopansa** [comment]
I was able to fix the issue by running `wget -q -O -
https://raw.githubusercontent.com/LedgerHQ/udev-rules/master/add_udev_rules.sh
| sudo bash`
