### ISSUE TITLE
ETC installation failure - 0x6a83

### ISSUE THREAD

**Issue by stecb** [LedgerHQ/ledger-live-desktop#3306]
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.16.0
- Platform and version: Mac 11.0.1 (big sur)

#### Expected behavior

It should correctly install the Ethereum Classic application

#### Actual behavior

When trying to install Ethereum Classic App it fails showing the following error:

<img width="758" alt="Screenshot 2020-11-21 at 01 03 32" src="https://user-images.githubusercontent.com/122819/99861110-72bc5a00-2b95-11eb-96cd-227eb540febd.png">

#### Steps to reproduce the behavior

- open the ledger app
- go to manager 
- connect and unlock ledger nano s
- search for ethereum classic app
- click on install
- it fails with `Ledger device: UNKNOWN_ERROR (0x6a83)`

**Comment by erdnapa** [comment]
Exact same issue here, Linux, Ledger Live 2.16.0
100% reproducible.

**Comment by benhk2005** [comment]
same here

**Comment by gakopp** [comment]
same here

**Comment by t1ght** [comment]
I have the same problem, but not with ETC app but with EWC (EnergyWebChain) App.

**Comment by spoiltrf** [comment]
same problem with ETC

**Comment by erdnapa** [comment]
Quick update: Ledger released ETC version 1.5.1, which fixes the issue.
