### ISSUE TITLE
Uniswap price incorrect

### ISSUE THREAD

**Issue by BurnyBoi** [LedgerHQ/ledger-live-desktop#3307]
#### Ledger Live Version and Operating System

Ledger Live 2.17.1 compiled develop branch

#### Expected behavior

Uniswap at the time of writing this is about $3.78

#### Actual behavior

Uniswap is showing as $0.009 in Ledger Live

#### Steps to reproduce the behavior

![pic-selected-201121-1448-21](https://user-images.githubusercontent.com/41203525/99886192-9ec4f300-2c08-11eb-95d4-e1b6f4e054d8.png)

**Comment by gre** [comment]
Is it still the case with Ledger Live 2.18 ? thanks

**Comment by Jsl-1** [comment]
Hi,
It's the same with 2.18 and 2.19 Uniswap  price is $0.003 instead of $3.54

**Comment by leeweezee777** [comment]
This is still an issue with 2.20 as well, price showing as $0.006.

**Comment by gre** [comment]
The fix is coming in 2.21.0.

**Comment by cthepot-ledger** [comment]
fixed
