### ISSUE TITLE
EWC (EnergyWeb) installation failure - 0x6a83

### ISSUE THREAD

**Issue by t1ght** [LedgerHQ/ledger-live-desktop#3311]
Ledger Live Version and Operating System

- tested on Ledger Live 2.16.0
- Platform and version: Windows 10 Home
- Ledger Firmware: 1.6.1.
- Ledger Nano S

Expected behavior
It should correctly install the EnergyWeb application

Actual behavior
When trying to install EnergyWeb App it fails showing the following error:

<img width="758" alt="99861110-72bc5a00-2b95-11eb-96cd-227eb540febd" src="https://user-images.githubusercontent.com/74836012/100001515-8fd67000-2dc3-11eb-9b24-bfaaa2ad2d91.png">

Steps to reproduce the behavior

- open the ledger app
- go to manager
- connect and unlock ledger nano s
- search for EnergyWeb app
- click on install
- it fails with Ledger device: UNKNOWN_ERROR (0x6a83)

**Comment by TamtamHero** [comment]
I couldn't reproduce it on the same setup.
Try to first install Ethereum app, then EWC (the Live should handle this automatically, no idea why it doesn't on your setup)
