### ISSUE TITLE
issue with Ledger Live synchronization "paused" and oops cannot connect to internet

### ISSUE THREAD

**Issue by apierceledger** [LedgerHQ/ledger-live-desktop#3319]
I hope anyone will be able to help me. as I have no answer from support team and I am not a technical person, so not sure how to solve this issue.
When connecting my Nano Ledger S to Ledger Live it won't synch. It starts synchronization and after a couple of seconds it says "paused".
When I go on the "Manager" tab on the left hand side it says : "Oops, cannot connect to the internet".
WHat can I do please?
- My internet connection is fine
- I installed the latest version of ledger live and the cleared the cache (as was advised on an article from support ledger)
- I restarted my computer
- I tried to use a different USB port.

What else could I try please? Thank you.

**Comment by gre** [comment]
dup https://github.com/LedgerHQ/ledger-live-desktop/issues/3319

**Comment by iazpiazu74** [comment]
Hello
I have the same issue
I am not able to synchronize. Appears "paused" too
Did you solved this issue?

**Comment by apierceledger** [comment]
No, never managed to solve the issue. I just changed computer, reinstalled
everything and then it worked.
