### ISSUE TITLE
Ledger nano S can`t interact with Eth2 Staking Smart Contract (Metamask)

### ISSUE THREAD

**Issue by victorelec14** [LedgerHQ/ledger-live-desktop#3338]
#### Ledger Live Version and Operating System

- tested on Ledger Live **Ledger nano X, firmware 1.2.4-5 , ETH 1.6.1**
- Platform and version: **Windows 10**

#### Steps to reproduce the behavior

Ledger cannot interact with the Eth2 SmartContrat (launchpad), the contract is not signed.

```
Contract data: Allow contract data in transactions -> Allowed
Ledger nano X,
Firmware 1.2.4-5 , 
App ETH 1.6.1
```

I have tried with different browsers, with Brave, Chrome + Metamask and with another usb cable.

the problem is happening to many people with the latest firmware.

```
MetaMask - RPC Error: Error: TransportStatusError: Ledger device: Condition of use not satisfied (denied by the user?) (0x6985) {code: -32603, message: "Error: TransportStatusError: Ledger device: Condit… use not satisfied (denied by the user?) (0x6985)", stack: "Error: Error: TransportStatusError: Ledger device:… use not satisfied (denied by the user?) (0x6985)"}
```

![image](https://user-images.githubusercontent.com/543450/100472365-66c42100-30dc-11eb-895a-90c10714e0ba.png)

![image](https://user-images.githubusercontent.com/543450/100473012-adfee180-30dd-11eb-86b9-c206613508c6.png)

More people with the same problem:
https://www.reddit.com/r/ledgerwallet/comments/k0l294/unable_to_interact_with_eth2_staking_contract/

**Comment by gre** [comment]
this is not the correct repository. this repository is about Ledger Live desktop.
