### ISSUE TITLE
Australian Dollar (AUD) countervalue STILL not available (it used to be)...

### ISSUE THREAD

**Issue by tester2011** [LedgerHQ/ledger-live-desktop#3344]
Guys, for the love of Buddha, PLEASE re-add the Australian Dollar countervalue (under settings).

Previous versions (prior to 2.10.x?) had it. Chr*st, there's even the Turkish Lire and shekel!

Forgive my frustration, but this is maddening...

**Comment by gre** [comment]
Hi, we have many other existing ticket regarding this situation. Please refer to other GitHub issues if you want to see more about this.

But the tldr is: good news, a new version is coming to solve this. ETA 1 week. 2.18
