### ISSUE TITLE
Ledger error Unable to reset the device in /polkadot-js/apps/

### ISSUE THREAD

**Issue by ercab24** [LedgerHQ/ledger-live-desktop#3345]
Today I am trying toy accesse my ledger and move some token that I have there and I have that problem. I have tried with Firefox, Brave and it is the same problem. Does anyone know how to solve this? What other option can you give me to move the assets?

**Comment by gre** [comment]
🤔 where does this error come from exactly?

**Comment by gre** [comment]
I don't think this is part of ledger-live-desktop project.
