### ISSUE TITLE
Ledger Live Support - NEO

### ISSUE THREAD

**Issue by 92Condors** [LedgerHQ/ledger-live-desktop#3353]
- [ Y] I have checked this feature was not yet requested.

Please implement Ledger Live support for NEO. The hardware support works great but not being able to see the balance in the portfolio is rather annoying.

**Comment by gre** [comment]
please contact our official support to request adding more crypto assets in Ledger Live. They are not directly managed on this Ledger Live Github repository but you can request it to our custom support and/or contact us on our Ledger Slack Devs (if you are a developer and have access).

Thanks.
