### ISSUE TITLE
xDAI

### ISSUE THREAD

**Issue by Pacmale** [LedgerHQ/ledger-live-desktop#3362]
I’d love to have xDAI in ledger live its an eth token I’m sure you have heard about it!

**Comment by gre** [comment]
Cc @FabriceDautriat

**Comment by FabriceDautriat** [comment]
The smart contract address could help @Pacmale 😉

**Comment by FabriceDautriat** [comment]
Maybe you wanted to say STAKE.

If that's the case, it's already supported.

See [here](https://github.com/LedgerHQ/ledgerjs/blob/56a9227fceb5f8b92f5ae77df0cdc82e5891608b/packages/cryptoassets/data/erc20.js#L1399).

**Comment by Pacmale** [comment]
@FabriceDautriat 
0x0Ae055097C6d159879521C384F1D2123D1f195e6

I noticed it was in there, yes. The STAKE token. I never use Github and I feel a bit out of place but directed here to suggest tokens to add to ledger live.

I can't add them in my accounts though. Only ERC20 tokens that show up are STR and POOL. no xDAI (STAKE) maybe I'm missing something

**Comment by Pacmale** [comment]
Right. I got it to work, not the traditional way but with Metamask 👍
