### ISSUE TITLE
Pre-release 2.18.0 doesn't show full total in Portfolio chart

### ISSUE THREAD

**Issue by jensamunch** [LedgerHQ/ledger-live-desktop#3365]
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.18.0
- Platform and version: OSX Big Sur

#### Expected behavior

Portfolio chart shows all crypto total

#### Actual behavior

Portfolio chart only shows total of first crypto in this case ethereum

#### Steps to reproduce the behavior

![image](https://user-images.githubusercontent.com/1650140/101292401-231d9580-3807-11eb-967e-e710130b043f.png)

**Comment by gre** [comment]
Can you try to click on the "Synchronized" to see if it helps reloading it?
If still not, can you try to Settings>Help and do a Clear cache?

Let us know which solution works. Thanks.

**Comment by jensamunch** [comment]
hey @gre i just opened the app again and it just showed the right number. so must have been a synching thing.

i didnt have to do anything to resolve it basically. thanks

**Comment by rocketflames** [comment]
Same issue on **2.18.1** on **Android** app.
I don't know how the **Portfolio** total value is computed, but it is much lower than the sum of each individual account displayed on the **Accounts** tab.
How do you force the portfolio page to synchronize on Android? I believe there used to be a pull to refresh function but it doesn't work anymore, so I expect it to always be synchronized but it's not.

**Comment by raetser** [comment]
Toal balance is wrong here too, on win10, shows a total that is much lower than the sum of the accounts...

**Comment by cthepot-ledger** [comment]
Should be fixed with latest versions.
