### ISSUE TITLE
Price graph displays straight line

### ISSUE THREAD

**Issue by remmelt** [LedgerHQ/ledger-live-desktop#3371]
#### Expected behavior

When viewing accounts, a graph should appear that displays the price over time

#### Actual behavior

The graph shows a straight line, although the mouseover shows different prices

#### Steps to reproduce the behavior

<img width="1552" alt="Screenshot 2020-12-10 at 07 49 29" src="https://user-images.githubusercontent.com/1133496/101731661-3efd9180-3abc-11eb-99aa-6393e7d29ed4.png">

**Comment by gre** [comment]
This is to me the correct behavior:

- your last operation is in 2018, so in a 1 YEAR range, there will be no variation in BTC
- as you are currently watching the graph in BTC price, it shows a straight line. Click on the ♻️  double arrow on the left of the balance to swap to the USD chart.
