### ISSUE TITLE
Ledger Live ETC Balance

### ISSUE THREAD

**Issue by AngelaMoerkel** [LedgerHQ/ledger-live-desktop#3372]
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.17.1
- Platform and version: Mac 11.01

#### Expected behavior

After setting up an ETC account in Ledger Live and then sending ETC to the account address, the funds should also be displayed in Ledger Live.

#### Actual behavior

Ledger Nano S was connected to the MacBook and Ledger Live was opened. The Ethereum Classic Wallet App was installed on the Ledger Nano S. After successful installation, a new ETC account was created in the Accounts menu item, the wallet address was checked on the Ledger Nano S and copied.

It was then sent from an Exchange ETC to the copied and verified address, on the Blockchain Explorer the transaction is already recorded.

Ledger Live still shows no transaction, same is on the mobile app on an iPhone 6S.
Meanwhile, almost 24 hours have passed and nothing is displayed.

I looked in Google today and came across a forum post (in German) where someone described the same problem. This person also made a transaction on an existing address, but unfortunately the transaction is in Ledger Live.

https://forum.blocktrainer.de/t/sync-ledger-live-und-etc/5149

#### Steps to reproduce the behavior

1. Ledger Live App öffnen
2. LedgerNano S einstecken
3. PIN
4. Open ETC App
5. Accounts
6. New Account
7. Receive funds
8. verify and copy Adress
9. Send funds to this Adress

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. 

This issue can happen for various reasons. We prefer to investigate such issues via contacting our customer support team.

could you send your logs to our support team and mention this github issue? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏  basically you can press Ctrl+E just after the problem occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.now.sh/logsviewer )
