### ISSUE TITLE
Ledger live windows showing 0 balance

### ISSUE THREAD

**Issue by gootloo** [LedgerHQ/ledger-live-desktop#3374]
I have a ledger nano s. I have connected it to my win 10 computer after quite a while. I updated to new firmware, installed new apps for my coins, added accounts etc. Now I can see all my coins accounts but balance is 0 and each of them has -100% beside them in red. I can see all my coins had withdrawl transactions as of today's date with Tx IDs...very confusing as I did not make any withdrawl. It seems like my coin balance were there yesterday but today they are gone as per the portfolio graphs I can see.

Transaction for ETH shows TXID as:
0xd68af78e1f44187f791fa5ea9bf69d66312582888fe70299ef00eb2af7820096

I tried changing rate providers, cleared cache, re-added accounts etc with no success. Any help?

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. 

This issue can happen for various reasons. We prefer to investigate such issues via contacting our customer support team.

could you send your logs to our support team and mention this github issue? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏  basically you can press Ctrl+E just after the problem occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.now.sh/logsviewer )

**Comment by gootloo** [comment]
HiI have uploaded the logs from ledger live to the link you sent me. I submitted support request yesterday. I did not get a ticket number or anything but ledger website showed request submitted successfully.Please assist.
ThanksDhru
 

    On Friday, December 11, 2020, 12:27:49 AM CST, Gaëtan Renaudeau <notifications@github.com> wrote:  
 
 


Closed #3374.

**Comment by gootloo** [comment]
How long does it take to get reply from ledger support?


Sent from Yahoo Mail for iPhone


On Friday, December 11, 2020, 10:50 AM, Dhru Das <dhru_xxx@yahoo.com> wrote:

HiI have uploaded the logs from ledger live to the link you sent me. I submitted support request yesterday. I did not get a ticket number or anything but ledger website showed request submitted successfully.Please assist.
ThanksDhru
 

    On Friday, December 11, 2020, 12:27:49 AM CST, Gaëtan Renaudeau <notifications@github.com> wrote:  
 
 


Closed #3374.
