### ISSUE TITLE
Spikes on the chart for BTC

### ISSUE THREAD

**Issue by Bird-NZ** [LedgerHQ/ledger-live-desktop#3376]
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.17.1
- Platform and version:  Windows 10, Build 18363

#### Expected behavior

I was expecting to have an accurate chart in ledger live that showed me the correct price of my BTC over time.

#### Actual behavior

I have spikes that show at the start of every month, as seen in the pic attached.
![image](https://user-images.githubusercontent.com/9666491/101954195-8ae93b80-3c60-11eb-9765-f0c8d29a53cd.png)

#### Steps to reproduce the behavior

Open Ledger live and see the graph.

**Comment by gre** [comment]
This is fixed in 2.18.0 and we will get even more fixed in following versions
