### ISSUE TITLE
Ledger customer support does not reply

### ISSUE THREAD

**Issue by gootloo** [LedgerHQ/ledger-live-desktop#3378]
Does ledger customer support reply at all? Its been over 3 days since I opened a case with ledger as all my coins are missing as soon as I opened ledger live windows and nobody cared to reply. I read on reddit that ledger support is responsive, but I am not seeing any reply. I submitted logs from ledge live also. And when I submitted ticket only thing I got was a pop up saying request submitted successfully. But no email or anything received giving me a ticket number. So how do I know if my request was received?
I paid for the ledger nano S. As customer we expect better service when our coins are missing. The sole purpose of ledger devices are to protect coins and it failed.

**Comment by jdetychey** [comment]
hey !
If you didn't get a support ticket number there s a high chance something went wrong with your email. Are you sure you provided the right address? Did you check your spam folder for a ticket number?

> The sole purpose of ledger devices are to protect coins and it failed.

That is not the sole purpose of ledger devices, they also provide a very good way of handling 2FA. Regarding whether Ledger devices successfully protected your coins or not, let's wait for the support to check with your incident as Ledger devices have been certified on several security aspects. 
You can have a look at security best practices here :
[](https://www.ledger.com/academy/hardwarewallet/best-practices-when-using-a-hardware-wallet)

**Comment by gootloo** [comment]
I checked my spam folder and no email from ledger with ticket from customer service. I opened ticket as per email from Gaetan. Please see below. I also uploaded the logs to the JSON link Gaetan sent. Why it is taking so long for ledger customer service to assist me?——————————————

Hi, thanks a lot for raising this issue.

This issue can happen for various reasons. We prefer to investigate such issues via contacting our customer support team.

could you send your logs to our support team and mention this github issue? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165 🙏 basically you can press Ctrl+E just after the problem occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.now.sh/logsviewer )

Sent from Yahoo Mail for iPhone


On Monday, December 14, 2020, 11:37 AM, Jerome de Tychey <notifications@github.com> wrote:




hey !
If you didn't get a support ticket number there s a high chance something went wrong with your email. Are you sure you provided the right address? Did you check your spam folder for a ticket number?


The sole purpose of ledger devices are to protect coins and it failed.


That is not the sole purpose of ledger devices, they also provide a very good way of handling 2FA. Regarding whether Ledger devices successfully protected your coins or not, let's wait for the support to check with your incident as Ledger devices have been certified on several security aspects.
You can have a look at security best practices here :

**Comment by cthepot-ledger** [comment]
@gootloo please re-issue your request on this URL. https://support.ledger.com/hc/en-us/requests/new.

Always ensure your submit tickets on ledger.com
