### ISSUE TITLE
After a new install of Live

### ISSUE THREAD

**Issue by RomHtK** [LedgerHQ/ledger-live-desktop#3379]
Hello, I have a question, I don't know if this is the right place for it, but I tried on twitter without answer and I can't find the answer on the support page. 
How can we find the list of crypto's held on a Nano S? I just reinstalled Ledger Live on my Debian but I don't remember which cryptos I have. Is there any other way than to reinstall the apps one by one to see their content?

Thanx in advance
Rom

**Comment by gre** [comment]
Unfortunately the only way is by adding the apps on the device and scanning accounts on each app.

There is an isolation between apps that prevent us to implement something more automatic (we can't scan LTC accounts on BTC app for instance)

**Comment by RomHtK** [comment]
Okay, thank you for this clarification. It's a real shame and annoying, I hope a solution will be possible one day.
