### ISSUE TITLE
Live Manager stuck on the "Loading" screen

### ISSUE THREAD

**Issue by ZeroEarl** [LedgerHQ/ledger-live-desktop#3395]
#### Ledger Live Version and Operating System

- tested on Ledger Live **2.18.0**
- Platform and version: **Mac 10.15.7**
- firewire: **1.2.4-4**

#### Expected behavior

Correctly display Manager content and manage apps

#### Actual behavior

Live Manager stuck on the "Loading" screen

#### Steps to reproduce the behavior

1. Open the  Dashboard
2. Click the “Manager” tab
3.  Unlock device and Allow Manager 
4. Display the "Loading" screen and always stop at this screen

![image](https://user-images.githubusercontent.com/46588563/102424656-9bc1f480-4046-11eb-8f07-ba9b0a017036.png)

**Comment by ZeroEarl** [comment]
Ledger: Ledger Nano X
Microcontroller: 2.10
Bootloader: 1.4

**Comment by cthepot-ledger** [comment]
@ZeroEarl thanks for reporting.

Could you double-check if
- there is only one single device plugged to your system
- there is only on version of Ledger Live opened (no Beta version should be opened)
- do you see the device illustration before the loading gets stuck? Can you reconfirm that you have allowed the manager on your device?

Thanks for your help,
Chris

**Comment by ZeroEarl** [comment]
- there is only one single device plugged to your system.
   yes
- there is only on version of Ledger Live opened (no Beta version should be opened)
  yes
- do you see the device illustration before the loading gets stuck? Can you reconfirm that you have allowed the manager on your device?
  I see the device illustration before the loading gets stuck, and have allowed the manager on my device.
- Finally do the counter value load in the portfolio tab?
 yes, the counter value is loaded successfully，but synchronization is often also “Loading”，As seen in the picture above.

**Comment by arthurk** [comment]
I have the same issue. 

Ledger Nano S
Ledger Live: 2.20.0
macOS: 10.15.7
Microcontroller: 1.12
Bootloader: 0.11

Not sure what changed, I've used it 1 month ago without any problems.

**Comment by arthurk** [comment]
It started working again, I'm very sure now that this is related to the network connection. Probably a server somewhere being overloaded and timing out. It would be helpful to see an error message instead of the never-ending "Loading..."

**Comment by lippling** [comment]
> I have the same issue.
> 
> I can see the "Connect and Unlock your Device" then "Allow Ledger Manager" and then it's stuck on "Loading"
> 
> Ledger Nano S
> Ledger Live: 2.20.0
> macOS: 10.15.7
> Microcontroller: 1.12
> Bootloader: 0.11
> 
> Not sure what changed, I've used it 1 month ago without any problems.

Same Problem here...

**Comment by juneyuanjunliu** [comment]
Ledger Nano S
Ledger Live: 2.20.0
macOS: 11.2
Microcontroller: 2.10
Bootloader: 1.4

I have the same problem. I updated the firmware this afternoon and the manager is stuck on Loading now. The ledger image popped up when I plug it in and I approved the ledger. Somehow it's always Loading.

**Comment by Naihan** [comment]
same here

Ledger Nano S
Ledger Live: 2.20.0
Windows 10
Secure Element 1.6.0
Micro controller 1.12

**Comment by cthepot-ledger** [comment]
@ZeroEarl Apologies for the late reply,

The customer support team would better tackle this issue as it would require proper troubleshooting.
Please open a ticket with our customer support https://support.ledger.com/hc/en-us

If you are experiencing this issue, kindly ensure:

- to run the latest version of Live
- the internet connection is stable
- to check status.ledger.com
- to reboot your system and reinstall Live
- to try with different USB cables
- to try with other computers or OS
- to take note of whether the device shows "Allow manager"

**Comment by lordeffk** [comment]
Hi,

On my side I solved the problem by deactiating in the Device Manager the other devices I had under USB Device...

Regards

**Comment by neocarmack** [comment]
same here. Anyone has a solution?

Ledger Nano S
Ledger Live: 2.40.0
Windows 10
