### ISSUE TITLE
Token values not updating in 2.18.0

### ISSUE THREAD

**Issue by falcon24c** [LedgerHQ/ledger-live-desktop#3396]
Since updating to Ledger Live 2.18.0 on Windows 10, the token values are not updating. The same is occurring since the recent app update on iOS 14.2. I can only confirm this for the XRP and XLM tokens. I have cleared the cache and nothing has changed. I first noticed this issue on iOS after updating the app on 12/15/2020, so I logged into the desktop app and all values were correct. I then took the 2.18.0 update and it immediately started showing the exact incorrect values as the iOS app.

**Comment by nabil17** [comment]
it doesn't work for btc eth and linkk either

**Comment by AdvancedStyle** [comment]
Same here on Ubuntu 20.04 with Ledger Live 2.18.0. values appear to be stuck even though "Synchronized" is showing a check.

Android version no values appear at all.

I'm guessing their price feed is down.

**Comment by CatMcDade** [comment]
I updated about 2 hours ago and have the same problem. Not updating BTC, ETH, LINK, etc...I synched many times and still have the problem.

**Comment by gre** [comment]
#3394 duplicate. Let's keep one thread. I'll answer there
