### ISSUE TITLE
Ledger Live Countervalue not working AGAIN

### ISSUE THREAD

**Issue by olivbrain** [LedgerHQ/ledger-live-desktop#3407]
Countervalue was not working, then you fixed it and it worked for 2 days..... and now it is not working again... PLEASE FIX

**Comment by gre** [comment]
status.ledger.com shows some spikes which indicates we still might have temporary issue during activity peak, even if this situation is not ideal, our back-end team is working on improving the performance of the service, meanwhile Ledgerr Live will be resilient and will continuously reload the missing data as soon as the API is responsive again. I think you can try again today.

Make sure to be on latest 2.19.0 which also fixed some bugs on countervalues.

Thanks

![Screenshot_20201223-102134](https://user-images.githubusercontent.com/211411/102981008-b0036700-4508-11eb-934f-91ee12718b86.jpg)

**Comment by gre** [comment]
On top of the fact we worked on infra/backend side to restore the situation back to normal,
Many other fixes will also land on the upcoming v2.20.0.
Thanks
