### ISSUE TITLE
Live Manager doesn't see the ledger nano S

### ISSUE THREAD

**Issue by RiccardoFerranti** [LedgerHQ/ledger-live-desktop#3417]
#### Ledger Live Version and Operating System

- tested on Ledger Live **v2.19**
- Platform and version: **e.g. Mac 10.15.7**
- firmware 1.5.5
- MCU 1.7

#### Expected behavior
Correctly display Manager content and manage apps

#### Actual behavior
After I unlock the ledger, I still see the message that ask me to connect and unlock the device, it's like the Ledger live application doesn't see it, but the usb seems work since the ledger is on correctly, so I cannot also send and receive nothing.
 

#### Steps to reproduce the behavior

1. Open the Dashboard
2. Click the “Manager” tab
3. Unlock device
4. I still see the words: "connect and unlock your device"

<img width="1005" alt="Screenshot 2020-12-27 at 01 59 29" src="https://user-images.githubusercontent.com/3688506/103161856-9e5fdf00-47e8-11eb-9302-c00334be0c26.png">

**Comment by deepure** [comment]
same problem

**Comment by RiccardoFerranti** [comment]
I tried 3 different cables and the third one is working, I don't understand very well what's going on, because also the other cables are working, since I tested them with other devices

**Comment by faket0shi** [comment]
Same here, version 2.18.0 works perfectly but version 2.19.0 does not recognize the device. 

Ledger Live Version and Operating System

    tested on Ledger Live v2.19
    Platform and version: e.g. Debian 10.4
    firmware 1.6.1

**Comment by tester2011** [comment]
Same issue here. Can't seem to see the device, even though it's showing as connected.

Ledger Live 2.19.0 (ledger-live-desktop-2.19.0-linux-x86_64.AppImage) on Linux Mint 19.3 64-bit.

I can also confirm that v2.18.0 works correctly.

Cheers,

Mike.

**Comment by ngkong** [comment]
same issue 

Ledger Live version: 2.19.0 (ledger-live-desktop-2.19.0-linux-x86_64.AppImage)
OS: ubuntu 18.04

previous version works

**Comment by deepure** [comment]
I tried four cables, the last one is working.

**Comment by RiccardoFerranti** [comment]
I bought another new cable and it seems working on this one as well, but apparently it seems working randomly, every cable I tried works with other devices.

**Comment by turbo124** [comment]
+1 works on windows, but not Ubuntu 18.04 for me

**Comment by er201662** [comment]
Having the same issue with my nano s. My nano s is on version 1.6.0 but can't update because I can't connect it. When I try to troubleshoot the nano s by updating it through the bootloader it gets stuck on 'bootloader' screen. Tried a handful of different USB cables in different ports including usb-c. It won't recognize it even after resetting and recovering the nano. Now my nano doesn't even show my assets since I recovered it. Please keep me posted.

**Comment by er201662** [comment]
> Having the same issue with my nano s. My nano s is on version 1.6.0 but can't update because I can't connect it. When I try to troubleshoot the nano s by updating it through the bootloader it gets stuck on 'bootloader' screen. Tried a handful of different USB cables in different ports including usb-c. It won't recognize it even after resetting and recovering the nano. Now my nano doesn't even show my assets since I recovered it. Please keep me posted.

***This is on Windows 10***

**Comment by er201662** [comment]
> > Having the same issue with my nano s. My nano s is on version 1.6.0 but can't update because I can't connect it. When I try to troubleshoot the nano s by updating it through the bootloader it gets stuck on 'bootloader' screen. Tried a handful of different USB cables in different ports including usb-c. It won't recognize it even after resetting and recovering the nano. Now my nano doesn't even show my assets since I recovered it. Please keep me posted.
> 
> _**This is on Windows 10**_

The 100th USB cord I tried worked...

**Comment by ngkong** [comment]
anyone with this problem just rollback to v2.18

**Comment by gre** [comment]
The situation will be fixed in our upcoming release v2.20.0
https://github.com/LedgerHQ/ledger-live-desktop/releases/tag/v2.20.0
^this build is still in **pre-release** stage but should become a **release** next Monday.

**Comment by RiccardoFerranti** [comment]
I still have the same problems after the releases, it's working just with some random cables and every cable is working with other devices

**Comment by vcavallo** [comment]
Reporting here: I was having the same issue here (device not being recognized in "genuine" check) even after following all the support articles and trying the various udev rules.

Tried a different cable and it's working now :facepalm: sort of insane.

**Comment by JosephMRally** [comment]
Having the same issue. cannot unlock device.

**Comment by code-haven** [comment]
I faced a similar problem while connecting my ledger nano S after a long time. I had to try three different mini-USB cables until the device was detected by the app.
