### ISSUE TITLE
SKL Support

### ISSUE THREAD

**Issue by cstrangedk** [LedgerHQ/ledger-live-desktop#3422]
I'd like to have SKALE (SKL) ERC777 token on Ledger Live as well (https://skale.network) .
The address is: `0x00c83aeCC790e8a4453e5dD3B0B4b3680501a7A7`

**Comment by payvint** [comment]
That's would be nice!

**Comment by cstrangedk** [comment]
https://etherscan.io/token/0x00c83aecc790e8a4453e5dd3b0b4b3680501a7a7

https://coinmarketcap.com/fr/currencies/skale-network/

**Comment by cstrangedk** [comment]
Hi @gre, also would like to see staking support on Ledger Live with SKL

**Comment by gre** [comment]
please contact our official support to request adding more crypto assets in Ledger Live. They are not directly managed on this Ledger Live Github repository but you can request it to our custom support and/or contact us on our Ledger Slack Devs (if you are a developer and have access).

Thanks.
