### ISSUE TITLE
AppImage not displaying icon once integrated with AppImageLauncher

### ISSUE THREAD

**Issue by herandol** [LedgerHQ/ledger-live-desktop#3426]
#### Ledger Live Version and Operating System

- tested on Ledger Live **2.19.0**
- Platform and version: **Ubuntu 20.04**

#### Expected behavior

The Ledger Live icon should be displayed

#### Actual behavior

No icon is displayed

#### Steps to reproduce the behavior

Install Ledger Live on Ubuntu 20.04 and integrate it with AppImageLauncher

![Screenshot from 2020-12-30 12-27-18](https://user-images.githubusercontent.com/72215353/103351344-3ee12800-4aa3-11eb-8647-ea879b61a203.png)

**Comment by gre** [comment]
Thanks to your fix, this is now included as part of https://github.com/LedgerHQ/ledger-live-desktop/releases/tag/v2.20.0
