### ISSUE TITLE
Ledger Live not working with Linux mode on Pixel Slate

### ISSUE THREAD

**Issue by jrgleason** [LedgerHQ/ledger-live-desktop#3428]
**What I would expect:**

I should be able to use the ledger live app to connect to my wallet using ChromeOS Linux Beta on my Pixel Slate.

**What happens**

I follow these steps (https://support.google.com/chromebook/thread/73745162?hl=en) and as I am trying to setup my existing Ledger it fails to recognize the usb.

**Script**

```
wget -q -O - https://raw.githubusercontent.com/LedgerHQ/udev-rules/master/add_udev_rules.sh | sudo bash
./ledger-live-desktop-2.19.0-linux-x86_64.AppImage --no-sandbox
```

Result

Gets stuck here... 

![Screenshot 2020-12-30 at 10 45 41 AM](https://user-images.githubusercontent.com/1319151/103364628-40ebbc80-4a8c-11eb-84d7-4caec4cd88ad.png)

**Comment by gre** [comment]
As far as I understand, this related to #3430
which is fixed in v2.20.0 https://github.com/LedgerHQ/ledger-live-desktop/releases/tag/v2.20.0
it will be released next monday (currently in pre-release)
