### ISSUE TITLE
Add support for ShapeShift FOX ERC-20 Token

### ISSUE THREAD

**Issue by Jsl-1** [LedgerHQ/ledger-live-desktop#3449]
- [*] I have checked this feature was not yet requested.

Currently there is no support for FOX ERC-20 Token (https://shapeshift.com).

Token page on etherscan: https://etherscan.io/token/0xc770eefad204b5180df6a14ee197d99d808ee52d?a=0x9532bb23F39A68847f4d5634A3f2cD805a747E55

Coin market cap :
https://coinmarketcap.com/fr/currencies/fox-token/

Thanks!

**Part of the application**  :  Accounts

**Comment by gre** [comment]
please contact our official support to request adding more crypto assets in Ledger Live. They are not directly managed on this Ledger Live Github repository but you can request it to our custom support and/or contact us on our Ledger Slack Devs (if you are a developer and have access).

Thanks.
