### ISSUE TITLE
Add Swedish krona (SEK) countervalue currency

### ISSUE THREAD

**Issue by mandrean** [LedgerHQ/ledger-live-desktop#3460]
Swedish users would be delighted if you could add the Swedish krona (SEK) as one of the countervalue currency options in the Ledger Live app.

It was previously discussed in #1467, but was at the time closed because there was no BTCSEK pair on TradingView

There is now, however: https://www.tradingview.com/symbols/BTCSEK/

**Comment by gre** [comment]
Actually, it's already the case.
![Capture d’écran 2021-01-12 à 17 00 33](https://user-images.githubusercontent.com/211411/104339272-b37e8280-54f7-11eb-8b8c-92680bc00cef.png)
