### ISSUE TITLE
Decred send error

### ISSUE THREAD

**Issue by beyondsoft978** [LedgerHQ/ledger-live-desktop#3478]
#### Ledger Live Version and Operating System

- tested on Ledger Live **2.20.0**
- Platform and version: ** Windows 10 / ..**
decred app  version upto 1.3.11
#### Expected behavior

PC and andriod ledger live  is same this error
#### Steps to reproduce the behavior

![image](https://user-images.githubusercontent.com/72330466/104794467-b07adf00-57e2-11eb-9372-6ed9394694e4.png)

**Comment by posa88** [comment]
I can't send dcr either,  with the following error:
**name":"TransportError","message":"data.length exceed 256 bytes limit. Got: 256 data.length exceed 256 bytes limit. Got: 256",**

**Comment by beyondsoft978** [comment]
Please correct this problem as soon as possible, the decred cannot be transferred normally

**Comment by beyondsoft978** [comment]
@gre  This problem has not been resolved, is there a temporary way to transfer out my Decred?

**Comment by posa88** [comment]
any progress?

**Comment by beyondsoft978** [comment]
> any progress?

not yet

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. 

Unfortunately i'm not able to reproduce the problem with my accounts, so it might be related to your specific accounts conditions (depends on what kind of transactions you have / utxos / maybe something specific you did with your Decred account?)

As Github is public, we prefer to investigate such issues via contacting our customer support team.

could you send your logs to our support team and mention this github issue? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏  basically you can press Ctrl+E just after the problem occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.now.sh/logsviewer )

Right now, it's hard to understand the issue.

**Comment by beyondsoft978** [comment]
@gre 
2789
2021-01-15T11:02:25.455Z
renderer
data.length exceed 256 bytes limit. Got: 257 data.length exceed 256 bytes limit. Got: 257
{stack: "Error at new TransportError (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:11043:18) at file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:11047:68 at deserializeError (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:10866:25) at EventEmitter.handleCommandEvent (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:305832:59) at EventEmitter.emit (events.js:327:22) at Object.onMessage (electron/js2c/renderer_init.js:91:925)", name: "TransportError", id: "DataLengthTooBig"}
stack: "Error at new TransportError (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:11043:18) at file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:11047:68 at deserializeError (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:10866:25) at EventEmitter.handleCommandEvent (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:305832:59) at EventEmitter.emit (events.js:327:22) at Object.onMessage (electron/js2c/renderer_init.js:91:925)"
name: "TransportError"
id: "DataLengthTooBig"
2790
2021-01-15T11:02:25.454Z
renderer
actions-transaction-event
error
{data: Object}
data: Object
type: "error"
error: Object
name: "TransportError"
message: "data.length exceed 256 bytes limit. Got: 257"
stack: "Error at new TransportError (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:11043:18) at file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:11047:68 at deserializeError (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:10866:25) at EventEmitter.handleCommandEvent (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:305832:59) at EventEmitter.emit (events.js:327:22) at Object.onMessage (electron/js2c/renderer_init.js:91:925)"
id: "DataLengthTooBig"
2791
2021-01-15T11:02:25.410Z
renderer
cmd.ERROR
✖ CMD AccountSignOperation error
{data: Object}
data: Object
name: "TransportError"
message: "data.length exceed 256 bytes limit. Got: 257"
stack: "Error at new TransportError (C:\Program Files\Ledger Live\resources\app.asar\node_modules\@ledgerhq\errors\dist\index.cjs.js:220:18) at TransportNodeHidSingleton.Transport.send (C:\Program Files\Ledger Live\resources\app.asar\node_modules\@ledgerhq\hw-transport\lib\Transport.js:52:15) at getTrustedInputRaw (C:\Program Files\Ledger Live\resources\app.asar\node_modules\@ledgerhq\hw-app-btc\lib\getTrustedInput.js:30:40) at processWholeScriptBlock (C:\Program Files\Ledger Live\resources\app.asar\node_modules\@ledgerhq\hw-app-btc\lib\getTrustedInput.js:84:44) at getTrustedInput (C:\Program Files\Ledger Live\resources\app.asar\node_modules\@ledgerhq\hw-app-btc\lib\getTrustedInput.js:97:23) at async createTransaction (C:\Program Files\Ledger Live\resources\app.asar\node_modules\@ledgerhq\hw-app-btc\lib\createTransaction.js:134:28) at async Btc.createPaymentTransactionNew (C:\Program Files\Ledger Live\resources\app.asar\node_modules\@ledgerhq\hw-transport\lib\Transport.js:240:16) at async signTransaction (C:\Program Files\Ledger Live\resources\app.asar\node_modules\@ledgerhq\live-common\lib\families\bitcoin\libcore-signOperation.js:145:21)"
id: "DataLengthTooBig"
2792
2021-01-15T11:02:25.408Z
internal
cmd.ERROR
✖ CMD AccountSignOperation error
{data: Object}
data: Object
name: "TransportError"
message: "data.length exceed 256 bytes limit. Got: 257"
stack: "Error at new TransportError (C:\Program Files\Ledger Live\resources\app.asar\node_modules\@ledgerhq\errors\dist\index.cjs.js:220:18) at TransportNodeHidSingleton.Transport.send (C:\Program Files\Ledger Live\resources\app.asar\node_modules\@ledgerhq\hw-transport\lib\Transport.js:52:15) at getTrustedInputRaw (C:\Program Files\Ledger Live\resources\app.asar\node_modules\@ledgerhq\hw-app-btc\lib\getTrustedInput.js:30:40) at processWholeScriptBlock (C:\Program Files\Ledger Live\resources\app.asar\node_modules\@ledgerhq\hw-app-btc\lib\getTrustedInput.js:84:44) at getTrustedInput (C:\Program Files\Ledger Live\resources\app.asar\node_modules\@ledgerhq\hw-app-btc\lib\getTrustedInput.js:97:23) at async createTransaction (C:\Program Files\Ledger Live\resources\app.asar\node_modules\@ledgerhq\hw-app-btc\lib\createTransaction.js:134:28) at async Btc.createPaymentTransactionNew (C:\Program Files\Ledger Live\resources\app.asar\node_modules\@ledgerhq\hw-transport\lib\Transport.js:240:16) at async signTransaction (C:\Program Files\Ledger Live\resources\app.asar\node_modules\@ledgerhq\live-common\lib\families\bitcoin\libcore-signOperation.js:145:21)"
id: "DataLengthTooBig"
2793
2021-01-15T11:02:25.408Z
internal
Command error:
{error: Object}
error: Object
name: "TransportError"
message: "data.length exceed 256 bytes limit. Got: 257"
stack: "Error at new TransportError (C:\Program Files\Ledger Live\resources\app.asar\node_modules\@ledgerhq\errors\dist\index.cjs.js:220:18) at TransportNodeHidSingleton.Transport.send (C:\Program Files\Ledger Live\resources\app.asar\node_modules\@ledgerhq\hw-transport\lib\Transport.js:52:15) at getTrustedInputRaw (C:\Program Files\Ledger Live\resources\app.asar\node_modules\@ledgerhq\hw-app-btc\lib\getTrustedInput.js:30:40) at processWholeScriptBlock (C:\Program Files\Ledger Live\resources\app.asar\node_modules\@ledgerhq\hw-app-btc\lib\getTrustedInput.js:84:44) at getTrustedInput (C:\Program Files\Ledger Live\resources\app.asar\node_modules\@ledgerhq\hw-app-btc\lib\getTrustedInput.js:97:23) at async createTransaction (C:\Program Files\Ledger Live\resources\app.asar\node_modules\@ledgerhq\hw-app-btc\lib\createTransaction.js:134:28) at async Btc.createPaymentTransactionNew (C:\Program Files\Ledger Live\resources\app.asar\node_modules\@ledgerhq\hw-transport\lib\Transport.js:240:16) at async signTransaction (C:\Program Files\Ledger Live\resources\app.asar\node_modules\@ledgerhq\live-common\lib\families\bitcoin\libcore-signOperation.js:145:21)"
id: "DataLengthTooBig"

**Comment by beyondsoft978** [comment]
I have used trezor transfer all out, please be careful! other users dont use  ledger keep you  ETH and  DCR ! 
you coin may be  dont seed!!!

**Comment by posa88** [comment]
still can't send my dcr, same error...

**Comment by posa88** [comment]
> I have used trezor transfer all out, please be careful! other users dont use ledger keep you ETC and DCR !
> you coin may be dont send out!!!

Can't recover my seed phrase to trezor, do you know why?

**Comment by posa88** [comment]
no body can help?

**Comment by WuCris** [comment]
I was able to send Decred from my Ledger on Mar 5, but I can't today. Perhaps this has something to do with the mixing of different inputs? Seeing how I am using the same version of Ledger Live I'm not sure what other discrepancy could exist.
