### ISSUE TITLE
New version 2.20 does not have simplified Chinese

### ISSUE THREAD

**Issue by ceozero** [LedgerHQ/ledger-live-desktop#3489]
The previous version has simplified Chinese.
Simplified Chinese cannot be selected after updating to the latest version.
Where can I download the simplified Chinese language pack?

**Comment by juan-cortes** [comment]
Due to the rework of the onboarding flows we dropped most of the experimental translations. 
Once we have the wording translated again we will make them available in a future release, sorry for the inconvenience.

**Comment by franco999** [comment]
> Due to the rework of the onboarding flows we dropped most of the experimental translations.
> Once we have the wording translated again we will make them available in a future release, sorry for the inconvenience.

@juan-cortes Does it mean that the translations function is no longer supported? It's a pity. It is very poor the internationalization of the app with only the 2 languages that brings (English and French) and in experimental it does not show me anything in Spanish (although there are already some translations for this in Crowdin).

**Comment by juan-cortes** [comment]
Maybe I wasn't clear on my previous message, if so, I apologize. The translations will be available as experimental again soon, and we are working towards stable translations for more languages in the near future

**Comment by franco999** [comment]
Now it is clearer to me. I am currently trying to translate the Spanish language and when I read the message I had thought that it was no longer supported and would not be implemented again. Good.
