### ISSUE TITLE
In Ledger Live the historical weekly view looks flat. It should be scaled so that min is the closest even number less than the min for the period

### ISSUE THREAD

**Issue by olofedlund** [LedgerHQ/ledger-live-desktop#3507]
See title

**Comment by gre** [comment]
Do you have a screenshot exemple of this behavior? I'm not sure to understand what you meant.

**Comment by olofedlund** [comment]
The values should be more pronounced, not just a “flat line”.

For ETH, if the price is between 1300 and 1400 for my chosen time period, lets say a week, then the Y-axis should start at 1300, not 0. The Y-axis should be 1300 - 1400, not 0 - 1400. If it starts at 0 then the line is just a rather flat line at the top. For every chart the min and the max should be such that the line barely stays between the min and max value on the Y-axis.

I feel uneasy making a screen shot but I tried to over-explain. If still unclear, I’ll try again.

**Comment by gre** [comment]
Ok explanation is clear. Indeed you are right.

I think we used to display the graph with a non-zero based graph. I'm surprised it's not anymore the case. I suspect we did a regression here during our recent rework. cc @JunichiSugiura

**Comment by olofedlund** [comment]
I have never seen it non zero based and I’ve used it ever since it was released. I might have missed it because there were some periods when I didn’t use it.

**Comment by WiebeVanAken** [comment]
As per 1/11/21, this issue has re-occured. My graph in Ledger Live is from 0 to (as an example) 400 euros. Making an almost flat line on my daily / weekly chart.

![image](https://user-images.githubusercontent.com/19958930/139675652-341d0ba0-5d08-4e09-b46c-9b812f9f8594.png)
