### ISSUE TITLE
'Something went wrong' during swap

### ISSUE THREAD

**Issue by gaardiolor** [LedgerHQ/ledger-live-desktop#3508]
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.20.0
- Platform and version: Windows 10

#### Expected behavior

A swap

#### Actual behavior

An error. 
![image](https://user-images.githubusercontent.com/22920143/105644356-7ae68d80-5e95-11eb-8d42-2572326967f4.png)

#### Steps to reproduce the behavior

Make a swap, 0.015 BTC to USDC. 

I'm able to send BTC with the same device & BTC account.

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. 

This issue can happen for various reasons. Unfortunately with the information provided here we can't really understand the problem. We prefer to investigate such issues via contacting our customer support team.

could you send your logs to our support team and mention this github issue? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏  basically you can press Ctrl+E just after the problem occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.now.sh/logsviewer )
