### ISSUE TITLE
Download takes forever and fails 

### ISSUE THREAD

**Issue by mzq1213** [LedgerHQ/ledger-live-desktop#3530]
What's wrong with the Ledger live desktop for Mac? The download takes forever and fails every time. Tried different network and vpn but not work at all

**Comment by juan-cortes** [comment]
Hello @mzq1213, Are you referring to downloading an update from within the application itself, or downloading the latest version from https://www.ledger.com/ledger-live/download

**Comment by gre** [comment]
unfortunately it relates to Github CDN. We might chose better places to host these releases because Github's can sometimes be slow.
