### ISSUE TITLE
Ledger Nano S” neither button works

### ISSUE THREAD

**Issue by djspops** [LedgerHQ/ledger-live-desktop#3531]
#### Ledger Live Version and Operating System

- tested on Ledger Live **version_here**
- Platform and version: **e.g. Mac 10.13.5 / Windows 10 / ..**

**Comment by djspops** [comment]
Version 2.20.0 broken on Win10  -

**Comment by juan-cortes** [comment]
Hello @djspops would you mind filling the rest of the fields in the issue template so that we can try to help you?
Perhaps [contacting support](https://support.ledger.com/hc/en-us) would be better suited in this particular case.

**Comment by djspops** [comment]
my Nano S does not respond using either of the buttons.  It only displays the "Welcome to Ledger Nano S".  It does not allow me to do anything else.   Ledger Support is not helpful in resolving this issue.  Are you familiar with this issue?

![WELCOME SCREEN](https://user-images.githubusercontent.com/56077323/106653688-21e9ba00-6565-11eb-9c71-528b00616757.jpg)

**Comment by juan-cortes** [comment]
If your device doesn't respond at all to key presses there's not much we can do from here to help you. I'm not aware of any scenario where the device becomes irresponsive like that on the welcome screen and you seem to be using the original cable that came with the device so I insist you contact support and you might be eligible for a replacement device.
