### ISSUE TITLE
Add ERC20 eXRD token

### ISSUE THREAD

**Issue by wton85** [LedgerHQ/ledger-live-desktop#3563]
https://etherscan.io/token/0x6468e79a80c0eab0f9a2b574c8d5bc374af59414?a=0xb7409e56c214d261dd6c69e2da405eb083ec24d5

**Comment by gre** [comment]
please contact our official support to request adding more crypto assets in Ledger Live. They are not directly managed on this Ledger Live Github repository but you can request it to our custom support and/or contact us on our Ledger Slack Devs (if you are a developer and have access).

Thanks.
