### ISSUE TITLE
[SIA][NanoX] Sia coin token and Ledger live support

### ISSUE THREAD

**Issue by jjfreez** [LedgerHQ/ledger-live-desktop#3569]
Please can you add support for Sia token on ledger nano X and ledger live ?

Today it’s not possible to install Sia app on nano x even if i enable experimental mode.

**Comment by gre** [comment]
please contact our official support to request adding more crypto assets in Ledger Live. They are not directly managed on this Ledger Live Github repository but you can request it to our custom support and/or contact us on our Ledger Slack Devs (if you are a developer and have access).

Thanks.
