### ISSUE TITLE
Add support for RGT (Rari Governance token)

### ISSUE THREAD

**Issue by m8nky** [LedgerHQ/ledger-live-desktop#3572]
[*] I have checked this feature was not yet requested.
Currently there is no support for RGT ERC-20 Token (https://www.rari.capital/).

Token page on etherscan: https://etherscan.io/token/0xd291e7a03283640fdc51b121ac401383a46cc623

Coingecko:
https://www.coingecko.com/en/coins/rari-governance-token

Thanks!

Part of the application: Accounts

**Comment by gre** [comment]
please contact our official support to request adding more crypto assets in Ledger Live. They are not directly managed on this Ledger Live Github repository but you can request it to our custom support and/or contact us on our Ledger Slack Devs (if you are a developer and have access).

Thanks.
