### ISSUE TITLE
Ledger live balance shows zero

### ISSUE THREAD

**Issue by redwavk** [LedgerHQ/ledger-live-desktop#3576]
#### Ledger Live Version and Operating System

I have tried synchronizing again, reinstall ledger live and also reset my ledger wallet. I tried all the 3 options but still my btc in ledger nano s shows zero balance. Any suggestions

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. 

This issue can happen for various reasons. We prefer to investigate such issues via contacting our customer support team.

could you send your logs to our support team and mention this github issue? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏  basically you can press Ctrl+E just after the problem occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.now.sh/logsviewer )
