### ISSUE TITLE
Connection Not Recognized Ledger Live 2.21.3 Desktop MAC to Ledger Nano S

### ISSUE THREAD

**Issue by alereisan** [LedgerHQ/ledger-live-desktop#3602]
impossible to connect Ledger Live 2.21.3 Desktop MAC to Ledger Nano S

I have tried all suggested solutions from this page, even reset the PRAM or NVRAM on my Mac:
https://support.ledger.com/hc/en-us/articles/115005165269-Fix-connection-issues

My System uses macOS 10.15.7 Catalina -> going to update it now to macOS Big Sur

Any suggestions would help.

**Comment by cthepot-ledger** [comment]
Hello @alereisan thanks for contacting us. Please contact our techsupport team https://support.ledger.com/hc/en-us.
