### ISSUE TITLE
MATIC installation failure - 0x6a83

### ISSUE THREAD

**Issue by skryptkid** [LedgerHQ/ledger-live-desktop#3604]
**Ledger Live Version and Operating System**

Platform and version: tested on Ledger Live 2.19.0
OS: Windows 10 - 10.0.18363 Build 18363
Ledger Firmware: 1.2.4-5

**Expected behavior**
It should correctly install the Matic application

Actual behavior
When trying to install Matic App it fails showing the following error:
![2021-02-24 10_17_31-Ledger Live](https://user-images.githubusercontent.com/39451629/109023732-09178480-768b-11eb-94a3-60673916439d.png)

**Steps to reproduce the behavior:**
open the ledger app	
go to manager	
connect and unlock ledger nano X	
search for MATIC app	
click on install;	it subsequently fails with Ledger device: UNKNOWN_ERROR (0x6a83)

**Comment by gre** [comment]
there are no Matic app yet available in production. it was accidentally deployed but was indeed not installable.
