### ISSUE TITLE
Cannot sync Cosmos (ATOM) after Stargate upgrade 

### ISSUE THREAD

**Issue by tessr** [LedgerHQ/ledger-live-desktop#3610]
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.17.1
- Platform and version: Mac 10.15.7

#### Expected behavior

Should be able to add an account on Ledger Live 

#### Actual behavior

When trying to add a new account, it fails to sync to the chain: "Oops, internet seems down." I suspect this is related to the Cosmos Stargate upgrade on February 18.

#### Steps to reproduce the behavior

![Screen Shot 2021-02-26 at 2 25 23 PM](https://user-images.githubusercontent.com/773524/109306421-72d88f80-783f-11eb-96fd-aa268cd10471.png)

I've saved the logs as well, and let me know if I (or anyone else on the Cosmos side) can help here. I've had folks report the same issue to me as well.

**Comment by gre** [comment]
We have an incoming LLD 2.23.0 that will restore Cosmos support.

**Comment by tessr** [comment]
Great, thanks!

**Comment by gre** [comment]
@BurnyBoi Did you try to do a "Clear Cache" ? (Settings > Help)

**Comment by BurnyBoi** [comment]
Clearing the cache on 2.24.0 has fixed the issue with the validators not showing their names. However, even when Ledger Live says "Synchronized," I have no Cosmos transactions:

![image](https://user-images.githubusercontent.com/41203525/110982087-15136f80-8336-11eb-9397-00a67cf39fc3.png)

**Comment by tonzola** [comment]
I am having the same problem with missing Cosmos transactions?

**Comment by BurnyBoi** [comment]
I just tried compounding some staking rewards to create a new transaction, and I see it is listed:

![image](https://user-images.githubusercontent.com/41203525/114317630-f7712b80-9ad6-11eb-890e-fac7f1ee7f6d.png)

However, even after clearing cache, only the new transaction shows, and all my other cosmos transactions are still missing from the UI.

**Comment by gre** [comment]
the initial task is fixed. we should discuss another other problem on another task, and preferably via our customer support team which will provide the best support for these.

could you send your logs to our support team and mention this github issue? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏  basically you can press Ctrl+E just after the problem occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.now.sh/logsviewer )
