### ISSUE TITLE
How do I close this window without exiting the application or approving on my Ledger?

### ISSUE THREAD

**Issue by Slyke** [LedgerHQ/ledger-live-desktop#3613]
#### Ledger Live Version and Operating System

v2.21.3

- tested on Ledger Live **version_here**
- Platform and version: Windows 10

#### Expected behavior

Should have an X on the top right.

#### Actual behavior

Can't close modal

#### Steps to reproduce the behavior

Step 3 of receive currency

![image](https://user-images.githubusercontent.com/6442613/109400682-dfff2a00-78fe-11eb-9011-4c641843dd86.png)

**Comment by Slyke** [comment]
Also, on this step on the mobile application one cannot go back unless you exit the app, or approve the transaction.

**Comment by dvwright** [comment]
On the desktop version, clicking on the background page (not where the modal is) closes the modal for me.

**Comment by Slyke** [comment]
> On the desktop version, clicking on the background page (not where the modal is) closes the modal for me.

Does this on step 1 and 2, but not 3 (the only step without an X).

**Comment by dvwright** [comment]
That is the step where you manually confirm on your device, once you appraove it via the device, the final window has the 'x' again. I believe this might be by design and not a bug, that is

**Comment by Slyke** [comment]
Nahh, it wouldn't create an inconsistent state, I've closed the app and restarted it many times during this step. Sometimes I just want to get my receive ID. It's just annoying to have to restart it.

**Comment by gre** [comment]
This works like this by design: the device don't allow the software side to "cancel" the receive action, so we intentionally block the UI to avoid possible inconsistent state if you were to go somewhere else while still having an action to do on your device.

If you unplug your device, OR accept OR deny on the device, the flow is "unlocked".

**Comment by Slyke** [comment]
> This works like this by design: the device don't allow the software side to "cancel" the receive action, so we intentionally block the UI to avoid possible inconsistent state if you were to go somewhere else while still having an action to do on your device.
> 
> If you unplug your device, OR accept OR deny on the device, the flow is "unlocked".

OR I close Ledger Live and open it back up; which is what I currently do since there's no other way to get the receive address. It doesn't create an inconsistant state either, I do this daily.
