### ISSUE TITLE
Polkadot - cannot specify address index in derivation path

### ISSUE THREAD

**Issue by AverageJoe89** [LedgerHQ/ledger-live-desktop#3634]
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.23.0
- Platform and version: Windows 10

#### Expected behavior

User can specify derivation path of address in same manner as they can do on polkadot.js.org.
Let user allow to choose X&Y values of derivation path "44'/354'/0'/X'/Y'" (at least under advanced)

#### Actual behavior

User cannot specify address index, ledger will automatically increment account type.
Therefore not all previously created addresses can be accessed via Live

#### Steps to reproduce the behavior

Create account using ledger on polkadot.js.org, with account type 0, address index 1.
Try to access this address from Ledger Live

**Comment by cthepot-ledger** [comment]
Please try the latest version. If it does not solve your situation please contact support on support.ledger.com.
