### ISSUE TITLE
ledger-live-desktop-2.21.3 Syncronisation error on Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by marbew** [LedgerHQ/ledger-live-desktop#3640]
#### Ledger Live Version and Operating System
ledger-live-desktop-2.21.3-linux-x86_64.AppImage 
Ubuntu 20.04.2 LTS

I updated the version of the app I received the same issue (Syncronization error message), I removed the app and re-installed it, same behaviour (Syncronization error message).

$ ./ledger-live-desktop-2.21.3-linux-x86_64.AppImage 
Ledger Live 2.21.3
(node:121084) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
init
Checking for update
Error: Error: net::ERR_EMPTY_RESPONSE
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6497)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
(node:121084) UnhandledPromiseRejectionWarning: Error: net::ERR_EMPTY_RESPONSE
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6497)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
(node:121084) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:121084) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
spawned internal process 121175

![synchronization_error](https://user-images.githubusercontent.com/10949785/110145827-c021a780-7dd1-11eb-820c-0b55565be974.png)

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. 

This issue can happen for various reasons. We prefer to investigate such issues via contacting our customer support team.

could you send your logs to our support team and mention this github issue? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏  basically you can press Ctrl+E just after the problem occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.now.sh/logsviewer )
