### ISSUE TITLE
Please add CARDANO ADA Full Wallet support 

### ISSUE THREAD

**Issue by gushani** [LedgerHQ/ledger-live-desktop#3646]
#### Ledger Live Version and Operating System

- tested on Ledger Live **version_here**
- Platform and version: **e.g. Mac 10.13.5 / Windows 10 / ..**

**Comment by twinko** [comment]
Hello Ledger Support,

how comes ADA is not supported by Ledger Live? It's 5th place in overall M-Cap? Would love to see Support for ADA.
Moreover it would would give you a lead from competitors ;)

Thank you for your work and great product.
![grafik](https://user-images.githubusercontent.com/11973158/120630794-70ea2200-c467-11eb-8036-665af06e7277.png)
