### ISSUE TITLE
Sync Error "expected <"

### ISSUE THREAD

**Issue by staticfrost** [LedgerHQ/ledger-live-desktop#3651]
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.23.0
- Platform and version:  Windows 10

#### Expected behavior
no-sync errors
#### Actual behavior

Sync Error:
![image](https://user-images.githubusercontent.com/1342176/110561766-fd9c8100-8193-11eb-88e8-036b43bce356.png)

#### Steps to reproduce the behavior

open ledger live and it has sync errors

**Comment by gre** [comment]
- is this still happening?
- could you tell us more about currencies you have and which one do you see as failing?

Thanks

**Comment by Transisto** [comment]
![image](https://user-images.githubusercontent.com/388716/110980963-6f133580-8334-11eb-93d0-c02ae39b356d.png)

Equally meaningless error message here.

**Comment by Transisto** [comment]
Great support.

**Comment by gre** [comment]
- Situation should have been fixed
- correct me if i'm wrong but when it happens it's a temporary backend issue

we don't have enough information to conclude anything. In future, please contact our tech support (support.ledger.com)
