### ISSUE TITLE
Ledger Live swap: stuck on loading indicator when canceling open app action 

### ISSUE THREAD

**Issue by momo258** [LedgerHQ/ledger-live-desktop#3652]
#### Ledger Live Version and Operating System

- tested on Ledger Live  **2.23.0**
- Platform and version: **Windows 10 Pro 20H2**

#### Expected behavior

Displaying a error message when canceling the action to open the exchange app on the ledger device. When trying to set up a swap transaction.

#### Actual behavior

After canceling the action on the ledger device. Ledger live seems to be stuck on the loading indicator. User still has the option to close the dialog screen but misses the correct error message in this case. 

#### Steps to reproduce the behavior

1. Set up a swap transaction between 2 random coins.
2. Continue by pressing the Exchange button
3. Confirm in the pop dialog the exchange rate by pressing Confirm
4. Ledger device will ask for permission to start the Exchange app
5. Cancel the action to open the Exchange app
6. Ledger Live will stay stuck on the loading indicator

**Comment by juan-cortes** [comment]
I'll look into this as part of a rework we are doing to the feature @momo258 I will update the issue with my findings, thanks for reporting

**Comment by juan-cortes** [comment]
Should be addressed as part of the v2 swap api pr https://github.com/LedgerHQ/ledger-live-common/pull/993 to be fully tested and QA'ed but I believe the issue is fixed. 

https://user-images.githubusercontent.com/4631227/110785673-7f131280-826b-11eb-88b7-ff3ca16463a6.mov
