### ISSUE TITLE
Can't connect metamask after latest firmware update

### ISSUE THREAD

**Issue by tuloski** [LedgerHQ/ledger-live-desktop#3657]
As title, I updated to latest firmware on Nano X, reinstalled all the apps, and I can't connect to metamask anymore.
Moreover trying to send transactions on BSC with ETH app they all fail, and I lost lots of BNB in fees and I'm losing lots of money because I can't send transactions.
I'm 99% sure it's a firmware problem because I started having issues right after the update.

This is an example of failed transaction on BSC: https://bscscan.com/tx/0x6bac9abe667c294d90ff0a0b1cba1a75a0dbdfe9db3820376fd5bf875edfc13c
I don't understand where the problem is.

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. 

This issue can happen for various reasons and is not really related to the project Ledger Live as far as I understood it. We prefer to investigate such issues via contacting our customer support team.

could you contact our support team? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏
Thanks

**Comment by tuloski** [comment]
It's not related to ledger live, but I didn't find any repo for Nano X firmware.
I sent a ticket to the support team.
