### ISSUE TITLE
ledger live not recognize nano S

### ISSUE THREAD

**Issue by soydepr** [LedgerHQ/ledger-live-desktop#3658]
i am running debian 10 inside chromebook .

using live 2.23
and firmware 1.60.

ledger-live does not see my nano S 
![Screenshot 2021-03-11 2 39 00 PM](https://user-images.githubusercontent.com/546367/110862148-205e9080-828d-11eb-90ad-a2528fb81851.png)

command line output 
Ledger Live 2.23.0
(node:5167) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
init
Checking for update
Update for version 2.23.0 is not available (latest version: 2.23.0, downgrade is disallowed).
spawned internal process 5238

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. 

This issue can happen for various reasons. We prefer to investigate such issues via contacting our customer support team.

could you send your logs to our support team and mention this github issue? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏  basically you can press Ctrl+E just after the problem occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.now.sh/logsviewer )
