### ISSUE TITLE
publish firmware hashes of the unsecured chip on Ledger Nano X

### ISSUE THREAD

**Issue by adrelanos** [LedgerHQ/ledger-live-desktop#3672]
Quote https://support.ledger.com/hc/en-us/articles/360015216913-Frequently-asked-questions

> Advanced users

> You can access the JTAG of the unsecured chip on Ledger Nano X, this allows you to verify the loaded firmware.

Quote https://blog.kraken.com/post/5590/kraken-security-labs-supply-chain-attacks-against-ledger-nano-x/

> This is misleading, because Ledger currently does not actually publish any hashes that would make it possible to check the memory contents against a known firmware image.

**Comment by gre** [comment]
Not really on Ledger Live's project i'm afraid. but I informed the team. Thanks

**Comment by gre** [comment]
https://support.ledger.com/hc/en-us/articles/360015216913-Frequently-asked-questions
