### ISSUE TITLE
Using legder live deskop in seperated private network

### ISSUE THREAD

**Issue by rlaace423** [LedgerHQ/ledger-live-desktop#3704]
Hello, I've used ledger nano x with ledger live desktop.

For now, I'm planning to use ledger behind firewall, which means has no public internet connection.
So I'm trying to add rules for using ledger live desktop.
For this, which urls or IPs should I allow?

**Comment by gre** [comment]
dup with https://github.com/LedgerHQ/ledger-live-desktop/issues/1073
