### ISSUE TITLE
Can someone help me how to import it to my Ledger live. Here is the hash. Can someone help ERN token not in Ledger live. My Cointracking API was able to import it but it does not show up on Ledger Live.

### ISSUE THREAD

**Issue by Anukshuk** [LedgerHQ/ledger-live-desktop#3712]
#### Ledger Live Version and Operating System

- tested on Ledger Live **version_here**
- Platform and version: **e.g. Mac 10.13.5 / Windows 10 / ..**

**Comment by mreed911** [comment]
Not a supported asset.  You'll have to use something like MetaMask.

https://www.ledger.com/supported-crypto-assets
