### ISSUE TITLE
Countervalue problem AGAIN

### ISSUE THREAD

**Issue by olivbrain** [LedgerHQ/ledger-live-desktop#3733]
Constant problems with countervalue.... now it is showting BTC price at 2081$ 

PLEASE FIX THIS ISSUE ONCE AND FOR ALL

Everything was working FINE when you could choose countervalue exchanges in setting.... then some very very smart individual at ledger decided that it is a bad idea and that this needs to be removed..... GREAT DECISION GENIUS!

**Comment by gre** [comment]
we are on it. nothing we can on on ledger-live-desktop project itself but it's being taking care of by our backend teams.
