### ISSUE TITLE
Ledger Live not locating account transactions

### ISSUE THREAD

**Issue by thephez** [LedgerHQ/ledger-live-desktop#3747]
#### Ledger Live Version and Operating System

- tested on Ledger Live **2.25.1**
- Platform and version: **Mac 11.2.3**

#### Expected behavior

Accounts that currently have a balance of zero but have previously had transactions should recognise and display the transaction history.

Secondarily, I expected to be able to import accounts from another computer via a file or qr code in the same way that the mobile app does. That would have made this a non-issue.

#### Actual behavior

The first account for a coin has been used in the past but currently has a balance of zero. When adding accounts on a new installation of Ledger Live, it won't recognise the account as being used. It doesn't show the transaction history and also will not allow me to add the subsequent accounts for the same coin that do have a current balance because it thinks the previous account has never been used. 

Side note: Why is it not possible to add an account even if the previous account index hasn't been used yet? This is a mystery to me - I know that's not a technical limitation of the hardware or BIP44.

#### Steps to reproduce the behavior

I haven't attempted to duplicate the issue for you, but these steps will get accounts in the same state as mine currently are.

**Setup**
1. Add account 1 for Dash (presumably other coins _might_ work the same way)
2. Send a tx to it
3. Add account 2 for the same coin
4. Send full balance from account 1 to account 2. Account 1 should have a zero balance now.

**On a new computer or account**
1. Install Ledger Live
2. Go to `Add account`, select relevant coin
3. Account 1 will be seen as a new account, not an already used one (see screenshot). As a consequence it won't scan for additional account.

In my specific case, Dash account 2 (path 44/5/1) has a non-zero balance but can't be added. A separate computer that had all the accounts added previously that the new installation is looking in the correct derivation path. For some reason it's not downloading the account history though.

Fortunately I know I can use Electrum or some other wallet that supports your hardware to access the "forgotten" accounts, but this is definitely a bad user experience even knowing that. For someone new to crypto, it could cause quite a panic.

![image](https://user-images.githubusercontent.com/8145677/115120359-08101e80-9f7b-11eb-99dd-0fbf998caa73.png)

**Comment by NicholasJonesCode** [comment]
I agree with this. This is one of my biggest gripes with Metamask, and it has caused a panic for many people on that app as well

**Comment by gre** [comment]
> Send full balance from account 1 to account 2. Account 1 should have a zero balance now.

actually a "zero balance" account is not a "New account" per ledger live logic. It's an existing account it shouldn't stop to discover account 2. If you have a case like this, then indeed it's a bug but on my side I do have these (on some other coins than Dash, but same implementation for other bitcoin forks).

As long at the account have history of transactions, it's considered "existing". I have reason to believe your "Account 1 detected as empty" had transactions very long time ago and maybe it's our explorers that don't see the transactions anymore. Were you able to confirm on another wallet that you indeed see the transactions history? (maybe with the xpub)

I hope we can understand the problem. Feel free to get in touch to our customer support @thephez but with the current information of this ticket, there is nothing I see we can do.


> Side note: Why is it not possible to add an account even if the previous account index hasn't been used yet? This is a mystery to me - I know that's not a technical limitation of the hardware or BIP44.

mmh, it's a spec recommendation, of BIP44, actually. https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki quoting => **_Software should prevent a creation of an account if a previous account does not have a transaction history (meaning none of its addresses have been used before)._**

**Comment by thephez** [comment]
>As long at the account have history of transactions, it's considered "existing". I have reason to believe your "Account 1 detected as empty" had transactions very long time ago and maybe it's our explorers that don't see the transactions anymore. 

Correct, it's being wrongly detected as empty. The account has txs over a number of years, but has had a 0 balance since the last tx ~9 months ago.

> Were you able to confirm on another wallet that you indeed see the transactions history? (maybe with the xpub)

Yes, I'm able to see the transaction history via other wallets (Electrum for example).

**Comment by gre** [comment]
@thephez ok thanks for coming back to me. Could you please try to enable the option in `Settings>Experimental>Experimental Explorers API` ? It enables another version of our explorer that may have fixed the situation.
Then also try to run `Settings>Help>Clear cache`

if it still doesn't solve the situation, I think we'll have to go through our techsupport if you could send them the address that is not recovered from our explorer (or ideally the xpub). + mention this github link.

**Comment by thephez** [comment]
@gre Switching to the Experiment Explorer API and clearing the cache resolved the issue. Should I switch back to the regular explorer after adding the accounts?

**Comment by gre** [comment]
Ok thanks a lot! that's very good to know.
Essentially it means
- our v2 explorers have indexing issue on Dash
- our v3 explorers are good on Dash

I'll inform my team and we'll see if we can plan to go V3 in a future release.

In meantime I think you may have to stay on this IF you use one of the account that was causing issue. otherwise you can go back to V2.
