### ISSUE TITLE
[Feature Request] Support Solana and SPL tokens on Ledger Live

### ISSUE THREAD

**Issue by NicholasJonesCode** [LedgerHQ/ledger-live-desktop#3748]
Hey Ledger Team, 

I am wondering when the Solana chain is going to be supported on the Ledger Live app? Solana has become popular very quickly, with its lightning fast transactions and extremely low network fees, along with ERC-20-like tokens with its SPL tokens. Solana even has native USDC and USDT, along with popular wrapped tokens like ETH and XRP

I think all-in-all it really deserves to have an interface on the Ledger app. More than dogecoin at least :) I use Solana and several SPL tokens a lot and it would really make things much easier for me. Part of the reason i bought a Ledger wallet initially was for my Solana tokens.

Please let me know what your team's thoughts are, thanks!

**Comment by GentlemansKiller** [comment]
Yes Please!

**Comment by RabbiShekelberg** [comment]
Shalom my fellow programmers. I strongly approve this message.

**Comment by TexasRedHuncho** [comment]
Please do this, It would be really helpful.
