### ISSUE TITLE
ETC NOT TRANSFERRED.

### ISSUE THREAD

**Issue by matt1496** [LedgerHQ/ledger-live-desktop#3766]
Hi,
I need some help please.

I transferred some crypto over to my Nano Ledger yesterday but the ETC never reached my cold wallet.  It shows Pending on Coinbase but success on when i "view transaction" ?

Its $700 so im very annoyed right now, i would like to know where my money / ETC is & who i should contact.

Would appreciate any help.

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. 

This issue can happen for various reasons. We prefer to investigate such issues via contacting our customer support team.

could you send your logs to our support team and mention this github issue? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏  basically you can press Ctrl+E just after the problem occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.now.sh/logsviewer )
