### ISSUE TITLE
Ledger Nano S Not Recognized by Ledger Live

### ISSUE THREAD

**Issue by herrmoltke** [LedgerHQ/ledger-live-desktop#3770]
#### Ledger Live Version and Operating System

- tested on Ledger Live Version 2.25.1
- Platform and version: NixOS

#### Expected behavior

Ledger Live should tell me whether my Ledger Nano S is genuine.

#### Actual behavior

Ledger Live does nothing, until a pop-up offering to help me repair my device comes up.

#### Steps to reproduce the behavior
- On "Get started with your Ledger device" page, select "Skip device setup"
- On "Select your device " page, select "Ledger Nano S"
- On "Security Checklist" page, answer "Yes" to questions (1) and (2), and then select "Check Now" for question (3). Connect your Ledger Nano S and enter your PIN.

**Comment by nickyrabit** [comment]
I dont think it should do that.

I believe if you downloaded a genuine ledger live app the device will connect and show balance. there is encryption inside that will only allow genuine ledger wallets to be connected

Also do not buy from 3rth parties or used ledgers even from a friend.
for further information please check https://support.ledger.com/hc/en-us/articles/360002481534-Check-if-device-is-genuine

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. 

This issue can happen for various reasons. We prefer to investigate such issues via contacting our customer support team.

could you send your logs to our support team and mention this github issue? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏  basically you can press Ctrl+E just after the problem occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.now.sh/logsviewer )
