### ISSUE TITLE
Account 0 value after Firmware Update Nano S, tried everything but unable to recover access to account.

### ISSUE THREAD

**Issue by L4v3nd3r** [LedgerHQ/ledger-live-desktop#3777]
Have tried scowering the web for answers the last few months to recover my account. Account last transaction was in 2019 but updated Nano S unable to gain access to account even with passphrase and reset. I even got to the point of purchasing a new Nano X to use with the passphrase but still no luck. Looked through MEW for thousands of addresses on multiple paths but unable to find one with my ETH. The only reference that i have now is an old PC that had Ledger Live installed and with my account information. Original address was at 0x229cC70deA4457d914D9ef90D74ac56a1d165697 with path 44'/60'/0'/0. But now no matter what i do i am unable to gain back access into my account!

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. 

This issue can happen for various reasons. We prefer to investigate such issues via contacting our customer support team.

could you send your logs to our support team and mention this github issue? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏  basically you can press Ctrl+E just after the problem occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.now.sh/logsviewer )
