### ISSUE TITLE
Ledger Live AppImage version 2.26-1 silently fails to launch on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by sysfu** [LedgerHQ/ledger-live-desktop#3788]
#### Ledger Live Version and Operating System

- tested on Ledger Live **2.26-1**
- Platform and version: **Ubuntu LTS 18.04**

#### Expected behavior

App launches
#### Actual behavior
App silently dies
#### Steps to reproduce the behavior
Launch app from terminal, displays version number and then dies.

``` 
sh -x ledger-live-desktop-2.26.1-linux-x86_64.AppImage 
+ 
ledger-live-desktop-2.26.1-linux-x86_64.AppImage: 1: ledger-live-desktop-2.26.1-linux-x86_64.AppImage: : not found
+ }P7pysH_fh
+ ledger-live-desktop-2.26.1-linux-x86_64.AppImage: 2: ledger-live-desktop-2.26.1-linux-x86_64.AppImage: }P7pysH_fh: not found
@@ PdjjBjBQ/lib64/ld-linux-x86-64.so.2GN,9?EV#wvX$x)m5

                                                      '!LS
M(t ؆zJl+2;B8/1@.WNUFk[ K^3Cjo~n
                                =eOZ
ledger-live-desktop-2.26.1-linux-x86_64.AppImage: 1: ledger-live-desktop-2.26.1-linux-x86_64.AppImage: @@: not found
+ ELFAI @@@@@@@@ b biqAՒ]
ledger-live-desktop-2.26.1-linux-x86_64.AppImage: 1: ledger-live-desktop-2.26.1-linux-x86_64.AppImage: ELFAI: not found
ledger-live-desktop-2.26.1-linux-x86_64.AppImage: 19: ledger-live-desktop-2.26.1-linux-x86_64.AppImage: Syntax error: Unterminated quoted string
```

**Comment by cthepot-ledger** [comment]
Please try the latest version. If it does not solve your situation please contact support on support.ledger.com.

**Comment by sysfu** [comment]
Similar issue occurring with 2.30

`sh -x ledger-live-desktop-2.30.0-linux-x86_64.AppImage
+ �
ledger-live-desktop-2.30.0-linux-x86_64.AppImage: 1: ledger-live-desktop-2.30.0-linux-x86_64.AppImage: �: not found
+ }�P7pysH��_f��h
ledger-live-desktop-2.30.0-linux-x86_64.AppImage: 2: ledger-live-desktop-2.30.0-linux-x86_64.AppImage: }�P7pysH��_f��h: not found
+ �b��@@ P�tdjjBjB�
                                  �
                                   Q�td/lib64/ld-linux-x86-64.so.2GNU�,��9��?�|EV�#���D���wv�X���0��Q����$�x�����������)m��5
                                        �I����
                                                 '!�ʡ�LS
��M���(t� �b؆�d<����ש{�%��4-�cl���!
                            z����J���	+2;B8/1@.WNUTFk[ K^3Cj�o~n
                                                                                  �=eO����Z�
ledger-live-desktop-2.30.0-linux-x86_64.AppImage: 1: ledger-live-desktop-2.30.0-linux-x86_64.AppImage: �b��@@: not found
ledger-live-desktop-2.30.0-linux-x86_64.AppImage: 1: ledger-live-desktop-2.30.0-linux-x86_64.AppImage: cannot create �F@@��@@: Permission denied
+ ELFAI @@@@@��@@@@���� ����b��b� �biq�A�Ւ��]�
ledger-live-desktop-2.30.0-linux-x86_64.AppImage: 1: ledger-live-desktop-2.30.0-linux-x86_64.AppImage: ELFAI: not found
ledger-live-desktop-2.30.0-linux-x86_64.AppImage: 19: ledger-live-desktop-2.30.0-linux-x86_64.AppImage: Syntax error: Unterminated quoted string`
