### ISSUE TITLE
Data not displaying on Ledger Live (Ubuntu)

### ISSUE THREAD

**Issue by wuno** [LedgerHQ/ledger-live-desktop#3789]
#### Ledger Live Version and Operating System
- tested on Ledger Live 2.26.1
- Platform and version: Ubuntu 20.04.2LTS

#### Expected behavior
I expect to see the balances of all my crypto holdings

#### Actual behavior
* displays in place of each char. Data is not showing up correctly.

#### Steps to reproduce the behavior
Open Ledger Live on the specified system with crypto in your Ledger wallet
![Screenshot from 2021-04-30 17-30-32](https://user-images.githubusercontent.com/8263539/116760225-04988080-a9da-11eb-830f-90198108a920.png)
![Screenshot from 2021-04-30 17-30-58](https://user-images.githubusercontent.com/8263539/116760228-05311700-a9da-11eb-8429-b21372357466.png)

**Comment by FrankP01** [comment]
> #### Ledger Live Version and Operating System
> * tested on Ledger Live 2.26.1
> * Platform and version: Ubuntu 20.04.2LTS
> 
> #### Expected behavior
> I expect to see the balances of all my crypto holdings
> 
> #### Actual behavior
> * displays in place of each char. Data is not showing up correctly.
> 
> #### Steps to reproduce the behavior
> Open Ledger Live on the specified system with crypto in your Ledger wallet
> ![Screenshot from 2021-04-30 17-30-32](https://user-images.githubusercontent.com/8263539/116760225-04988080-a9da-11eb-830f-90198108a920.png)
> ![Screenshot from 2021-04-30 17-30-58](https://user-images.githubusercontent.com/8263539/116760228-05311700-a9da-11eb-8429-b21372357466.png)

I will advise you contact the ledger support team on telegram it’s helpful and they are active here is the username to contact the support team @ledgersupport0 they will be glad to help you on this .. check it out cheers

**Comment by wuno** [comment]
> > #### Ledger Live Version and Operating System
> > 
> > * tested on Ledger Live 2.26.1
> > * Platform and version: Ubuntu 20.04.2LTS
> > 
> > #### Expected behavior
> > I expect to see the balances of all my crypto holdings
> > #### Actual behavior
> > 
> > * displays in place of each char. Data is not showing up correctly.
> > 
> > #### Steps to reproduce the behavior
> > Open Ledger Live on the specified system with crypto in your Ledger wallet
> > ![Screenshot from 2021-04-30 17-30-32](https://user-images.githubusercontent.com/8263539/116760225-04988080-a9da-11eb-830f-90198108a920.png)
> > ![Screenshot from 2021-04-30 17-30-58](https://user-images.githubusercontent.com/8263539/116760228-05311700-a9da-11eb-8429-b21372357466.png)
> 
> I will advise you contact the ledger support team on telegram it’s helpful and they are active here is the username to contact the support team @ledgersupport0 they will be glad to help you on this .. check it out cheers

If anyone sees this, please do not listen to this person. This is clearly a scammer trying to phish people and they have posted the same note in other issues on this repo.

**Comment by gre** [comment]
@wuno correct me if i'm wrong but is sounds like you have toggled on the Discreet mode. you need to click this button: 
![Capture d’écran 2021-05-04 à 13 50 33](https://user-images.githubusercontent.com/211411/116999312-b6d48e80-acdf-11eb-8568-dce071b21b13.png)

**Comment by wuno** [comment]
Well, that's embarrassing! Thank you a ton, I have been dealing with that for a month.
