### ISSUE TITLE
WINK Token is not showing prices

### ISSUE THREAD

**Issue by nickyrabit** [LedgerHQ/ledger-live-desktop#3790]
#### Ledger Live Version and Operating System

Ledger Live 2.26.1 
- Platform and version: ** Windows 10.**

#### Expected behaviour
See the price for WIN token 

See the price for wink token and percentage increase
#### Actual behavior

No Prices

#### Steps to reproduce the behaviour
Check the wink price

Tron network is big we need to see the tron network token prices too

**Comment by FrankP01** [comment]
> #### Ledger Live Version and Operating System
> Ledger Live 2.26.1
> 
> * Platform and version: ** Windows 10.**
> 
> #### Expected behaviour
> See the price for WIN token
> 
> See the price for wink token and percentage increase
> 
> #### Actual behavior
> No Prices
> 
> #### Steps to reproduce the behaviour
> Check the wink price
> 
> Tron network is big we need to see the tron network token prices too

I will advise you contact the ledger support team on telegram it’s helpful and they are active here is the username to contact the support team @ledgersupport0 they will be glad to help you on this .. check it out cheers

**Comment by nickyrabit** [comment]
thanks

**Comment by nickyrabit** [comment]
Dont fall for anyone acting to be like a support guy for ledger sending you to telegram
