### ISSUE TITLE
Tanzanian , Ugandan Shillings Countervalues not seen

### ISSUE THREAD

**Issue by nickyrabit** [LedgerHQ/ledger-live-desktop#3791]
#### Ledger Live Version and Operating System

Ledger Live 2.26.1
- tested on Ledger Live **2.26.1**

- Platform and version: **Windows 10 / ..**

#### Expected behaviour
To see the pricing in Tanzanian and Ugandan shillings

#### Actual behavior
Blank and grey  graph with no numbers

#### Steps to reproduce the behaviour
Change counter value to Tanzanian and Ugandan shillings

**Comment by FrankP01** [comment]
> #### Ledger Live Version and Operating System
> Ledger Live 2.26.1
> 
> * tested on Ledger Live **2.26.1**
> * Platform and version: **Windows 10 / ..**
> 
> #### Expected behaviour
> To see the pricing in Tanzanian and Ugandan shillings
> 
> #### Actual behavior
> Blank and grey graph with no numbers
> 
> #### Steps to reproduce the behaviour
> Change counter value to Tanzanian and Ugandan shillings

I will advise you contact the ledger support team on telegram it’s helpful and they are active here is the username to contact the support team @ledgersupport0 they will be glad to help you on this .. check it out cheers

**Comment by nickyrabit** [comment]
Some one block this thief and scamer

**Comment by gre** [comment]
We're investigating. thanks.

**Comment by cthepot-ledger** [comment]
Please try the latest version. If it does not solve your situation please contact support on support.ledger.com.
