### ISSUE TITLE
Polkadot now showing more DOT than it should

### ISSUE THREAD

**Issue by BurnyBoi** [LedgerHQ/ledger-live-desktop#3793]
I'm seeing that on Ledger Live, it says I have 17 trillion dollars worth of DOT recently:

![image](https://user-images.githubusercontent.com/41203525/116790541-9a87e600-aa82-11eb-92fe-898b02386271.png)

This persists if I clear cache, and I am currently on the latest git version. I have confirmed on Polkadot JS that I unfortunately was not actually given 17 trillion dollars :(

**Comment by FrankP01** [comment]
> I'm seeing that on Ledger Live, it says I have 17 trillion dollars worth of DOT recently:
> 
> ![image](https://user-images.githubusercontent.com/41203525/116790541-9a87e600-aa82-11eb-92fe-898b02386271.png)
> 
> This persists if I clear cache, and I am currently on the latest git version. I have confirmed on Polkadot JS that I unfortunately was not actually given 17 trillion dollars :(

I will advise you contact the ledger support team on telegram it’s helpful and they are active here is the username to contact the support team @ledgersupport0 they will be glad to help you on this .. check it out cheers

**Comment by BurnyBoi** [comment]
I just saw Ledger sent the alert in the application about the network issue with Polkadot, and it seems to be working now so will just close this out
