### ISSUE TITLE
Request: Pls add Helium(HNT) to Ledger Live and Nano X

### ISSUE THREAD

**Issue by bttfw** [LedgerHQ/ledger-live-desktop#3809]
Pls add Helium(HNT) to Ledger Live and Nano X

https://www.helium.com/

Their is an Helium App for Nano S mybe talk to them to add it to the hole Family

thx

**Comment by kellybyrd** [comment]
The helium Ledger app has been submitted to the Ledger app already to Ledger:
https://github.com/LedgerHQ/app-helium. From what I understand, it works on Nano S and X

It needs approval, then we're just missing support in Ledger Live.
