### ISSUE TITLE
Synchronization error 

### ISSUE THREAD

**Issue by whiteblXK** [LedgerHQ/ledger-live-desktop#3812]
#### Ledger Live Version and Operating System

- tested on Ledger Live **2.26.1**
- Platform and version: **Windows 10**

#### Expected behavior

Sync, I guess?

#### Actual behavior

Internal process error: 4294930435

#### Steps to reproduce the behavior

My problems with sync started after I bought some DOGE TOKEN, tried to clear cache and uninstall app without results.
Finally I send ALL my DOGE TOKEN to other wallet(checked on stellarport.io and stellarterm.com, I have only XLM) and yea, still disappointment :/

![wCwDleM](https://user-images.githubusercontent.com/6029889/117434356-ddd3d000-af2c-11eb-9c67-f28066d844cd.png)

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. 

This issue can happen for various reasons. We prefer to investigate such issues via contacting our customer support team.

could you send your logs to our support team and mention this github issue? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏  basically you can press Ctrl+E just after the problem occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.now.sh/logsviewer )
