### ISSUE TITLE
Can't send WINK token to binance from ledger live desktop. 

### ISSUE THREAD

**Issue by alansmithie** [LedgerHQ/ledger-live-desktop#3816]
#### Ledger Live Version and Operating System

- tested on Ledger Live **2.26.1**
- Platform and version: **Mac OS. 11.3**

#### Expected behavior

Be able to send WINK token to binance account. 

#### Actual behavior

Is not able to send WINK token to binance account. Shows the following message: Sending TRC20 to a new account won't activate it. 

#### Steps to reproduce the behavior

Select WINK token from your corresponding account in Ledger Live and try to send a certain amount to the corresponding Binance account.

**Comment by cthepot-ledger** [comment]
Please try the latest version. If it does not solve your situation please contact support on support.ledger.com.
