### ISSUE TITLE
When sending ETH,  the partial destination address is displayed instead of amount of ETH (!)

### ISSUE THREAD

**Issue by jonsats** [LedgerHQ/ledger-live-desktop#3830]
#### Ledger Live Version and Operating System

- tested on Ledger Live **2.26.1**
- Platform and version: ** Mac 10.13.5 **

#### Expected behavior

When sending ETH you should be able to see the amount of ETH being sent on the Ledger Nano S device (2.0.0)

#### Actual behavior

When sending ETH the Amount section shows a partial address of the destination rather than the quantity of ETH, the destination address is then shown in full as expected on the following screen.

#### Steps to reproduce the behavior

ETH app version 1.7.5

**Comment by gre** [comment]
The issue was identified and was quickly fixed a few weeks ago. Thanks.
