### ISSUE TITLE
[Feature Request] Always display app icon on the ready screen

### ISSUE THREAD

**Issue by phantomcrypt** [LedgerHQ/ledger-live-desktop#3831]
Some of the coin apps do not show their icon on the "Application is ready" screen on my Nano X. For people like me, that have many app coins installed, it is quite troublesome to understand which one is currently opened. I have to quit and enter the app again.
I believe if the UX always shows the icon at the ready screen for every app, it would greatly simplify the usability.

**Comment by juan-cortes** [comment]
It's up to the individual coin app developers to implement the layout and display the icon when doing so. There are several layouts to choose from for a device screen, and in particular, the `pnn` and `pb`  layouts allow you to display an icon alongside some text. I agree it would be ideal and clearer from a user's perspective but it's a task for the authors of the apps.

```UX_STEP_NOCB(step_menu, pnn, {&C_app_logo, "App", "is ready"});```


https://developers.ledger.com/docs/NA/u_display_management/

**Comment by phantomcrypt** [comment]
In that case, instead of leaving it up to the developers to use best design practices, would you consider enforcing this particular use case when apps are submitted to the Ledger team? I would like to see every app submitted requiring the app icon displayed on the first screen to help users know what they are signing for. There is no extra work involved, as every app already requires the [device icon](https://developers.ledger.com/docs/NA/a_publishing_an_app/#design-guidelines).
On the same note, it seems to me that the best apps already do this, and are generally more intuitive to use.

Although I understand this is not the Ledger's team focus, having somewhat good design guidelines can help in the long run. Considering some changes can be as small as this. A good example is [Android's Material System](https://material.io/design).
