### ISSUE TITLE
Recieve DOT doesn't show recieve address on Ledger Live (only on device)

### ISSUE THREAD

**Issue by gilescope** [LedgerHQ/ledger-live-desktop#3842]
#### Ledger Live Version and Operating System

Windows 10 

#### Expected behavior

When recieving DOT, a Polkadot QR code to be shown in ledger live or at least show the address on the computer.

#### Actual behavior

When recieving DOT you have to get a magnifying glass out and read the address carefully from the ledger and type it all in manually.

I tried to raise this here: https://github.com/Zondax/ledger-polkadot/issues/88 but they said here was the right place. Not much needs to be done to make it usable, just show the DOT recieving address on the computer screen so it can be copied and pasted somewhere. Typing these addresses by hand is auboptimal and high-risk.

**Comment by gre** [comment]
I don't understand the issue. I just tried and i am able to receive and have an address.

https://user-images.githubusercontent.com/211411/121569693-57c21200-ca21-11eb-947f-d56cb4cf6edd.mov

It sounds like maybe you accept too fast on the device? when you accept on the device it means "i'm done, i used the address".

when you copy paste it somewhere else, the device still should display that address and you will be able to verify the device screen against the place you pasted it, and possibly even in 2FA ways (e.g. exchange will send you a mail to confirm it's really your address and you verify it somewhere else – at this point your device still display the address)

I hope it's clear.

**Comment by gilescope** [comment]
Ah ok could well have been that and me not noticing. It is a bit confusing becuase on the screen it says "Address shared securely" once you've hit approve on the device. Where has it been shared securely to? 

As a user when I press approve on the device, I feel like I am confirming that "I have verified that the address I see on screen looks the same as the address on the ledger". On the whole I think the UX would be smoother if it stayed displaying the recieve address until you click 'Done' on the desktop window.
