### ISSUE TITLE
DASH explorer has incorrect/outdated URL

### ISSUE THREAD

**Issue by Eddict** [LedgerHQ/ledger-live-desktop#3857]
#### Ledger Live Version and Operating System

- tested on Ledger Live Ledger Live 2.26.1
- Platform and version:  Windows 10

#### Expected behavior

After doing a transfer (eg. Send) and clicking View in Explorer the transaction should be shown
https://explorer.dash.org/insight/tx/##TXID##

#### Actual behavior

After doing a transfer (eg. Send) and clicking View in Explorer an incorrect/outdated url is used.
https://explorer.dash.org/tx/##TXID##

#### Steps to reproduce the behavior

Send DASH, click View in Explorer and you will see an error like; Cannot GET /tx/##TXID##

**Comment by valpinkman** [comment]
Thank you @Eddict for the good find. 
It's been integrated to our task.
