### ISSUE TITLE
[Feature Request] Keep all settings after firmware upgrade

### ISSUE THREAD

**Issue by phantomcrypt** [LedgerHQ/ledger-live-desktop#3867]
I realised that after upgrading firmware on the Ledger, all settings are lost. It is quite inconvenient having to change the settings again. Not only for the device, but for some of the apps.
This is a request to improve the firmware upgrade process to export and import all the settings when it is done.
In order for the app settings to remain without unexpected changes, the same version should be installed. Not the latest. Although I do not know the current behaviour.

It would not only ease the pain for experienced users, but also help new users that are afraid to change something again.

**Comment by juan-cortes** [comment]
I checked with the FW team and there are plans to maintain OS settings between firmware updates in a future version, I can't give you a date but it's in the pipeline. As for the application settings, it's a different monster altogether and as far as I know, it's not happening anytime soon.
