### ISSUE TITLE
Installation of Bitcoin app failed, but was shown as successful on Manager screen.

### ISSUE THREAD

**Issue by seanjsong** [LedgerHQ/ledger-live-desktop#3873]
#### Ledger Live Version and Operating System

- tested on Ledger Live **2.26.1**
- Platform and version: **MacOS 10.12.6 and MacOS 11.3.1**

#### Expected behavior

The Manager screen should show Bitcoin app installation failed.

#### Actual behavior

The Manager screen shows Bitcoin app installed successfully but it's not true, when I switch to the Accounts screen and then back to Manager screen, Bitcoin app is shown as not installed again.

#### Steps to reproduce the behavior

Reset a device and install Bitcoin app v1.6.1. I also reported this issue here: https://github.com/LedgerHQ/app-bitcoin/issues/191#issue-907746765

Wrong behavior screenshot:

<img width="999" alt="Screen Shot 2021-06-01 at 12 41 46 AM" src="https://user-images.githubusercontent.com/229229/120247834-00a59a00-c2c9-11eb-9148-2e48d5777b7b.png">

**Comment by IbrahimTanyalcin** [comment]
Hi Sean, I opened a [**similar**](https://github.com/LedgerHQ/ledger-live-desktop/issues/3869) issue yesterday, but a [**fix**](https://status.ledger.com/incidents/0rfbktw595xv) has been issued and I could not reproduce it anymore. 

Do you still have the issue?

**Comment by seanjsong** [comment]
I can confirm the issue no longer exists. Thank you
