### ISSUE TITLE
Cannot read property getRawData() of undefined

### ISSUE THREAD

**Issue by webandapptest** [LedgerHQ/ledger-live-desktop#3889]
The issue happens when you try to deploy a newly compiled token following the official tutorial at Step 4 on deployment: https://developers.tron.network/docs/issuing-trc20-tokens-tutorial

See error message: 

![Tron_Ledger_Error](https://user-images.githubusercontent.com/28724198/120895655-95edb900-c650-11eb-86fe-e26563f7ad62.png)

**Comment by gre** [comment]
@webandapptest thanks for raising the issue but I think this do not concerns Ledger Live but either:

- the frontend library you are using? maybe https://github.com/LedgerHQ/ledgerjs ?
- if it's an issue on the device Tron app itself, it would be this repository => https://github.com/klever-io/trx-ledger

You can probably create the issue there. Thanks.
