### ISSUE TITLE
Are there only ERC20 Stable coins supported?

### ISSUE THREAD

**Issue by legalaffect** [LedgerHQ/ledger-live-desktop#3890]
Dear Team,

I tried to check whether there are other types of Stable coins supported or not.. I could not find BUSD on Binance Smart Chain.. or USDT on Tron etc .... 

Can you please add these ones...????

Thanks !!

**Comment by gre** [comment]
- BSC is not yet supported
- usdt on Tron is available
- for erc20 we do have more than just stable coins. You can find the list here https://github.com/LedgerHQ/ledger-live-desktop/blob/develop/cryptoassets.md
