### ISSUE TITLE
[Can't access Stellar Wallet] Can't view my funds at Stellar account viewer using Ledger Nano S( Google Chrome)

### ISSUE THREAD

**Issue by DRIX-cmd** [LedgerHQ/ledger-live-desktop#3893]
I get the following error every time I try to enter Stellar account viewer via Google Chrome browser in my MacOS

"TransportInterfaceNotAvailable: Unable to claim interface." 

At first when I installed the Ledger Live and activated my Ledger Nano S - The Stellar account viewer worked just fine(about 2 weeks ago). 

How can i regain access to my Stellar wallet ?

Thanks.

**Comment by juan-cortes** [comment]
I'm not sure if this can be related to the bug from Chrome that made the usb interface stop working but just in case, could you update Chrome to the latest version and try again? I believe it should be fixed on version 93 of Chrome https://bugs.chromium.org/p/chromium/issues/detail?id=1215767#c23

**Comment by DRIX-cmd** [comment]
@juan-cortes Thanks for the reply.

I believe that the current Chrome version that I have(Version 91.0.4472.77) is the latest one since the browser says that I am up to date with the version already.
I been trying to enter my Stellar Account Viewer via various browsers like Brave and Edge but failed getting the "TransportInterfaceNotAvailable: Unable to claim interface" error message 
(The most first error message was: "TransportInterfaceNotAvailable: Device is disconnected" )

Now, I thought that the problem is with my Ledger nano s device so I restored it using the 24 phrase recovery sheet but even that couldn't solve my issue.

I really need help here -.-

**Comment by gre** [comment]
You can try chrome canary or revert to chrome 91
You can follow GitHub issue https://github.com/LedgerHQ/ledgerjs/issues/607

**Comment by DRIX-cmd** [comment]
I could access to Stellar Account Viewer via the Chrome Canary browser.

Thanks.
