### ISSUE TITLE
Latest ledger-live-desktop-2.29.0-linux-x86_64.AppImage sha512sum doesn't match with provided sha512sum in latest-linux.yml file !

### ISSUE THREAD

**Issue by liondani** [LedgerHQ/ledger-live-desktop#3904]
version: 2.29.0

downloaded
ledger-live-desktop-2.29.0-linux-x86_64.AppImage

but sha256sum ce45335df820401499b6c6659c368311345f7297c894742110a47406bc0679c81ea8e84d4474ce9bafa1a50f3aa5da4914b3ef64fe0b4109eb0e359b37095a84

doesn't match with provided 
zkUzXfggQBSZtsZlnDaDETRfcpfIlHQhEKR0BrwGecgeqOhNRHTOm6+hpQ86pdpJFLPvZP4LQQnrDjWbNwlahA==

from latest-linux.yml

**Comment by juan-cortes** [comment]
I believe you are comparing a `base64` representation of the checksum, provided by `latest-linux.yml` with a `hex` representation of the checksum. If you convert the `base64` string to `hex`, you'll get the expected result. You can also run the checksum and pipe the output to base64 to get it directly as provided, I suppose.

```
Buffer.from('zkUzXfggQBSZtsZlnDaDETRfcpfIlHQhEKR0BrwGecgeqOhNRHTOm6+hpQ86pdpJFLPvZP4LQQnrDjWbNwlahA==', 'base64').toString('hex') 
```

**Comment by liondani** [comment]
I used this online converter https://conv.darkbyte.ru/ and you are absolutely right @juan-cortes 
Thank you! 
I can close the "issue" now :)

**Comment by jacques-martin10** [comment]
Where is file `latest-linux.yml`? Thanks!
