### ISSUE TITLE
How can transfer out ERC20 theta

### ISSUE THREAD

**Issue by beyondsoft978** [LedgerHQ/ledger-live-desktop#4032]
I use ledger  + theta web wallet
The online wallet shows the balance based on ETH and the transfer page prompts not to transfer theta to the ERC20 address
https://docs.thetatoken.org/docs/preventing-lost-eth-erc20-tokens
How can I transfer out? Currently, all exchanges are ERC20 theta addresses.

**Comment by Paulo23456** [comment]
> I use ledger  + theta web wallet
> 
> The online wallet shows the balance based on ETH and the transfer page prompts not to transfer theta to the ERC20 address
> 
> https://docs.thetatoken.org/docs/preventing-lost-eth-erc20-tokens
> 
> How can I transfer out? Currently, all exchanges are ERC20 theta addresses.

Hello friend what's your email so you can be send instructions to follow

**Comment by beyondsoft978** [comment]
> > I use ledger  + theta web wallet
> > The online wallet shows the balance based on ETH and the transfer page prompts not to transfer theta to the ERC20 address
> > https://docs.thetatoken.org/docs/preventing-lost-eth-erc20-tokens
> > How can I transfer out? Currently, all exchanges are ERC20 theta addresses.
> 
> Hello friend what's your email so you can be send instructions to follow

Please provide the solutions you know here and it can also help others. Thank you!!!
