### ISSUE TITLE
DEV protocol ERC-20 Addition

### ISSUE THREAD

**Issue by Lamasusb000** [LedgerHQ/ledger-live-desktop#4140]
Can the Ledger team add support for the Dev Protocol ERC-20 token. Currently the amounts owned are shown within ledger but no price is shown. 

Contract: 0x5cAf454Ba92e6F2c929DF14667Ee360eD9fD5b26
Ticker: DEV

**Comment by gre** [comment]
please contact our official support to request adding more crypto assets in Ledger Live. They are not directly managed on this Ledger Live Github repository but you can request it to our custom support and/or contact us on our Ledger Slack Devs (if you are a developer and have access).

Thanks.
