### ISSUE TITLE
[broken link]  `Re-verify` on Binance Smart Chain (BSC) Receive view and `Gas price` on send view

### ISSUE THREAD

**Issue by CruiseMan** [LedgerHQ/ledger-live-desktop#4172]
When created address `Re-verify` links leads to broken url https://support.ledger.com/hc/en-us/articles/360006444193?utm_source=ledger_live_desktop&utm_medium=self_referral&utm_content=sendflow&null=true

<img width="544" alt="Screen Shot 2021-09-06 at 10 58 54 PM" src="https://user-images.githubusercontent.com/15807643/132291863-38181b9d-fb46-4e85-980e-f1fe81070090.png">

And here `Gas price`

https://support.ledger.com/hc/en-us/articles/360006535873?utm_source=ledger_live_desktop&utm_medium=self_referral&utm_content=fees&docs=true
<img width="505" alt="Screen Shot 2021-09-06 at 11 51 07 PM" src="https://user-images.githubusercontent.com/15807643/132297862-04c8afb0-8fbb-4da9-92e3-a97eda0f4b2c.png">

https://support.ledger.com/hc/en-us/articles/360006535873?utm_source=ledger_live_desktop&utm_medium=self_referral&utm_content=fees&docs=true

**Comment by gre** [comment]
Thanks for report,
Fixed by https://github.com/LedgerHQ/ledger-live-desktop/commit/e161660ef520ab832fce864aec353f0100b7f75d and will be in our next release.

**Comment by CruiseMan** [comment]
> Thanks for report,
> Fixed by [e161660](https://github.com/LedgerHQ/ledger-live-desktop/commit/e161660ef520ab832fce864aec353f0100b7f75d) and will be in our next release.

Just want to say i start testing Ledger vs Trezor, and found UI, UX, dev support is better here.
