### ISSUE TITLE
ETH App Installation Failure - Ledger device: UNKNOWN_ERROR (0x6a83)

### ISSUE THREAD

**Issue by stersj** [LedgerHQ/ledger-live-desktop#4174]
#### Ledger Live Version and Operating System

- Tested on Ledger Live 2.32.2
- Platform and version: Windows 10
- Ledger Nano X Firmware 1.3.0

#### Expected behavior

It should correctly install the latest version of the Ethereum application

#### Actual behavior

When trying to install Ethereum App it fails showing the following error:
![screenshot](https://user-images.githubusercontent.com/63779260/132305647-5d3c09cb-a36b-4b5c-91e3-9172ac4d8fca.gif)

#### Steps to reproduce the behavior

- Open the Ledger Live app
- Go to Manager
- Connect and unlock ledger nano X
- Search for Ethereum app
- Click on install
- It fails with pop-up `Ledger device: UNKNOWN_ERROR (0x6a83)`

**Comment by gre** [comment]
Hi, thanks a lot for raising this issue. 

This issue can happen for various reasons. We prefer to investigate such issues via contacting our customer support team.

could you send your logs to our support team and mention this github issue? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏  basically you can press Ctrl+E just after the problem occurs. ( alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.now.sh/logsviewer )

**Comment by stersj** [comment]
Dear Gre,

I have tried to send this issue twice to the ledger live team.
No one has help to resolve the issue.
I simply do not know what else to do anymore.
Should I move to Trezor?

Best Regards,
Esther
