### ISSUE TITLE
shiba inu support on BSC 

### ISSUE THREAD

**Issue by bitseaman** [LedgerHQ/ledger-live-desktop#4227]
#### Ledger Live Version and Operating System

- tested on Ledger Live **2.32.2**
- Platform and version: ** Windows 10 /**

#### Expected behavior

SHIB token shows on Ledger Live.

#### Actual behavior

SHIB token does not show on Ledger Live.

#### Steps to reproduce the behavior

I withdraw SHIB on BSC network to my Nano hardwallet. But I cannot see SHIB coming in. It is late for me to find out that SHIB on BSC is not supported now from this page. So when will Ledger Live support SHIB on BSC?

https://github.com/LedgerHQ/ledger-live-desktop/blob/develop/cryptoassets.md

**Comment by alwyn** [comment]
I too would like to be able to add SHIB as a token on BSC.

**Comment by bitseaman** [comment]
added.
