### ISSUE TITLE
As a user, I'd like to be able to reorganize the applications on my Ledger devices

### ISSUE THREAD

**Issue by sudoforge** [LedgerHQ/ledger-live-desktop#4356]
I would like to be able to organize (move) the order of applications on my Ledger devices. The main driver for this feature request is being able to relocate applications at in order to align with point-in-time preferences, without requiring users to uninstall and reinstall all applications, which forces users to reconfigure application settings.

**Comment by phantomcrypt** [comment]
Hi. There is already a request for this #3833
Hopefully the ledger team sees it 🙏🏼
