### ISSUE TITLE
Lost 0.5 LTC. it never reached the exchange

### ISSUE THREAD

**Issue by dobor0** [LedgerHQ/ledger-live-desktop#4370]
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.33.1
- Platform and version: linux

#### Expected behavior

I usually do a test transaction, it always works.

#### Actual behavior

did a test transaction, but 0.5 LTC never reached binance.
the 0.5 LTC are gone, i see the transaction in ledger live desktop. 
status says "Not confirmed" and the weird part, the transaction ID does not exist in the explorer.
i really would like to know what happened!

it's a massive loss in confidence. i don't dare to move coins from ledger via desktop live.

what are my possibilities now?

**Comment by dobor0** [comment]
370238f2fa429bbb39c65be855c9a7c0a5979da666d37618946e61928e32e162

this is the transaction ID in ledger live desktop

**Comment by Al-cm** [comment]
It is not lost. It can be seen on the Blockchair explorer. There is a waiting queue. This is your transaction: 
https://blockchair.com/nl/litecoin/transaction/370238f2fa429bbb39c65be855c9a7c0a5979da666d37618946e61928e32e162
It has been processed with a transaction fee of 0.00000258LTC.

**Comment by dobor0** [comment]
I see, thanks! The link given in desktop live is confusing.
Is there a timeout? Will it pass at some point?

**Comment by Al-cm** [comment]
I don't know, you could a) wait some time, or b) try to speed up the transaction by REPLACING the transaction, see the link:
https://support.bc-vault.com/support/solutions/articles/43000626327-how-can-i-speedup-or-replace-an-eth-erc20-btc-ltc-grs-doge-transaction-after-it-s-been-sent-to-the-bl
Good luck!

**Comment by dobor0** [comment]
Very good. Replace transaction, did not know that. Thanks for help!
