### ISSUE TITLE
Assets with special characters in it cause Ledger Live to stop working

### ISSUE THREAD

**Issue by phillipfickl** [LedgerHQ/ledger-live-desktop#4371]
#### Ledger Live Version and Operating System

- tested on Ledger Live >2.34.0
- Platform and version: Windows 10, Mac OS 12

It **does** still work with Ledger Live <= 2.33.1

#### Expected behavior

Ledger Live should work with any kind of assets. An Ethereum Account having an asset with special characters (eg. DEFI++ from PieDAO) should not make Ledger Live crash.

#### Actual behavior

Upon adding the account, Ledger Live crashes with an error message 
`Invalid regular expression: /1INCH|AAVE|LEND|ALINK|AUNI|AWBTC|GHST|ALCX|ALUSD|ALPHA|`....`Nothing to repeat`

#### Steps to reproduce the behavior

1. Add an Ethereum account with an asset that would make the regex invalid 
2. See Ledger Live crashing and refusing to start

Logs & Screenshot:
[ledgerlive-logs-2021.11.01-10.07.35-1833c2f.txt](https://github.com/LedgerHQ/ledger-live-desktop/files/7452036/ledgerlive-logs-2021.11.01-10.07.35-1833c2f.txt)

<img width="1015" alt="Screenshot 2021-11-01 at 10 11 08" src="https://user-images.githubusercontent.com/1156835/139649002-c2f1d8d4-c95f-49fe-8b2f-bf292ecae672.png">

**Comment by 0xaardling** [comment]
Can confirm this is an issue on Linux with v2.34.4 too.

The solution is to properly escape the regex. What causes the problem for me is also the DEFI++ ERC20 token.

`SyntaxError: Invalid regular expression: /BUSD|BTC|CVP|DAI|ETH|FARM|GSE|KICK|LINK|LPT|DEFI++|TRX|USDC|YDAI/: Nothing to repeat`

Should be 'DEFI\+\+' with proper escaping.

**Comment by dOrgJelli** [comment]
This is a problem for me as well, currently blocked.

**Comment by outcassed** [comment]
I'm also having this problem with DEFI++ and DEFI+L

**Comment by phillipfickl** [comment]
Still the same problem with 2.35.2.
Any chance you guys could look into this please? Hope you forgive me for tagging you but I can't use any version of ledger live > 2.33 atm.
@gre @valpinkman

**Comment by valpinkman** [comment]
We are sorry for not having seen this. A fix has been proposed https://github.com/LedgerHQ/ledger-live-common/pull/1559 here but I cannot tell exactly when this will be shipped.

**Comment by phillipfickl** [comment]
> We are sorry for not having seen this. A fix has been proposed [LedgerHQ/ledger-live-common#1559](https://github.com/LedgerHQ/ledger-live-common/pull/1559) here but I cannot tell exactly when this will be shipped.

No worries, thanks for the response and (future) fixing ✌

**Comment by porenes-ledger** [comment]
Fixed in https://github.com/LedgerHQ/ledger-live-desktop/releases/tag/v2.36.1 (live soon)
