### ISSUE TITLE
Ledger live Icon Not showing on macbook

### ISSUE THREAD

**Issue by cowie69** [LedgerHQ/ledger-live-desktop#4450]
#### Ledger Live Version and Operating System

- tested on Ledger Live **2.35.1**
Mac os catalina verison 10.15.7

![20211120_015227](https://user-images.githubusercontent.com/94727066/142710747-987b8bb4-52c7-41fe-85ff-530340b6188b.jpg)

Everything is fine but just for ease of use anybody know how to fix this?

**Comment by phantomcrypt** [comment]
See https://github.com/LedgerHQ/ledger-live-desktop/issues/4454#issuecomment-978149793

**Comment by valpinkman** [comment]
closing this as it is resolved
