### ISSUE TITLE
Solana support

### ISSUE THREAD

**Issue by plk** [LedgerHQ/ledger-live-desktop#4475]
Can we expect SPL network support? Some large exchanges like FTX support BTC/ETH etc. transfers over SPL instead of much slower and more expensive networks and it would be good to have SPL network support for Ledger accounts. Same sort of thing for swaps - Changelly seems mostly an ETH-token based service and until ETH 2.0 reduces gas fees, this is not very attractive.

**Comment by owenvoke** [comment]
Check out and upvote https://github.com/LedgerHQ/ledger-live-desktop/discussions/4005 👍🏻

**Comment by gushani** [comment]
I am asking for this to be implemented long time ago but ledger devs just ignored me

**Comment by plk** [comment]
I notice that this has been announced and so closing this.
