### ISSUE TITLE
Latest ledger-live-desktop-2.36.2-mac.dmg sha512sum doesn't match with provided sha512sum in your website!

### ISSUE THREAD

**Issue by fogmoon** [LedgerHQ/ledger-live-desktop#4557]
#### Ledger Live Version and Operating System

- tested on Ledger Live **2.36.2**
- Platform and version: **10.15**

#### Expected behavior
The downloaded install package from [your official website](https://www.ledger.com/ledger-live/lld-signatures) or from [GitHub release page ](https://github.com/LedgerHQ/ledger-live-desktop/releases)  has **same** sha512sum with your provided sha512sum [in your website](https://www.ledger.com/ledger-live/lld-signatures).

#### Actual behavior

The downloaded install package from [your official website](https://www.ledger.com/ledger-live/lld-signatures) or from [GitHub release page ](https://github.com/LedgerHQ/ledger-live-desktop/releases)  has **different** sha512sum with your provided sha512sum [in your website](https://www.ledger.com/ledger-live/lld-signatures).
- sha512sum in your website: `d701e404f7ee7f357d022f9e518d2ec9843c52cf135bba1eb79101fe54734a48c0d229ed43f1b80e31a26d589789efcdcf739f33f56b8561e4b123046bc649df `
- sha512sum in my tested 3 Mac: `bbd176239bf2056f88d6d0f32b15eea93d93d1ba2568fefd33374c6495d196c4e0c6c89223480078f46e6a1a0881fab517479f5a9a27d2ed69786879a41cf861`

#### Steps to reproduce the behavior
- Download the install package `ledger-live-desktop-2.36.2-mac.dmg sha512sum` from [your official website](https://www.ledger.com/ledger-live/lld-signatures) or from [GitHub release page ](https://github.com/LedgerHQ/ledger-live-desktop/releases) 
- run the command `shasum -a 512 ledger-live-desktop-2.36.2-mac.dmg` 
- compare the result with your website's result

**Comment by valpinkman** [comment]
Thank you for your feedback. There's been an issue when generating the sha from the downloaded artifacts (it seems like a network error) so the artifacts for macos where not similar. 
Anyway, this is resolved in v2.36.3 which is already in pre-release

**Comment by fogmoon** [comment]
Close it for this issue has been fixed in [v2.36.3](https://github.com/LedgerHQ/ledger-live-desktop/releases).

Thanks for your fix timely. 🍺

**Comment by valpinkman** [comment]
You're welcome
