### ISSUE TITLE
2.40.4 Black Screen on Fedora 36 Wayland

### ISSUE THREAD

**Issue by glennbarrett** [LedgerHQ/ledger-live-desktop#4952]
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.40.4
- Platform and version: Fedora 36 RC2 with Wayland on nvidia

#### Expected behavior

Ledger Live app should launch and show interface

#### Actual behavior

Ledger Live app launches but the window is a black screen

#### Steps to reproduce the behavior

Launch AppImage on Fedora 36 RC2 using Wayland
![ledger-bug](https://user-images.githubusercontent.com/1709271/165805743-3b6c800e-06b5-445b-b59c-ee2f07329ca3.png)

**Comment by thiagodebastos** [comment]
I am having the same issue with the same version and platform.

**Comment by glennbarrett** [comment]
Not sure exactly what fixed it, but after a few updates came for Fedora 36 RC, including kernel and nvidia drivers, this is now working on the same version that was experiencing the issue.
