### ISSUE TITLE
No mouse "pointer" cursor hovering over a content of a button

### ISSUE THREAD

**Issue by juliusosokinas** [LedgerHQ/ledger-live-desktop#901]
#### Ledger Live Version and Operating System

- Ledger Live 1.0.0-rc.2
- Platform: macOS

#### Expected behavior

When hovering over a button, mouse cursor should be set as "pointer".

#### Actual behavior

When hovering over a button, mouse cursor is set as "pointer" only when inside button's padding area, but is *not* within button content (icon/text).

#### Steps to reproduce the behavior

Click on image to see the video:

[![Reproducing the current issue](https://cdn-b-east.streamable.com/image/ff2pw.jpg)](https://streamable.com/ff2pw)

**Comment by gre** [comment]
Thanks for the issue.
It seems this is a current limitation of Electron https://github.com/electron/electron/issues/13104

**Comment by gre** [comment]
it looks like https://electronjs.org/docs/api/frameless-window#custombuttonsonhover would fix it however you no longer see the native button which is not really good option to me

![a](https://user-images.githubusercontent.com/211411/42409165-954e4576-81d6-11e8-8951-5d92b2eb26b6.gif)

**Comment by juliusosokinas** [comment]
I see.

Might then be worth looking at alternative solutions, e.g. Atom app displays the native title bar:

<img width="724" alt="Ledger Live (Desktop) - example of window frame on Atom app" src="https://user-images.githubusercontent.com/35398799/42411892-71ecbc2c-81fc-11e8-9c07-79a715847512.png">

But also on macOS apps usually don't have "pointer" cursors at all:

[![Atom app example](https://cdn-b-east.streamable.com/image/wpl26.jpg)](https://streamable.com/wpl26)

Or you can just keep an issue open until possibly Electron will resolve it...

**Comment by gre** [comment]
to retake Atom's example, it does not look like so consistent.
I guess not using pointer at all for the header par could be a tmp solution. the fact it hover with a background color make it pretty clear it's an action.

![a](https://user-images.githubusercontent.com/211411/42412388-d08f2238-820b-11e8-8b55-11ef317495ee.gif)

**Comment by meriadec** [comment]
IMO: If we choose to put cursor default on some buttons, we should do it for all buttons/interactive boxes (except for links like). It's a more native approach and I recommend.

If not, I would go for `custombuttonsonhover` which is pretty quick to implement.

**Comment by gre** [comment]
cc @bscholving

**Comment by valpinkman** [comment]
After a talk with @khalilbenihoud, we've decided to remove the cursor pointer everywhere (except for links), at least until we rework a custom toolbar.
