### ISSUE TITLE
"View in explorer" for Komodo operation does not work

### ISSUE THREAD

**Issue by juliusosokinas** [LedgerHQ/ledger-live-desktop#912]
#### Ledger Live Version and Operating System

- Ledger Live Live 1.0.0-rc.2
- Platform: macOS

#### Expected behavior

Clicking "View in explorer" for Komodo operation a new browser window should be opened with operation details.

#### Actual behavior

Clicking "View in explorer" for Komodo operation a new browser window is opened, however with a content "502 Bad Gateway".

#### Steps to reproduce the behavior

1. Make a Komodo operation
2. Open operation details
3. Press "View in explorer" button

<img width="724" alt="Ledger Live (Desktop) - not working Komodo operation explorer" src="https://user-images.githubusercontent.com/35398799/42413232-f56634e0-8213-11e8-97c1-cc2a4eb79046.png">

I personally suspect that the link is to an old explorer. Currently the official Komodo website directs to this one - https://kmdexplorer.io 🤔

**Comment by gre** [comment]
@juliusosokinas good catch, thanks!
