### ISSUE TITLE
Ripple operations gone after clearing app cache

### ISSUE THREAD

**Issue by juliusosokinas** [LedgerHQ/ledger-live-desktop#914]
#### Ledger Live Version and Operating System

- Ledger Live 1.0.0-rc.2
- Platform: macOS

#### Expected behavior

When app cache is cleared, resynchronization should retrieve and display all previous Ripple operations.

#### Actual behavior

When app cache is cleared, resynchronization is not retrieving (and not displaying) any of previous Ripple operations.

#### Steps to reproduce the behavior

1. Add Ripple account
2. Make operation(s)
3. Clear app cache
4. Resynchronize the app
5. Go back to Ripple account

Please note that I had only incoming operations for my Ripple account.

To get all previous Ripple operations back on the list I had to reset the Ledger Live (though probably removing the account and adding it back would have worked also).

**Comment by gre** [comment]
good catch. there were definitely a bug
