### ISSUE TITLE
two last point on graph use same countervalue

### ISSUE THREAD

**Issue by gre** [LedgerHQ/ledger-live-desktop#917]
#### Ledger Live Version and Operating System

- Ledger Live **rc.2**
- Platform: **mac**

#### Expected behavior

the two last point countervalues should be different like other points

#### Actual behavior

two last points are identically

#### Steps to reproduce the behavior

![a](https://user-images.githubusercontent.com/211411/42418879-25f24a36-82aa-11e8-8535-58afd1fc2bf8.gif)

**Comment by gre** [comment]
can no longer repro the bug this morning

**Comment by gre** [comment]
ok the issue is that the 2 last point are pointing to the same date.

for countervalues we use "close" date value so basically Jul 09 at 00:00 should be a lookup in Jul 08. if we do `- 1 ms` as a hack somewhere it would fix the problem but need to think this a bit more. cc @meriadec 

<img width="736" alt="capture d ecran 2018-07-09 a 07 35 36" src="https://user-images.githubusercontent.com/211411/42432411-b2bd6b80-834a-11e8-85fd-e9fee3babbb7.png">

**Comment by gre** [comment]
<img width="762" alt="capture d ecran 2018-07-09 a 07 41 13" src="https://user-images.githubusercontent.com/211411/42432593-79b4bb12-834b-11e8-8eb4-3e87df26ae1e.png">

like this hack literally work but meh.

**Comment by gre** [comment]
I think something more fundamental wrong is going on btw

look at this graph, it's saying 2018-07-08 but on the axis it's Jul 9

<img width="1238" alt="capture d ecran 2018-07-09 a 07 42 29" src="https://user-images.githubusercontent.com/211411/42432615-a855e3a6-834b-11e8-96fa-bf9075b30ba5.png">

**Comment by gre** [comment]
this can wait after the release. focus on other things ;)

**Comment by meriadec** [comment]
2 things:

- "can't repro bug this morning" : not really, the "bug" (which is not really a bug) is present this morning, but we don't see it because...it's the morning and the 2 points for today are too close
- the date problem comes from the fact the date is just an ISOString cutted at 0-10 indexes. With the format fix commit, the dates are correct (and in the right format)

If you launch the tests in live-common, you will see there is two items for the same date at the end of the array. It's not a regression, always been like that.

**Comment by gre** [comment]
@meriadec  no actually i can repro xD but yeah. mmh no the problem is that we build date with the start of the day and not at the "end of the previous day" and it's my fault, it's a regression in live-common. i just locally fixed it from live-common and i think that's all we need to do 


helpers/account.js, getBalanceHistory
```
  t = new Date(startOfDay(t) - 1) // midnight yesterday
```


don't worry about the bug for now, we need to focus on the release

**Comment by meriadec** [comment]
will do PR for the date format though
