### ISSUE TITLE
Fix uninstall confirmation of app that was not installed

### ISSUE THREAD

**Issue by dasilvarosa** [LedgerHQ/ledger-live-desktop#925]
#### Ledger Live Version and Operating System

- Ledger Live **RC2**
- Platform: **macOS**

#### Expected behavior

Modal:
title: Oops, that app can't be uninstalled
description: Check on your device which apps are installed

#### Actual behavior
Modal:
{{cryptocurrency}} has been uninstalled from your device

#### Steps to reproduce the behavior

Uninstall an app that's not installed.

**Comment by gre** [comment]
I think at the moment we can't technically detect this. (@amougel)

**Comment by gre** [comment]
@amougel do you know if we can technical differenciate this case?

**Comment by gre** [comment]
So as we need to support older firmware for now and current firmware don't even offer it, it is not fixable for now, we need to raise this usecase to hardware team.
Actually, the proper way to solve this will be when we will be able to know which app is currently installed, this problem will then disappear. we can create another feature request for this in the future
