### ISSUE TITLE
Windows: Internal process error (3765269347)

### ISSUE THREAD

**Issue by Re-Diculous** [LedgerHQ/ledger-live-desktop#933]
(@gre edit) **we are aware of this important bug and having hard time to reproduce it.** The bug is that, on Windows, it crashes at boot with this "Internal process error". This happens to less than 5% of our users.

**current workaround we have is to invite you to "Run as Admin"** https://support.ledgerwallet.com/hc/en-us/articles/360006702834-Troubleshooting-on-Windows

we are really looking forward to understand what is wrong. If you want to investigate on your side please don't hesitate to add comments in this issue.

--- 

Error was thrown:

```
Error
    at o (file:///E:/Ledger%20Live/resources/app.asar/renderer.js:1:25413)
    at a (file:///E:/Ledger%20Live/resources/app.asar/renderer.js:1:25600)
    at EventEmitter.l (file:///E:/Ledger%20Live/resources/app.asar/renderer.js:1:27016)
    at emitTwo (events.js:130:20)
    at EventEmitter.emit (events.js:213:7)
```
Error happens directly after clicking "Get started". Windows 7 Home Premium SP1 64bit, intel i7.

**Comment by gre** [comment]
@Re-Diculous thanks for the report!

would you mind trying to reproduce it and JUST after hitting Ctrl+E , save the file, open the log file and locate the part where the error happen and paste here? (make sure there is no personal info in the logs you send here)

thanks

**Comment by michi6383** [comment]
same here
{"type":"cmd.ERROR","data":{"message":"Internal process error (3765269347)","name":"InternalError"},"level":"warn","message":"✖ CMD libcoreGetVersion error","pname":"renderer","timestamp":"2018-07-09T10:54:37.201Z"}
{"message":"Internal process error (3765269347)","name":"InternalError","level":"error","pname":"renderer","timestamp":"2018-07-09T10:54:37.201Z"}

**Comment by gre** [comment]
is there any special error logs a bit before, that mention `"pname": "internal"` ?

**Comment by michi6383** [comment]
{"type":"db","level":"info","message":"📁  read user","pname":"main","timestamp":"2018-07-09T10:53:11.573Z"}
{"type":"db","level":"info","message":"📁  write user","pname":"main","timestamp":"2018-07-09T10:53:11.602Z"}
{"level":"info","message":"booting internal process...","pname":"main","timestamp":"2018-07-09T10:53:15.801Z"}
{"type":"db","level":"info","message":"📁  read migrations","pname":"renderer","timestamp":"2018-07-09T10:53:15.366Z"}
{"type":"db","level":"info","message":"📁  write migrations","pname":"renderer","timestamp":"2018-07-09T10:53:15.395Z"}
{"type":"db","level":"info","message":"📁  read settings","pname":"renderer","timestamp":"2018-07-09T10:53:15.539Z"}
{"type":"action","action":{"type":"FETCH_SETTINGS","payload":{}},"level":"info","message":"⚛️  FETCH_SETTINGS","pname":"renderer","timestamp":"2018-07-09T10:53:15.540Z"}
{"type":"db","level":"info","message":"📁  write settings","pname":"renderer","timestamp":"2018-07-09T10:53:15.574Z"}
{"type":"db","level":"info","message":"📁  read countervalues","pname":"renderer","timestamp":"2018-07-09T10:53:15.629Z"}
{"type":"db","level":"info","message":"📁  read user","pname":"renderer","timestamp":"2018-07-09T10:53:15.670Z"}
{"type":"db","level":"info","message":"📁  read accounts","pname":"renderer","timestamp":"2018-07-09T10:53:15.785Z"}
{"type":"action","action":{"type":"SET_ACCOUNTS","payload":[]},"level":"info","message":"⚛️  SET_ACCOUNTS","pname":"renderer","timestamp":"2018-07-09T10:53:15.786Z"}
{"type":"action","action":{"type":"@@router/LOCATION_CHANGE","payload":{"pathname":"/","search":"","hash":""}},"level":"info","message":"⚛️  @@router/LOCATION_CHANGE","pname":"renderer","timestamp":"2018-07-09T10:53:15.795Z"}
{"level":"info","message":"info","pname":"renderer","timestamp":"2018-07-09T10:53:15.802Z"}
{"level":"info","message":"info","pname":"renderer","timestamp":"2018-07-09T10:53:15.802Z"}
{"type":"anaytics-track","properties":{},"level":"info","message":"△ track App Starts","pname":"renderer","timestamp":"2018-07-09T10:53:15.853Z"}
{"type":"anaytics-page","properties":{},"level":"info","message":"△ page Onboarding Start","pname":"renderer","timestamp":"2018-07-09T10:53:15.866Z"}
{"level":"info","message":"Internal process is up!","pname":"internal","timestamp":"2018-07-09T10:53:17.636Z"}
{"level":"warn","message":"Internal process ended with code 3765269347","pname":"main","timestamp":"2018-07-09T10:53:17.776Z"}
{"type":"cmd.ERROR","data":{"message":"Internal process error (3765269347)","name":"InternalError"},"level":"warn","message":"✖ CMD listenDevices error","pname":"renderer","timestamp":"2018-07-09T10:53:17.777Z"}
{"message":"listenDevices error","name":"InternalError","level":"warn","pname":"renderer","timestamp":"2018-07-09T10:53:17.780Z"}
{"type":"action","action":{"type":"RESET_DEVICES"},"level":"info","message":"⚛️  RESET_DEVICES","pname":"renderer","timestamp":"2018-07-09T10:53:17.780Z"}
{"level":"info","message":"info","pname":"renderer","timestamp":"2018-07-09T10:53:17.780Z"}
{"type":"cmd.ERROR","data":{"message":"Internal process error (3765269347)","name":"InternalError"},"level":"warn","message":"✖ CMD libcoreGetVersion error","pname":"renderer","timestamp":"2018-07-09T10:53:17.781Z"}
{"message":"Internal process error (3765269347)","name":"InternalError","level":"error","pname":"renderer","timestamp":"2018-07-09T10:53:17.781Z"}
{"level":"info","message":"booting internal process...","pname":"main","timestamp":"2018-07-09T10:53:17.780Z"}
{"level":"info","message":"Internal process is up!","pname":"internal","timestamp":"2018-07-09T10:53:19.634Z"}
{"level":"info","message":"info","pname":"internal","timestamp":"2018-07-09T10:53:19.655Z"}
{"type":"action","action":{"type":"UPDATE_SET_STATUS","payload":{"status":"checking"}},"level":"info","message":"⚛️  UPDATE_SET_STATUS","pname":"renderer","timestamp":"2018-07-09T10:53:20.928Z"}
{"type":"action","action":{"type":"UPDATE_SET_STATUS","payload":{"status":"unavailable"}},"level":"info","message":"⚛️  UPDATE_SET_STATUS","pname":"renderer","timestamp":"2018-07-09T10:53:22.824Z"}
{"level":"info","message":"killing internal process...","pname":"main","timestamp":"2018-07-09T10:53:34.358Z"}
{"type":"db","level":"info","message":"📁  read migrations","pname":"renderer","timestamp":"2018-07-09T10:53:34.074Z"}
{"type":"db","level":"info","message":"📁  read settings","pname":"renderer","timestamp":"2018-07-09T10:53:34.136Z"}
{"type":"action","action":{"type":"FETCH_SETTINGS","payload":{"hasCompletedOnboarding":false,"counterValue":"USD","counterValueExchange":null,"language":null,"region":null,"orderAccounts":"balance|asc","password":{"isEnabled":false,"value":""},"selectedTimeRange":"month","marketIndicator":"western","currenciesSettings":{},"developerMode":false,"loaded":true,"shareAnalytics":false,"sentryLogs":true,"lastUsedVersion":"1.0.0"}},"level":"info","message":"⚛️  FETCH_SETTINGS","pname":"renderer","timestamp":"2018-07-09T10:53:34.136Z"}
{"type":"db","level":"info","message":"📁  write settings","pname":"renderer","timestamp":"2018-07-09T10:53:34.161Z"}
{"type":"db","level":"info","message":"📁  read countervalues","pname":"renderer","timestamp":"2018-07-09T10:53:34.224Z"}
{"type":"db","level":"info","message":"📁  read user","pname":"renderer","timestamp":"2018-07-09T10:53:34.264Z"}
{"type":"db","level":"info","message":"📁  read accounts","pname":"renderer","timestamp":"2018-07-09T10:53:34.342Z"}
{"type":"action","action":{"type":"SET_ACCOUNTS","payload":[]},"level":"info","message":"⚛️  SET_ACCOUNTS","pname":"renderer","timestamp":"2018-07-09T10:53:34.342Z"}
{"type":"action","action":{"type":"@@router/LOCATION_CHANGE","payload":{"pathname":"/","search":"","hash":""}},"level":"info","message":"⚛️  @@router/LOCATION_CHANGE","pname":"renderer","timestamp":"2018-07-09T10:53:34.351Z"}
{"level":"info","message":"info","pname":"renderer","timestamp":"2018-07-09T10:53:34.355Z"}
{"level":"info","message":"booting internal process...","pname":"main","timestamp":"2018-07-09T10:53:34.359Z"}
{"level":"info","message":"info","pname":"renderer","timestamp":"2018-07-09T10:53:34.357Z"}
{"type":"anaytics-track","properties":{},"level":"info","message":"△ track App Starts","pname":"renderer","timestamp":"2018-07-09T10:53:34.413Z"}
{"type":"anaytics-page","properties":{},"level":"info","message":"△ page Onboarding Start","pname":"renderer","timestamp":"2018-07-09T10:53:34.425Z"}
{"level":"info","message":"Internal process is up!","pname":"internal","timestamp":"2018-07-09T10:53:36.168Z"}
{"level":"warn","message":"Internal process ended with code 3765269347","pname":"main","timestamp":"2018-07-09T10:53:36.254Z"}
{"type":"cmd.ERROR","data":{"message":"Internal process error (3765269347)","name":"InternalError"},"level":"warn","message":"✖ CMD listenDevices error","pname":"renderer","timestamp":"2018-07-09T10:53:36.252Z"}
{"level":"info","message":"booting internal process...","pname":"main","timestamp":"2018-07-09T10:53:36.258Z"}
{"message":"listenDevices error","name":"InternalError","level":"warn","pname":"renderer","timestamp":"2018-07-09T10:53:36.255Z"}
{"type":"action","action":{"type":"RESET_DEVICES"},"level":"info","message":"⚛️  RESET_DEVICES","pname":"renderer","timestamp":"2018-07-09T10:53:36.255Z"}
{"level":"info","message":"info","pname":"renderer","timestamp":"2018-07-09T10:53:36.255Z"}
{"type":"cmd.ERROR","data":{"message":"Internal process error (3765269347)","name":"InternalError"},"level":"warn","message":"✖ CMD libcoreGetVersion error","pname":"renderer","timestamp":"2018-07-09T10:53:36.256Z"}
{"message":"Internal process error (3765269347)","name":"InternalError","level":"error","pname":"renderer","timestamp":"2018-07-09T10:53:36.256Z"}
{"level":"info","message":"Internal process is up!","pname":"internal","timestamp":"2018-07-09T10:53:38.042Z"}
{"level":"info","message":"info","pname":"internal","timestamp":"2018-07-09T10:53:38.062Z"}
{"type":"action","action":{"type":"UPDATE_SET_STATUS","payload":{"status":"checking"}},"level":"info","message":"⚛️  UPDATE_SET_STATUS","pname":"renderer","timestamp":"2018-07-09T10:53:39.362Z"}
{"type":"action","action":{"type":"UPDATE_SET_STATUS","payload":{"status":"checking"}},"level":"info","message":"⚛️  UPDATE_SET_STATUS","pname":"renderer","timestamp":"2018-07-09T10:53:39.362Z"}
{"type":"action","action":{"type":"UPDATE_SET_STATUS","payload":{"status":"unavailable"}},"level":"info","message":"⚛️  UPDATE_SET_STATUS","pname":"renderer","timestamp":"2018-07-09T10:53:40.694Z"}
{"type":"action","action":{"type":"UPDATE_SET_STATUS","payload":{"status":"unavailable"}},"level":"info","message":"⚛️  UPDATE_SET_STATUS","pname":"renderer","timestamp":"2018-07-09T10:53:40.694Z"}
{"type":"anaytics-page","properties":{},"level":"info","message":"△ page Modal HardReset","pname":"renderer","timestamp":"2018-07-09T10:53:43.013Z"}
{"type":"db","level":"info","message":"📁  clear settings","pname":"renderer","timestamp":"2018-07-09T10:53:45.760Z"}
{"type":"db","level":"info","message":"📁  clear accounts","pname":"renderer","timestamp":"2018-07-09T10:53:45.836Z"}
{"type":"db","level":"info","message":"📁  clear countervalues","pname":"renderer","timestamp":"2018-07-09T10:53:45.898Z"}
{"level":"info","message":"killing internal process...","pname":"main","timestamp":"2018-07-09T10:53:49.655Z"}
{"type":"db","level":"info","message":"📁  read migrations","pname":"renderer","timestamp":"2018-07-09T10:53:49.285Z"}
{"type":"db","level":"info","message":"📁  read settings","pname":"renderer","timestamp":"2018-07-09T10:53:49.383Z"}
{"type":"action","action":{"type":"FETCH_SETTINGS","payload":{}},"level":"info","message":"⚛️  FETCH_SETTINGS","pname":"renderer","timestamp":"2018-07-09T10:53:49.383Z"}
{"type":"db","level":"info","message":"📁  write settings","pname":"renderer","timestamp":"2018-07-09T10:53:49.407Z"}
{"type":"db","level":"info","message":"📁  read countervalues","pname":"renderer","timestamp":"2018-07-09T10:53:49.484Z"}
{"type":"db","level":"info","message":"📁  read user","pname":"renderer","timestamp":"2018-07-09T10:53:49.528Z"}
{"type":"db","level":"info","message":"📁  read accounts","pname":"renderer","timestamp":"2018-07-09T10:53:49.634Z"}
{"type":"action","action":{"type":"SET_ACCOUNTS","payload":[]},"level":"info","message":"⚛️  SET_ACCOUNTS","pname":"renderer","timestamp":"2018-07-09T10:53:49.634Z"}
{"type":"action","action":{"type":"@@router/LOCATION_CHANGE","payload":{"pathname":"/","search":"","hash":""}},"level":"info","message":"⚛️  @@router/LOCATION_CHANGE","pname":"renderer","timestamp":"2018-07-09T10:53:49.643Z"}
{"level":"info","message":"info","pname":"renderer","timestamp":"2018-07-09T10:53:49.650Z"}
{"level":"info","message":"info","pname":"renderer","timestamp":"2018-07-09T10:53:49.651Z"}
{"level":"info","message":"booting internal process...","pname":"main","timestamp":"2018-07-09T10:53:49.655Z"}
{"type":"anaytics-track","properties":{},"level":"info","message":"△ track App Starts","pname":"renderer","timestamp":"2018-07-09T10:53:49.700Z"}
{"type":"anaytics-page","properties":{},"level":"info","message":"△ page Onboarding Start","pname":"renderer","timestamp":"2018-07-09T10:53:49.716Z"}
{"level":"info","message":"Internal process is up!","pname":"internal","timestamp":"2018-07-09T10:53:51.532Z"}
{"level":"warn","message":"Internal process ended with code 3765269347","pname":"main","timestamp":"2018-07-09T10:53:51.623Z"}
{"type":"cmd.ERROR","data":{"message":"Internal process error (3765269347)","name":"InternalError"},"level":"warn","message":"✖ CMD listenDevices error","pname":"renderer","timestamp":"2018-07-09T10:53:51.618Z"}
{"level":"info","message":"booting internal process...","pname":"main","timestamp":"2018-07-09T10:53:51.627Z"}
{"message":"listenDevices error","name":"InternalError","level":"warn","pname":"renderer","timestamp":"2018-07-09T10:53:51.621Z"}
{"type":"action","action":{"type":"RESET_DEVICES"},"level":"info","message":"⚛️  RESET_DEVICES","pname":"renderer","timestamp":"2018-07-09T10:53:51.621Z"}
{"level":"info","message":"info","pname":"renderer","timestamp":"2018-07-09T10:53:51.622Z"}
{"type":"cmd.ERROR","data":{"message":"Internal process error (3765269347)","name":"InternalError"},"level":"warn","message":"✖ CMD libcoreGetVersion error","pname":"renderer","timestamp":"2018-07-09T10:53:51.622Z"}
{"message":"Internal process error (3765269347)","name":"InternalError","level":"error","pname":"renderer","timestamp":"2018-07-09T10:53:51.622Z"}
{"level":"info","message":"Internal process is up!","pname":"internal","timestamp":"2018-07-09T10:53:53.490Z"}
{"level":"info","message":"info","pname":"internal","timestamp":"2018-07-09T10:53:53.508Z"}
{"type":"action","action":{"type":"UPDATE_SET_STATUS","payload":{"status":"checking"}},"level":"info","message":"⚛️  UPDATE_SET_STATUS","pname":"renderer","timestamp":"2018-07-09T10:53:54.655Z"}
{"type":"action","action":{"type":"UPDATE_SET_STATUS","payload":{"status":"checking"}},"level":"info","message":"⚛️  UPDATE_SET_STATUS","pname":"renderer","timestamp":"2018-07-09T10:53:54.655Z"}
{"type":"action","action":{"type":"UPDATE_SET_STATUS","payload":{"status":"checking"}},"level":"info","message":"⚛️  UPDATE_SET_STATUS","pname":"renderer","timestamp":"2018-07-09T10:53:54.655Z"}
{"type":"action","action":{"type":"UPDATE_SET_STATUS","payload":{"status":"unavailable"}},"level":"info","message":"⚛️  UPDATE_SET_STATUS","pname":"renderer","timestamp":"2018-07-09T10:53:56.177Z"}
{"type":"action","action":{"type":"UPDATE_SET_STATUS","payload":{"status":"unavailable"}},"level":"info","message":"⚛️  UPDATE_SET_STATUS","pname":"renderer","timestamp":"2018-07-09T10:53:56.177Z"}
{"type":"action","action":{"type":"UPDATE_SET_STATUS","payload":{"status":"unavailable"}},"level":"info","message":"⚛️  UPDATE_SET_STATUS","pname":"renderer","timestamp":"2018-07-09T10:53:56.177Z"}
{"level":"info","message":"killing internal process...","pname":"main","timestamp":"2018-07-09T10:54:29.130Z"}
{"type":"db","level":"info","message":"📁  read migrations","pname":"renderer","timestamp":"2018-07-09T10:54:28.801Z"}
{"type":"db","level":"info","message":"📁  read settings","pname":"renderer","timestamp":"2018-07-09T10:54:28.879Z"}
{"type":"action","action":{"type":"FETCH_SETTINGS","payload":{"hasCompletedOnboarding":false,"counterValue":"USD","counterValueExchange":null,"language":null,"region":null,"orderAccounts":"balance|asc","password":{"isEnabled":false,"value":""},"selectedTimeRange":"month","marketIndicator":"western","currenciesSettings":{},"developerMode":false,"loaded":true,"shareAnalytics":false,"sentryLogs":true,"lastUsedVersion":"1.0.0"}},"level":"info","message":"⚛️  FETCH_SETTINGS","pname":"renderer","timestamp":"2018-07-09T10:54:28.879Z"}
{"type":"db","level":"info","message":"📁  write settings","pname":"renderer","timestamp":"2018-07-09T10:54:28.912Z"}
{"type":"db","level":"info","message":"📁  read countervalues","pname":"renderer","timestamp":"2018-07-09T10:54:28.988Z"}
{"type":"db","level":"info","message":"📁  read user","pname":"renderer","timestamp":"2018-07-09T10:54:29.031Z"}
{"type":"db","level":"info","message":"📁  read accounts","pname":"renderer","timestamp":"2018-07-09T10:54:29.115Z"}
{"type":"action","action":{"type":"SET_ACCOUNTS","payload":[]},"level":"info","message":"⚛️  SET_ACCOUNTS","pname":"renderer","timestamp":"2018-07-09T10:54:29.116Z"}
{"level":"info","message":"booting internal process...","pname":"main","timestamp":"2018-07-09T10:54:29.131Z"}
{"type":"action","action":{"type":"@@router/LOCATION_CHANGE","payload":{"pathname":"/","search":"","hash":""}},"level":"info","message":"⚛️  @@router/LOCATION_CHANGE","pname":"renderer","timestamp":"2018-07-09T10:54:29.125Z"}
{"level":"info","message":"info","pname":"renderer","timestamp":"2018-07-09T10:54:29.130Z"}
{"level":"info","message":"info","pname":"renderer","timestamp":"2018-07-09T10:54:29.132Z"}
{"type":"anaytics-track","properties":{},"level":"info","message":"△ track App Starts","pname":"renderer","timestamp":"2018-07-09T10:54:29.187Z"}
{"type":"anaytics-page","properties":{},"level":"info","message":"△ page Onboarding Start","pname":"renderer","timestamp":"2018-07-09T10:54:29.200Z"}
{"level":"info","message":"Internal process is up!","pname":"internal","timestamp":"2018-07-09T10:54:30.930Z"}
{"level":"warn","message":"Internal process ended with code 3765269347","pname":"main","timestamp":"2018-07-09T10:54:31.016Z"}
{"type":"cmd.ERROR","data":{"message":"Internal process error (3765269347)","name":"InternalError"},"level":"warn","message":"✖ CMD listenDevices error","pname":"renderer","timestamp":"2018-07-09T10:54:31.017Z"}
{"level":"info","message":"booting internal process...","pname":"main","timestamp":"2018-07-09T10:54:31.020Z"}
{"message":"listenDevices error","name":"InternalError","level":"warn","pname":"renderer","timestamp":"2018-07-09T10:54:31.020Z"}
{"type":"action","action":{"type":"RESET_DEVICES"},"level":"info","message":"⚛️  RESET_DEVICES","pname":"renderer","timestamp":"2018-07-09T10:54:31.020Z"}
{"level":"info","message":"info","pname":"renderer","timestamp":"2018-07-09T10:54:31.020Z"}
{"type":"cmd.ERROR","data":{"message":"Internal process error (3765269347)","name":"InternalError"},"level":"warn","message":"✖ CMD libcoreGetVersion error","pname":"renderer","timestamp":"2018-07-09T10:54:31.021Z"}
{"message":"Internal process error (3765269347)","name":"InternalError","level":"error","pname":"renderer","timestamp":"2018-07-09T10:54:31.021Z"}
{"level":"info","message":"Internal process is up!","pname":"internal","timestamp":"2018-07-09T10:54:32.839Z"}
{"level":"info","message":"info","pname":"internal","timestamp":"2018-07-09T10:54:32.859Z"}
{"level":"info","message":"killing internal process...","pname":"main","timestamp":"2018-07-09T10:54:35.294Z"}
{"type":"db","level":"info","message":"📁  read migrations","pname":"renderer","timestamp":"2018-07-09T10:54:34.941Z"}
{"type":"db","level":"info","message":"📁  read settings","pname":"renderer","timestamp":"2018-07-09T10:54:35.037Z"}
{"type":"action","action":{"type":"FETCH_SETTINGS","payload":{"hasCompletedOnboarding":false,"counterValue":"USD","counterValueExchange":null,"language":null,"region":null,"orderAccounts":"balance|asc","password":{"isEnabled":false,"value":""},"selectedTimeRange":"month","marketIndicator":"western","currenciesSettings":{},"developerMode":false,"loaded":true,"shareAnalytics":false,"sentryLogs":true,"lastUsedVersion":"1.0.0"}},"level":"info","message":"⚛️  FETCH_SETTINGS","pname":"renderer","timestamp":"2018-07-09T10:54:35.038Z"}
{"type":"db","level":"info","message":"📁  write settings","pname":"renderer","timestamp":"2018-07-09T10:54:35.076Z"}
{"type":"db","level":"info","message":"📁  read countervalues","pname":"renderer","timestamp":"2018-07-09T10:54:35.152Z"}
{"level":"info","message":"booting internal process...","pname":"main","timestamp":"2018-07-09T10:54:35.294Z"}
{"type":"db","level":"info","message":"📁  read user","pname":"renderer","timestamp":"2018-07-09T10:54:35.192Z"}
{"type":"db","level":"info","message":"📁  read accounts","pname":"renderer","timestamp":"2018-07-09T10:54:35.277Z"}
{"type":"action","action":{"type":"SET_ACCOUNTS","payload":[]},"level":"info","message":"⚛️  SET_ACCOUNTS","pname":"renderer","timestamp":"2018-07-09T10:54:35.278Z"}
{"type":"action","action":{"type":"@@router/LOCATION_CHANGE","payload":{"pathname":"/","search":"","hash":""}},"level":"info","message":"⚛️  @@router/LOCATION_CHANGE","pname":"renderer","timestamp":"2018-07-09T10:54:35.287Z"}
{"level":"info","message":"info","pname":"renderer","timestamp":"2018-07-09T10:54:35.292Z"}
{"level":"info","message":"info","pname":"renderer","timestamp":"2018-07-09T10:54:35.293Z"}
{"type":"anaytics-track","properties":{},"level":"info","message":"△ track App Starts","pname":"renderer","timestamp":"2018-07-09T10:54:35.354Z"}
{"type":"anaytics-page","properties":{},"level":"info","message":"△ page Onboarding Start","pname":"renderer","timestamp":"2018-07-09T10:54:35.369Z"}
{"type":"action","action":{"type":"ONBOARDING_JUMP_STEP","payload":"init"},"level":"info","message":"⚛️  ONBOARDING_JUMP_STEP","pname":"renderer","timestamp":"2018-07-09T10:54:36.390Z"}
{"type":"anaytics-page","properties":{},"level":"info","message":"△ page Onboarding Init","pname":"renderer","timestamp":"2018-07-09T10:54:36.409Z"}
{"level":"info","message":"Internal process is up!","pname":"internal","timestamp":"2018-07-09T10:54:37.110Z"}
{"level":"warn","message":"Internal process ended with code 3765269347","pname":"main","timestamp":"2018-07-09T10:54:37.197Z"}
{"type":"cmd.ERROR","data":{"message":"Internal process error (3765269347)","name":"InternalError"},"level":"warn","message":"✖ CMD listenDevices error","pname":"renderer","timestamp":"2018-07-09T10:54:37.198Z"}
{"level":"info","message":"booting internal process...","pname":"main","timestamp":"2018-07-09T10:54:37.202Z"}
{"message":"listenDevices error","name":"InternalError","level":"warn","pname":"renderer","timestamp":"2018-07-09T10:54:37.200Z"}
{"type":"action","action":{"type":"RESET_DEVICES"},"level":"info","message":"⚛️  RESET_DEVICES","pname":"renderer","timestamp":"2018-07-09T10:54:37.201Z"}
{"level":"info","message":"info","pname":"renderer","timestamp":"2018-07-09T10:54:37.201Z"}
{"type":"cmd.ERROR","data":{"message":"Internal process error (3765269347)","name":"InternalError"},"level":"warn","message":"✖ CMD libcoreGetVersion error","pname":"renderer","timestamp":"2018-07-09T10:54:37.201Z"}
{"message":"Internal process error (3765269347)","name":"InternalError","level":"error","pname":"renderer","timestamp":"2018-07-09T10:54:37.201Z"}
{"level":"info","message":"Internal process is up!","pname":"internal","timestamp":"2018-07-09T10:54:39.006Z"}
{"level":"info","message":"info","pname":"internal","timestamp":"2018-07-09T10:54:39.033Z"}
{"type":"action","action":{"type":"UPDATE_SET_STATUS","payload":{"status":"checking"}},"level":"info","message":"⚛️  UPDATE_SET_STATUS","pname":"renderer","timestamp":"2018-07-09T10:54:40.297Z"}
{"type":"action","action":{"type":"UPDATE_SET_STATUS","payload":{"status":"checking"}},"level":"info","message":"⚛️  UPDATE_SET_STATUS","pname":"renderer","timestamp":"2018-07-09T10:54:40.297Z"}
{"type":"action","action":{"type":"UPDATE_SET_STATUS","payload":{"status":"checking"}},"level":"info","message":"⚛️  UPDATE_SET_STATUS","pname":"renderer","timestamp":"2018-07-09T10:54:40.298Z"}
{"type":"action","action":{"type":"UPDATE_SET_STATUS","payload":{"status":"checking"}},"level":"info","message":"⚛️  UPDATE_SET_STATUS","pname":"renderer","timestamp":"2018-07-09T10:54:40.298Z"}
{"type":"action","action":{"type":"UPDATE_SET_STATUS","payload":{"status":"unavailable"}},"level":"info","message":"⚛️  UPDATE_SET_STATUS","pname":"renderer","timestamp":"2018-07-09T10:54:41.818Z"}
{"type":"action","action":{"type":"UPDATE_SET_STATUS","payload":{"status":"unavailable"}},"level":"info","message":"⚛️  UPDATE_SET_STATUS","pname":"renderer","timestamp":"2018-07-09T10:54:41.818Z"}
{"type":"action","action":{"type":"UPDATE_SET_STATUS","payload":{"status":"unavailable"}},"level":"info","message":"⚛️  UPDATE_SET_STATUS","pname":"renderer","timestamp":"2018-07-09T10:54:41.818Z"}
{"type":"action","action":{"type":"UPDATE_SET_STATUS","payload":{"status":"unavailable"}},"level":"info","message":"⚛️  UPDATE_SET_STATUS","pname":"renderer","timestamp":"2018-07-09T10:54:41.818Z"}
{"type":"anaytics-track","properties":{"url":"https://github.com/LedgerHQ/ledger-live-desktop/issues/new?title=Error%3A%20Internal%20process%20error%20(3765269347)&body=Error%20was%20thrown%3A%0A%0A%60%60%60%0AError%0A%20%20%20%20at%20o%20(file%3A%2F%2F%2FC%3A%2FProgram%2520Files%2FLedger%2520Live%2Fresources%2Fapp.asar%2Frenderer.js%3A1%3A25413)%0A%20%20%20%20at%20a%20(file%3A%2F%2F%2FC%3A%2FProgram%2520Files%2FLedger%2520Live%2Fresources%2Fapp.asar%2Frenderer.js%3A1%3A25600)%0A%20%20%20%20at%20EventEmitter.l%20(file%3A%2F%2F%2FC%3A%2FProgram%2520Files%2FLedger%2520Live%2Fresources%2Fapp.asar%2Frenderer.js%3A1%3A27016)%0A%20%20%20%20at%20emitTwo%20(events.js%3A130%3A20)%0A%20%20%20%20at%20EventEmitter.emit%20(events.js%3A213%3A7)%0A%60%60%60%0A"},"level":"info","message":"△ track OpenURL","pname":"renderer","timestamp":"2018-07-09T10:54:45.982Z"}
{"type":"anaytics-track","level":"info","message":"△ track ExportLogs","pname":"renderer","timestamp":"2018-07-09T10:55:11.139Z"}
{"resourceUsage":{"images":{"count":3,"size":56362,"liveSize":15376},"scripts":{"count":1,"size":2881995,"liveSize":1918454},"cssStyleSheets":{"count":0,"size":0,"liveSize":0},"xslStyleSheets":{"count":0,"size":0,"liveSize":0},"fonts":{"count":11,"size":104456,"liveSize":0},"other":{"count":0,"size":0,"liveSize":0}},"release":"1.0.0","git_commit":"576b4b050600e1ec0ecde631b45e2f17a006e18b","environment":"production","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) LedgerLive/1.0.0 Chrome/59.0.3071.115 Electron/1.8.7 Safari/537.36","level":"info","message":"exportLogsMeta","pname":"renderer","timestamp":"2018-07-09T10:55:11.141Z"}

**Comment by gre** [comment]
Ok. It looks like a raw crash for our C++ lib. cc @KhalilBellakrid ( any log file we would need, is there a special crash log file? i suspect it crash at load of the lib so maybe there won't even be any logs )

**Comment by michi6383** [comment]
If I say, "run as admin" it works. maybe that helps as a "workaround".
Michael

**Comment by Re-Diculous** [comment]
Same for me here. Same process error as for Michael. Running as admin works!

**Comment by KhalilBellakrid** [comment]
@gre we can try to get logs located in : `C:\Users\<userName>\AppData\Roaming\Ledger Live\sqlite\log_file_v1_ledger_live_desktop-l` but since it crashes at libcoreGetVersion command I don't think we'll get significant logs.

**Comment by michi6383** [comment]
@KhalilBellakrid you are right. Same logs as "Ledger Live Export" nothing new.

**Comment by suvayu** [comment]
As mentioned in the duplicate bug, I have pretty much the same error.  But in my case it says `Internal process error (null)`, and there is no traceback on the terminal.  I'm on Linux, so this is not Windows only.

**Comment by gre** [comment]
@suvayu so I guess it's a different bug? would you mind opening another issue? this one is specifically happening on windows

**Comment by GergoR6** [comment]
Same here.

InternalError: Internal process error (3765269347)
Error
    at o (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/renderer.js:1:25413)
    at a (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/renderer.js:1:25600)
    at EventEmitter.l (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/renderer.js:1:27016)
    at emitTwo (events.js:130:20)
    at EventEmitter.emit (events.js:213:7)

**Comment by suvayu** [comment]
@gre sorry, about that. I opened a new issue: #1010

**Comment by gre** [comment]
@geg780 you are correct!!

**Comment by michi6383** [comment]
I have no special character in username.

**Comment by gre** [comment]
we can at least reproduce it on our side if we create such a username. maybe the fix we'll do will cover your case too @michi6383 🤔

**Comment by michi6383** [comment]
i will definitely give it a try @gre ;)

**Comment by meriadec** [comment]
we reproduced with the name "Mickaël" so it sounds related, yep

**Comment by maplewaffle** [comment]
================================================================
**Running with administrator privileges continues to fail**
================================================================
InternalError: Internal process error (3765269347)
Error
    at o (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/renderer.js:1:25413)
    at a (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/renderer.js:1:25600)
    at EventEmitter.l (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/renderer.js:1:27016)
    at emitTwo (events.js:130:20)
    at EventEmitter.emit (events.js:213:7)
----------------------------------------------------------------------------------------------------------------
[ledgerlive-export-2018.07.21-11.13.25-e22b31b14f1a604a954bf1ef66405cf07b354a88.txt](https://github.com/LedgerHQ/ledger-live-desktop/files/2215809/ledgerlive-export-2018.07.21-11.13.25-e22b31b14f1a604a954bf1ef66405cf07b354a88.txt)

**Comment by michi6383** [comment]
Error. Is still there with 1.0.4. -.-

**Comment by meriadec** [comment]
:scream: apparently the fix is not enough on your case. We managed to reproduce the error and fix it with a username containing special chars, so it must be something else, again.

Just by curiosity, what's your Window username, and what's your session home path? `C:\Users\...` when displayed in the explorer URL?

**Comment by michi6383** [comment]
@meriadec AD folder redirection \\fs00\users$\mynamewithoutspecialcharacters\

**Comment by meriadec** [comment]
![](https://i.imgflip.com/2elm7p.jpg)

**Comment by KhalilBellakrid** [comment]
@maplewaffle did you try with 1.0.4 release ? 
Because I created a session with same username and it worked.
If it's not working even with 1.0.4 then you're facing another issue than the one we fixed here, in that case could you please send your most recent logs (with 1.0.4) ?

**Comment by gre** [comment]
Can you guys try the 1.0.5? It should fix it. You might have to re-download and install the app again (not sure it does offer an update)

BTW we have no support of LDAP filesystem planned for now so you will have to install the app in a normal environment.

**Comment by meriadec** [comment]
:joy: I loled.
