### ISSUE TITLE
Support for Monero (XMR)

### ISSUE THREAD

**Issue by plavirudar** [LedgerHQ/ledger-live-desktop#939]
- [x] I have checked this feature was not yet requested.

#### Part of the application

Accounts section

#### Description

Monero is an internally developed wallet app, and therefore it should be reasonably easy to allow for integration with the default wallet app, perhaps using RPC on a local Monero wallet which can be launched directly from the Ledger Live application.

**Comment by bryan** [comment]
Tracking Monero's development through here: https://github.com/monero-project/monero-gui/pull/1446

**Comment by pascalmartin** [comment]
Why monero is not officialy supported in this list ? https://www.ledger.com/pages/supported-crypto-assets

**Comment by dasilvarosa** [comment]
@pascalmartin The crypto assets in that list are sport easy-to-use user interfaces. As Monero still requires some advanced computer skills to set up, we choose not to include it in that list until Monero can be set up and managed using GUIs.

**Comment by pascalmartin** [comment]
In the last version it is supported with the  GUIs ?
![image](https://user-images.githubusercontent.com/1377165/46354513-c58ccd80-c62c-11e8-81ef-3e5a60a26dd1.png)

**Comment by pascalmartin** [comment]
This doc is outdated, a configure on my desktop with the GUI only without any command line.

**Comment by dasilvarosa** [comment]
OK. I'll see if it needs an update. Thanks for notifying.

**Comment by gre** [comment]
Thanks for the issue.
We're unifying integration requests into [#1560](https://github.com/LedgerHQ/ledger-live-desktop/issues/1560).

Please follow [#1560](https://github.com/LedgerHQ/ledger-live-desktop/issues/1560) for updates on what will be the process.

**Comment by NullVoxPopuli** [comment]
The linked issue hasn't been updated in a while. Where should I go for the most up to date information about built-in monero support in the live app? (I also didn't see anything on Trello)
