### ISSUE TITLE
Support for a button that will select the full account value

### ISSUE THREAD

**Issue by Luuk2016** [LedgerHQ/ledger-live-desktop#941]
- [x] I have checked this feature was not yet requested.

#### Part of the application

Send section

#### Description
In the old application if you typed in a amount it would display a button that will put in the max you got on your account. So if i would type in 2btc while i only had 1, it would display a button that will select the whole account value. This function would be handy if you want to send your whole accounts value.

**Comment by gre** [comment]
thanks for the issue. we will try to cover this with #905 as soon as possible
