### ISSUE TITLE
Missing Ethereum Classic app

### ISSUE THREAD

**Issue by elkimek** [LedgerHQ/ledger-live-desktop#945]
#### Ledger Live Version and Operating System

- Ledger Live **1.0.0**
- Platform: **Windows 10**

#### Expected behavior

Unlock/get into ETC wallet

#### Actual behavior

Client says open ETC app, there is no app. 

#### Steps to reproduce the behavior

Tried with ETH app, not working.

**Comment by northbound1** [comment]
I believe it works on both with the Ethereum app but you have to go to settings disable browser support.

**Comment by gre** [comment]
You are right that there is no ETC app, this is a typo, for Ethereum Classic you actually have to use Ethereum app

**Comment by gre** [comment]
let's keep this issue opened, because it's a legit concern. we currently do not say correctly the app to install. we can easily improve it (technically need to associate crypto -> app )

**Comment by elkimek** [comment]
ETC is not "working" here correctly. Two ways I can reproduce.

1) I go to ETH on my Ledger, add ETC account, no balance.
2) I add ETC account, go to ETH app on my Ledger and the field "Open the Ethereum Classic app on your device" is hanging on loading.

Either way I can't get to my balance.

**Comment by gre** [comment]
@elkimek might be related to #947 , if you had prefork ETC or if you have used a ETH address to your ETC

**Comment by elkimek** [comment]
Neither :) never had ETC prefork no used ETH adress for ETC.

I can get to my balance via Chrome ETH app just fine tho.

**Comment by gre** [comment]
I see. we have found the problem and it should be fixed in next patch we will do ASAP

**Comment by gre** [comment]
i'll create another issue to not forget about the concern of displaying "you should install 'Ethereum' app"

**Comment by gabrieldov** [comment]
This is not ETC related - there's no option to start a ETH wallet as well... ETH and ETC are not working with current version
