### ISSUE TITLE
Password Length > 20

### ISSUE THREAD

**Issue by sanpedromanuel** [LedgerHQ/ledger-live-desktop#953]
#### Ledger Live Version and Operating System

- Ledger Live **1.0.0**
- Platform: **linux**

#### Expected behavior

Not that much a bug, but it seems that there is a 20 characters limit on the password length (since nothing appears on the screen if I type more). 
So when I type more than 20 characters,  should'nt I be warned?

#### Actual behavior

(At fist I though the (unseen) extra characters were taken into account for the password, but they are not. my bad!) 
Still, I'd like to be warned about the password policy

#### Steps to reproduce the behavior
During the password creation, enter more than 20 characters,

**Comment by gre** [comment]
let's just not limit the password. WDYT? @sanpedromanuel

**Comment by sanpedromanuel** [comment]
I am not aware about the discussions about the password usage, but I note two things:
- it is not mandatory
- there is no policy regarding Password Strength,

Which I understand, since it is only a problem of privacy for the user as I understand now.

So my Issue may not be very important :/

**Comment by sanpedromanuel** [comment]
But a simple warning would have be enough for me :)

**Comment by meriadec** [comment]
:+1: 

If it's not mandatory + no policy, let's let users choose whatever password length they want.

**Comment by Deozaan** [comment]
This is an especially dangerous practice because it truncates long passwords without telling you what the limit is. Which means you may never know what the app thinks your password is. I'm glad to see this issue being resolved in #958.
