### ISSUE TITLE
First syncing after opening the App stops and says "paused"

### ISSUE THREAD

**Issue by i-am-pierre** [LedgerHQ/ledger-live-desktop#956]
Issue description:
When opening the app, after entering the password,  synchronization stops, and its status switch to "Paused" 

Pressing the paused/synchronization button again will update balances

Configuration:
- macOS 10.13.5
- Ledger live 1.0.0
- 3 accounts set (1* BTC, 1* ZEC, 1* ETH)
- internet connection

Step to reproduce:
Open Ledger Live, enter the password and wait for first Sync to fail

Expected behavior:
Not fail the first synchronization

<img width="327" alt="screen shot 2018-07-09 at 11 00 06 pm" src="https://user-images.githubusercontent.com/36464418/42458462-85d8f4cc-83cc-11e8-966c-b0b87c99079a.png">

**Comment by gre** [comment]
Can you try to click it? does it solve the problem?

Technical reason:

- sync stops when you open a modal (like Add accounts / Send / Receive )
- when you close the modal, it will eventually restart the background sync (each 2 minutes)

**Comment by i-am-pierre** [comment]
Hi Gre,

Yes, clicking on it will restart the sync. I just think that failing / pausing upon first use after unlocking the app (without touching anything) is a great user experience.

Could it be related to my ZEC account? ( ZEC related failure advertised on http://status.ledger.fr)

**Comment by gre** [comment]
Totally agree with you, we need to improve current behavior that unlock need to trigger a resync for you. Thanks for this feedback we totally missed this case :)

Yes ZCash has recently migrated to 'overwinter' and we have not yet migrated to this mode but will do it this week :) #904

**Comment by gre** [comment]
this was fixed in 1.0.2
