### ISSUE TITLE
Order of settings in Help

### ISSUE THREAD

**Issue by dasilvarosa** [LedgerHQ/ledger-live-desktop#959]
#### Ledger Live Version

- Ledger Live **1.0.0**

#### Part of the application to improve

Settings / Help

#### Description

![screen shot 2018-07-09 at 17 08 54](https://user-images.githubusercontent.com/712580/42458958-2dc7dbb2-839b-11e8-8489-6ad393be45ba.png)

**Comment by EricLarch** [comment]
Agree

**Comment by khalilbenihoud** [comment]
I do agree!
