### ISSUE TITLE
Settings: Please add Indonesia to Region selection

### ISSUE THREAD

**Issue by jemekite** [LedgerHQ/ledger-live-desktop#960]
- [x] I have checked this feature was not yet requested.

#### Part of the application

App > Settings > General > Region

#### Description

Please add Indonesia to region selection drop-down menu

![region](https://user-images.githubusercontent.com/1957943/42459647-4b7f36c0-83c6-11e8-9c76-6f028eb6cdd4.png)

Thanks..

**Comment by gre** [comment]
I'm afraid the region list is current dependent to the language. the wording is incorrect, sorry for this, this does not actually have any impact on the time zone. it is only used for date and time formatting at the moment.

We might come back to a better feature to provide a time zone system. (like being able to chose your city like you see in normal apps `Paris (UTC+2)` ,

btw at the moment we will just use the system's timezone so you should be fine.

**Comment by jemekite** [comment]
what about adding `en-ID` to region.json, I can't set currency exchange to IDR (Indonesian Rupiah) because of this. Same problem with ledger wallet bitcoin chrome apps.

**Comment by gre** [comment]
we might want to reconsider this feature in a near future.

**Comment by EricLarch** [comment]
We are going to remove completely the region selection, as it is quite confusing. We'll use the timezone of the local computer.
