### ISSUE TITLE
No desktop icon for mac ledger live

### ISSUE THREAD

**Issue by dylankilkenny** [LedgerHQ/ledger-live-desktop#961]
#### Ledger Live Version and Operating System

- Ledger Live 1.0.0
- Platform: Mac

#### Expected behavior

Desktop icon

#### Actual behavior

![screen shot 2018-07-09 at 16 37 43](https://user-images.githubusercontent.com/9889539/42460820-c42b5d9a-8396-11e8-9e54-c0b1b5488c70.png)

#### Steps to reproduce the behavior

downloaded and ran -> https://github.com/LedgerHQ/ledger-live-desktop/releases/download/v1.0.0/ledger-live-desktop-1.0.0-mac.dmg

**Comment by nikilase** [comment]
I also don't have an App Icon but on Ubuntu 18.04

**Comment by dylankilkenny** [comment]
MacOs sierra v10.12.5

**Comment by gre** [comment]
please try again on 1.0.2. we can reopen if still happening 🤔

**Comment by kaspersoerensen** [comment]
I am having the same issue. The logo does not show up. 
Ledger Live Version 1.0.2
MacOS: 10.12.6
Downloaded DMG the from github.

**Comment by gre** [comment]
apart from the logo issue, is there any issue with the app itself? 🤔

**Comment by kaspersoerensen** [comment]
Will check tomorrow or the day after. 
For me the logo is the only thing missing. Seems like the portfolio is working fine.

**Comment by gre** [comment]
on issue https://github.com/LedgerHQ/ledger-live-desktop/issues/1159 the bug is a tiny different , it looks like logo is in the bar but not in Applications 🤔

**Comment by thijstriemstra** [comment]
The 256 or 512 version is probably missing.

**Comment by gre** [comment]
@meriadec are you aware of this? we might need to regen the icns?

**Comment by briannyeko** [comment]
still having this issue, running Ledger Live 1.0.2. 
![image](https://user-images.githubusercontent.com/5855195/42832721-5d455bfa-89f2-11e8-83f5-0d10715fa0a3.png)

**Comment by kyur4thich** [comment]
this appears to be happening again on this latest release.

**Comment by sziegler11** [comment]
I am also seeing this, running 2.35.1

**Comment by redmice** [comment]
Same here, Ledger Live 2.35.1, MacOS 10.15.7

**Comment by simonbrunelle** [comment]
Same here, Ledger Live 2.35.2, MacOS 10.15.7

**Comment by redmice** [comment]
This issue was closed in 2018. I've just opened a new one: https://github.com/LedgerHQ/ledger-live-desktop/issues/4454. Please comment there

**Comment by asantos** [comment]
Same issue here: Mac OS Catalina 10.15.3 (19D76) with Ledger Live 2.35.2
