### ISSUE TITLE
Increase number of minimum confirmations Bitcoin (max 4 now)

### ISSUE THREAD

**Issue by Luuk2016** [LedgerHQ/ledger-live-desktop#963]
- [x] I have checked this feature was not yet requested.

#### Part of the application

Currency settings -> Bitcoin

#### Description

Now the maximum number of confirmations is at 4. 
Isn't it better to increase this number?

**Comment by gre** [comment]
to which value would you see it extended?
the current implementation will default the confirmations number to the number of blocks that correspond to 30mn and have a max value of 1h. we could technically don't set any limit, but i guess we still need a sane max , like 24h or something 😅

**Comment by EricLarch** [comment]
I think 6 confirmations should be a reasonable max. Never heard anyone needing more. If we had more than 6, then it would raise more question than anything.

**Comment by gre** [comment]
so 1h30 max for all coins ?
