### ISSUE TITLE
Litecoin Transaction Details wrong

### ISSUE THREAD

**Issue by nikilase** [LedgerHQ/ledger-live-desktop#964]
#### Ledger Live Version and Operating System

- Ledger Live 1.0.0
- Platform: Windows 10

#### Actual behavior
As seen in the screenshots, the "From" address shows nothing in Ledger Live and displays Coinbase (which is true) in the old Bitcoin Wallet app. 
Also, just for comprehension: Why does it show Coinbase and not a normal address in the first place? 

![litecoin1](https://user-images.githubusercontent.com/38077998/42463190-b5f80156-83a5-11e8-9ba5-03df6aefa90e.png)
![litecoin2](https://user-images.githubusercontent.com/38077998/42463191-b6114cd8-83a5-11e8-8ee5-1db6087a00dd.png)
![litecoin3](https://user-images.githubusercontent.com/38077998/42463192-b62afe12-83a5-11e8-911b-c470351631c4.png)

**Comment by KhalilBellakrid** [comment]
@nikilase thanks for the report !
This is probably a native segwit transaction which is not supported but our API for the moment (feature request) so we don't get the from address.
Actually Coinbase are using native segwit transactions !
For Chrome App, it's same problem, when we don't have a transaction's from address we assume it's a coinbase transaction resulting from mining process ( and not a transaction from Coinbase exchange)
