### ISSUE TITLE
Minor currency chart bug

### ISSUE THREAD

**Issue by nikilase** [LedgerHQ/ledger-live-desktop#965]
#### Ledger Live Version and Operating System

- Ledger Live 1.0.0
- Platform: Windows 10

#### Actual behavior
When not using USD as the standard currency the price charts for the accounts (not the big chart of the portfolio) still show USD although they are in my case the right EUR values

![ltc](https://user-images.githubusercontent.com/38077998/42463491-8d9b25a2-83a6-11e8-8897-f8af70d6a588.png)

**Comment by gre** [comment]
good catch! 👍
