### ISSUE TITLE
Account issues + some other issues

### ISSUE THREAD

**Issue by BTCYamakaza** [LedgerHQ/ledger-live-desktop#966]
#### Ledger Live Version and Operating System

Ethereum 1.0.24
Ripple 1.0.4

- Ledger Live 1.0.0
- Platform: windows 10

Ledger nano S 1.4.2

#### Expected behavior

Two issues here

1)Adding accounts to go smooth without hiccups. 
2)Reliability of connection between Ledger live application and ledger itself doesn't work like it should.

#### Actual behavior

1)Installing Ripple and Ethereum accounts does not work. It keeps running on the "Open the Ripple app on your device" step. This does not go away while being in the app.

Going out of the Ripple or Ethereum app and going back in while in that step does not help.

Result is not being able to add the accounts to the application.

2) If you want to use the application Manager it asks you to navigate to the dashboard on the device. While being in the dashboard it does not always trigger the next step. it keeps on loading.

When this happens going inside and outside a crypto app does not seem to trigger the "navigation to the dashboard" event. Again you are stuck.

Lastly I find it weird that when I disconnect the device from the computer while being in the Manager it still has a check mark next to the "Connect and unlock your Ledger device". Only when going to another menu and comming back to the Manager the status is correct.

#### Steps to reproduce the behavior

Click add accounts, choose ripple or Ethereum. open the ledger wallet app on the device. No progress in the live app.

Weird that those apps don't work while qtum and btc work fine.

**Comment by EricLarch** [comment]
Can you please upgrade to 1.0.1 and test again?

**Comment by BTCYamakaza** [comment]
Fixed all of my issues. You guys are very fast.

**Comment by rictoken** [comment]
Hi, same problem here with eth app. Software apdated to 1.0.1 but stil on loading

**Comment by gre** [comment]
@rictoken  see  https://github.com/LedgerHQ/ledger-live-desktop/issues/949
