### ISSUE TITLE
Amount BTG incorrect

### ISSUE THREAD

**Issue by thuongle88** [LedgerHQ/ledger-live-desktop#969]
#### Ledger Live Version and Operating System

- Ledger Live **1.0.1**
- Platform: **windows**

#### Expected behavior

I want all BTG in wallet display correct.

#### Actual behavior

My BTG wallet display incorrect. Problem can be from blockchain explorer. My BTG address is ALUfGyBr9dxfcuzzQWCUv8QzKSX6p1Av9F. I search in http://btgexp.com/ not found. But I have BTG when I search in https://explorer.bitcoingold.org/ and https://btgexplorer.com/ . 

#### Steps to reproduce the behavior
Can you change BTG blockchain explorer

**Comment by EricLarch** [comment]
We are currently having a maintenance on the BTG explorers, causing the issue. You can find more information on our status page here http://status.ledger.fr/pages/maintenance/5a4c9f706fbc5823d37bed62/5b439c3b25b01d04b829145d

I'm closing this issue as it is not related to the Ledger Live app.
