### ISSUE TITLE
Support for ERC20 tokens

### ISSUE THREAD

**Issue by balthazar** [LedgerHQ/ledger-live-desktop#970]
#### Part of the application

ETH portfolio calculations, sending dialog & related APIs.

#### Description

As a Ledger evangelist, I think the main (and potentially only) missing feature which prevents your user base from completely switching to Ledger Live and ditch current solutions like MEW or MyCrypto is ERC20 support.

I don't believe I'm qualified enough to undertake such a task, but I'm sure @meriadec would be up for it!

---

And Good job on the release !

**Comment by ksheni56** [comment]
Yes, Token support is a strong need.
And probably the Ledger Team should try to dive into a partnership with Global Blockchain Technologies and support there new currency Laser "Photons".

Niceday

**Comment by gre** [comment]
I agree with you about this feature, this is in the Roadmap.

**Comment by andrehortab2u** [comment]
Support token erc20 native!

**Comment by wichtigwicht** [comment]
That's pretty much the only reason I don't use Ledger Live. My portfolio consists mainly of ERC20 tokens. It would be great if the team could dedicate themselves to integrating this function. But I don't just want to complain: The software itself looks great and I'm generally very happy that you exist. Keep up the good work!

**Comment by sci4me** [comment]
Is this actively being worked on?

**Comment by andrehortab2u** [comment]
You can use. Just use etherscan to see the erc20 balance

Em qua, 15 de ago de 2018 19:28, Scitoshi Nakayobro <
notifications@github.com> escreveu:

**Comment by sci4me** [comment]
@andrehortab2u That's not at all what I asked. I'm asking if support for ERC-20 tokens is being worked on for Ledger Live. Of course I can use etherscan or ethplorer or whatever but that's not even related.

**Comment by balthazar** [comment]
@sci4me No point answering to someone who obviously doesn't know what he's talking about, just ignore them.

**Comment by andrehortab2u** [comment]
You can store erc20 in your ledger, this is a fact.

And to see this erc20 tokens you will need to use etherscan or another web
wallet

Em qua, 15 de ago de 2018 21:16, Scitoshi Nakayobro <
notifications@github.com> escreveu:

**Comment by balthazar** [comment]
![](https://assets-auto.rbl.ms/5f0de158ec0109684184bfae945ebace6d5a2cd69923980f268ca7a91b8830a3)

**Comment by andrehortab2u** [comment]
Kkkkk

Em qui, 16 de ago de 2018 08:51, Balthazar Gronon <notifications@github.com>
escreveu:

**Comment by sci4me** [comment]
@andrehortab2u Again, you're not answering the question. You're completely ignoring it, actually. Be useful or go away lol.

**Comment by andrehortab2u** [comment]
You are a competitor that lost the game and think I'm a employe of Ledger
Wallet, but you are complete wrong. I'm just a customer that find the best
way to keep safe more than 1000 btc, eth, xrp, ltc, ecr20 token... in one
device, Ledger Wallet.

Invest in Scrum and P&D so you could try to hit the same level of Ledger
Wallet. It's not perfect, but is the best cold wallet that we have in this
planet.

Em qui, 16 de ago de 2018 18:16, Scitoshi Nakayobro <
notifications@github.com> escreveu:

**Comment by sci4me** [comment]
@andrehortab2u -_-

**Comment by stevesbrain** [comment]
@andrehortab2u Everybody here actually agrees with you - you can definitely store ERC20 tokens on the Ledger.

However, this feature request is for integrating/displaying ERC20 token balances in the "Ledger Live" software. Basically, people want to see ERC20 tokens as part of the unified interface, rather than *having* to use MEW etc.

**Comment by andrehortab2u** [comment]
Yes sure, so let's wait the team to do this

Em sex, 17 de ago de 2018 00:43, Steve Divskinsy <notifications@github.com>
escreveu:

**Comment by gre** [comment]
Yes, the Nano S does support ERC20 tokens via the Ethereum app and obviously can already be used in many websites like decentralized exchanges but it's not integrated and visible on Ledger Live as part of your global portfolio nor you can make ERC20 transactions with Ledger Live yet. It is obvious there are work to be done to support these ERC20 tokens **in Ledger Live**, it is not so trivial and we already have started to discussed about it internally.

I'm locking the thread because the team need to focus on its implementation first. Please keep such discussion outside of our GitHub.

**Comment by theoturner** [comment]
As this conversation is now unlocked again, I'd like to voice support for ERC20 management in Ledger Live.

**Comment by gre** [comment]
yes

**Comment by fuorissimo** [comment]
One year passed and erc20 native, still not added? o my god!

**Comment by gre** [comment]
was shipped in develop.

**Comment by meriadec** [comment]
:rocket:
