### ISSUE TITLE
Clicking "Update now" closes app but does nothing else

### ISSUE THREAD

**Issue by Deozaan** [LedgerHQ/ledger-live-desktop#972]
#### Ledger Live Version and Operating System

- Ledger Live 1.0.0
- Platform: Windows 10

#### Expected behavior

The Portfolio section tells me there is an update available with a link to "Update now" which when clicked should close the app, update the app, and then relaunch the app with the newly updated version.

#### Actual behavior

Clicking "Update now" just closes the app and nothing else seems to happen.

#### Steps to reproduce the behavior

1. Download and unpack ledger-live-desktop-1.0.0-win.zip.
2. Launch Ledger Live.exe and complete initial setup.
3. Go to Portfolio section of app and wait for update notification to appear.
4. Click "Update now" and see the app close itself.
5. ...
6. Nothing seems to be happening.
7. Relaunching Ledger Live.exe manually shows it is still on v1.0.0.

**Comment by gre** [comment]
We will have to try to reproduce on our side. In the meantime, you can probably manually install the new version.

**Comment by meriadec** [comment]
Can you try with the `.exe` instead of the zip? Also, would you mind use the v1.0.0 version, so it should trigger an auto-update:

https://github.com/LedgerHQ/ledger-live-desktop/releases/tag/v1.0.0

**Comment by Deozaan** [comment]
Installing the app from the .exe, running it and updating it from inside the app worked as it should.

Maybe the zip-version failed because it was on a different drive? Or maybe because it wasn't installed, it lacked the permissions to update itself? Or maybe it just didn't know how to update the files in its own directory and was looking for the default installation directory?
