### ISSUE TITLE
Genuine check: handle specifically the "Http 404" to be "DeviceTooOld" error

### ISSUE THREAD

**Issue by gre** [LedgerHQ/ledger-live-desktop#975]
#### Ledger Live Version

- Ledger Live **1.0.1**

#### Part of the application to improve

genuine / manager

#### Description

identify exactly which call is returning 404 but we basically need to treat that differently because it basically means user need to contact our support to replace device because it is old / no longer supported.

**Comment by gre** [comment]
Actually we will be able to upgrade for old firmware. It’s just a temporary glitch

**Comment by phzi** [comment]
This is still an issue?

Current Ledger Live won't allow you to update firmware without validating the device. If you have an older blue, it doesn't validate (404).
