### ISSUE TITLE
I can't insert the address when sending

### ISSUE THREAD

**Issue by KMFDM29** [LedgerHQ/ledger-live-desktop#977]
#### Ledger Live Version and Operating System

- Ledger Live **version_here**
- Platform: **windows OR mac OR linux**

**Comment by gre** [comment]
please provide more detail

**Comment by KMFDM29** [comment]
I copy the address and try to paste by pressing the right mouse button but this button is like not working
![10-07-2018 051729](https://user-images.githubusercontent.com/41021204/42471326-a72da472-8400-11e8-9777-858a19229c3d.jpg)

**Comment by KMFDM29** [comment]
push the button and the no-load

**Comment by gre** [comment]
`Ctrl V` is the paste shortcut to do it. So you were looking at a way to right click > Paste ? It seems like our app don't allow to right click, that's a legit concern.

**Comment by KMFDM29** [comment]
Thank you!

**Comment by gre** [comment]
i'm going to create another issue to make it clear what feature to improve ;)

**Comment by KMFDM29** [comment]
![10-07-2018 054803](https://user-images.githubusercontent.com/41021204/42472553-053a138a-8405-11e8-8e0b-87c4e395e968.jpg)
Why is this happening?

**Comment by gre** [comment]
@KhalilBellakrid any idea? I suspect we don't yet support this new address format. (if confirmed, we might want to open a feature request)

**Comment by KMFDM29** [comment]
Most likely

**Comment by KhalilBellakrid** [comment]
Right, this is the "Cash Address" format and for the moment we only support "legacy" address format. 
I agree to open a feature request but we should first open that request from our APIs side because I don't think they support it yet.
Or we could have a "converter" to/from this type of addresses .
