### ISSUE TITLE
Cashaddr format for Bitcoin Cash

### ISSUE THREAD

**Issue by KMFDM29** [LedgerHQ/ledger-live-desktop#980]
#### Ledger Live Version and Operating System

- Ledger Live **version_here**
- Platform: **windows OR mac OR linux**

#### Steps to reproduce the behavior

![10-07-2018 054803](https://user-images.githubusercontent.com/41021204/42476413-39264ec8-8411-11e8-9c84-682decc5a889.jpg)

**Comment by Deozaan** [comment]
My guess is that Ledger is expecting the address to start with a 1 or a 3, like BTC addresses do.

**Comment by gre** [comment]
CashAddr format is not yet supported

**Comment by dagurval** [comment]
@chaintip 180 days

**Comment by chaintip** [comment]
Hi @dagurval, ChainTip was down while this mention was made and for some reason this mention did not get picked up on restart (usually it would). If you still want to tip this issue please could you mention chaintip again. Apologies. I'm looking into the reason for the downtime.

**Comment by dagurval** [comment]
Alright, let's try again :-)
@chaintip 180 days

**Comment by chaintip** [comment]
`0.03428 BCH`| `~  23.32 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4tasvk6v5tydrjsydhr56uuq00dqhfvakpt6) to this issue by @dagurval.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/41), get a pull request merged with ```@chaintip fixes #980``` in the creation comment.

**Comment by chaintip** [comment]
Thank you @dagurval! `0.04628 BCH`| `~  37.81 USD` has now been tipped to this issue.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/41), get a pull request merged with ```@chaintip fixes #980``` in the creation comment.

**Comment by KMFDM29** [comment]
What do I need to do?
![20-07-2018 024854](https://user-images.githubusercontent.com/41021204/42958040-c0386e9c-8bc7-11e8-86bf-888bd541a2b9.jpg)

**Comment by chaintip** [comment]
Sorry, only see this now @KMFDM29.

See, https://www.chaintip.org/github#claim-bounty

and https://github.com/bitpay/copay/pull/8698 for an example.

**Comment by tcjdesign** [comment]
I feel like this should have made more progress in two years.

**Comment by gre** [comment]
https://github.com/LedgerHQ/ledger-live-common/pull/788 :)

**Comment by chaintip** [comment]
`0 BCH`| `~   0.00 USD` has now been claimed by @gre when pull request [#3121](http://github.chaintip.org/LedgerHQ/ledger-live-desktop/pull/3121) was merged. This will be sent to your wallet once you link it with chaintip.
