### ISSUE TITLE
Why do I wait so long for my reward ????   Already more than 2 hours

### ISSUE THREAD

**Issue by KMFDM29** [LedgerHQ/ledger-live-desktop#982]
![10-07-2018 073722](https://user-images.githubusercontent.com/41021204/42477656-487b72b4-8415-11e8-9db3-3f0882c70fd3.jpg)

**Comment by meriadec** [comment]
?

**Comment by KMFDM29** [comment]
And what is unclear in my question? It's been over 3 hours, and nothing's come back.I mean it...
![10-07-2018 090136](https://user-images.githubusercontent.com/41021204/42480310-0c96770c-8420-11e8-8e9e-ddd070d56b58.jpg)

**Comment by KMFDM29** [comment]
![10-07-2018 090339](https://user-images.githubusercontent.com/41021204/42480330-2f7a0fae-8420-11e8-889f-a05cf1891e55.jpg)

**Comment by meriadec** [comment]
sfyl

The screenshot you just gave are not affiliated/related at all with Ledger Live

U got scammed

**Comment by meriadec** [comment]
This is not related to Ledger Live. This is a scam.

**Comment by KMFDM29** [comment]
This was posted on your Twitter.This is posted by you.
![10-07-2018 091358](https://user-images.githubusercontent.com/41021204/42480630-c7627684-8421-11e8-9674-a017eac562a5.jpg)

**Comment by khalilbenihoud** [comment]
As @meriadec said, this is a scam unfortunately. We do have a verified Twitter account and it's the only source of truth: https://twitter.com/LedgerHQ

**Comment by KMFDM29** [comment]
If I was deceived, is it possible to reverse it?

**Comment by plavirudar** [comment]
No. https://www.reddit.com/r/SorryForYourLoss/
