### ISSUE TITLE
Show percentage of each crypto in respect to total portfolio

### ISSUE THREAD

**Issue by ibiscp** [LedgerHQ/ledger-live-desktop#984]
For those who use "asset allocation strategy" to allocate money between investments, it is really important to know how much percent each asset represent of your total portfolio.

So, together with the value of each account, it would be really interesting to see also how much percent that value represents.

**Comment by meriadec** [comment]
We can't really give ETA on that, but it's an open discussion and clearly useful. Some points that needs to be lightened:

- useful AND beautiful way to display total holding?
  - shape (pie or bar chart? something else?)
  - able to draw edge cases without being unreadable/weird (e.g: 10 verrrry small fractions and one big fraction) 
- should it replace or complete or "is switchable" with the current portfolio graph?
- what interactions are possible with it

etc.

**Comment by sadpandas** [comment]
I don't want to be that person stealing ideas but exodus wallet has the best portfolio tab I've ever seen
Has both useful and beautiful pie display on top of the current market of individual holdings. You are able to hover over the pie sections to see % holdings and name 

Here are some stock examples 

![](https://www.exodus.io/img/2018/portfolio@2x.jpg)

a gif showing a earlier mock up
https://cdn-images-1.medium.com/max/800/1*6tXwBSZVDr9mW3h-1a-oHA.gif

**Comment by THESHade** [comment]
Yes, please. Make this happen. This is what I wrote to support:

"""The Portfolio tab, it'd be great if it showed me percentage and a pie chart of the assets I own (have connected) in terms of Fiat currency value.
So if I own 9k of Bitcoin and 1k of Litecoin then it should tell me that my Portfolio (See? :P ) is 90% BTC, 10% LTC.

I'm a Digital Product Designer so I can even create a mockup for you if you want.
But this is one feature I expected from the Portfolio app that I'm still missing one year in (or 6 months? I dont know)"""
