### ISSUE TITLE
Show total holdings of each coin

### ISSUE THREAD

**Issue by 12345abcdef** [LedgerHQ/ledger-live-desktop#985]
**Part of the application:**
Display area above the historical chart.

**Description:**
It would be very helpful if the total holdings of each coin could be shown. In the old Ledger apps the combined total of all your accounts in any given crypto are combined and the total balance is shown in the top right corner. Right now if you have many accounts in a coin there's no efficient way of seeing how many total units of that coin you have.

**Comment by gre** [comment]
(a bit related https://github.com/LedgerHQ/ledger-live-desktop/issues/984 )

**Comment by reiff-awacker** [comment]
Any Updates?

**Comment by meriadec** [comment]
closing - discussion on #984
