### ISSUE TITLE
Fraud!

### ISSUE THREAD

**Issue by KMFDM29** [LedgerHQ/ledger-live-desktop#988]
One thing I don't understand.Why is this spam still on your Twitter page? Why don't you delete or block it so it doesn't mislead someone else?
![10-07-2018 091358](https://user-images.githubusercontent.com/41021204/42482954-01adef38-842e-11e8-8592-5e26eed7f758.jpg)

**Comment by 12345abcdef** [comment]
How can they delete it? It's not their tweet. Blocking that user won't get rid of the tweet either.

**Comment by Deozaan** [comment]
@KMFDM29 Look at the Twitter username: @Le**m**dgerHQ is quite obviously not the official LedgerHQ.
