### ISSUE TITLE
Unable to verify SHA512 hash for ledger-live-desktop-1.0.1-mac.zip

### ISSUE THREAD

**Issue by noman-land** [LedgerHQ/ledger-live-desktop#991]
#### Ledger Live Version and Operating System

- Ledger Live 1.0.1
- Platform: Mac

#### Expected behavior

According to the [`latest-mac.yml`](https://github.com/LedgerHQ/ledger-live-desktop/releases/download/v1.0.1/latest-mac.yml) file on the [`1.0.1` release page](https://github.com/LedgerHQ/ledger-live-desktop/releases/tag/v1.0.1) the SHA512 hash of the [`ledger-live-desktop-1.0.1-mac.zip`](https://github.com/LedgerHQ/ledger-live-desktop/releases/download/v1.0.1/ledger-live-desktop-1.0.1-mac.zip) file should be:

`my4a8kHrjRSZzo8XUDGGYgwW4Tw6mlFcwoHDZru4dfqYBVGFiyJnJCatjdcioOpgqlg7KBACHtBHCLwMNN6KrQ==`

#### Actual behavior

The SHA512 hash I'm getting for the [`ledger-live-desktop-1.0.1-mac.zip`](https://github.com/LedgerHQ/ledger-live-desktop/releases/download/v1.0.1/ledger-live-desktop-1.0.1-mac.zip) file is:

`9b2e1af241eb8d1499ce8f17503186620c16e13c3a9a515cc281c366bbb875fa980551858b22672426ad8dd722a0ea60aa583b2810021ed04708bc0c34de8aad`

#### Steps to reproduce the behavior

1. Download [`ledger-live-desktop-1.0.1-mac.zip`](https://github.com/LedgerHQ/ledger-live-desktop/releases/download/v1.0.1/ledger-live-desktop-1.0.1-mac.zip)
2. Run `shasum -a 512 ledger-live-desktop-1.0.1-mac.zip`
3. Receive output:
    `9b2e1af241eb8d1499ce8f17503186620c16e13c3a9a515cc281c366bbb875fa980551858b22672426ad8dd722a0ea60aa583b2810021ed04708bc0c34de8aad  ledger-live-desktop-1.0.1-mac.zip`

**Comment by SomberNight** [comment]
Those strings are the same but one is base64 encoded, the other is hex..

**Comment by petri** [comment]
It would be good to provide some instructions on the download page on how to verify the download.

**Comment by meriadec** [comment]
Thx for your feedback, we'll update our docs to describe that step.
