### ISSUE TITLE
Empty ledger defaults to different HD derivation than chrome app

### ISSUE THREAD

**Issue by davis12529** [LedgerHQ/ledger-live-desktop#993]
#### Ledger Live Version and Operating System

- Ledger Live **1.0.1**
- Platform: **macOS High Sierra**

#### Expected behavior

Ethereum receive address of freshly initialised on Ledger Live should be same as Ledger Wallet Ethereum. Not sure if chrome app is compatible with `m/44'/60'/0'/0`

#### Actual behavior

Different address is shown as Ledger Live defaulted to `m/44'/60'/0'/0`. This is confusing when ledger is used between Ledger Live and the chrome app.

I have added other ledgers with transactions on `m/44'/60'/0'/` to Ledger Live and they default to `m/44'/60'/0'/` so adding existing ledgers is okay.

#### Steps to reproduce the behavior

1. Initialise Ledger Nano S (Secure 1.5.2)
2. Add Ethereum account in Ledger Live
3. Get receive address in Ledger Live

```
{
  "index": 0,
  "freshAddressPath": "44'/60'/0'/0/0",
  "ethereumjs:ethereum:...."
}
```

**Comment by davis12529** [comment]
If the move to ` m/44'/60'/0'/0` is intended, it should be communicated clearly to users to prevent confusion when they move to use the chrome app

**Comment by gre** [comment]
Ledger Live should be able to improve old derivation paths (that include the one MEW is derivating too) but you are right, the new derivation path is going to be `44'/60'/0'/0/0` , `44'/60'/1'/0/0`, and so on. This unify the BIP44 convention across all our cryptocurrencies.

Agree we will need to communicate more on this, blog post to come.
