### ISSUE TITLE
Windows dev environment fails

### ISSUE THREAD

**Issue by solemnify** [LedgerHQ/ledger-live-desktop#996]
\* \* \* ***maintainer edit*** \* \* \*
bug is identified
you can find a workaround in [this comment](https://github.com/LedgerHQ/ledger-live-desktop/issues/996#issuecomment-403803010)
\* \* \* ***maintainer edit end*** \* \* \*

#### Ledger Live Version and Operating System

- Ledger Live **master (development mode)**
- Platform: **Windows 10**
- Yarn: **v1.7.0**
- Node: **v8.11.3**
#### Expected behavior

The application should proceed as expected.

#### Actual behavior

The application gets stuck at the loading screen.
#### Steps to reproduce the behavior

1. Install all dependencies (Node, Yarn, production windows-build-tools 
2. yarn (Install dependencies)
3. yarn start (Launch the app)

![image](https://user-images.githubusercontent.com/8888547/42494194-5e47a658-83d4-11e8-843e-cd0dda3d6773.png)

**Comment by gre** [comment]
Thanks for the report.
I can confirm this seems to happen on Windows and we have not figured out why. We can build it but not run it in dev.
Help is welcomed :)
